import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u13-l3-d1',
    title: 'Will, going to or shall?',
    titleUz: 'Will, going to va shall',
    goal: "Reja (**going to**) va shu zahoti qaror (**will**) ni farqlashni va **Shall I / Shall we** bilan taklif qilishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "*I've already decided. I ___ study medicine.*", opts: ['am going to', 'will to', 'going to', 'shall'], a: 0, why: "Oldindan qilingan qaror → **am going to**." },
      { k: 'choice', q: '*Oh, there is no milk. I ___ buy some.*', opts: ['will', 'am going to', 'am buying', 'shall'], a: 0, why: "Shu zahoti qaror → **will** (*I'll buy*)." },
      { k: 'choice', q: '*Look at those black clouds! It ___ rain.*', opts: ['will', 'is going to', 'shall', 'is go to'], a: 1, why: "Ko'rinib turgan dalil bor → **is going to**." },
      { k: 'match', pairs: [["I've booked a hotel.", "We're going to stay there."], ["It's hot in here.", "I'll open the window."], ['Look at the sky!', "It's going to rain."], ['I think', "it'll be a nice day."]] },
      { k: 'fill', q: 'Shall I ___ the window? It is hot in here.', a: ['open'], uz: "Derazani ochaymi? Bu yer issiq.", why: "**Shall I + V1** — yordam taklifi." },
      { k: 'fill', q: 'We ___ going to fly to Dubai on Monday. We have the tickets.', a: ['are'], why: "*we* + **are** going to." },
      { k: 'tf', q: "*Shall he help you?* — to'g'ri gap.", a: false, why: "**Shall** faqat **I / we** bilan ishlatiladi." },
      { k: 'listen', say: 'Shall we go to the cinema tonight?', opts: ['Shall we go to the cinema tonight?', 'Will we go to the cinema tonight?', 'Shall I go to the cinema tonight?', 'Are we going to the cinema tonight?'], a: 0, why: "**Shall we** — birgalikda ish qilishni taklif." },
      { k: 'order', uz: "Dam olish kuni parkka boraylikmi?", words: ['Shall', 'we', 'go', 'to', 'the', 'park', 'on', 'Sunday?'], extra: ['going', 'you'], why: "**Shall we + V1** (*to* yo'q)." },
      { k: 'fix', wrong: 'I will going to visit my grandmother on Sunday.', a: ["I'm going to visit my grandmother on Sunday.", 'I am going to visit my grandmother on Sunday.', 'I will visit my grandmother on Sunday.', "I'll visit my grandmother on Sunday."], hint: "will va going to birga kelmaydi", why: "**will** va **going to** ni birga ishlatmang: faqat bittasi." },
      { k: 'fix', wrong: 'Shall I to help you?', a: ['Shall I help you?'], why: "**Shall** dan keyin **to** yo'q: *Shall I help…?*" },
      { k: 'translate', uz: "Menimcha, ertaga yomg'ir yog'adi.", a: ["I think it will rain tomorrow", "I think it'll rain tomorrow", "I think it's going to rain tomorrow", 'I think it is going to rain tomorrow'], why: "Fikr, dalil yo'q → **will**." },
    ],
  },
  {
    id: 'u13-l4-d1',
    title: "I'm meeting Laylo at six",
    titleUz: 'Present Continuous: kelishilgan rejalar',
    goal: "Kelishilgan rejani **Present Continuous** bilan, jadvalni **Present Simple** bilan aytishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*I ___ Laylo at six tonight.*', opts: ['am meeting', 'meet', 'will meeting', 'meets'], a: 0, why: "Kelishilgan reja → **am meeting**." },
      { k: 'choice', q: '*The train ___ at 8:15 tomorrow.* (jadval)', opts: ['leaves', 'leave', 'leaving', 'does leave'], a: 0, why: "Rasmiy jadval → **Present Simple**." },
      { k: 'match', pairs: [['tonight', 'bugun kechqurun'], ['tomorrow morning', 'ertaga ertalab'], ['next week', 'kelasi hafta'], ['on Friday', 'juma kuni'], ["at seven o'clock", 'soat yettida']] },
      { k: 'fill', q: 'My cousin ___ visiting us this weekend.', a: ['is'], uz: "Amakivachcham shu hafta oxiri biznikiga keladi.", why: "*my cousin* = he → **is** + V-ing." },
      { k: 'fill', q: 'What time ___ you leaving tomorrow?', a: ['are'], uz: "Ertaga soat nechada jo'naysan?", why: "*you* + **are** + V-ing." },
      { k: 'listen', say: "We're having lunch with my aunt on Sunday.", opts: ["We're having lunch with my aunt on Sunday.", 'We had lunch with my aunt on Sunday.', "We're having lunch with my uncle on Sunday.", 'We have lunch with my aunt every Sunday.'], a: 0, why: "**We're having** — kelasi yakshanbaga reja." },
      { k: 'tf', q: "*My friend and I are having dinner at eight.* — bu kelishilgan reja.", a: true, why: "Vaqt va odam belgilangan → **Present Continuous**." },
      { k: 'order', uz: "Dushanba kuni stomatologga borasanmi?", words: ['Are', 'you', 'seeing', 'the', 'dentist', 'on', 'Monday?'], extra: ['Do', 'see'], why: "Savol: **Are you + V-ing?**" },
      { k: 'fix', wrong: 'Do you coming to the party on Saturday?', a: ['Are you coming to the party on Saturday?'], hint: "do bilan emas", why: "Present Continuous savoli: **Are you coming…?**" },
      { k: 'fix', wrong: "It's raining tomorrow afternoon.", a: ["It's going to rain tomorrow afternoon.", 'It is going to rain tomorrow afternoon.', 'It will rain tomorrow afternoon.', "It'll rain tomorrow afternoon."], hint: "Ob-havo bilan kelishib bo'lmaydi", why: "Ob-havo taxmini uchun **going to** yoki **will**." },
      { k: 'translate', uz: "Biz shanba kuni Samarqandga boramiz.", a: ["We're going to Samarkand on Saturday", 'We are going to Samarkand on Saturday', "We're travelling to Samarkand on Saturday", 'We are travelling to Samarkand on Saturday', "We're traveling to Samarkand on Saturday", 'We are traveling to Samarkand on Saturday'], why: "Kelishilgan reja → **We're going**." },
      { k: 'translate', uz: "Ertaga soat oltida do'stim meni olib ketadi.", a: ['My friend is picking me up at six tomorrow', "My friend's picking me up at six tomorrow", 'Tomorrow at six my friend is picking me up', 'My friend is picking me up tomorrow at six', "My friend is picking me up at six o'clock tomorrow", "My friend is picking me up tomorrow at six o'clock"], why: "Aniq vaqt belgilangan → **is picking me up**." },
    ],
  },
  {
    id: 'u13-l5-d1',
    title: 'May and might',
    titleUz: 'May / might: ehtimol',
    goal: "**may / might + V1** bilan ishonchsiz kelajakni aytishni va **maybe / may be** ni adashtirmaslikni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*It ___ rain this afternoon.*', opts: ['might', 'mights', 'might to', 'is might'], a: 0, why: "**might + V1**; *s* qo'shilmaydi." },
      { k: 'choice', q: "Qaysi gap **to'g'ri**?", opts: ['She may to come.', 'She may come.', 'She mays come.', 'She may comes.'], a: 1, why: "**may + V1** — *to* ham, *-s* ham yo'q." },
      { k: 'match', pairs: [['I will go.', 'Albatta boraman.'], ["I'll probably go.", 'Ehtimol, boraman.'], ['I might go.', 'Balki boraman.'], ["I definitely won't go.", 'Aniq bormayman.']] },
      { k: 'fill', q: "I'm not sure. I ___ stay at home tonight.", a: ['might', 'may'], uz: "Ishonchim yo'q. Bugun kechqurun uyda qolishim mumkin.", why: "Ishonchsizlik → **might / may**." },
      { k: 'fill', q: 'Maybe she is at home. = She ___ be at home.', a: ['may', 'might'], why: "**maybe** gap boshida; fe'l bilan **may / might be**." },
      { k: 'tf', q: "*He maybe late.* — to'g'ri gap.", a: false, why: "Fe'l o'rnida **may be** (ikki so'z) kerak: *He may be late.*" },
      { k: 'listen', say: 'She may not come to the party.', opts: ['She may not come to the party.', 'She may come to the party.', "She won't come to the party.", 'She might come to the party.'], a: 0, why: "**may not** — inkor ehtimol." },
      { k: 'order', uz: "Ehtimol ertaga uyda qolaman.", words: ['I', 'might', 'stay', 'at', 'home', 'tomorrow.'], extra: ['to', 'mights'], alt: [['Tomorrow', 'I', 'might', 'stay', 'at', 'home.']], why: "**might + V1**." },
      { k: 'fix', wrong: 'My brother may visits us on Sunday.', a: ['My brother may visit us on Sunday.'], hint: "may dan keyin", why: "Modal fe'ldan keyin **V1**: *may visit*." },
      { k: 'fix', wrong: 'I might to go to the cinema tonight.', a: ['I might go to the cinema tonight.'], why: "**might** dan keyin **to** yo'q." },
      { k: 'fix', wrong: 'It maybe rain tomorrow.', a: ['It may rain tomorrow.', 'It might rain tomorrow.', 'Maybe it will rain tomorrow.', "Maybe it'll rain tomorrow."], hint: 'maybe yoki may', why: "Fe'l bilan **may / might**, **maybe** esa gap boshida." },
      { k: 'translate', uz: "Akam bu yil bizni ko'rgani kelmasligi mumkin.", a: ['My brother might not visit us this year', 'My brother may not visit us this year', 'My brother might not come to see us this year', 'My brother may not come to see us this year'], why: "**might not / may not + V1**." },
    ],
  },
  {
    id: 'u13-l6-d1',
    title: 'If it rains, we will stay',
    titleUz: 'Birinchi shart gap: if + Present, will',
    goal: "**If + Present Simple, will + V1** qolipini va *if it will rain* xatosidan qochishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*If the weather is nice, we ___ to the lake.*', opts: ['will go', 'go', 'are go', 'would go'], a: 0, why: "Natija qismida **will + V1**." },
      { k: 'choice', q: "*If it rains, we ___ go to the park.*", opts: ["won't", "don't", "aren't", 'not will'], a: 0, why: "Natija qismida inkor: **won't + V1**." },
      { k: 'match', pairs: [['If you miss the bus,', "you'll be late."], ['If I find your phone,', "I'll tell you."], ["If it's sunny,", "we'll go to the lake."], ["If you don't hurry,", "we'll miss the train."]] },
      { k: 'fill', q: "If Dilnoza ___ the exam, her parents will be happy. (pass)", a: ['passes'], why: "if-qismda **Present Simple**: *she passes*." },
      { k: 'fill', q: 'I ___ call you if I have time.', a: ['will'], uz: "Vaqtim bo'lsa, senga qo'ng'iroq qilaman.", why: "**will** — natija qismida." },
      { k: 'listen', say: 'If you study hard, you will pass the test.', opts: ['If you study hard, you will pass the test.', 'If you studied hard, you would pass the test.', 'If you will study hard, you pass the test.', 'You will pass the test if you study.'], a: 0, why: "**If + Present Simple, will + V1**." },
      { k: 'tf', q: "*If it will rain tomorrow, I'll take an umbrella.* — to'g'ri gap.", a: false, why: "**if** dan keyin **will** yo'q: *If it **rains** tomorrow…*" },
      { k: 'order', uz: "Agar kech qolsang, men seni kutmayman.", words: ['If', 'you', 'are', 'late,', 'I', "won't", 'wait', 'for', 'you.'], extra: ['will', 'am'], alt: [['If', "you're", 'late,', 'I', "won't", 'wait', 'for', 'you.'], ['I', "won't", 'wait', 'for', 'you', 'if', 'you', 'are', 'late.']], why: "**If** + Present, **won't** + V1." },
      { k: 'fix', wrong: "If you will hurry, you'll catch the bus.", a: ["If you hurry, you'll catch the bus."], hint: 'if dan keyin', why: "**if** dan keyin Present Simple: **hurry**." },
      { k: 'fix', wrong: "If he doesn't comes, we'll start without him.", a: ["If he doesn't come, we'll start without him."], why: "**doesn't** dan keyin V1: **come**." },
      { k: 'fix', wrong: "If I will have time tomorrow, I'll call you.", a: ["If I have time tomorrow, I'll call you."], why: "if-qismda **will** ishlatilmaydi." },
      { k: 'translate', uz: "Agar ertaga bo'sh bo'lsam, senga yordam beraman.", a: ["If I'm free tomorrow, I'll help you", 'If I am free tomorrow, I will help you', "I'll help you if I'm free tomorrow", 'I will help you if I am free tomorrow', "If I have time tomorrow, I'll help you", 'If I have time tomorrow, I will help you'], why: "**If I'm free…, I'll help…**" },
    ],
  },
  {
    id: 'u13-l6-d2',
    title: 'First conditional: tricky mix',
    titleUz: 'Birinchi shart gap: qiyin aralash mashqlar',
    goal: "**unless**, inkor if-qism va *if it will be* kabi tipik xatolarni tuzatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "Qaysi gap **to'g'ri**?", opts: ["If it will be sunny, we'll go to the lake.", "If it is sunny, we'll go to the lake.", 'If it is sunny, we go will to the lake.', "If it's sunny, we would go to the lake."], a: 1, why: "**If + Present Simple, will + V1**." },
      { k: 'choice', q: "*I won't go ___ you come with me.*", opts: ['unless', 'if', 'because', 'although'], a: 0, why: "**unless** = *if … not*: *…if you don't come*." },
      { k: 'choice', q: '*What ___ you do if you miss the last bus?*', opts: ['will', 'shall', 'are', 'did'], a: 0, why: "Savolda natija qismi savolga aylanadi: **What will you do…?**" },
      { k: 'tf', q: "*Unless you hurry* — *If you don't hurry* bilan bir xil ma'noda.", a: true, why: "**Unless** o'zi inkor ma'nosini beradi." },
      { k: 'fill', q: "We'll have a picnic ___ it rains. (if not)", a: ['unless'], uz: "Yomg'ir yog'masa, pikinik qilamiz.", why: "**unless it rains** = *if it doesn't rain*." },
      { k: 'fill', q: 'If you see Aziz, ___ him to call me.', a: ['tell'], uz: "Azizni ko'rsang, menga qo'ng'iroq qilishini ayt.", why: "Natija qismida buyruq: **tell**." },
      { k: 'dictation', say: "If you don't hurry, you'll miss the train." },
      { k: 'fix', wrong: "If you won't help me, I'll do it myself.", a: ["If you don't help me, I'll do it myself."], hint: "if-qismda inkor", why: "if-qismda **don't** ishlating, **won't** emas." },
      { k: 'fix', wrong: "Unless you don't study, you'll fail the test.", a: ["Unless you study, you'll fail the test.", "If you don't study, you'll fail the test."], hint: 'unless ichida inkor bor', why: "**Unless** ning o'zi inkor, *don't* kerak emas." },
      { k: 'fix', wrong: "We'll go for a walk if it will be sunny.", a: ["We'll go for a walk if it is sunny.", "We'll go for a walk if it's sunny."], why: "**if** dan keyin **will** yo'q: *if it is sunny*." },
      { k: 'order', uz: "Agar yomg'ir yog'sa, biz kinoga boramiz.", words: ['If', 'it', 'rains,', "we'll", 'go', 'to', 'the', 'cinema.'], extra: ['will', 'rained'], alt: [['If', 'it', 'rains,', 'we', 'will', 'go', 'to', 'the', 'cinema.'], ["We'll", 'go', 'to', 'the', 'cinema', 'if', 'it', 'rains.']], why: "**If it rains**, so'ng vergul va **will**." },
      { k: 'translate', uz: "Agar bu kitobni o'qisang, ingliz tiling yaxshilanadi.", a: ['If you read this book, your English will improve', "If you read this book, your English will get better", "If you read this book, your English will be better", "Your English will improve if you read this book", "Your English will get better if you read this book"], why: "**If you read…, your English will improve.**" },
    ],
  },
];
