import type { Part1Topic } from './types.js';

export const PART1: Part1Topic[] = [
  {
    slug: "hometown",
    title: "Hometown",
    intro: "Examiners often start with where you come from. Describe the place simply, then add one personal detail.",
    qa: [
      { q: "Where is your hometown?", a: "I come from Samarkand, a historic city in the east of Uzbekistan. It is famous for its beautiful old mosques and madrasas, so there are always plenty of tourists walking around the centre." },
      { q: "What do you like most about your hometown?", a: "I really like the atmosphere. People are friendly, the food is excellent and everything feels familiar. I can walk to the market or visit my relatives within minutes, which makes daily life very comfortable." },
      { q: "Is your hometown a good place for young people?", a: "In many ways, yes. There are universities, cafés and sports clubs. However, the number of well-paid jobs is limited, so some graduates move to the capital to build their careers." },
      { q: "Has your hometown changed much in recent years?", a: "Quite a lot. New roads and shopping centres have appeared, and the old centre has been renovated. It looks much more modern than it did when I was a child, although I miss some of the small local shops." },
      { q: "Would you like to live there in the future?", a: "I think so. Big cities are exciting, but I would like to raise a family somewhere calmer and closer to my parents, so returning to my hometown is a realistic plan." },
      { q: "What would you recommend a visitor to do there?", a: "I would suggest starting with a morning walk through the old town, then trying local plov at a traditional restaurant. If time allows, a visit to the bazaar is a great way to meet people." },
    ],
    vocab: [["historic", "important in history"], ["bustling", "full of busy activity"], ["renovated", "repaired and improved"], ["lively atmosphere", "an energetic, enjoyable feeling"], ["tourist attraction", "a place visitors want to see"], ["close-knit community", "people who know and support each other"], ["raise a family", "bring up children"]],
    tips: ["Answer in two or three sentences, then stop. The examiner will ask the next question.", "Use present simple for facts and present perfect for change: “It has changed a lot.”", "Avoid reciting a memorised paragraph. Natural pauses and small corrections are fine."],
  },
  {
    slug: "work",
    title: "Work",
    intro: "If you work, talk about the job and what you enjoy. If you study, say what you plan to do in the future.",
    qa: [
      { q: "Do you work or are you a student?", a: "I am currently working as a marketing assistant at a small technology company, and I also take evening classes to improve my English." },
      { q: "Why did you choose that job?", a: "I have always been interested in how brands communicate with people. This job lets me be creative and analytical at the same time, which suits my personality." },
      { q: "What do you enjoy most about your work?", a: "Definitely the variety. One day I might write social media posts, and the next day I analyse customer data. I rarely feel bored, and I learn something new almost every week." },
      { q: "Is there anything you dislike about your job?", a: "Sometimes the deadlines are tight, especially before a product launch. It can be stressful, but it has taught me to plan my time more carefully." },
      { q: "Would you like to change your job in the future?", a: "Not immediately. I want to gain more experience first, but in a few years I might move into a management role or start my own agency." },
      { q: "What job did you want to do when you were a child?", a: "When I was little I dreamed of being a pilot because I loved aeroplanes. As I grew older my interests changed, and I realised I preferred working with ideas." },
    ],
    vocab: [["demanding", "needing a lot of effort"], ["rewarding", "giving satisfaction"], ["tight deadline", "very little time to finish work"], ["career prospects", "chances of progress in a job"], ["colleagues", "people you work with"], ["flexible hours", "working times you can adjust"], ["gain experience", "learn by doing"]],
    tips: ["Give a reason with “because”, “so” or “which means”.", "If you are unemployed, talk about the job you hope to get.", "Use a range of tenses: present for now, past for history, future for plans."],
  },
  {
    slug: "studies",
    title: "Studies",
    intro: "Part 1 questions about your studies are common. Name your subject, explain why you chose it and say what you want to achieve.",
    qa: [
      { q: "What subject are you studying?", a: "I am studying international relations at university. It covers politics, economics and languages, so it gives me a broad understanding of how countries work together." },
      { q: "Why did you choose that subject?", a: "I was always curious about world events and I enjoy learning languages. This course combines both interests, and it should open doors to careers in diplomacy or international business." },
      { q: "What do you find most difficult about your studies?", a: "Managing my time. There are many readings and presentations each week, so I have to be disciplined and make a plan if I want to avoid last-minute stress." },
      { q: "Do you prefer studying alone or with other people?", a: "It depends. I concentrate better alone, but group study is useful before exams because friends can explain things I did not understand and we share notes." },
      { q: "Is there anything you would change about your course?", a: "I would add more practical projects. Theory is important, but real experience, such as internships, helps students understand how knowledge is used in the workplace." },
      { q: "What do you want to do after you finish your studies?", a: "I would like to work for an international organisation, ideally one connected with education. Before that, I may continue to a master's degree abroad." },
    ],
    vocab: [["major in", "study as the main subject"], ["coursework", "work done during a course"], ["lecture", "a talk given to students"], ["deadline", "the last time to hand in work"], ["tuition fees", "money paid for teaching"], ["graduate", "finish a degree"], ["hands-on experience", "practical work"]],
    tips: ["Say what you study in the first sentence, then explain.", "Show opinions: “I would change…”, “I find … quite challenging.”", "Use a linking word to extend an answer: “However”, “Besides”, “That is why”."],
  },
  {
    slug: "hobbies",
    title: "Hobbies",
    intro: "Hobby questions are friendly and easy. They are a good chance to show natural, descriptive language.",
    qa: [
      { q: "What do you like to do in your free time?", a: "I enjoy photography. On weekends I often take my camera to a park or the old town and try to capture interesting scenes. It helps me relax after a busy week." },
      { q: "How long have you had this hobby?", a: "For about four years. I started with my phone, and when I realised how much I enjoyed it, I saved up and bought a proper camera." },
      { q: "Do you prefer indoor or outdoor activities?", a: "Mostly outdoor ones, especially when the weather is pleasant. Being outside clears my mind, though I like reading or watching films at home when it rains." },
      { q: "Is it a popular hobby in your country?", a: "It is becoming more popular, mainly because of social media. Many young people like sharing photos online, and there are now clubs and exhibitions for beginners." },
      { q: "Would you like to try a new hobby?", a: "Yes, I would love to learn the guitar. Music has always interested me, and I think playing an instrument would be a nice contrast to my visual hobby." },
      { q: "Do you think hobbies are important?", a: "Definitely. A hobby gives you a break from work or study, reduces stress and often teaches useful skills such as patience and creativity." },
    ],
    vocab: [["pastime", "an activity done for enjoyment"], ["keen on", "very interested in"], ["take up", "start a new activity"], ["unwind", "relax after work"], ["hands-on", "practical, active"], ["passionate about", "extremely enthusiastic about"], ["a break from routine", "a change from normal duties"]],
    tips: ["Do not just name the hobby. Say why you like it.", "Use “I'm really into…” or “I'm keen on…” instead of repeating “I like”.", "Mention frequency: “once a week”, “every other weekend”."],
  },
  {
    slug: "food-and-cooking",
    title: "Food and Cooking",
    intro: "Food is a favourite Part 1 theme. Describe flavours, habits and traditions with specific details.",
    qa: [
      { q: "What is your favourite food?", a: "I love plov, our national dish. It is made with rice, carrots and meat, and the smell alone makes me hungry. My father cooks it every Sunday, so it also reminds me of family." },
      { q: "Do you enjoy cooking?", a: "Yes, although I am not an expert. I can prepare simple dishes like pasta and omelettes, and I am slowly learning more complicated recipes from videos online." },
      { q: "Do you prefer eating at home or in restaurants?", a: "I prefer home cooking because it is healthier and cheaper, but I enjoy going to a restaurant with friends once or twice a month for a change." },
      { q: "Is food in your country healthy?", a: "Traditional food contains lots of vegetables, fruit and bread, which is healthy. However, many dishes are quite oily, and fast food is becoming more common among young people." },
      { q: "What did you eat for breakfast today?", a: "I had tea with bread, cheese and a boiled egg. I am usually in a hurry in the morning, so I keep breakfast simple." },
      { q: "Have your eating habits changed over the years?", a: "Yes. I used to eat a lot of sweets, but now I try to eat more fruit and drink water instead of fizzy drinks because I want to stay in good shape." },
    ],
    vocab: [["national dish", "a food typical of a country"], ["home-cooked", "made at home"], ["nutritious", "good for your health"], ["greasy", "containing too much oil"], ["a balanced diet", "eating different foods in healthy amounts"], ["fizzy drinks", "sweet drinks with bubbles"], ["mouth-watering", "looking or smelling delicious"]],
    tips: ["Add sensory detail: taste, smell, texture.", "Use comparisons: “healthier than”, “not as spicy as”.", "Past habits: “I used to…” is a safe, accurate structure."],
  },
  {
    slug: "music",
    title: "Music",
    intro: "Talk about the music you like, when you listen to it and how it affects your mood.",
    qa: [
      { q: "What kind of music do you like?", a: "I mostly listen to pop and some classical music. Pop is energetic, and classical music helps me concentrate when I study." },
      { q: "When do you usually listen to music?", a: "On my way to university and while I exercise. It makes long journeys feel shorter and gives me extra energy at the gym." },
      { q: "Can you play a musical instrument?", a: "Not really. I had piano lessons as a child but stopped after a couple of years. I would like to start again when I have more free time." },
      { q: "Has your taste in music changed since you were younger?", a: "Yes, a lot. As a teenager I only liked loud rock music, but now I enjoy calmer songs with meaningful lyrics." },
      { q: "Do you prefer live music or recorded music?", a: "Live music, definitely. The atmosphere at a concert is hard to describe, and you feel connected to the performers and the audience." },
      { q: "Is music important in your culture?", a: "Very much. Traditional songs and dances are part of weddings and festivals, and many families still pass down folk music through generations." },
    ],
    vocab: [["catchy", "easy to remember and enjoyable"], ["lyrics", "the words of a song"], ["upbeat", "positive and lively"], ["soothing", "calming"], ["live performance", "music played in front of an audience"], ["folk music", "traditional music of a region"], ["on repeat", "played again and again"]],
    tips: ["You do not need to name artists. Describe the feeling and the situation.", "Link music to emotion: “It cheers me up.”", "Give a contrast: “Although I like pop, I find classical music more relaxing.”"],
  },
  {
    slug: "travel",
    title: "Travel",
    intro: "Travel questions invite stories. Use past tenses accurately and add a feeling or reaction.",
    qa: [
      { q: "Do you like travelling?", a: "Very much. Visiting new places teaches me about other cultures, and I always return with fresh ideas and great photos." },
      { q: "What was the last place you visited?", a: "I recently went to Bukhara for a weekend. We explored the old streets, tasted local sweets and visited several historic buildings. It was tiring but unforgettable." },
      { q: "Do you prefer travelling alone or with others?", a: "With others. Sharing the experience makes it more fun, and we can split the costs. Also, it is safer in an unfamiliar place." },
      { q: "How do you usually travel?", a: "Within the country I take the high-speed train because it is fast and comfortable. For longer trips abroad, I fly, although I try to book early to save money." },
      { q: "Where would you like to go in the future?", a: "Japan is at the top of my list. I am fascinated by the mix of tradition and technology, and I would love to try the food." },
      { q: "Are there any problems with tourism in your country?", a: "In popular cities, some areas become overcrowded in summer. It also puts pressure on historic sites, so better management is needed." },
    ],
    vocab: [["sightseeing", "visiting famous places"], ["itinerary", "a plan of a journey"], ["off the beaten track", "away from usual tourist areas"], ["unforgettable", "impossible to forget"], ["budget", "plan spending carefully"], ["overcrowded", "too full of people"], ["broaden your horizons", "gain new experiences and ideas"]],
    tips: ["Use past simple for trips: “We explored…”, “I tasted…”.", "Add a feeling: “It was breathtaking.”", "For future plans use “I'm planning to…” or “I'd love to…”."],
  },
  {
    slug: "weather",
    title: "Weather",
    intro: "Weather is an easy topic if you add personal feelings and comparisons between seasons.",
    qa: [
      { q: "What is the weather like in your hometown?", a: "Summers are hot and dry, often above thirty-five degrees, while winters are cold with occasional snow. Spring and autumn are mild and very pleasant." },
      { q: "What is your favourite season?", a: "Spring. Everything turns green, the temperature is comfortable and the days get longer, so I feel more energetic and spend more time outside." },
      { q: "Does the weather affect your mood?", a: "Yes, I think it does. Sunny days make me cheerful, but dark, rainy weather sometimes makes me feel tired and less motivated." },
      { q: "What do you usually do when it rains?", a: "I stay at home with a cup of tea, read a book or watch a series. If I must go out, I take an umbrella and wear a waterproof jacket." },
      { q: "Do you think the climate is changing?", a: "It seems so. Summers are hotter than they were when I was young, and there are more unusual storms. I believe it is linked to global warming." },
      { q: "Do you check the weather forecast?", a: "Every morning on my phone. It helps me decide what to wear and whether to plan outdoor activities." },
    ],
    vocab: [["scorching", "extremely hot"], ["mild", "not too hot or cold"], ["drizzle", "light rain"], ["freezing", "very cold"], ["humid", "damp and sticky"], ["forecast", "prediction of the weather"], ["heatwave", "a long period of very hot weather"]],
    tips: ["Compare two seasons to extend your answer naturally.", "Use precise adjectives instead of “very hot”: scorching, boiling.", "Give a reason for your preference."],
  },
  {
    slug: "daily-routine",
    title: "Daily Routine",
    intro: "Describe a normal day in order, using time expressions and a few linking words.",
    qa: [
      { q: "What is your daily routine like?", a: "I get up around seven, have breakfast and go to class or work by nine. In the afternoon I study or do errands, and in the evening I relax with family before going to bed around eleven." },
      { q: "Do you prefer mornings or evenings?", a: "Evenings. My mind is sharper and I feel more creative, so I do my best work after dinner. Early mornings are always a struggle for me." },
      { q: "Is there anything you would like to change about your routine?", a: "I would like to exercise more regularly. At the moment I am too busy during the week, so I need to find a way to fit a short workout into the morning." },
      { q: "Do you think routines are important?", a: "Yes. A regular schedule helps you use time wisely and reduces stress, though a little flexibility keeps life from becoming boring." },
      { q: "What do you usually do on weekends?", a: "I sleep in a little, meet friends and sometimes go hiking. Sundays are mostly for family and preparing for the week ahead." },
      { q: "Has your routine changed in the past few years?", a: "Considerably. Since I started university my days are less predictable, and I have learned to manage my time instead of following a fixed timetable." },
    ],
    vocab: [["get up", "leave your bed"], ["run errands", "do small necessary tasks"], ["hectic", "very busy"], ["unwind", "relax"], ["a night owl", "someone active late at night"], ["an early bird", "someone who wakes up early"], ["stick to a schedule", "follow a plan"]],
    tips: ["Use sequence words: first, then, after that, finally.", "Use frequency adverbs correctly: usually, rarely, occasionally.", "Do not list every minute. Choose two or three details."],
  },
  {
    slug: "friends",
    title: "Friends",
    intro: "Friendship questions let you describe people and explain what you value in a relationship.",
    qa: [
      { q: "Do you have many friends?", a: "I have a small group of close friends and a larger circle of acquaintances. I would rather have a few people I can truly rely on than many casual contacts." },
      { q: "How often do you see your friends?", a: "Usually once or twice a week. We meet for coffee or play football, and we chat online almost every day when we are busy." },
      { q: "What do you usually do together?", a: "We go to the cinema, try new restaurants or simply walk around the city. Honestly, the activity is not important; I just enjoy their company." },
      { q: "What makes a good friend?", a: "Honesty and loyalty. A good friend tells you the truth politely, supports you in difficult times and celebrates your success without jealousy." },
      { q: "Is it easy to make friends in your country?", a: "Generally yes. People are sociable and hospitable, and shared activities such as sports or studying together make it simple to connect." },
      { q: "Do you keep in touch with friends from your childhood?", a: "A few of them. We live in different cities now, but we send messages and meet when I visit my hometown. Some friendships last for life." },
    ],
    vocab: [["close-knit", "very friendly and supportive"], ["acquaintance", "someone you know slightly"], ["reliable", "can be trusted"], ["hang out", "spend time together"], ["keep in touch", "stay in contact"], ["see eye to eye", "agree with each other"], ["lifelong friend", "a friend for your whole life"]],
    tips: ["Describe qualities with a short example: “She always listens, for instance when…”.", "Use “would rather” to show preference.", "Avoid giving long personal stories. Two sentences are enough."],
  },
  {
    slug: "reading",
    title: "Reading",
    intro: "Reading questions are about habits and preferences. Be specific about types of books and when you read.",
    qa: [
      { q: "Do you enjoy reading?", a: "Yes, I do. Reading helps me relax and learn new vocabulary. I try to read at least twenty pages before bed every night." },
      { q: "What kinds of books do you like?", a: "Mainly biographies and popular science. I like learning how successful people think, and science books explain complicated ideas in an interesting way." },
      { q: "Do you prefer paper books or e-books?", a: "I prefer paper books because I like the feel of the pages and they do not tire my eyes. But e-books are handy when I travel because I can carry a whole library." },
      { q: "Did you read a lot as a child?", a: "My parents read to me every evening, so I developed the habit early. I loved adventure stories and often finished a book in a weekend." },
      { q: "Do you think people read less nowadays?", a: "Probably, because of smartphones and social media. However, audiobooks and online articles mean people are still consuming a lot of written content." },
      { q: "Where do you usually read?", a: "In my bedroom or on the bus. A quiet place is best, but I can concentrate on a good book almost anywhere." },
    ],
    vocab: [["page-turner", "an exciting book"], ["bookworm", "a person who loves reading"], ["biography", "a book about someone's life"], ["bestseller", "a very popular book"], ["skim", "read quickly for the main idea"], ["audiobook", "a recording of a book"], ["absorbed in", "completely interested in"]],
    tips: ["Mention the type of book, not only the word “book”.", "Give a reason for each preference.", "Use comparison: “Paper books are more … than e-books.”"],
  },
  {
    slug: "technology",
    title: "Technology and the Internet",
    intro: "Technology questions are common. Mix personal habits with a balanced opinion.",
    qa: [
      { q: "How often do you use the internet?", a: "Almost all day. I use it for studying, communicating with friends and entertainment. It is hard to imagine my life without it." },
      { q: "What do you mostly use your phone for?", a: "Messaging, listening to music and checking the news. I also use language-learning apps for about twenty minutes every day." },
      { q: "Do you think people spend too much time online?", a: "Many do. It is easy to lose track of time on social media, which can affect sleep and concentration, so I try to set limits for myself." },
      { q: "What technology could you not live without?", a: "My laptop. I use it for coursework, research and creative projects, and it connects me with the rest of the world." },
      { q: "Are older people good at using technology?", a: "Some are, but many find it confusing at first. In my family, I often help my grandparents video call relatives, and they are learning quickly." },
      { q: "How has technology changed the way you study?", a: "Enormously. I can find information instantly, watch lessons online and collaborate with classmates without meeting in person, which saves a lot of time." },
    ],
    vocab: [["cutting-edge", "very modern and advanced"], ["user-friendly", "easy to use"], ["glued to the screen", "looking at a screen constantly"], ["go online", "connect to the internet"], ["gadget", "a small useful device"], ["tech-savvy", "skilled with technology"], ["addictive", "hard to stop using"]],
    tips: ["Balance advantages and disadvantages: “On the one hand… on the other hand…”.", "Use present perfect for change: “Technology has changed…”.", "Give concrete examples: apps, devices, situations."],
  },
];
