import type { Part1Topic } from './types.js';

export const PART1_MORE: Part1Topic[] = [
  {
    slug: "family",
    title: "Family",
    intro: "Family questions are warm and personal. Describe people briefly and add one detail that makes your answer specific.",
    qa: [
      { q: "Tell me about your family.", a: "There are five of us: my parents, my younger brother, my grandmother and me. We live together in one house, so we spend a lot of time with each other, especially at dinner." },
      { q: "Do you spend much time with your family?", a: "Yes, quite a lot. We have dinner together every evening, and on weekends we often visit relatives or go for a picnic if the weather is nice." },
      { q: "Who are you closest to in your family?", a: "My mother, I would say. She listens carefully and gives honest advice, so whenever I have a problem, she is the first person I talk to." },
      { q: "Do you look like anyone in your family?", a: "People say I look like my father because of our eyes and smile, although my personality is closer to my mother's. I am calmer than he is." },
      { q: "What do you usually do together as a family?", a: "We cook traditional meals, watch films on Friday evenings and sometimes travel to my grandparents' village. Those trips are my favourite part of the year." },
      { q: "Is family important in your culture?", a: "Very much. Families are close, and several generations often live nearby. People help each other with money, childcare and big decisions." },
    ],
    vocab: [["close-knit", "very friendly and supportive"], ["extended family", "relatives beyond parents and children"], ["take after", "be similar to a parent"], ["get along", "have a good relationship"], ["look up to", "admire and respect"], ["generation", "people of a similar age in a family"], ["upbringing", "the way you were raised"]],
    tips: ["Give one specific detail about each person you mention.", "Use “we” stories to show shared habits.", "Avoid listing names; two or three sentences are enough."],
  },
  {
    slug: "neighbours",
    title: "Neighbours",
    intro: "Neighbour questions test everyday vocabulary. Describe relationships and give a short example.",
    qa: [
      { q: "Do you know your neighbours?", a: "Yes, I know most of them. We live in a small building, so we meet on the stairs and often chat for a few minutes about the news or the weather." },
      { q: "How often do you see your neighbours?", a: "Almost every day. On weekends we sometimes drink tea together in the yard, and during holidays we exchange small gifts or sweets." },
      { q: "Have you ever helped a neighbour?", a: "Yes, last winter I helped an elderly neighbour carry her shopping home. It was a small thing, but she was very grateful and invited me for tea." },
      { q: "Is it important to have good neighbours?", a: "Definitely. Good neighbours make you feel safe and can help in an emergency, whereas noisy or unfriendly ones can make daily life stressful." },
      { q: "Do people in your country usually know their neighbours?", a: "In most places, yes. Neighbourhoods are close, and people often attend each other's weddings and family events, which builds strong relationships." },
      { q: "Would you like to live next to a friend?", a: "It sounds nice, but I think a little distance helps friendships. I would prefer to live nearby, perhaps a few streets away, rather than next door." },
    ],
    vocab: [["neighbourhood", "the area where you live"], ["on good terms", "having a friendly relationship"], ["close community", "people who know and support each other"], ["noisy", "making a lot of sound"], ["hospitable", "welcoming to guests"], ["borrow", "take something to return later"], ["lend a hand", "help"]],
    tips: ["Mix a general answer with one real example.", "Use present simple for habits: “we often chat”.", "Show contrast with “whereas” or “however”."],
  },
  {
    slug: "home-and-accommodation",
    title: "Home and Accommodation",
    intro: "You will often be asked about where you live. Describe the place, what you like and what you would change.",
    qa: [
      { q: "Do you live in a house or an apartment?", a: "I live in an apartment on the third floor of a quiet building. It has three rooms and a small balcony where I like to drink tea in the evening." },
      { q: "What is your favourite room at home?", a: "My bedroom, because it is my private space. I have a desk by the window where I study, and the view of the trees helps me concentrate." },
      { q: "How long have you lived there?", a: "For about eight years. We moved when I was in primary school, so most of my memories are connected with this place." },
      { q: "Would you like to move to a different home in the future?", a: "Maybe. I would like a bigger place with a garden, preferably in a quieter area, but I would still want to be close to my family." },
      { q: "What do you like about your neighbourhood?", a: "It is peaceful and green, and there are shops, a park and a bus stop within five minutes. Everything I need is nearby." },
      { q: "Is there anything you would change about your home?", a: "I would add more storage space, because it fills up quickly. A larger kitchen would also be useful when the whole family cooks together." },
    ],
    vocab: [["spacious", "having plenty of room"], ["cosy", "warm and comfortable"], ["convenient location", "close to useful places"], ["storage space", "room to keep things"], ["residential area", "a part of town where people live"], ["move house", "go to live in a new home"], ["well-equipped", "having everything needed"]],
    tips: ["Describe size, location and atmosphere with a few adjectives.", "Use “I would” for imaginary changes.", "Mention one detail, such as a balcony or a view."],
  },
  {
    slug: "shopping",
    title: "Shopping",
    intro: "Shopping questions are about habits and preferences. Compare options and give reasons.",
    qa: [
      { q: "Do you like shopping?", a: "I enjoy it when I need something specific, but I do not like wandering around shopping centres for hours. I prefer to go with a list and finish quickly." },
      { q: "Do you prefer shopping online or in stores?", a: "Online, mostly, because it is faster and I can compare prices easily. For clothes, though, I still like to try things on in a shop." },
      { q: "What was the last thing you bought?", a: "A pair of headphones. My old ones broke, so I read several reviews online and chose a model that was comfortable and not too expensive." },
      { q: "Do you usually go shopping alone or with others?", a: "Usually with a friend. They give me an honest opinion, and shopping is more fun when you can chat while you walk around." },
      { q: "Are there any markets near where you live?", a: "Yes, there is a large bazaar about ten minutes away. It sells fresh fruit, vegetables and spices, and the prices are lower than in supermarkets." },
      { q: "Do you think people buy too many things nowadays?", a: "I think many do. Discounts and online advertising encourage people to buy things they do not really need, and this creates a lot of waste." },
    ],
    vocab: [["browse", "look at things without a plan to buy"], ["bargain", "something cheap for its quality"], ["impulse buy", "an unplanned purchase"], ["retail therapy", "shopping to feel better"], ["compare prices", "check which is cheaper"], ["discount", "a reduction in price"], ["bazaar", "a traditional market"]],
    tips: ["Give a clear preference and a reason.", "Use a recent personal example for variety.", "Compare with “whereas” and “on the other hand”."],
  },
  {
    slug: "sports",
    title: "Sports",
    intro: "Sports questions let you talk about habits and opinions. Mention what you do and why it matters.",
    qa: [
      { q: "Do you play any sports?", a: "Yes, I play football twice a week with friends. It is a great way to stay fit, and I also enjoy the teamwork." },
      { q: "What sports are popular in your country?", a: "Football is the most popular, followed by wrestling and boxing. Many young people also enjoy running and going to the gym." },
      { q: "Did you play sports as a child?", a: "Yes, a lot. I played in the yard with my cousins every afternoon, and at school I joined the basketball team for two years." },
      { q: "Do you prefer watching sports or playing them?", a: "Playing, definitely. Watching a match is fun, but nothing compares with being on the pitch and feeling the energy of the game." },
      { q: "Is it important for children to do sports?", a: "Yes. Sports keep children healthy, teach discipline and teamwork, and give them a break from studying and screens." },
      { q: "Would you like to try a new sport?", a: "I would love to try swimming seriously. I only swim for fun at the moment, but I would like to learn proper technique." },
    ],
    vocab: [["keep fit", "stay physically healthy"], ["teamwork", "working well with others"], ["competitive", "wanting to win"], ["stamina", "physical energy to continue"], ["work out", "exercise"], ["pitch", "a field for sports"], ["spectator", "a person who watches"]],
    tips: ["Use frequency words: twice a week, every weekend.", "Say why a sport matters for health or character.", "Use “would” for sports you want to try."],
  },
  {
    slug: "public-transport",
    title: "Public Transport",
    intro: "Transport questions are practical. Compare ways of travelling and mention advantages and problems.",
    qa: [
      { q: "How do you usually travel around your city?", a: "I mostly take the metro and sometimes the bus. The metro is fast and cheap, and it avoids traffic jams, which can be terrible at rush hour." },
      { q: "Is public transport good in your city?", a: "It is improving. The metro is clean and reliable, but buses can be crowded in the mornings, and some routes do not run late at night." },
      { q: "Do you prefer buses or trains?", a: "Trains, because they are faster and more comfortable. On a bus, I often get stuck in traffic, whereas the train arrives on time." },
      { q: "How could public transport be improved?", a: "More frequent buses, better night services and an easy mobile app for tickets would help a lot. Also, more bus lanes would make journeys faster." },
      { q: "Do many people use bicycles where you live?", a: "Not as many as in some countries. There are few cycle lanes, so people feel it is unsafe, but the number of cyclists is slowly growing." },
      { q: "Would you ever want to travel to work by car?", a: "Only if the distance were long. Driving in the city is stressful and parking is expensive, so I would rather use the metro." },
    ],
    vocab: [["rush hour", "busy time when people travel to or from work"], ["commute", "travel regularly to work"], ["punctual", "arriving on time"], ["traffic jam", "a long line of stopped cars"], ["overcrowded", "too full of people"], ["frequency", "how often something happens"], ["fare", "money paid for a journey"]],
    tips: ["Compare two options and finish with your preference.", "Use “whereas” to contrast.", "Mention one problem and one possible solution."],
  },
  {
    slug: "clothes",
    title: "Clothes",
    intro: "Clothing questions are light. Talk about style, comfort and occasions with simple descriptive language.",
    qa: [
      { q: "What kind of clothes do you usually wear?", a: "Mostly casual clothes like jeans and a shirt or a sweater. They are comfortable, and I can wear them at university and with friends." },
      { q: "Do you like to follow fashion?", a: "A little. I like to look neat, but I do not buy new clothes every season. I prefer a few good items that match each other." },
      { q: "Do you wear formal clothes?", a: "Only on special occasions, such as weddings or interviews. I like how smart a suit looks, but it is not very comfortable for every day." },
      { q: "Where do you usually buy clothes?", a: "In shopping centres, and sometimes online. I check the size and reviews carefully because returning items is a hassle." },
      { q: "Do people in your country wear traditional clothes?", a: "Yes, on holidays and at weddings. Many people love colourful national dresses and embroidered caps, which are an important part of our culture." },
      { q: "Is it important to dress well at work?", a: "I think so. Neat clothes make a good first impression and show respect for colleagues and customers, although comfort is also important." },
    ],
    vocab: [["casual", "relaxed and informal"], ["formal wear", "clothes for special or official events"], ["trendy", "fashionable"], ["comfortable", "pleasant to wear"], ["first impression", "the opinion formed when you first meet someone"], ["embroidered", "decorated with stitched patterns"], ["match", "look good together"]],
    tips: ["Use adjectives like casual, smart and comfortable.", "Link clothes to occasions.", "Mention culture when it fits the question."],
  },
  {
    slug: "photography",
    title: "Photography",
    intro: "Photography questions combine habits and memories. Describe what you photograph and why.",
    qa: [
      { q: "Do you like taking photos?", a: "Yes, especially when I travel. Photos help me remember small details that I might forget, such as the colours of a street or a meal." },
      { q: "What do you usually take photos of?", a: "Landscapes and food, mostly. I also like photographing friends when they are not expecting it, because those natural pictures are the best." },
      { q: "Do you prefer taking photos with a phone or a camera?", a: "A phone, for convenience. It is always in my pocket, and modern phone cameras are good enough for most situations." },
      { q: "Do you share your photos online?", a: "Sometimes. I post my best pictures on social media, but I keep personal ones, such as family photos, in a private folder." },
      { q: "Do you keep printed photos?", a: "A few. My parents have albums with old pictures, and I love looking through them because they show how different life was." },
      { q: "Why do people like taking photos?", a: "They want to keep memories and share experiences. A picture can bring back emotions quickly, even many years later." },
    ],
    vocab: [["capture a moment", "record a special moment"], ["candid", "natural, not posed"], ["snap", "take a quick photo"], ["scenery", "natural views"], ["keepsake", "an item kept for memories"], ["album", "a book for photos"], ["share online", "post on the internet"]],
    tips: ["Use past tenses for a recent photo story.", "Explain why photos matter emotionally.", "Contrast phone and camera with one clear reason."],
  },
  {
    slug: "sleep",
    title: "Sleep",
    intro: "Sleep questions are about routines. Be clear about times and habits and show cause and effect.",
    qa: [
      { q: "How many hours do you usually sleep?", a: "About seven hours on weekdays. I try to go to bed before midnight, but sometimes I stay up studying and feel tired the next day." },
      { q: "Do you take naps during the day?", a: "Occasionally, on weekends. A short nap of twenty minutes refreshes me, but if I sleep longer, I feel even more tired afterwards." },
      { q: "Do you find it easy to fall asleep?", a: "Usually yes, but it depends on my day. If I use my phone late at night, my mind stays active, and it takes me longer to relax." },
      { q: "Is sleep important?", a: "Absolutely. Without enough sleep, I cannot concentrate, my mood gets worse, and I make more mistakes at work or in class." },
      { q: "What do you do if you cannot sleep?", a: "I put my phone away, read a few pages of a book or listen to calm music. Usually, that helps me fall asleep within half an hour." },
      { q: "Do you prefer sleeping late in the morning?", a: "On weekends, yes, but only up to a point. If I sleep too long, I lose half of the day, so I try to get up by nine." },
    ],
    vocab: [["fall asleep", "start sleeping"], ["stay up late", "go to bed late"], ["well-rested", "having had enough sleep"], ["nap", "a short sleep in the day"], ["sleep deprived", "not getting enough sleep"], ["wind down", "relax before bed"], ["alarm clock", "a device that wakes you"]],
    tips: ["Give actual times and amounts.", "Use “if” sentences to show consequences.", "Mention one habit that helps you sleep."],
  },
  {
    slug: "health-and-fitness",
    title: "Health and Fitness",
    intro: "Health questions are common. Talk about habits you have and habits you would like to build.",
    qa: [
      { q: "Do you do anything to stay healthy?", a: "I try to walk at least thirty minutes a day, drink enough water and eat vegetables. I am not perfect, but these small habits make a difference." },
      { q: "Do you think you are a healthy person?", a: "Fairly healthy. I rarely get ill, although I should exercise more often and sleep earlier. My diet is generally balanced." },
      { q: "Do you go to the gym?", a: "I used to go three times a week, but I stopped when my university schedule became busy. I now do short home workouts instead." },
      { q: "What do you do when you feel stressed?", a: "I go for a walk or listen to music. Moving around clears my head, and talking to a friend also helps me feel calmer." },
      { q: "Is it expensive to stay healthy in your country?", a: "It can be. Fresh food and gym memberships cost money, but walking, running in the park and cooking at home are cheap ways to stay in good shape." },
      { q: "Do you think people today are healthier than in the past?", a: "In some ways, yes, because medical care is better and people know more about nutrition. However, many people exercise less because of desk jobs." },
    ],
    vocab: [["balanced diet", "eating different foods in healthy amounts"], ["in good shape", "physically fit"], ["workout", "a session of exercise"], ["stress relief", "a way to reduce stress"], ["sedentary lifestyle", "a lifestyle with little movement"], ["nutrition", "the food you eat and its effect"], ["check-up", "a medical examination"]],
    tips: ["Be honest and realistic; perfect habits sound unnatural.", "Use “used to” for past routines.", "Contrast past and present with “however”."],
  },
  {
    slug: "festivals",
    title: "Festivals and Celebrations",
    intro: "Festival questions invite description. Use sensory detail and say how the day feels.",
    qa: [
      { q: "What is your favourite festival?", a: "Navruz, the spring festival. The weather is warm, people cook special food like sumalak, and there are concerts and fairs in every neighbourhood." },
      { q: "How do you celebrate it?", a: "My family gathers at my grandparents' house, and we prepare traditional dishes together. Children play games outside while adults chat and drink tea." },
      { q: "Do you think festivals are important?", a: "Yes. They keep traditions alive and bring families and communities together, which is something we need in our busy modern lives." },
      { q: "Have festivals changed since you were a child?", a: "A little. There are more public events and decorations now, but at home the customs are the same as when I was young." },
      { q: "Is there a festival you would like to experience abroad?", a: "I would love to see the lantern festival in Asia. The pictures of thousands of glowing lights look magical." },
      { q: "Do you prefer big celebrations or small family gatherings?", a: "Small gatherings. They feel warmer and more personal, and I can really talk to everyone instead of just shouting over loud music." },
    ],
    vocab: [["tradition", "a custom passed down over time"], ["festive atmosphere", "a joyful, celebratory mood"], ["gather", "come together"], ["customs", "traditional ways of behaving"], ["decorations", "things used to make a place look special"], ["public holiday", "an official day off"], ["feast", "a large special meal"]],
    tips: ["Use present simple for annual traditions.", "Describe food, sounds and feelings.", "Compare past and present with “used to”."],
  },
  {
    slug: "pets-and-animals",
    title: "Pets and Animals",
    intro: "Animal questions are friendly. Answer with a short story and your opinion.",
    qa: [
      { q: "Do you have a pet?", a: "I have a cat called Luna. We adopted her two years ago, and she has become a real member of the family, always waiting for me at the door." },
      { q: "Are pets popular in your country?", a: "More and more. Cats and small dogs are common in cities, while in villages people keep animals mainly for work or protection." },
      { q: "Would you like to have a different pet?", a: "Perhaps a dog, but they need a lot of attention and walks, and my schedule is too busy at the moment." },
      { q: "Do you like visiting zoos?", a: "I used to enjoy it as a child. Now I feel a bit uncomfortable seeing animals in small cages, so I prefer wildlife parks." },
      { q: "Why do people keep pets?", a: "For company and joy. Pets reduce loneliness, and taking care of an animal teaches children responsibility." },
      { q: "Is it expensive to keep a pet?", a: "It can be, because of food, vaccinations and vet visits. Before getting a pet, people should be sure they can afford it." },
    ],
    vocab: [["adopt", "take an animal as your own"], ["companion", "someone who keeps you company"], ["vet", "an animal doctor"], ["responsibility", "a duty to look after something"], ["wildlife", "wild animals in nature"], ["stray", "an animal without a home"], ["affectionate", "showing love"]],
    tips: ["Add a short personal story.", "Give one reason with “because”.", "Show a balanced view when talking about zoos."],
  },
  {
    slug: "languages",
    title: "Languages",
    intro: "Language questions are very common. Talk about learning habits, difficulties and goals.",
    qa: [
      { q: "What languages do you speak?", a: "Uzbek and Russian since childhood, and I am learning English. I can have everyday conversations in English, but I want to speak more fluently." },
      { q: "Why are you learning English?", a: "For my studies and career. Most of the best resources and jobs in my field require English, and it also lets me communicate with people from other countries." },
      { q: "What is difficult about learning English?", a: "Pronunciation and phrasal verbs. Some words are written one way but pronounced differently, and phrasal verbs have so many meanings." },
      { q: "How do you practise English?", a: "I watch series with subtitles, read short articles and talk to a friend twice a week. Writing about my day also helps me use new words." },
      { q: "Do you think everyone should learn a foreign language?", a: "Yes, because it opens doors to new cultures and jobs. It also trains your brain and makes travelling much more enjoyable." },
      { q: "Would you like to learn another language?", a: "Japanese, maybe. I enjoy the culture, and I would like to understand anime and manga without translation." },
    ],
    vocab: [["fluent", "able to speak smoothly"], ["pronunciation", "the way words are said"], ["phrasal verb", "a verb with a particle, like give up"], ["subtitles", "text translations on screen"], ["native speaker", "a person who learned the language as a child"], ["vocabulary", "the words you know"], ["practise regularly", "do something often to improve"]],
    tips: ["Give concrete methods you use.", "Mention a goal to show motivation.", "Use present continuous for “I am learning”."],
  },
  {
    slug: "museums-and-history",
    title: "Museums and History",
    intro: "Museum questions mix habits with opinions. Mention a place you know and why history matters.",
    qa: [
      { q: "Do you like visiting museums?", a: "Yes, when I have time. I enjoy history museums especially, because seeing real objects makes the past feel more alive than reading a book." },
      { q: "When did you last visit a museum?", a: "A few months ago, I went to the history museum in my city with my friends. We spent about two hours there and learned a lot about local traditions." },
      { q: "Are museums popular in your country?", a: "They are popular with tourists and school groups, but fewer local adults visit them regularly. I think better advertising could change that." },
      { q: "Do you think museums should be free?", a: "Ideally yes, or at least cheap for students. Education should be accessible to everyone, but museums also need money to look after their collections." },
      { q: "Are you interested in history?", a: "Quite. I like learning how people lived in the past, and it helps me understand why our society works the way it does today." },
      { q: "How can museums attract more young people?", a: "By using technology, such as interactive screens and virtual tours, and by organising events like night visits and workshops." },
    ],
    vocab: [["exhibit", "an item displayed in a museum"], ["artefact", "an object made by people in the past"], ["heritage", "history and traditions passed down"], ["guided tour", "a visit led by an expert"], ["interactive", "allowing you to take part"], ["collection", "a group of items kept together"], ["admission fee", "the price to enter"]],
    tips: ["Give a recent example with past simple.", "State an opinion and a reason.", "Suggest a solution when asked how to improve something."],
  },
  {
    slug: "birthdays",
    title: "Birthdays",
    intro: "Birthday questions are light and personal. Use past tenses for memories and present simple for customs.",
    qa: [
      { q: "How do you usually celebrate your birthday?", a: "Quietly, with my family and a few close friends. My mother bakes a cake, and we have dinner together at home." },
      { q: "What was your best birthday?", a: "My sixteenth. My friends organised a surprise party in the park, and I really did not expect it. I still remember how happy I felt." },
      { q: "Do you prefer to receive or give gifts?", a: "Giving, actually. I enjoy thinking about what a person would like and seeing their face when they open the present." },
      { q: "Is it common to have big birthday parties in your country?", a: "For children, yes, with games and cakes. Adults usually celebrate in smaller groups, perhaps at a restaurant or at home." },
      { q: "What is a good birthday gift?", a: "Something personal and useful, such as a book or a handwritten letter. I do not think the price matters as much as the thought." },
      { q: "Do you think birthdays are more important for children than adults?", a: "Probably, because children are excited by presents and parties. Adults often just want a relaxed day with the people they love." },
    ],
    vocab: [["surprise party", "a secret celebration for someone"], ["blow out candles", "extinguish candles on a cake"], ["thoughtful gift", "a present chosen with care"], ["celebrate", "do something special for an event"], ["gathering", "a meeting of people"], ["greeting card", "a card with a message"], ["milestone birthday", "an important age, like 18 or 30"]],
    tips: ["Use past simple for the best birthday story.", "Add one emotion word: thrilled, touched, surprised.", "Compare children and adults with “whereas”."],
  },
  {
    slug: "mobile-phones",
    title: "Mobile Phones",
    intro: "Phone questions are about daily habits. Balance advantages and disadvantages.",
    qa: [
      { q: "How often do you use your phone?", a: "Many times a day. I use it for messages, music, maps and studying, so it is difficult to imagine a day without it." },
      { q: "What do you use your phone for most?", a: "Messaging and social media, followed by learning apps. I also take most of my photos with it." },
      { q: "Do you think people use their phones too much?", a: "Many do. People check their phones during meals and conversations, which reduces real communication, so I try to put mine away when I am with friends." },
      { q: "Can you remember your first phone?", a: "Yes, it was a simple Nokia with buttons. I could only call and send messages, but I was so proud of it at that age." },
      { q: "Do you prefer calling or texting?", a: "Texting, because it is quicker and I can reply when I have time. For important or emotional matters, though, I prefer to call." },
      { q: "How have phones changed daily life?", a: "They have made life more convenient, because we can pay, navigate and learn from one device. On the other hand, people feel they must always be reachable." },
    ],
    vocab: [["glued to the screen", "looking at a screen all the time"], ["notification", "an alert on a device"], ["multi-purpose", "used for many things"], ["screen time", "time spent using screens"], ["reachable", "available to contact"], ["data plan", "a mobile internet package"], ["switch off", "turn off a device"]],
    tips: ["Use present simple for habits and present perfect for change.", "Give both a benefit and a drawback.", "Add a personal habit, like putting your phone away at dinner."],
  },
  {
    slug: "television",
    title: "Television and Films",
    intro: "Entertainment questions let you talk about taste. Name genres and say why you enjoy them.",
    qa: [
      { q: "Do you watch much television?", a: "Not really. I mostly watch series and films on my laptop in the evening, and I rarely turn on a regular TV channel." },
      { q: "What kind of programmes do you like?", a: "Documentaries and crime series. Documentaries teach me something new, while crime series keep me interested with their surprising plots." },
      { q: "Did you watch a lot of TV as a child?", a: "Yes, cartoons every afternoon. My brother and I used to argue about the remote, and my parents had to set rules." },
      { q: "Do you prefer watching films at the cinema or at home?", a: "At home, because it is cheaper and more comfortable. But for big action films, the cinema experience with a large screen and loud sound is hard to beat." },
      { q: "Do you think television is good for children?", a: "In moderation, yes. Educational programmes can teach them a lot, but too much screen time harms their concentration and sleep." },
      { q: "Is there a TV show you would recommend?", a: "A nature documentary series about oceans. The pictures are stunning, and I learned so much about marine life." },
    ],
    vocab: [["binge-watch", "watch many episodes at once"], ["plot", "the story of a film or series"], ["documentary", "a factual film"], ["genre", "a type of film or book"], ["gripping", "very exciting"], ["episode", "one part of a series"], ["in moderation", "not too much"]],
    tips: ["Name specific genres rather than saying “all kinds”.", "Give a reason with “because” or “while”.", "Use “used to” for childhood habits."],
  },
  {
    slug: "art-and-drawing",
    title: "Art and Drawing",
    intro: "Art questions are personal. Even if you are not an artist, describe what you enjoy and why.",
    qa: [
      { q: "Do you like drawing or painting?", a: "I like drawing as a way to relax, although I am not very talented. I sometimes sketch people or landscapes in a notebook." },
      { q: "Did you learn art at school?", a: "Yes, we had one lesson per week. I enjoyed it because the teacher gave us freedom to be creative, not just copy pictures." },
      { q: "Do you visit art galleries?", a: "Occasionally. I like modern art because it makes me think, even when I do not completely understand it." },
      { q: "Is art important in education?", a: "Yes. It develops creativity and patience, and it gives students who are not strong in other subjects a chance to succeed." },
      { q: "Do you have any paintings at home?", a: "A few. My mother likes landscape paintings, so there are several in the living room, and one of them was painted by my uncle." },
      { q: "Would you like to improve your drawing skills?", a: "Yes, I would like to take a short course. Learning basic techniques would let me express my ideas better." },
    ],
    vocab: [["sketch", "a quick drawing"], ["gallery", "a place to display art"], ["creative", "using imagination"], ["landscape", "a picture of natural scenery"], ["express yourself", "show your feelings or ideas"], ["talented", "having natural ability"], ["modern art", "art from recent times"]],
    tips: ["It is fine to say you are not an expert; explain what you enjoy.", "Use “would like to” for plans.", "Give a reason why art matters."],
  },
];
