// Uzbek topic word lists for the public SEO section /inglizcha-sozlar: English word, IPA, Uzbek meaning.
export type WordTopic = {
  slug: string; level: 'beginner' | 'elementary' | 'pre-intermediate';
  h1: string; metaTitle: string; metaDesc: string; intro: string;
  words: [en: string, ipa: string, uz: string][];
  phrases: [en: string, uz: string][];
  tip: string; faq: { q: string; a: string }[];
  lesson: [level: string, slug: string]; related: string[];
};

export const WORD_TOPICS: WordTopic[] = [
  {
    slug: 'sonlar-1-100', level: 'beginner',
    h1: `Ingliz tilida sonlar: 1 dan 100 gacha`,
    metaTitle: `Ingliz tilida sonlar 1 dan 100 gacha: o'qilishi va talaffuzi (o'zbekcha)`,
    metaDesc: `Inglizcha sonlar 1 dan 100 gacha, talaffuz transkripsiyasi va o'zbekcha izoh. Teen va ty sonlarining farqi, yosh, telefon raqami va narxni aytish. Jadval va misollar.`,
    intro: `Sonlarni bilish yosh, narx, vaqt va telefon raqamini aytish uchun kerak. Asosiy 20 ta sonni yodlasangiz, qolganlarini qoida bo'yicha tuzasiz: o'nliklar (twenty, thirty...) + birlik (one, two...).`,
    words: [[`zero`,`/ˈzɪərəʊ/`,`nol`],[`one`,`/wʌn/`,`bir`],[`two`,`/tuː/`,`ikki`],[`three`,`/θriː/`,`uch`],[`four`,`/fɔː/`,`to'rt`],[`five`,`/faɪv/`,`besh`],[`six`,`/sɪks/`,`olti`],[`seven`,`/ˈsevn/`,`yetti`],[`eight`,`/eɪt/`,`sakkiz`],[`nine`,`/naɪn/`,`to'qqiz`],[`ten`,`/ten/`,`o'n`],[`eleven`,`/ɪˈlevn/`,`o'n bir`],[`twelve`,`/twelv/`,`o'n ikki`],[`thirteen`,`/ˌθɜːˈtiːn/`,`o'n uch`],[`fourteen`,`/ˌfɔːˈtiːn/`,`o'n to'rt`],[`fifteen`,`/ˌfɪfˈtiːn/`,`o'n besh`],[`sixteen`,`/ˌsɪksˈtiːn/`,`o'n olti`],[`seventeen`,`/ˌsevnˈtiːn/`,`o'n yetti`],[`eighteen`,`/ˌeɪˈtiːn/`,`o'n sakkiz`],[`nineteen`,`/ˌnaɪnˈtiːn/`,`o'n to'qqiz`],[`twenty`,`/ˈtwenti/`,`yigirma`],[`thirty`,`/ˈθɜːti/`,`o'ttiz`],[`forty`,`/ˈfɔːti/`,`qirq`],[`fifty`,`/ˈfɪfti/`,`ellik`],[`sixty`,`/ˈsɪksti/`,`oltmish`],[`seventy`,`/ˈsevnti/`,`yetmish`],[`eighty`,`/ˈeɪti/`,`sakson`],[`ninety`,`/ˈnaɪnti/`,`to'qson`],[`one hundred`,`/wʌn ˈhʌndrəd/`,`yuz`]],
    phrases: [[`I am twenty-five years old.`,`Men yigirma besh yoshdaman.`],[`It costs forty-five thousand sums.`,`Bu qirq besh ming so'm turadi.`],[`My number is nine-nine-eight, nine-zero...`,`Mening raqamim to'qqiz-to'qqiz-sakkiz, to'qqiz-nol...`],[`There are thirty students in my class.`,`Sinfimda o'ttiz nafar o'quvchi bor.`]],
    tip: `Teen (13–19) va ty (30–90) sonlarini adashtirmang: thirteen /θɜːˈtiːn/ da urg'u oxirida («-teen»), thirty /ˈθɜːti/ da boshida. 21 dan 99 gacha o'nlik va birlik defis bilan yoziladi: twenty-one, sixty-four.`,
    faq: [{ q: `Thirteen va thirty farqi nima?`, a: `Thirteen (13) da urg'u oxirgi bo'g'inda va «-teen» uzun aytiladi, thirty (30) da urg'u birinchi bo'g'inda va oxiri qisqa.` }, { q: `Telefon raqami qanday aytiladi?`, a: `Raqamlar birma-bir aytiladi, nol odatda «oh» yoki «zero» deyiladi. Bir xil ikki raqam «double» bilan aytilishi mumkin: 55 — double five.` }],
    lesson: [`beginner`, `numbers-0-20`], related: [`hafta-kunlari-va-oylar`, `ranglar`],
  },
  {
    slug: 'hafta-kunlari-va-oylar', level: 'beginner',
    h1: `Ingliz tilida hafta kunlari va oylar`,
    metaTitle: `Inglizcha hafta kunlari va oylar nomi: talaffuzi va tarjimasi (o'zbekcha)`,
    metaDesc: `Ingliz tilida hafta kunlari (Monday...Sunday) va 12 oy nomi, talaffuzi, o'zbekcha tarjimasi. Katta harf qoidasi, on/in predloglari va sana aytish usullari.`,
    intro: `Hafta kunlari va oylar ingliz tilida har doim bosh harf bilan yoziladi. Ularni bilsangiz, uchrashuv belgilash, jadval tuzish va sanani aytish osonlashadi.`,
    words: [[`Monday`,`/ˈmʌndeɪ/`,`dushanba`],[`Tuesday`,`/ˈtjuːzdeɪ/`,`seshanba`],[`Wednesday`,`/ˈwenzdeɪ/`,`chorshanba`],[`Thursday`,`/ˈθɜːzdeɪ/`,`payshanba`],[`Friday`,`/ˈfraɪdeɪ/`,`juma`],[`Saturday`,`/ˈsætədeɪ/`,`shanba`],[`Sunday`,`/ˈsʌndeɪ/`,`yakshanba`],[`January`,`/ˈdʒænjuəri/`,`yanvar`],[`February`,`/ˈfebruəri/`,`fevral`],[`March`,`/mɑːtʃ/`,`mart`],[`April`,`/ˈeɪprəl/`,`aprel`],[`May`,`/meɪ/`,`may`],[`June`,`/dʒuːn/`,`iyun`],[`July`,`/dʒuˈlaɪ/`,`iyul`],[`August`,`/ˈɔːɡəst/`,`avgust`],[`September`,`/sepˈtembə/`,`sentyabr`],[`October`,`/ɒkˈtəʊbə/`,`oktyabr`],[`November`,`/nəʊˈvembə/`,`noyabr`],[`December`,`/dɪˈsembə/`,`dekabr`],[`weekend`,`/ˌwiːkˈend/`,`dam olish kunlari`],[`today`,`/təˈdeɪ/`,`bugun`],[`tomorrow`,`/təˈmɒrəʊ/`,`ertaga`],[`yesterday`,`/ˈjestədeɪ/`,`kecha`]],
    phrases: [[`The lesson is on Monday.`,`Dars dushanba kuni.`],[`My birthday is in October.`,`Mening tug'ilgan kunim oktyabrda.`],[`See you on Friday!`,`Juma kuni ko'rishamiz!`],[`I was born on 5 May 2000.`,`Men 2000-yil 5-mayda tug'ilganman.`]],
    tip: `Kun nomlari bilan on (on Monday), oylar bilan in (in May), aniq sana bilan on (on 5 May) ishlatiladi. Kunlarning oxiri «-day» /deɪ/ (kun) so'zidan olingan. Wednesday /ˈwenzdeɪ/ da d aytilmaydi.`,
    faq: [{ q: `Inglizcha hafta qaysi kundan boshlanadi?`, a: `Ko'p mamlakatlarda yakshanba (AQSH), Buyuk Britaniyada va xalqaro standartda dushanba hisoblanadi. Jadval va ish haftasi odatda dushanbadan boshlanadi.` }, { q: `Oylar bosh harf bilan yoziladimi?`, a: `Ha. Hafta kunlari va oylar nomlari ingliz tilida doim bosh harf bilan yoziladi.` }],
    lesson: [`beginner`, `days-months-in-on-at`], related: [`sonlar-1-100`, `ranglar`],
  },
  {
    slug: 'ranglar', level: 'beginner',
    h1: `Ranglar ingliz tilida: asosiy ranglar va tarjimasi`,
    metaTitle: `Inglizcha ranglar nomi: 20 ta rang talaffuzi va tarjimasi (o'zbekcha)`,
    metaDesc: `Ranglarning inglizcha nomlari: red, blue, green, yellow va boshqalar. Transkripsiya, o'zbekcha tarjima, qorong'i va och ranglar (dark, light) va gap ichida ishlatish.`,
    intro: `Ranglar sifat bo'lib, otdan oldin keladi: a red car (qizil mashina). Ingliz tilida sifat ko'plik shaklini olmaydi: two red cars.`,
    words: [[`red`,`/red/`,`qizil`],[`blue`,`/bluː/`,`ko'k`],[`green`,`/ɡriːn/`,`yashil`],[`yellow`,`/ˈjeləʊ/`,`sariq`],[`orange`,`/ˈɒrɪndʒ/`,`to'q sariq`],[`purple`,`/ˈpɜːpl/`,`binafsha`],[`pink`,`/pɪŋk/`,`pushti`],[`brown`,`/braʊn/`,`jigarrang`],[`black`,`/blæk/`,`qora`],[`white`,`/waɪt/`,`oq`],[`grey`,`/ɡreɪ/`,`kulrang`],[`gold`,`/ɡəʊld/`,`oltin rang`],[`silver`,`/ˈsɪlvə/`,`kumush rang`],[`dark`,`/dɑːk/`,`to'q`],[`light`,`/laɪt/`,`och`],[`colour`,`/ˈkʌlə/`,`rang`]],
    phrases: [[`What colour is your bag?`,`Sumkangiz qanday rangda?`],[`It is dark blue.`,`U to'q ko'k.`],[`My favourite colour is green.`,`Mening sevimli rangim yashil.`],[`She is wearing a white shirt and black trousers.`,`U oq ko'ylak va qora shim kiygan.`]],
    tip: `Rang so'zi otdan oldin keladi (a blue car), o'zbek tilidagi tartib bilan bir xil. To'q va och rang uchun dark/light ni rang oldiga qo'ying: dark green, light blue. Amerikacha yozuv color, britancha colour.`,
    faq: [{ q: `«Qanday rang?» inglizcha qanday aytiladi?`, a: `What colour is it? Javob: It is red / It's blue.` }, { q: `Colour va color farqi nima?`, a: `Bir xil so'z: colour — britancha, color — amerikacha imlo.` }],
    lesson: [`beginner`, `colours-things`], related: [`sonlar-1-100`, `kiyim-nomlari`],
  },
  {
    slug: 'oila-azolari', level: 'beginner',
    h1: `Oila a'zolari ingliz tilida: family`,
    metaTitle: `Oila a'zolari inglizcha: ota, ona, aka, opa va boshqalar (talaffuzi bilan)`,
    metaDesc: `Ingliz tilida oila a'zolari nomi: mother, father, brother, sister, grandmother va boshqalar. Talaffuz, o'zbekcha tarjima, aka-uka, opa-singil farqi va gap misollari.`,
    intro: `Ingliz tilida «aka» va «uka» uchun bitta so'z (brother), «opa» va «singil» uchun ham bitta so'z (sister) bor. Katta-kichikni aytish kerak bo'lsa, older va younger qo'shiladi.`,
    words: [[`family`,`/ˈfæməli/`,`oila`],[`parents`,`/ˈpeərənts/`,`ota-ona`],[`mother`,`/ˈmʌðə/`,`ona`],[`father`,`/ˈfɑːðə/`,`ota`],[`mum / mom`,`/mʌm/`,`oyi (ona)`],[`dad`,`/dæd/`,`dada (ota)`],[`brother`,`/ˈbrʌðə/`,`aka, uka`],[`sister`,`/ˈsɪstə/`,`opa, singil`],[`son`,`/sʌn/`,`o'g'il`],[`daughter`,`/ˈdɔːtə/`,`qiz`],[`husband`,`/ˈhʌzbənd/`,`er`],[`wife`,`/waɪf/`,`xotin`],[`grandfather`,`/ˈɡrænfɑːðə/`,`bobo`],[`grandmother`,`/ˈɡrænmʌðə/`,`buvi`],[`uncle`,`/ˈʌŋkl/`,`amaki, tog'a`],[`aunt`,`/ɑːnt/`,`xola, amma`],[`cousin`,`/ˈkʌzn/`,`amakivachcha, tog'avachcha`],[`nephew`,`/ˈnefjuː/`,`jiyan (o'g'il)`],[`niece`,`/niːs/`,`jiyan (qiz)`],[`baby`,`/ˈbeɪbi/`,`chaqaloq`]],
    phrases: [[`I have two brothers and one sister.`,`Mening ikkita aka-ukam va bitta opa-singlim bor.`],[`This is my older sister.`,`Bu mening opam.`],[`My grandmother lives with us.`,`Buvim biz bilan yashaydi.`],[`How many people are there in your family?`,`Oilangizda necha kishi bor?`]],
    tip: `Oila haqida gapirganda have (I have two brothers) yoki there are (There are five people in my family) ishlatiladi. Egalik olmoshi bilan: my mother, his brother, her sister. Ota-onaga murojaatda Mum va Dad deyiladi.`,
    faq: [{ q: `Aka va uka inglizchada qanday ajratiladi?`, a: `Ikkalasi brother. Katta bo'lsa older brother (big brother), kichik bo'lsa younger brother (little brother).` }, { q: `Amaki, tog'a, xola va amma qanday aytiladi?`, a: `Uncle (amaki, tog'a) va aunt (xola, amma): ingliz tilida ota yoki ona tomondan ajratilmaydi.` }],
    lesson: [`beginner`, `have-got-family`], related: [`kasblar`, `salomlashish-iboralari`],
  },
  {
    slug: 'salomlashish-iboralari', level: 'beginner',
    h1: `Ingliz tilida salomlashish va tanishish iboralari`,
    metaTitle: `Inglizcha salomlashish: Hello, How are you va tanishuv iboralari (tarjimasi bilan)`,
    metaDesc: `Ingliz tilida salomlashish, xayrlashish, tanishish va minnatdorchilik iboralari: Hello, How are you, Nice to meet you. Rasmiy va norasmiy variantlar, tarjima va javoblar.`,
    intro: `Salomlashish iboralarini bilsangiz, ingliz tilidagi har qanday suhbatni boshlay olasiz. Quyida kundalik hayot uchun eng kerakli iboralar va ularga javoblar.`,
    words: [[`Hello`,`/həˈləʊ/`,`Salom`],[`Hi`,`/haɪ/`,`Salom (norasmiy)`],[`Good morning`,`/ɡʊd ˈmɔːnɪŋ/`,`Xayrli tong`],[`Good afternoon`,`/ɡʊd ˌɑːftəˈnuːn/`,`Xayrli kun`],[`Good evening`,`/ɡʊd ˈiːvnɪŋ/`,`Xayrli kech`],[`Goodbye`,`/ˌɡʊdˈbaɪ/`,`Xayr`],[`Bye`,`/baɪ/`,`Xayr (norasmiy)`],[`See you later`,`/siː juː ˈleɪtə/`,`Keyin ko'rishamiz`],[`Please`,`/pliːz/`,`Iltimos`],[`Thank you`,`/ˈθæŋk juː/`,`Rahmat`],[`You're welcome`,`/jɔː ˈwelkəm/`,`Arzimaydi`],[`Sorry`,`/ˈsɒri/`,`Kechirasiz`],[`Excuse me`,`/ɪkˈskjuːs miː/`,`Kechirasiz (e'tibor jalb qilish)`],[`Nice to meet you`,`/naɪs tə miːt juː/`,`Tanishganimdan xursandman`]],
    phrases: [[`How are you? — I'm fine, thank you. And you?`,`Ahvolingiz qanday? — Yaxshi, rahmat. O'zingiz-chi?`],[`What's your name? — My name is Aziza.`,`Ismingiz nima? — Mening ismim Aziza.`],[`Where are you from? — I'm from Uzbekistan.`,`Siz qayerdansiz? — Men O'zbekistondanman.`],[`Nice to meet you, too.`,`Men ham tanishganimdan xursandman.`],[`See you tomorrow!`,`Ertaga ko'rishamiz!`]],
    tip: `«How are you?» ko'pincha haqiqiy savol emas, salomlashish shakli: qisqa javob (Fine, thanks. And you?) yetarli. Rasmiy vaziyatda Good morning/afternoon, do'stlar orasida Hi ishlatiladi. Sorry — xato uchun, Excuse me — e'tibor jalb qilish yoki yo'l so'rash uchun.`,
    faq: [{ q: `«How are you?» ga qanday javob beriladi?`, a: `I'm fine, thanks. And you? yoki I'm good / Not bad. Uzoq tushuntirish shart emas.` }, { q: `Salom va xayr rasmiy qanday aytiladi?`, a: `Salomlashish: Good morning / Good afternoon / Good evening. Xayrlashish: Goodbye, Have a nice day.` }],
    lesson: [`beginner`, `hello-greetings`], related: [`oila-azolari`, `kasblar`],
  },
  {
    slug: 'kasblar', level: 'beginner',
    h1: `Kasblar nomi ingliz tilida (jobs)`,
    metaTitle: `Inglizcha kasblar nomi: 30 ta kasb talaffuzi va tarjimasi (o'zbekcha)`,
    metaDesc: `Ingliz tilida kasblar nomi: teacher, doctor, engineer, driver va boshqalar. Transkripsiya, o'zbekcha tarjima, a/an qoidasi va «Siz kim bo'lib ishlaysiz?» savoliga javob.`,
    intro: `Kasbni aytganda to be fe'li va a/an kerak: She is a doctor. «Siz nima ish qilasiz?» savoliga What do you do? deb so'raladi.`,
    words: [[`teacher`,`/ˈtiːtʃə/`,`o'qituvchi`],[`student`,`/ˈstjuːdnt/`,`talaba, o'quvchi`],[`doctor`,`/ˈdɒktə/`,`shifokor`],[`nurse`,`/nɜːs/`,`hamshira`],[`engineer`,`/ˌendʒɪˈnɪə/`,`muhandis`],[`driver`,`/ˈdraɪvə/`,`haydovchi`],[`cook`,`/kʊk/`,`oshpaz`],[`waiter`,`/ˈweɪtə/`,`ofitsiant`],[`policeman`,`/pəˈliːsmən/`,`politsiyachi`],[`lawyer`,`/ˈlɔːjə/`,`advokat`],[`accountant`,`/əˈkaʊntənt/`,`buxgalter`],[`programmer`,`/ˈprəʊɡræmə/`,`dasturchi`],[`manager`,`/ˈmænɪdʒə/`,`menejer`],[`businessman`,`/ˈbɪznəsmən/`,`tadbirkor`],[`farmer`,`/ˈfɑːmə/`,`dehqon`],[`builder`,`/ˈbɪldə/`,`quruvchi`],[`dentist`,`/ˈdentɪst/`,`tish shifokori`],[`pilot`,`/ˈpaɪlət/`,`uchuvchi`],[`singer`,`/ˈsɪŋə/`,`qo'shiqchi`],[`journalist`,`/ˈdʒɜːnəlɪst/`,`jurnalist`],[`shop assistant`,`/ʃɒp əˈsɪstənt/`,`sotuvchi`],[`hairdresser`,`/ˈheədresə/`,`sartarosh`],[`artist`,`/ˈɑːtɪst/`,`rassom`],[`secretary`,`/ˈsekrətri/`,`kotiba`]],
    phrases: [[`What do you do? — I'm a teacher.`,`Nima ish qilasiz? — Men o'qituvchiman.`],[`My father is an engineer.`,`Otam muhandis.`],[`She works in a hospital. She is a nurse.`,`U kasalxonada ishlaydi. U hamshira.`],[`I want to be a doctor.`,`Men shifokor bo'lmoqchiman.`]],
    tip: `Kasb oldida a yoki an qo'yiladi: a teacher, an engineer (unli tovush oldida an). «Men talabaman» — I am a student, I student emas. Ko'plikda artikl tushadi: We are teachers.`,
    faq: [{ q: `«Kasbingiz nima?» inglizcha qanday aytiladi?`, a: `What do you do? yoki What is your job? Javob: I am a / an + kasb.` }, { q: `Nima uchun kasb oldida a/an kerak?`, a: `Chunki kasb sanaladigan ot hisoblanadi va ingliz tilida birlikda artikl talab qiladi: a doctor, an engineer.` }],
    lesson: [`beginner`, `countries-nationalities-jobs`], related: [`oila-azolari`, `salomlashish-iboralari`],
  },
  {
    slug: 'ovqat-va-ichimliklar', level: 'beginner',
    h1: `Ovqat va ichimliklar nomi inglizcha`,
    metaTitle: `Inglizcha ovqat va ichimliklar: 40 ta so'z talaffuzi va tarjimasi (o'zbekcha)`,
    metaDesc: `Ingliz tilida ovqat, meva, sabzavot va ichimliklar nomlari: bread, rice, apple, tea. Talaffuz, o'zbekcha tarjima, sanaladigan va sanalmaydigan otlar va kafedagi iboralar.`,
    intro: `Ovqat nomlarini bilish kafe, do'kon va mehmondorchilikda kerak. Bu mavzuda muhim grammatik qoida bor: ba'zi ovqatlar sanaladi (an apple), ba'zilari sanalmaydi (rice, water).`,
    words: [[`bread`,`/bred/`,`non`],[`rice`,`/raɪs/`,`guruch, palov`],[`meat`,`/miːt/`,`go'sht`],[`chicken`,`/ˈtʃɪkɪn/`,`tovuq`],[`fish`,`/fɪʃ/`,`baliq`],[`egg`,`/eɡ/`,`tuxum`],[`cheese`,`/tʃiːz/`,`pishloq`],[`butter`,`/ˈbʌtə/`,`sariyog'`],[`soup`,`/suːp/`,`sho'rva`],[`salad`,`/ˈsæləd/`,`salat`],[`potato`,`/pəˈteɪtəʊ/`,`kartoshka`],[`tomato`,`/təˈmɑːtəʊ/`,`pomidor`],[`onion`,`/ˈʌnjən/`,`piyoz`],[`carrot`,`/ˈkærət/`,`sabzi`],[`apple`,`/ˈæpl/`,`olma`],[`banana`,`/bəˈnɑːnə/`,`banan`],[`grape`,`/ɡreɪp/`,`uzum`],[`melon`,`/ˈmelən/`,`qovun`],[`water`,`/ˈwɔːtə/`,`suv`],[`tea`,`/tiː/`,`choy`],[`coffee`,`/ˈkɒfi/`,`qahva`],[`milk`,`/mɪlk/`,`sut`],[`juice`,`/dʒuːs/`,`sharbat`],[`sugar`,`/ˈʃʊɡə/`,`shakar`],[`salt`,`/sɔːlt/`,`tuz`],[`breakfast`,`/ˈbrekfəst/`,`nonushta`],[`lunch`,`/lʌntʃ/`,`tushlik`],[`dinner`,`/ˈdɪnə/`,`kechki ovqat`]],
    phrases: [[`I'd like a cup of tea, please.`,`Menga bir piyola choy bering, iltimos.`],[`Can I have some water?`,`Menga ozgina suv bersangiz bo'ladimi?`],[`I don't eat meat.`,`Men go'sht yemayman.`],[`What do you usually have for breakfast?`,`Odatda nonushtada nima yeysiz?`]],
    tip: `Sanalmaydigan ovqatlar (water, rice, bread, milk) bilan a/an ishlatilmaydi, ularni idish bilan sanaymiz: a glass of water, a cup of tea, a slice of bread. Sanaladigan ovqatlar (apple, egg, potato) bilan a/an va ko'plik ishlatiladi.`,
    faq: [{ q: `Nega bread va rice sanalmaydi?`, a: `Ingliz tilida ular bir butun massa sifatida qaraladi. Sanash uchun o'lchov so'zi kerak: a loaf of bread, a bowl of rice.` }, { q: `Kafede buyurtmani qanday aytiladi?`, a: `I'd like... (menga ... kerak) yoki Can I have...? deb. Please qo'shib muloyim qiling.` }],
    lesson: [`elementary`, `food-containers-a-cup-of`], related: [`ranglar`, `uy-va-xonalar`],
  },
  {
    slug: 'uy-va-xonalar', level: 'beginner',
    h1: `Uy, xonalar va uy jihozlari inglizcha`,
    metaTitle: `Uy va xonalar nomi inglizcha: room, kitchen, bed va jihozlar (tarjimasi bilan)`,
    metaDesc: `Ingliz tilida uy, xonalar va mebel nomlari: kitchen, bedroom, sofa, table. Transkripsiya, o'zbekcha tarjima, there is/are bilan uyni tasvirlash va joy predloglari.`,
    intro: `O'z uyingizni tasvirlash ingliz tilidagi eng keng tarqalgan mavzulardan biri. Uchta narsa kerak: xona nomlari, jihozlar va joy predloglari (in, on, next to).`,
    words: [[`house`,`/haʊs/`,`uy`],[`flat / apartment`,`/flæt/`,`kvartira`],[`room`,`/ruːm/`,`xona`],[`kitchen`,`/ˈkɪtʃɪn/`,`oshxona`],[`bedroom`,`/ˈbedruːm/`,`yotoqxona`],[`bathroom`,`/ˈbɑːθruːm/`,`hammom`],[`living room`,`/ˈlɪvɪŋ ruːm/`,`mehmonxona`],[`garden`,`/ˈɡɑːdn/`,`bog'`],[`door`,`/dɔː/`,`eshik`],[`window`,`/ˈwɪndəʊ/`,`deraza`],[`floor`,`/flɔː/`,`pol, qavat`],[`wall`,`/wɔːl/`,`devor`],[`table`,`/ˈteɪbl/`,`stol`],[`chair`,`/tʃeə/`,`stul`],[`bed`,`/bed/`,`karavot`],[`sofa`,`/ˈsəʊfə/`,`divan`],[`fridge`,`/frɪdʒ/`,`muzlatgich`],[`lamp`,`/læmp/`,`chiroq`],[`carpet`,`/ˈkɑːpɪt/`,`gilam`],[`shelf`,`/ʃelf/`,`javon, tokcha`],[`mirror`,`/ˈmɪrə/`,`ko'zgu`],[`TV`,`/ˌtiːˈviː/`,`televizor`]],
    phrases: [[`There is a big window in my room.`,`Xonamda katta deraza bor.`],[`The lamp is on the table.`,`Chiroq stol ustida.`],[`My flat has three rooms and a balcony.`,`Kvartiramda uchta xona va balkon bor.`],[`We live in a small house with a garden.`,`Biz bog'li kichkina uyda yashaymiz.`]],
    tip: `Uyni tasvirlashda There is / There are ishlatiladi (There is a sofa in the living room). Joy predloglari: in (ichida), on (ustida), under (ostida), next to (yonida), between (orasida), in front of (oldida).`,
    faq: [{ q: `House va home farqi nima?`, a: `House — bino (jismoniy uy), home — oila yashaydigan joy, «uy» ma'nosida. At home — uyda, I live in a house — men uyda (binoda) yashayman.` }, { q: `Flat va apartment farqi bormi?`, a: `Ma'nosi bir xil: kvartira. Flat — britancha, apartment — amerikacha.` }],
    lesson: [`elementary`, `my-home`], related: [`ovqat-va-ichimliklar`, `kiyim-nomlari`],
  },
  {
    slug: 'kiyim-nomlari', level: 'beginner',
    h1: `Kiyim-kechak nomlari ingliz tilida (clothes)`,
    metaTitle: `Inglizcha kiyim nomlari: shirt, dress, shoes va boshqalar (talaffuzi, tarjimasi)`,
    metaDesc: `Ingliz tilida kiyim-kechak nomlari: shirt, trousers, dress, jacket, shoes. Talaffuz, o'zbekcha tarjima, wear va put on farqi, do'konda o'lcham va narxni so'rash.`,
    intro: `Kiyim nomlari do'konda xarid qilish, ob-havoga mos kiyinish va tashqi ko'rinishni tasvirlash uchun kerak. Ba'zi kiyimlar ingliz tilida faqat ko'plikda ishlatiladi: trousers, jeans, shorts, glasses.`,
    words: [[`clothes`,`/kləʊðz/`,`kiyimlar`],[`shirt`,`/ʃɜːt/`,`ko'ylak (erkaklar)`],[`T-shirt`,`/ˈtiː ʃɜːt/`,`futbolka`],[`dress`,`/dres/`,`ko'ylak (ayollar)`],[`skirt`,`/skɜːt/`,`yubka`],[`trousers`,`/ˈtraʊzəz/`,`shim`],[`jeans`,`/dʒiːnz/`,`jinsi`],[`jacket`,`/ˈdʒækɪt/`,`kurtka, pidjak`],[`coat`,`/kəʊt/`,`palto`],[`sweater`,`/ˈswetə/`,`sviter`],[`suit`,`/suːt/`,`kostyum`],[`shoes`,`/ʃuːz/`,`poyabzal`],[`boots`,`/buːts/`,`etik`],[`trainers`,`/ˈtreɪnəz/`,`krossovka`],[`socks`,`/sɒks/`,`paypoq`],[`hat`,`/hæt/`,`shlyapa`],[`cap`,`/kæp/`,`kepka`],[`scarf`,`/skɑːf/`,`sharf`],[`gloves`,`/ɡlʌvz/`,`qo'lqop`],[`belt`,`/belt/`,`kamar`],[`bag`,`/bæɡ/`,`sumka`],[`size`,`/saɪz/`,`o'lcham`]],
    phrases: [[`She is wearing a red dress.`,`U qizil ko'ylak kiygan.`],[`Can I try this jacket on?`,`Bu kurtkani kiyib ko'rsam bo'ladimi?`],[`What size do you wear?`,`Qanday o'lcham kiyasiz?`],[`How much are these shoes?`,`Bu poyabzal necha pul?`],[`It's too small. Do you have a bigger one?`,`U juda kichik. Kattaroq bormi?`]],
    tip: `Wear — kiyib yurish (She wears glasses), put on — kiyish harakati (Put on your coat), try on — o'lchab ko'rish. Trousers, jeans, shorts, glasses ko'plik shaklida: these jeans, a pair of jeans (bir juft jinsi).`,
    faq: [{ q: `Wear va put on farqi nima?`, a: `Wear — kiyib turish holati (I am wearing a hat), put on — kiyish jarayoni (I put on my hat).` }, { q: `Nega jeans va trousers ko'plikda?`, a: `Ular ikki oyoq qismidan iborat deb qaraladi. Bitta shim aytilganda «a pair of trousers/jeans» deyiladi.` }],
    lesson: [`elementary`, `shopping-for-clothes`], related: [`ranglar`, `ovqat-va-ichimliklar`],
  },
  {
    slug: 'ob-havo-va-fasllar', level: 'elementary',
    h1: `Ob-havo va fasllar ingliz tilida (weather)`,
    metaTitle: `Inglizcha ob-havo va fasllar: sunny, rainy, spring va boshqalar (tarjimasi bilan)`,
    metaDesc: `Ingliz tilida ob-havo va fasllar nomlari: sunny, cloudy, rainy, snowy, hot, cold. Talaffuz, o'zbekcha tarjima, «What's the weather like?» savoli va javoblar.`,
    intro: `Ob-havo haqida gapirish ingliz tilidagi eng keng tarqalgan suhbat mavzusi: odamlar suhbatni ko'pincha shu bilan boshlaydi. Asosiy savol: What's the weather like today?`,
    words: [[`weather`,`/ˈweðə/`,`ob-havo`],[`sunny`,`/ˈsʌni/`,`quyoshli`],[`cloudy`,`/ˈklaʊdi/`,`bulutli`],[`rainy`,`/ˈreɪni/`,`yomg'irli`],[`snowy`,`/ˈsnəʊi/`,`qorli`],[`windy`,`/ˈwɪndi/`,`shamolli`],[`foggy`,`/ˈfɒɡi/`,`tumanli`],[`hot`,`/hɒt/`,`issiq`],[`warm`,`/wɔːm/`,`iliq`],[`cool`,`/kuːl/`,`salqin`],[`cold`,`/kəʊld/`,`sovuq`],[`rain`,`/reɪn/`,`yomg'ir`],[`snow`,`/snəʊ/`,`qor`],[`storm`,`/stɔːm/`,`bo'ron`],[`temperature`,`/ˈtemprətʃə/`,`harorat`],[`spring`,`/sprɪŋ/`,`bahor`],[`summer`,`/ˈsʌmə/`,`yoz`],[`autumn`,`/ˈɔːtəm/`,`kuz`],[`winter`,`/ˈwɪntə/`,`qish`],[`umbrella`,`/ʌmˈbrelə/`,`soyabon`]],
    phrases: [[`What's the weather like today? — It's sunny and warm.`,`Bugun ob-havo qanday? — Quyoshli va iliq.`],[`It's raining.`,`Yomg'ir yog'yapti.`],[`It's thirty degrees.`,`Havo o'ttiz daraja.`],[`I like summer, but it is too hot in Tashkent.`,`Menga yoz yoqadi, lekin Toshkentda juda issiq.`],[`It's going to snow tomorrow.`,`Ertaga qor yog'adi.`]],
    tip: `Ob-havo gaplarida egasi it bo'ladi: It is cold, It is raining. Fasllar bilan in ishlatiladi: in summer, in winter. Sifat (rainy) va fe'l (rain) farqiga e'tibor bering: It is rainy = It rains/is raining.`,
    faq: [{ q: `«Bugun ob-havo qanday?» inglizcha qanday aytiladi?`, a: `What's the weather like today? Javob: It's sunny / cold / rainy.` }, { q: `Autumn va fall farqi nima?`, a: `Ikkalasi ham kuz: autumn — britancha, fall — amerikacha.` }],
    lesson: [`elementary`, `whats-the-weather-like`], related: [`hafta-kunlari-va-oylar`, `kiyim-nomlari`],
  },
  {
    slug: 'sayohat-va-transport', level: 'elementary',
    h1: `Sayohat va transport: aeroport, vokzal, mehmonxona inglizcha`,
    metaTitle: `Sayohat uchun inglizcha so'zlar: airport, ticket, hotel (tarjimasi bilan)`,
    metaDesc: `Sayohat va transport bo'yicha inglizcha so'zlar va iboralar: airport, ticket, passport, hotel, taxi. Talaffuz, o'zbekcha tarjima va aeroport hamda mehmonxonada suhbatlar.`,
    intro: `Chet elga sayohat qilganda aeroport, transport va mehmonxonadagi 30 ga yaqin so'z va 10 ta ibora ko'p muammoni hal qiladi. Quyida eng zarurlari to'plangan.`,
    words: [[`airport`,`/ˈeəpɔːt/`,`aeroport`],[`flight`,`/flaɪt/`,`reys`],[`ticket`,`/ˈtɪkɪt/`,`chipta`],[`passport`,`/ˈpɑːspɔːt/`,`pasport`],[`luggage`,`/ˈlʌɡɪdʒ/`,`yuk, bagaj`],[`suitcase`,`/ˈsuːtkeɪs/`,`chemodan`],[`gate`,`/ɡeɪt/`,`chiqish eshigi (gate)`],[`passenger`,`/ˈpæsɪndʒə/`,`yo'lovchi`],[`train`,`/treɪn/`,`poyezd`],[`station`,`/ˈsteɪʃn/`,`vokzal, bekat`],[`bus`,`/bʌs/`,`avtobus`],[`taxi`,`/ˈtæksi/`,`taksi`],[`metro`,`/ˈmetrəʊ/`,`metro`],[`hotel`,`/həʊˈtel/`,`mehmonxona`],[`reservation`,`/ˌrezəˈveɪʃn/`,`bron qilish`],[`single room`,`/ˈsɪŋɡl ruːm/`,`bir kishilik xona`],[`double room`,`/ˈdʌbl ruːm/`,`ikki kishilik xona`],[`key`,`/kiː/`,`kalit`],[`map`,`/mæp/`,`xarita`],[`tourist`,`/ˈtʊərɪst/`,`sayyoh`],[`arrive`,`/əˈraɪv/`,`yetib kelmoq`],[`depart`,`/dɪˈpɑːt/`,`jo'nab ketmoq`],[`delayed`,`/dɪˈleɪd/`,`kechikkan`]],
    phrases: [[`Where is the check-in desk?`,`Ro'yxatdan o'tish stoli qayerda?`],[`I'd like a single room for two nights.`,`Ikki kechaga bir kishilik xona kerak.`],[`What time does the train leave?`,`Poyezd soat nechada jo'naydi?`],[`Could you tell me the way to the station?`,`Vokzalga qanday borishni aytib bera olasizmi?`],[`My flight is delayed.`,`Mening reysim kechikdi.`]],
    tip: `Muloyim iltimos uchun Could you... ? va I'd like... iboralarini yodlang. Vaqt jadvali haqida Present Simple ishlatiladi: The train leaves at 8. Yo'l so'rash: Excuse me, where is...? How do I get to...?`,
    faq: [{ q: `Aeroportda nimalarni bilish kerak?`, a: `Check-in (ro'yxatdan o'tish), boarding pass (chiqish talon), gate (chiqish eshigi), luggage (yuk) va passport control (pasport nazorati) so'zlarini.` }, { q: `Mehmonxonada xona qanday bron qilinadi?`, a: `I'd like to book a room for... nights. Do you have any rooms available? iboralaridan foydalaning.` }],
    lesson: [`elementary`, `at-the-station-airport`], related: [`ob-havo-va-fasllar`, `salomlashish-iboralari`],
  },
];
