import type { Task2Question } from './types.js';

export const TASK2: Task2Question[] = [
  {
    slug: "social-media-negative-impact",
    title: "Social media and its impact on society",
    category: "Technology",
    type: "Opinion (agree/disagree)",
    question: "Many people believe that social media has a negative impact on both individuals and society. To what extent do you agree or disagree?",
    analysis: "You must decide how far you agree that social media harms both individuals and society. “To what extent” allows a balanced position, such as partly agreeing, but you must stay consistent and mention both individuals and society.",
    outline: [
      { heading: "Introduction", text: "Paraphrase the statement and give your position, for example that you largely agree but accept some benefits." },
      { heading: "Body 1: individuals", text: "Mental health, comparison with others and loss of concentration, supported by an example such as sleep problems." },
      { heading: "Body 2: society", text: "Misinformation and weaker face-to-face relationships; briefly concede that connection and awareness are positives." },
      { heading: "Conclusion", text: "Restate your position: the harms outweigh the benefits unless usage is managed." },
    ],
    sample: [
      "It is often claimed that social media damages both individuals and communities. While I accept that these platforms bring some benefits, I largely agree that their negative effects are significant.",
      "For individuals, constant exposure to carefully edited images and success stories encourages unhealthy comparison. Teenagers in particular may feel inadequate when their lives seem less exciting than those of their online peers, and studies have linked heavy use to anxiety and sleep problems. In addition, endless notifications fragment attention, making it harder for students to concentrate on demanding tasks such as reading or revision.",
      "At the level of society, the rapid spread of unverified information is a serious concern. False news can travel faster than corrections, influencing public opinion on health or politics before facts are checked. Moreover, people who spend hours online often have less time for real conversations, which may weaken family and community bonds. Experts also warn that recommendation algorithms promote shocking content because it attracts more clicks, so extreme opinions often receive more attention than balanced ones, which deepens social division and makes constructive public debate much harder than it needs to be.",
      "Admittedly, social media also allows people to keep in touch across continents and helps small businesses reach customers cheaply. Nevertheless, these advantages do not remove the underlying risks, especially when platforms are designed to maximise screen time.",
      "In conclusion, although social media has genuine uses, I believe its harmful effects on mental well-being, attention and public debate outweigh its benefits unless users and companies take more responsibility."
    ],
    vocab: [["unhealthy comparison", "judging yourself harshly against others"], ["fragment attention", "break concentration into pieces"], ["unverified information", "facts not yet checked"], ["weaken bonds", "make relationships less strong"], ["maximise screen time", "make people use devices as long as possible"], ["outweigh", "be more important than"], ["inadequate", "not good enough"]],
    mistakes: ["Writing only about advantages or only about disadvantages when the question says “to what extent”.", "Giving general statements without an example, such as sleep problems or false news.", "Changing your opinion between the introduction and the conclusion."],
  },
  {
    slug: "university-academic-skills-or-employment",
    title: "Should universities focus on academic or job skills?",
    category: "Education",
    type: "Discussion + opinion",
    question: "Some people believe that universities should focus on providing academic skills, while others think they should prepare students for employment. Discuss both views and give your opinion.",
    analysis: "You must discuss two views fairly in separate paragraphs and then give your own opinion, preferably in the introduction and again in the conclusion.",
    outline: [
      { heading: "Introduction", text: "Introduce the debate and signal your opinion, for example that a balance is best." },
      { heading: "Body 1: academic skills", text: "Critical thinking, research and deep subject knowledge benefit students for life and drive innovation." },
      { heading: "Body 2: employment focus", text: "Graduates need practical skills, internships and communication to find jobs and reduce unemployment." },
      { heading: "Conclusion", text: "Restate that universities should combine both, with academic depth supported by practical experience." },
    ],
    sample: [
      "Opinions differ on whether universities should concentrate on academic learning or on preparing students for the labour market. Although both views have merit, I believe the most effective approach combines the two.",
      "Those who support an academic focus argue that higher education should develop critical thinking and deep subject knowledge. A student who learns how to analyse evidence and solve complex problems can adapt to many careers, even those that do not yet exist. Furthermore, universities have a duty to advance research, which leads to discoveries in medicine, engineering and the humanities that benefit society as a whole.",
      "On the other hand, supporters of job-oriented education point out that students and their families invest large sums in tuition and expect a reasonable chance of employment afterwards. Practical training, internships and lessons in teamwork or presentation skills make graduates more attractive to employers. In countries where graduate unemployment is high, universities that ignore this reality may fail their students. Employers themselves often say that graduates know a great deal of theory but struggle with everyday workplace tasks such as writing reports, meeting deadlines or working in a team, which suggests that universities cannot afford to ignore practical preparation completely.",
      "In my view, these goals are not opposites. Courses can teach theory while including projects with real companies, so students learn to apply knowledge in practice. For example, a business degree that combines economics with a placement at a local firm gives both understanding and experience.",
      "In conclusion, universities should not choose between academic and vocational aims; a balanced curriculum serves students, employers and society best."
    ],
    vocab: [["labour market", "the supply of workers and jobs"], ["vocational", "related to a particular job"], ["adapt to", "change to suit new conditions"], ["advance research", "move knowledge forward"], ["placement", "a short period of work experience"], ["curriculum", "the subjects taught in a course"], ["tuition", "money paid for teaching"]],
    mistakes: ["Describing only one view in detail and ignoring the other.", "Forgetting to give your own opinion clearly.", "Using memorised phrases like “nowadays, in this modern world” instead of a direct opening."],
  },
  {
    slug: "rich-poor-gap-problems-solutions",
    title: "The growing gap between rich and poor",
    category: "Society",
    type: "Problem and solution",
    question: "In many countries, the gap between the rich and the poor is increasing. What problems does this cause and what solutions can be proposed?",
    analysis: "Two tasks: identify problems caused by inequality, and suggest solutions. Give each its own paragraph and link solutions to the problems you mentioned.",
    outline: [
      { heading: "Introduction", text: "Paraphrase the question and state that the essay will examine problems and solutions." },
      { heading: "Body 1: problems", text: "Social tension and crime, unequal access to healthcare and education, wasted talent." },
      { heading: "Body 2: solutions", text: "Progressive taxation, investment in public education, and support for small businesses and training." },
      { heading: "Conclusion", text: "Summarise that the problems are serious but can be reduced by government action." },
    ],
    sample: [
      "In many parts of the world, wealth is becoming concentrated among a small proportion of the population while others struggle to meet basic needs. This essay will outline the main problems this trend creates and propose some practical solutions.",
      "The first problem is social division. When ordinary families see little chance of improving their lives, frustration grows, which can lead to higher crime rates and political unrest. Inequality also affects access to essential services: wealthy citizens can pay for private healthcare and elite schools, whereas poorer children may receive lower-quality education, which limits their future opportunities. As a result, society loses the talents of many capable people.",
      "There are several ways to address these issues. Governments could introduce progressive taxation, where higher earners pay a larger percentage, and use the revenue to improve public schools and hospitals. Investment in vocational training would help low-income workers acquire skills for better-paid jobs, while loans and advice for small businesses could create employment in poorer regions. Technology can play a part too: free online courses and low-cost internet access allow people in poorer regions to learn valuable skills without moving to expensive cities, which gives them a realistic chance to improve their income over time.",
      "Individuals and companies also have a role to play. Employers can offer fair wages and apprenticeships, and charities can provide scholarships for talented students from disadvantaged backgrounds. Such measures give people tools to climb the economic ladder rather than depend on assistance.",
      "In conclusion, widening inequality leads to social tension and unequal opportunities, but fairer taxation, better public services and targeted training can reduce these problems."
    ],
    vocab: [["concentrated", "held by a few"], ["social unrest", "public disorder and anger"], ["progressive taxation", "higher tax rates for higher incomes"], ["disadvantaged background", "a poor or difficult start in life"], ["apprenticeship", "paid training for a skilled job"], ["essential services", "basic public needs"], ["income inequality", "unequal distribution of earnings"]],
    mistakes: ["Listing problems but offering solutions that do not match them.", "Writing a very long first body paragraph and a short second one.", "Using vague solutions such as “the government should do something”."],
  },
  {
    slug: "prison-sentences-and-crime",
    title: "Longer prison sentences or other ways to reduce crime",
    category: "Crime",
    type: "Discussion + opinion",
    question: "Some people think that the best way to reduce crime is to give longer prison sentences. Others, however, believe there are better alternative ways of reducing crime. Discuss both views and give your opinion.",
    analysis: "Discuss the argument for harsher punishment and the argument for alternatives, then state which you find more convincing.",
    outline: [
      { heading: "Introduction", text: "Present both sides and say you favour alternatives, with prison for serious offences." },
      { heading: "Body 1: longer sentences", text: "Deterrence and protecting the public by keeping dangerous criminals away from society." },
      { heading: "Body 2: alternatives", text: "Education, job training and community service reduce reoffending; poverty is a root cause." },
      { heading: "Conclusion", text: "Prevention and rehabilitation work better than longer sentences alone." },
    ],
    sample: [
      "Crime remains a major concern for governments everywhere. Some argue that tougher prison terms are the most effective solution, whereas others prefer different strategies. While harsher punishment has some value, I believe alternative approaches are more successful in the long term.",
      "Supporters of longer sentences claim that they deter potential offenders. If people know that a serious crime could mean many years behind bars, they may think twice before committing it. In addition, keeping violent criminals in prison protects the public for longer, which is especially important in cases such as armed robbery or murder.",
      "However, evidence suggests that severe punishment alone does not address the causes of crime. Many offenders come from poor backgrounds with little education, and a long prison term can leave them with a criminal record and no job prospects, making reoffending more likely. By contrast, programmes that teach vocational skills, provide counselling or offer community service help offenders rebuild their lives. Countries that have invested in rehabilitation, such as Norway, report much lower rates of repeat offending. Prison itself can also be costly and counterproductive, because young offenders who share cells with experienced criminals may learn new illegal methods, so a heavy reliance on custody can unintentionally produce more crime than it prevents in the long run.",
      "Prevention is equally important. Better education, youth clubs and employment opportunities reduce the temptation to commit crime in the first place, and they are cheaper than housing prisoners for decades.",
      "In conclusion, although long sentences are appropriate for dangerous criminals, I believe that rehabilitation and prevention are more effective ways to create a safer society."
    ],
    vocab: [["deter", "discourage from doing something"], ["reoffend", "commit another crime"], ["rehabilitation", "helping someone return to normal life"], ["criminal record", "official history of crimes"], ["community service", "unpaid work as punishment"], ["root causes", "the main reasons for a problem"], ["behind bars", "in prison"]],
    mistakes: ["Giving only your own opinion and ignoring the other view.", "Using extreme statements such as “all criminals should be executed”.", "Not including an example or evidence to support a claim."],
  },
  {
    slug: "working-from-home",
    title: "Working from home: advantages and disadvantages",
    category: "Work",
    type: "Advantages and disadvantages",
    question: "More and more people are working from home instead of in an office. Do the advantages of this trend outweigh the disadvantages?",
    analysis: "You must weigh advantages against disadvantages and decide which side is stronger. Clearly state your judgement in the introduction and conclusion.",
    outline: [
      { heading: "Introduction", text: "Introduce the trend and say that the advantages outweigh the disadvantages." },
      { heading: "Body 1: advantages", text: "Saves commuting time and money, flexible schedules, wider job choice for people in remote areas." },
      { heading: "Body 2: disadvantages", text: "Isolation, blurred boundaries between work and home, and fewer collaboration opportunities; suggest these can be managed." },
      { heading: "Conclusion", text: "Restate your view: the benefits are greater, especially with hybrid models." },
    ],
    sample: [
      "Thanks to improvements in technology, remote working has become common in many industries. Although it has drawbacks, I believe the benefits for both employees and employers outweigh them.",
      "The most obvious advantage is the time and money saved on commuting. A worker in a large city may spend two hours a day travelling, and eliminating this journey gives more time for family, exercise or rest. Furthermore, flexible schedules allow people to work when they are most productive, which often improves the quality of their work. Remote positions also open up opportunities for people who live far from big companies or who have disabilities that make travelling difficult.",
      "On the other hand, working from home can cause isolation, because employees miss the daily contact with colleagues that builds team spirit. It can also be hard to separate work from private life when the office is only a few steps from the kitchen, leading some people to work longer hours. Finally, creative collaboration is sometimes easier face to face. Employers benefit as well, since they can reduce spending on office rent and electricity and recruit talented staff from any city, which is why many large companies have decided to keep flexible arrangements even after the pandemic ended.",
      "Nevertheless, these problems are manageable. Companies can organise regular video meetings and occasional office days, while employees can set fixed working hours and a dedicated workspace. Many firms already use this hybrid model successfully.",
      "In conclusion, remote working offers significant savings, flexibility and wider opportunities, and its disadvantages can be reduced with sensible planning. Therefore, I believe the advantages outweigh the drawbacks."
    ],
    vocab: [["commute", "travel regularly to work"], ["flexible schedule", "working hours you can adjust"], ["team spirit", "shared enthusiasm in a group"], ["blur the boundary", "make the difference unclear"], ["hybrid model", "a mix of home and office work"], ["productive", "achieving a lot"], ["isolation", "feeling alone"]],
    mistakes: ["Writing a list of advantages without explaining them.", "Not stating which side is stronger.", "Using “firstly, secondly, thirdly” for every idea instead of developing two good ones."],
  },
  {
    slug: "obesity-causes-and-solutions",
    title: "Obesity: causes and solutions",
    category: "Health",
    type: "Two-part question",
    question: "In some countries, the average weight of people is increasing and their level of health and fitness is decreasing. What do you think are the causes of these problems and what measures could be taken to solve them?",
    analysis: "Answer two questions directly: causes, and measures. Dedicate one body paragraph to each and give specific causes and realistic measures.",
    outline: [
      { heading: "Introduction", text: "Paraphrase and state that unhealthy diets and inactive lifestyles are the main causes." },
      { heading: "Body 1: causes", text: "Cheap processed food, sedentary jobs and screen-based leisure." },
      { heading: "Body 2: measures", text: "Education about nutrition, taxes on sugary products, and better sports facilities and PE in schools." },
      { heading: "Conclusion", text: "Summarise that the problem needs cooperation between government, schools and families." },
    ],
    sample: [
      "In a growing number of countries, people are gaining weight and becoming less fit. This trend is mainly caused by changes in diet and lifestyle, and it can be addressed through education and sensible government policy.",
      "One major cause is the availability of cheap, processed food. Fast food and sugary drinks are heavily advertised and often cost less than fresh vegetables, so families on low incomes may buy them regularly. At the same time, modern lifestyles are increasingly sedentary. Many people sit at desks all day, travel by car rather than on foot and spend their free time watching screens instead of playing sport. Together, these habits mean that people consume more calories than they burn.",
      "Several measures could help. Firstly, schools should teach children about nutrition and cooking, so they learn to make healthy choices from an early age. Secondly, governments could impose taxes on sugary products and use the revenue to subsidise fruit and vegetables, making healthy food more affordable. Thirdly, building parks, cycle lanes and public sports facilities would encourage physical activity, and compulsory physical education in schools would help children form lifelong habits. Clear food labelling would also help, because shoppers who can quickly see how much sugar, salt and fat a product contains are more likely to choose healthier alternatives, especially when the information is simple and displayed on the front of the packet.",
      "Employers can also contribute by offering gym memberships or active breaks, since adults spend so much time at work.",
      "In conclusion, poor diets and inactivity are the main reasons for declining fitness, and a combination of education, fair pricing and better facilities could reverse the trend."
    ],
    vocab: [["processed food", "food changed by factory methods"], ["sedentary", "involving a lot of sitting"], ["subsidise", "reduce price with public money"], ["impose a tax", "introduce a required payment"], ["calorie intake", "the energy you take in from food"], ["lifelong habits", "behaviours kept for life"], ["affordable", "not too expensive"]],
    mistakes: ["Answering only the causes or only the solutions.", "Writing about obesity as a personal failure instead of examining social factors.", "Using “fatty people”; use neutral language such as “people who are overweight”."],
  },
  {
    slug: "cultural-traditions-and-tourism",
    title: "Cultural traditions and tourism",
    category: "Globalization",
    type: "Discussion + opinion",
    question: "Some people think that cultural traditions will be destroyed when they are used as money-making attractions aimed at tourists. Others believe this is the only way to save such traditions. Discuss both views and give your opinion.",
    analysis: "Discuss why tourism may damage traditions and why it may save them, then give your opinion. Use a concrete example such as a festival or craft.",
    outline: [
      { heading: "Introduction", text: "Introduce the debate and say that tourism can help if it is managed carefully." },
      { heading: "Body 1: damage", text: "Commercialisation changes events to please tourists, losing meaning and authenticity." },
      { heading: "Body 2: preservation", text: "Tourist income funds craftspeople and festivals, giving young people a reason to continue them." },
      { heading: "Conclusion", text: "Tourism is acceptable when local communities keep control and respect traditions." },
    ],
    sample: [
      "Cultural traditions are valuable parts of a country's identity, yet many are now performed mainly for visitors. Some people fear that this commercialisation will destroy them, while others see tourism as their only hope. In my opinion, tourism can protect traditions, provided it is managed carefully.",
      "Critics argue that when a ceremony is shortened or changed to entertain tourists, it loses its original meaning. For instance, a sacred dance performed several times a day in a hotel may become just a show, and local people may begin to see their heritage as a product to sell rather than a living practice. Mass tourism can also bring crowds that disturb quiet religious sites.",
      "On the other hand, tourism provides money that many communities could not otherwise obtain. Traditional crafts such as pottery or carpet weaving are expensive to produce, and without buyers, young people may abandon them for better-paid work in cities. Income from visitors pays for training, festivals and the restoration of old buildings. In several Central Asian towns, craft workshops have survived precisely because tourists buy their products. Tourism can even revive customs that were fading, because villagers who once felt embarrassed about old songs or costumes often regain pride when they see visitors admiring them, and that renewed confidence encourages the next generation to learn them seriously.",
      "The key is balance. Local communities should decide which parts of their culture are shared with visitors, while keeping the most sacred rituals private. Authorities can also limit visitor numbers and educate tourists to behave respectfully.",
      "In conclusion, although commercialisation carries risks, I believe tourism can save traditions when communities control how their culture is presented."
    ],
    vocab: [["commercialisation", "making something a business product"], ["authenticity", "being genuine"], ["heritage", "history and traditions passed down"], ["sacred", "holy and deeply respected"], ["restoration", "repair to original condition"], ["mass tourism", "large numbers of tourists"], ["living tradition", "a custom still practised today"]],
    mistakes: ["Using vague phrases like “culture is important” without examples.", "Treating tourism as only good or only bad.", "Missing your own opinion in the introduction."],
  },
  {
    slug: "public-transport-investment",
    title: "Government investment in public transport",
    category: "Government",
    type: "Opinion (agree/disagree)",
    question: "Some people believe that governments should spend more money on public transport rather than building new roads. To what extent do you agree or disagree?",
    analysis: "Decide how strongly you agree that public transport deserves more funding than road building. Support your opinion with reasons about congestion, the environment and cost.",
    outline: [
      { heading: "Introduction", text: "Say that you strongly agree, with limited road building where it is really needed." },
      { heading: "Body 1: efficiency and environment", text: "Buses and trains move more people per space, reducing congestion and pollution." },
      { heading: "Body 2: social and economic benefits", text: "Affordable transport helps low-income people reach jobs; new roads often attract more cars." },
      { heading: "Conclusion", text: "Restate that public transport is the smarter investment." },
    ],
    sample: [
      "As cities grow larger, governments must decide how to move people efficiently. I strongly agree that more public money should be spent on public transport than on new roads, although some road improvements are still necessary.",
      "The main reason is efficiency. A single train can carry as many passengers as hundreds of cars, using far less space and fuel. Building new roads often fails to solve congestion because more road space encourages more people to drive, and traffic soon returns to its previous level. By contrast, reliable metro and bus systems take cars off the streets permanently, shortening journeys for everyone. They also reduce air pollution and carbon emissions, which is vital for public health and for tackling climate change.",
      "Public transport also has important social benefits. People with low incomes, students and elderly citizens often cannot afford or drive a car, so affordable buses and trains give them access to jobs, education and healthcare. A good network can therefore reduce inequality and strengthen the local economy. Cities such as Singapore demonstrate that this approach works: heavy charges for car ownership combined with excellent trains and buses have kept the roads moving smoothly even though the population is large and the available land is extremely limited.",
      "Admittedly, in rural areas where populations are small, roads remain essential, and well-maintained bridges and highways are needed for freight. However, even there, budgets should prioritise repairs over constructing additional roads.",
      "In conclusion, I believe that investment in public transport produces greater long-term benefits for congestion, the environment and social fairness than expanding the road network."
    ],
    vocab: [["congestion", "too much traffic"], ["carbon emissions", "gases released that warm the planet"], ["reliable", "can be depended on"], ["afford", "have enough money for"], ["freight", "goods transported"], ["prioritise", "treat as most important"], ["metro system", "an underground railway network"]],
    mistakes: ["Describing the problems of traffic without answering the question.", "Making absolute claims such as “roads are useless”.", "Not using a clear example to support the argument."],
  },
  {
    slug: "online-learning-replace-classrooms",
    title: "Will online learning replace classroom teaching?",
    category: "Education",
    type: "Opinion (agree/disagree)",
    question: "Some people think that online education will eventually replace classroom teaching. To what extent do you agree or disagree?",
    analysis: "Decide whether you think online learning will completely replace classrooms. A balanced answer, partially disagreeing, is often easiest to support.",
    outline: [
      { heading: "Introduction", text: "State that online learning will grow but will not replace classrooms." },
      { heading: "Body 1: strengths of online", text: "Flexibility, lower cost and access to world-class lessons, especially in remote areas." },
      { heading: "Body 2: limits", text: "Motivation, social development, practical subjects and the role of teachers." },
      { heading: "Conclusion", text: "A blended approach is the likely future." },
    ],
    sample: [
      "Digital technology has made it possible to study almost anything from home. While online education will certainly continue to grow, I disagree that it will completely replace classroom teaching.",
      "There is no doubt that online learning offers real advantages. Students can study at their own pace, repeat difficult lessons and attend courses from top universities without leaving their town. This flexibility is particularly valuable for working adults and for people in remote areas where good schools are scarce. It can also be cheaper because it removes travel and accommodation costs.",
      "Nevertheless, classrooms provide benefits that screens cannot easily replace. Young children need guidance, routine and social contact with classmates to develop communication skills and teamwork. Many subjects, such as chemistry experiments, medicine or music performance, require hands-on practice and immediate feedback from an instructor. Moreover, online courses demand strong self-discipline; statistics show that a large percentage of students abandon them before finishing. The pandemic provided a clear example, as many schools that moved entirely online reported falling attention and growing gaps between motivated students and those without quiet study spaces, showing that digital lessons work best as a supplement rather than a substitute.",
      "Teachers also do more than deliver information. They inspire, notice when a student is struggling and adapt their explanations, which is difficult through a screen.",
      "In conclusion, online learning will play a bigger role in the future, but the most effective model is likely to be a combination of digital resources and face-to-face teaching, so classrooms will remain important."
    ],
    vocab: [["at their own pace", "at a speed that suits them"], ["scarce", "in short supply"], ["hands-on", "practical, involving real activity"], ["self-discipline", "ability to control yourself"], ["blended learning", "a mix of online and in-person lessons"], ["interactive", "involving two-way communication"], ["abandon", "leave without finishing"]],
    mistakes: ["Writing only about the advantages of online learning.", "Saying “classrooms are old-fashioned” without reasons.", "Not addressing the word “replace”; the question is about complete replacement."],
  },
  {
    slug: "zoos-should-be-banned",
    title: "Should zoos be closed?",
    category: "Environment",
    type: "Opinion (agree/disagree)",
    question: "Some people think that zoos are cruel and should be closed. Others believe they are necessary for protecting wildlife. To what extent do you agree or disagree?",
    analysis: "Choose a position on zoos. You may argue that well-run zoos are useful while poor ones should close, but your position must be clear.",
    outline: [
      { heading: "Introduction", text: "State that modern zoos are valuable if they meet high welfare standards." },
      { heading: "Body 1: concerns", text: "Small enclosures, stress and animals taken from the wild." },
      { heading: "Body 2: benefits", text: "Breeding programmes for endangered species, research and education for children." },
      { heading: "Conclusion", text: "Good zoos should stay; poor ones should close." },
    ],
    sample: [
      "Zoos have been popular attractions for centuries, but many people now question whether it is right to keep wild animals in captivity. I disagree that all zoos should be closed, because well-run ones play an important role in conservation.",
      "The concerns are understandable. In some zoos, animals live in small enclosures that do not allow natural behaviour, and this can cause stress and illness. Large animals such as elephants and polar bears, which normally travel long distances, are particularly vulnerable. Visitors who see animals pacing back and forth may conclude, with reason, that captivity is cruel.",
      "However, modern zoos can offer significant benefits. Many take part in international breeding programmes that have saved species such as the Arabian oryx and the California condor from extinction. Researchers also use zoo animals to study diseases and behaviour, producing knowledge that helps protect wild populations. In addition, zoos educate millions of children who might never see a giraffe or a tiger otherwise, and this contact can inspire a lifelong respect for nature. Visitors also bring revenue that pays for rescue centres and field projects abroad, so closing every zoo could actually reduce the funding available to protect animals in their natural habitats, where poaching and deforestation remain very serious threats.",
      "The solution is regulation rather than closure. Governments should set strict standards for space, diet and veterinary care, and shut down facilities that fail to meet them. Zoos should also focus on species that really need protection instead of simply attracting crowds.",
      "In conclusion, while poor-quality zoos should be closed, responsible ones contribute to conservation, research and education, so I do not think zoos should be banned altogether."
    ],
    vocab: [["in captivity", "kept in a controlled place, not free"], ["enclosure", "a fenced area for animals"], ["endangered species", "animals at risk of extinction"], ["breeding programme", "planned reproduction to increase numbers"], ["conservation", "protecting nature"], ["welfare standards", "rules for the care of animals"], ["extinction", "disappearance of a species"]],
    mistakes: ["Only describing feelings about animals without arguments.", "Using unclear pronouns like “they” for both zoos and animals.", "Ignoring the second part of the statement (the necessity for protecting wildlife)."],
  },
  {
    slug: "ai-and-jobs",
    title: "Artificial intelligence and the job market",
    category: "Technology",
    type: "Problem and solution",
    question: "Artificial intelligence is replacing workers in many industries. What problems might this cause and what can be done to deal with them?",
    analysis: "Identify problems linked to AI replacing workers (not only benefits) and propose realistic solutions. Keep problems and solutions connected.",
    outline: [
      { heading: "Introduction", text: "Introduce AI's growth and say that unemployment and inequality are the main risks." },
      { heading: "Body 1: problems", text: "Job losses in routine work, widening gap between skilled and unskilled workers, stress for older employees." },
      { heading: "Body 2: solutions", text: "Retraining programmes, education that focuses on creativity and digital skills, and social support during transition." },
      { heading: "Conclusion", text: "With planning, AI can create new opportunities." },
    ],
    sample: [
      "Artificial intelligence is now able to perform tasks that once required human workers, from answering customer questions to analysing medical images. Although this brings efficiency, it also creates serious challenges. This essay will discuss the main problems and suggest practical responses.",
      "The most immediate problem is unemployment. Jobs involving routine tasks, such as data entry or basic customer service, are the easiest to automate, so thousands of employees may lose their income. The effects will not be equal: highly skilled workers who can use AI tools are likely to earn more, while people without such skills may find it difficult to find new positions, widening the gap between rich and poor. Older workers, who may find it harder to retrain, are particularly at risk.",
      "Several solutions are available. Governments and employers should fund retraining programmes so that workers can move into growing sectors such as healthcare, renewable energy or technology support. Schools and universities also need to adapt by teaching digital literacy, creativity and problem-solving, which machines cannot easily copy. During the transition, temporary financial support and career advice can protect families from hardship. Policymakers may also consider shorter working weeks or tax incentives for companies that retain and retrain their staff, so that the productivity gains created by machines are shared more fairly instead of benefiting only a small number of business owners.",
      "Companies themselves can help by introducing AI gradually and assigning displaced staff to new roles instead of dismissing them immediately.",
      "In conclusion, AI poses a real risk of job losses and inequality, but through retraining, updated education and responsible business practices, societies can turn this technology into an opportunity."
    ],
    vocab: [["automate", "make a process work without people"], ["routine tasks", "repetitive, predictable work"], ["retrain", "learn new job skills"], ["displaced workers", "people who lost their jobs"], ["digital literacy", "ability to use technology"], ["widen the gap", "make the difference larger"], ["transition", "change from one state to another"]],
    mistakes: ["Writing only about advantages of AI.", "Offering solutions without linking them to the problems.", "Using technical vocabulary incorrectly; choose words you can control."],
  },
  {
    slug: "space-exploration-spending",
    title: "Money spent on space exploration",
    category: "Government",
    type: "Opinion (agree/disagree)",
    question: "Some people say that governments should not spend money on space exploration because there are more important problems on Earth. To what extent do you agree or disagree?",
    analysis: "Decide whether space spending is a waste when problems like poverty and disease exist. Provide a clear position and evidence of benefits or drawbacks.",
    outline: [
      { heading: "Introduction", text: "State that you partly agree: priorities matter, but space research brings useful benefits." },
      { heading: "Body 1: urgent problems", text: "Hunger, healthcare and education need funding; space budgets are large." },
      { heading: "Body 2: benefits of space", text: "Satellites, weather forecasts, medical and materials technology developed through space programmes." },
      { heading: "Conclusion", text: "Space spending should be modest and linked to practical benefits." },
    ],
    sample: [
      "Space programmes cost billions of dollars every year, leading some people to argue that this money should be used to solve problems on our own planet. I partly agree with this view, since basic needs must come first, but I do not think space exploration should be abandoned.",
      "The argument against space spending is easy to understand. Millions of people still lack clean water, adequate healthcare or access to education, and even a small proportion of a space budget could build many schools or hospitals. When governments face economic difficulties, it seems unfair to spend public money on missions that will not improve daily life in the short term.",
      "However, space research has produced technologies that benefit everyone. Satellites provide weather forecasts that warn communities about storms, support navigation systems and allow global communication. Medical devices, water purification systems and lightweight materials have been developed or improved through work originally done for space. These advances often justify the investment by saving lives and creating new industries. It is also worth noting that space agencies employ many thousands of engineers and technicians, so the money is not simply thrown away; it supports skilled jobs and inspires young people to study science, which strengthens the wider economy for years afterwards.",
      "Moreover, studying other planets helps scientists understand climate change and the future of the Earth itself.",
      "In conclusion, because people's basic needs are a priority, space budgets should remain moderate and be linked to practical outcomes, but eliminating them entirely would cost society valuable scientific progress."
    ],
    vocab: [["priority", "something treated as most important"], ["public funds", "money from taxes"], ["navigation system", "technology that shows where you are"], ["spin-off technology", "useful products created from other research"], ["justify", "show to be reasonable"], ["modest budget", "a fairly small amount of money"], ["scientific progress", "advances in knowledge"]],
    mistakes: ["Only listing problems on Earth without answering the question about space.", "Giving examples that are too general, such as “technology is good”.", "Using “I think” in every sentence."],
  },
  {
    slug: "compulsory-foreign-language-school",
    title: "Should all children learn a foreign language at school?",
    category: "Education",
    type: "Opinion (agree/disagree)",
    question: "Some people believe that all children should learn at least one foreign language at school. To what extent do you agree or disagree?",
    analysis: "Decide whether foreign-language learning should be compulsory. Support your position with benefits (career, cognition, culture) and acknowledge a practical limitation.",
    outline: [
      { heading: "Introduction", text: "Say that you strongly agree because the benefits are wide-ranging." },
      { heading: "Body 1: personal benefits", text: "Better memory and problem-solving, improved understanding of grammar in the first language." },
      { heading: "Body 2: social and economic benefits", text: "Career opportunities, tolerance for other cultures, travel and communication." },
      { heading: "Conclusion", text: "Languages should be taught well, with trained teachers and speaking practice." },
    ],
    sample: [
      "In an increasingly connected world, the ability to speak more than one language is a valuable asset. I strongly agree that every child should learn at least one foreign language at school, as the benefits are both personal and social.",
      "From a personal perspective, learning another language develops the brain. Research suggests that bilingual people often have better memory and are more skilled at switching between tasks. Studying a foreign grammar system also helps children understand their own language more clearly, which can improve their writing. Furthermore, mastering a difficult subject builds confidence and perseverance.",
      "At a wider level, languages bring important economic and cultural advantages. Employees who speak English, Chinese or Spanish can work for international companies and enjoy more career options, which also benefits the national economy. Learning a language includes learning about another culture, and this can reduce prejudice and encourage tolerance between communities. A teenager who has exchanged letters with a student abroad is less likely to believe harmful stereotypes. Early exposure matters as well, because younger children usually acquire pronunciation more naturally than adults, and those who begin in primary school are far more likely to reach a comfortable level of fluency by the time they finish secondary education.",
      "Of course, the policy only works if teaching is good. Schools need trained teachers, small classes and plenty of speaking practice rather than memorising lists of words. Technology such as language apps and video exchanges can support this.",
      "In conclusion, because language skills improve thinking, careers and understanding between nations, I believe foreign language learning should be compulsory in schools, provided that it is taught effectively."
    ],
    vocab: [["bilingual", "able to speak two languages"], ["asset", "something valuable"], ["perseverance", "continuing despite difficulty"], ["cultural exchange", "sharing customs and ideas between countries"], ["stereotype", "a fixed, oversimplified idea about a group"], ["compulsory", "required by rule"], ["fluency", "ability to speak smoothly"]],
    mistakes: ["Writing about learning English only, not “a foreign language” in general.", "Repeating the same reason in both body paragraphs.", "Ignoring how languages should be taught."],
  },
  {
    slug: "english-as-a-global-language",
    title: "English as a global language: advantages and disadvantages",
    category: "Globalization",
    type: "Advantages and disadvantages",
    question: "English is increasingly used as a global language for business and communication. Do the advantages of this development outweigh the disadvantages?",
    analysis: "Weigh the benefits of a shared language against the risks, such as loss of local languages and unequal opportunities, then give a clear judgement.",
    outline: [
      { heading: "Introduction", text: "State that, overall, the advantages are greater, but there are real risks." },
      { heading: "Body 1: advantages", text: "Easier international trade, scientific cooperation, travel and access to information." },
      { heading: "Body 2: disadvantages", text: "Decline of minority languages and unfair advantage for native speakers; suggest bilingual education." },
      { heading: "Conclusion", text: "Benefits outweigh drawbacks if local languages are protected." },
    ],
    sample: [
      "English has become the most widely used language in international business, science and the internet. This trend has some drawbacks, but I believe the advantages outweigh them.",
      "The main benefit is easier communication across borders. When companies from different countries share a common language, they can negotiate and trade without costly translation, which supports economic growth. Scientists also publish their findings in English, allowing researchers worldwide to build on each other's work and speeding up progress in medicine and technology. For ordinary people, English opens access to an enormous amount of online information, from university courses to news, and makes travelling much simpler.",
      "However, the dominance of English creates certain problems. Smaller languages may lose speakers as young people choose English for education and careers, and when a language disappears, a unique way of seeing the world disappears with it. In addition, native speakers have a natural advantage in international business and academic competition, while others must spend years and money mastering the language. Some people also worry that a single dominant language will make cultures more alike, yet in practice young people often use English for work while still expressing humour, emotion and identity in their own language, which suggests the two can coexist.",
      "These risks can be reduced. Governments can support bilingual education that teaches English alongside the mother tongue, and use media and festivals to keep local languages alive.",
      "In conclusion, a global language makes cooperation easier and knowledge more accessible. Provided that local languages are actively protected, I believe the advantages of English as an international language are greater than its disadvantages."
    ],
    vocab: [["lingua franca", "a common language between different peoples"], ["mother tongue", "first language"], ["minority language", "a language spoken by few people"], ["dominance", "being the most powerful or common"], ["cross-border", "between countries"], ["linguistic diversity", "a variety of languages"], ["accessible", "easy to reach or obtain"]],
    mistakes: ["Describing English history instead of answering the question.", "Writing only advantages.", "Using “native” and “mother tongue” incorrectly."],
  },
  {
    slug: "individuals-or-governments-environment",
    title: "Who should protect the environment: individuals or governments?",
    category: "Environment",
    type: "Discussion + opinion",
    question: "Some people believe that individuals should take responsibility for protecting the environment, while others think this is the job of governments. Discuss both views and give your opinion.",
    analysis: "Discuss the role of individuals and the role of governments, then state which is more important or how they work together.",
    outline: [
      { heading: "Introduction", text: "Say that both are needed, but governments have greater power to cause change." },
      { heading: "Body 1: individuals", text: "Recycling, energy saving and consumer choices create demand for greener products." },
      { heading: "Body 2: governments", text: "Laws, taxes and large infrastructure such as public transport and renewable energy." },
      { heading: "Conclusion", text: "Real progress needs cooperation, led by government policy." },
    ],
    sample: [
      "Environmental problems such as pollution and climate change affect everyone, but opinions differ on who should act. Some believe the responsibility lies with individuals, while others emphasise governments. In my view, both are necessary, though governments must take the lead.",
      "Supporters of individual responsibility point out that environmental damage is the sum of millions of daily decisions. When people recycle, save electricity, use public transport and avoid wasting food, the combined effect is considerable. Consumers who choose sustainable products also push companies to produce them, because businesses respond to demand. Personal action can also set an example for children and neighbours.",
      "However, individuals have limited power. A resident cannot build a wind farm or force a factory to reduce emissions. Governments, by contrast, can pass laws on pollution, tax carbon-heavy industries and invest in renewable energy and efficient public transport. These measures change behaviour on a national scale. For example, charging for plastic bags in many countries led to a dramatic drop in their use within months. Businesses should not be forgotten either, since large companies control supply chains and packaging, and when governments require transparent reporting of emissions, firms compete to improve their image, which spreads cleaner practices much faster than appeals to individual conscience.",
      "Government policy also makes green choices easier: people are more likely to cycle if safe cycle lanes exist, and to recycle if collection is convenient.",
      "In conclusion, individual actions matter and can inspire others, but the scale of environmental problems demands strong laws and investment from governments. Real progress will happen only when both work together."
    ],
    vocab: [["sustainable", "able to continue without harming the environment"], ["carbon-heavy", "producing a lot of carbon dioxide"], ["renewable energy", "power from sources that do not run out"], ["emissions", "gases released into the air"], ["infrastructure", "basic physical systems such as roads"], ["set an example", "behave as a model for others"], ["on a national scale", "across the whole country"]],
    mistakes: ["Giving only one view fully.", "Using “we should protect the earth” as a conclusion without a specific point.", "Not clarifying which side you prefer."],
  },
];
