// Uzbek grammar guides for the public SEO section /ingliz-tili-qoidalari. Each guide explains one topic for Uzbek
// speakers, points out the typical traps caused by Uzbek, and leads to the matching interactive lesson.
export type GuideSection = { h2: string; p?: string[]; list?: string[]; table?: { head: string[]; rows: string[][] }; ex?: [en: string, uz: string][] };
export type Guide = {
  slug: string; level: 'beginner' | 'elementary' | 'pre-intermediate';
  h1: string; metaTitle: string; metaDesc: string; intro: string;
  sections: GuideSection[]; traps: string[]; faq: { q: string; a: string }[];
  lesson: [level: string, slug: string]; related: string[];
};

export const GUIDES: Guide[] = [
  {
    slug: 'ingliz-alifbosi', level: 'beginner',
    h1: `Ingliz alifbosi va harflarning o'qilishi`,
    metaTitle: `Ingliz alifbosi: 26 harf, o'qilishi va talaffuzi o'zbek tilida`,
    metaDesc: `Ingliz alifbosining 26 harfi, har birining nomi va talaffuzi (transkripsiya bilan), unli va undoshlar, o'zbek tilidan farqlari. Yangi boshlovchilar uchun.`,
    intro: `Ingliz alifbosi lotin yozuviga asoslangan, shuning uchun o'zbek o'quvchisi uchun tanish. Lekin harflarning nomi va tovushi o'zbek alifbosidagidan farq qiladi: ingliz tilida 26 harf, 44 ga yaqin tovush bor.`,
    sections: [
      { h2: `26 harf va ularning nomi`, p: [`Quyidagi jadvalda har bir harfning nomi (ismi) transkripsiya bilan berilgan. Harfning nomi va u so'zda bergan tovush ko'pincha bir xil bo'lmaydi: masalan, C harfi nomi «si», lekin cat so'zida «k» deb o'qiladi.`],
        table: { head: [`Harf`, `Nomi`, `Misol`], rows: [
          [`A a`, `/eɪ/`, `apple`], [`B b`, `/biː/`, `book`], [`C c`, `/siː/`, `cat`], [`D d`, `/diː/`, `dog`], [`E e`, `/iː/`, `egg`], [`F f`, `/ef/`, `fish`], [`G g`, `/dʒiː/`, `green`],
          [`H h`, `/eɪtʃ/`, `house`], [`I i`, `/aɪ/`, `ice`], [`J j`, `/dʒeɪ/`, `juice`], [`K k`, `/keɪ/`, `key`], [`L l`, `/el/`, `lemon`], [`M m`, `/em/`, `milk`], [`N n`, `/en/`, `nose`],
          [`O o`, `/əʊ/`, `orange`], [`P p`, `/piː/`, `pen`], [`Q q`, `/kjuː/`, `queen`], [`R r`, `/ɑː(r)/`, `red`], [`S s`, `/es/`, `sun`], [`T t`, `/tiː/`, `tea`], [`U u`, `/juː/`, `umbrella`],
          [`V v`, `/viː/`, `very`], [`W w`, `/ˈdʌbljuː/`, `water`], [`X x`, `/eks/`, `box`], [`Y y`, `/waɪ/`, `yellow`], [`Z z`, `/zed/ yoki /ziː/`, `zoo`],
        ] } },
      { h2: `Unli va undosh harflar`, p: [`Ingliz alifbosida 5 ta unli harf bor: A, E, I, O, U. Qolgan 21 tasi undosh. Y harfi so'z o'rtasida va oxirida ko'pincha unli kabi o'qiladi (my, happy).`, `Muhim farq: o'zbek tilida bitta harf odatda bitta tovush beradi, ingliz tilida esa bitta unli harf bir nechta turlicha o'qilishi mumkin (cat, cake, car, all). Shuning uchun yangi so'zni har doim talaffuzi bilan birga o'rganing.`] },
      { h2: `Harf birikmalari`, p: [`Ba'zi harflar birga kelganda bitta yangi tovush beradi:`],
        list: [`sh — /ʃ/: ship, fish («sh»ga o'xshash, o'zbekcha «sh»)`, `ch — /tʃ/: chair, teacher («ch»)`, `th — /θ/ yoki /ð/: think, this (til tishlar orasida; o'zbek tilida bunday tovush yo'q)`, `ph — /f/: phone`, `ng — /ŋ/: sing, long (burun orqali, «n+g» emas)`] },
      { h2: `So'zni harflab aytish (spelling)`, p: [`Ism yoki familiyani harflab aytish kundalik hayotda ko'p kerak bo'ladi: telefonda, mehmonxonada, aeroportda. Savol: «How do you spell your name?» Javob: «It's A-B-D-U-L-L-A-H.» Qo'sh harf bo'lsa «double L» (LL) deyiladi.`],
        ex: [[`How do you spell your surname?`, `Familiyangizni qanday harflab aytasiz?`], [`M-O-R-G-A-N. Double R? No, just one R.`, `M-O-R-G-A-N. Qo'sh R? Yo'q, bitta R.`]] },
    ],
    traps: [`O'zbek tilidagi o', g', sh, ch, ng harflari ingliz alifbosida yo'q: o'zbekcha «o'» (o‘) uchun ingliz tilida alohida harf bo'lmaydi.`, `W harfini «v» deb o'qimang: water /ˈwɔːtə/ so'zida lablar yumaloqlanib «u»ga yaqin tovush chiqadi, very so'zida esa V tishlar lab bilan hosil qilinadi.`, `H harfi ingliz tilida nafas bilan yengil aytiladi (house), o'zbekchadagi «x» kabi qattiq emas.`, `Harf nomini tovush bilan adashtirmang: A nomi «ey», lekin apple da /æ/ ga yaqin ochiq tovush.`],
    faq: [{ q: `Ingliz alifbosida nechta harf bor?`, a: `26 ta: 5 ta unli (A, E, I, O, U) va 21 ta undosh. Tovushlar esa 44 ga yaqin.` }, { q: `Nega ingliz tilida harf va tovush mos kelmaydi?`, a: `Ingliz imlosi tarixan shakllangan va ko'p so'zlar qadimgi talaffuzni saqlagan. Shuning uchun so'zni yodlashda talaffuzi va transkripsiyasini ham ko'rish kerak.` }, { q: `Alifboni qancha vaqtda o'rganish mumkin?`, a: `Harflar nomini odatda 1–2 kunda eslab qolasiz. Tovushlarni o'qish ko'nikmasi esa o'nlab so'zni audio bilan takrorlash orqali shakllanadi.` }],
    lesson: [`beginner`, `the-alphabet-a-m`], related: [`to-be-am-is-are`, `shaxs-olmoshlari`],
  },
  {
    slug: 'to-be-am-is-are', level: 'beginner',
    h1: `Ingliz tilida to be fe'li: am, is, are`,
    metaTitle: `To be fe'li: am, is, are qoidasi o'zbek tilida (misollar bilan)`,
    metaDesc: `Ingliz tilida to be fe'li: am, is, are qachon ishlatiladi, inkor va so'roq shakllari, qisqartmalar va o'zbek tilidan farqli xatolar. Misollar va javoblar.`,
    intro: `To be (bo'lmoq) ingliz tilidagi eng muhim fe'l. Uning yordamida o'zingiz haqingizda gapirasiz: ismingiz, yoshingiz, kasbingiz, qayerdaligingiz. O'zbek tilida bu ma'noni «-man, -san, -di» qo'shimchalari beradi, ingliz tilida esa alohida so'z kerak.`,
    sections: [
      { h2: `Shakllari`, table: { head: [`Shaxs`, `To be`, `Misol`, `Qisqartma`], rows: [[`I`, `am`, `I am a student.`, `I'm`], [`You`, `are`, `You are late.`, `you're`], [`He / She / It`, `is`, `She is a doctor.`, `she's`], [`We`, `are`, `We are friends.`, `we're`], [`They`, `are`, `They are at home.`, `they're`]] },
        p: [`Hozirgi zamonda to be uchta shaklga ega: am (faqat I bilan), is (he, she, it va bitta narsa bilan), are (you, we, they va ko'plik bilan).`] },
      { h2: `Inkor gap`, p: [`To be dan keyin not qo'yiladi: I am not, he is not (isn't), they are not (aren't).`], ex: [[`I am not tired.`, `Men charchamaganman.`], [`He isn't at school.`, `U maktabda emas.`], [`We aren't ready.`, `Biz tayyor emasmiz.`]] },
      { h2: `So'roq gap`, p: [`So'roq gapda to be gapning boshiga chiqadi: Am I...? Is she...? Are they...?`], ex: [[`Are you a teacher?`, `Siz o'qituvchimisiz?`], [`Is she from Tashkent?`, `U Toshkentdanmi?`], [`Where are you from?`, `Siz qayerdansiz?`]] },
      { h2: `Qachon ishlatiladi?`, list: [`Ism, yosh, kasb: My name is Ali. I am 20. He is an engineer.`, `Millat va davlat: She is from Uzbekistan. We are Uzbek.`, `Holat va his: I am happy. They are tired.`, `Joy: The book is on the table.`, `Tavsif: The city is big and beautiful.`] },
    ],
    traps: [`O'zbek tilida «Men talabaman» deymiz, ingliz tilida esa to be ni tushirib bo'lmaydi: «I student» emas, «I am a student».`, `Kasb oldida a/an kerak: «He is doctor» emas, «He is a doctor».`, `Yosh ham to be bilan aytiladi: «I am 20» (I have 20 emas).`, `He/she/it bilan faqat is: «She are» xato.`],
    faq: [{ q: `Am, is, are farqi nima?`, a: `Bu bitta fe'lning shaxsga qarab o'zgargan shakllari: I → am, he/she/it → is, you/we/they → are.` }, { q: `Nega «I am» deb aytiladi, «I is» emas?`, a: `To be tartibsiz fe'l: uning shakllari qoidaga bo'ysunmaydi va yodlash kerak.` }, { q: `Savol berishda do/does ishlatamizmi?`, a: `To be bilan yo'q. Savolda to be ning o'zi oldinga chiqadi: «Are you ready?» (Do you are ready? emas).` }],
    lesson: [`beginner`, `to-be-am-is-are`], related: [`shaxs-olmoshlari`, `present-simple`],
  },
  {
    slug: 'shaxs-olmoshlari', level: 'beginner',
    h1: `Ingliz tilida olmoshlar: I, you, he, she va my, your`,
    metaTitle: `Ingliz tilida olmoshlar: shaxs va egalik olmoshlari (jadval)`,
    metaDesc: `Ingliz tilida shaxs olmoshlari (I, you, he, she, it, we, they), egalik olmoshlari (my, your, his...) va object shakllari (me, him, us). Jadval va misollar.`,
    intro: `Olmoshlar gapni qisqa va tabiiy qiladi: har safar ismni takrorlash o'rniga he, she, it deymiz. Ingliz tilida uch xil muhim olmosh guruhi bor: kim? (I), kimning? (my) va kimni? (me).`,
    sections: [
      { h2: `Hammasi bitta jadvalda`, table: { head: [`Shaxs`, `Kim? (subject)`, `Kimning? (egalik)`, `Kimni? (object)`], rows: [[`men`, `I`, `my`, `me`], [`sen / siz`, `you`, `your`, `you`], [`u (erkak)`, `he`, `his`, `him`], [`u (ayol)`, `she`, `her`, `her`], [`u (narsa, hayvon)`, `it`, `its`, `it`], [`biz`, `we`, `our`, `us`], [`ular`, `they`, `their`, `them`]] } },
      { h2: `Qanday ishlatiladi`, list: [`Subject olmosh fe'ldan oldin: She works here. They live in Samarkand.`, `Egalik olmosh otdan oldin: my phone, your book, their house.`, `Object olmosh fe'ldan keyin: Call me. I like him. She helps us.`], ex: [[`This is my brother. He is a student.`, `Bu mening akam. U talaba.`], [`I know them. Their house is near ours.`, `Men ularni bilaman. Ularning uyi bizniki yaqinida.`]] },
      { h2: `Ingliz tilida «siz» va «sen» yo'q`, p: [`O'zbek tilida hurmat bilan «siz», yaqin odamga «sen» deymiz. Ingliz tilida ikkalasi ham you. Hurmat so'zlar bilan (please, could you...) ifodalanadi.`] },
    ],
    traps: [`It — jonsiz narsa va hayvon uchun: «It is a book.» Odam uchun ishlatilmaydi.`, `His va her faqat egasining jinsiga bog'liq: «her brother» — uning (ayolning) akasi, «his sister» — uning (erkakning) singlisi.`, `Egalik olmoshdan oldin the/a qo'yilmaydi: «my the book» xato.`, `You har doim ko'plik fe'li bilan: you are (yakka odamga ham).`],
    faq: [{ q: `He va she o'rniga o'zbekcha «u» deymiz, qanday adashmaslik kerak?`, a: `Odamning jinsiga qarang: erkak bo'lsa he, ayol bo'lsa she. O'zbek tilida bunday ajratish yo'q, shuning uchun avval ongli ravishda mashq qilish kerak.` }, { q: `Its va it's bir xilmi?`, a: `Yo'q. Its — uning (egalik), it's esa it is ning qisqartmasi.` }],
    lesson: [`beginner`, `personal-pronouns`], related: [`to-be-am-is-are`, `articles-a-an-the`],
  },
  {
    slug: 'present-simple', level: 'beginner',
    h1: `Present Simple: hozirgi oddiy zamon qoidasi`,
    metaTitle: `Present Simple qoidasi: tuzilishi, -s qo'shimchasi va misollar (o'zbekcha)`,
    metaDesc: `Present Simple (oddiy hozirgi zamon) qachon ishlatiladi, he/she/it bilan -s, do/does bilan inkor va savol, always/usually kabi so'zlar. O'zbekcha tushuntirish.`,
    intro: `Present Simple odatlar, doimiy holatlar va umumiy haqiqatlarni ifodalaydi: «Men har kuni ertalab choy ichaman», «Yer Quyosh atrofida aylanadi». Bu eng ko'p ishlatiladigan zamon.`,
    sections: [
      { h2: `Tuzilishi`, p: [`I, you, we, they bilan fe'l o'zgarmaydi. He, she, it bilan fe'lga -s (yoki -es) qo'shiladi.`], table: { head: [`Shaxs`, `Fe'l`, `Misol`], rows: [[`I / you / we / they`, `work`, `They work in a bank.`], [`he / she / it`, `works`, `She works in a bank.`]] } },
      { h2: `-s qo'shish qoidalari`, list: [`Ko'pchilik fe'llarga -s: work → works, play → plays.`, `-s, -sh, -ch, -x, -o bilan tugasa -es: watch → watches, go → goes, wash → washes.`, `Undosh + y bilan tugasa y → ies: study → studies, try → tries.`, `Maxsus: have → has.`] },
      { h2: `Inkor va savol`, p: [`Inkor gapda don't (do not) yoki doesn't (does not) ishlatiladi, fe'l esa asl shaklida qoladi. Savolda Do/Does gap boshiga chiqadi.`], ex: [[`I don't drink coffee.`, `Men qahva ichmayman.`], [`He doesn't work on Sundays.`, `U yakshanba kuni ishlamaydi.`], [`Do you live in Tashkent?`, `Siz Toshkentda yashaysizmi?`], [`Does she speak English?`, `U inglizcha gapiradimi?`]] },
      { h2: `Vaqt ko'rsatkichlari`, p: [`Present Simple bilan ko'pincha chastota so'zlari keladi: always (doim), usually (odatda), often (tez-tez), sometimes (ba'zan), never (hech qachon), every day (har kuni), on Mondays (dushanba kunlari).`], ex: [[`I always get up at 6.`, `Men doim soat 6 da turaman.`], [`She never eats meat.`, `U hech qachon go'sht yemaydi.`]] },
    ],
    traps: [`He/she/it bilan -s ni unutish eng ko'p uchraydigan xato: «She work» emas, «She works».`, `Does bilan fe'lga -s qo'shilmaydi: «Does she works?» emas, «Does she work?».`, `Chastota so'zi to be dan keyin, oddiy fe'ldan oldin keladi: «She is always late», «She always works».`, `«I am work» deb yozmang: to be va oddiy fe'l birga ishlatilmaydi.`],
    faq: [{ q: `Present Simple va Present Continuous farqi nima?`, a: `Present Simple odat va umumiy holat uchun (I work every day), Present Continuous hozir sodir bo'layotgan ish uchun (I am working now).` }, { q: `Nega faqat he/she/it ga -s qo'shiladi?`, a: `Ingliz tilida fe'lning shaxs qo'shimchasi qolgan yagona izi shu: 3-shaxs birlik. Qolgan shaxslarda fe'l asl shaklda.` }, { q: `Savol so'zi bilan savol qanday tuziladi?`, a: `Savol so'zi + do/does + ega + fe'l: «Where do you work?», «What does he do?».` }],
    lesson: [`beginner`, `present-simple-i-you-we-they`], related: [`present-continuous`, `savol-tuzish-wh-questions`],
  },
  {
    slug: 'present-continuous', level: 'beginner',
    h1: `Present Continuous: hozir davom etayotgan ish`,
    metaTitle: `Present Continuous qoidasi: am/is/are + -ing (misollar, o'zbekcha)`,
    metaDesc: `Present Continuous (hozirgi davomli zamon): tuzilishi, -ing qo'shish qoidalari, inkor va savol, Present Simple bilan farqi. O'zbek tilida tushuntirish va misollar.`,
    intro: `Present Continuous aynan hozir yoki shu kunlarda davom etayotgan ishni bildiradi: «Men hozir ingliz tilini o'rganyapman», «U telefonda gaplashyapti».`,
    sections: [
      { h2: `Tuzilishi`, p: [`am / is / are + fe'l + -ing`], table: { head: [`Gap turi`, `Tuzilishi`, `Misol`], rows: [[`Darak`, `I am working.`, `Men ishlayapman.`], [`Inkor`, `She is not (isn't) working.`, `U ishlamayapti.`], [`Savol`, `Are you working?`, `Siz ishlayapsizmi?`]] } },
      { h2: `-ing qo'shish qoidalari`, list: [`Oddiy fe'l: work → working, play → playing.`, `-e bilan tugasa e tushadi: make → making, write → writing.`, `Bir bo'g'inli, qisqa unli + undosh: oxirgi undosh ikkilanadi: run → running, sit → sitting.`, `-ie → -ying: lie → lying.`] },
      { h2: `Qachon ishlatiladi`, list: [`Aynan hozir: Listen! The baby is crying.`, `Shu kunlarda: I am reading a good book this week.`, `Yaqin reja: We are meeting tomorrow at 5.`, `O'zgarayotgan holat: Prices are rising.`], ex: [[`What are you doing?`, `Nima qilyapsiz?`], [`I'm studying English now.`, `Men hozir ingliz tilini o'rganyapman.`]] },
      { h2: `-ing qabul qilmaydigan fe'llar`, p: [`Holat va his bildiruvchi fe'llar odatda davomli zamonda ishlatilmaydi: know, understand, like, love, want, need, have (egalik), believe. «I am knowing» emas, «I know».`] },
    ],
    traps: [`To be ni unutmang: «I working» emas, «I am working».`, `Odat uchun Present Simple: «I am going to school every day» emas, «I go to school every day».`, `Like, want, know bilan -ing ishlatilmaydi.`],
    faq: [{ q: `Present Continuous o'zbek tilidagi qaysi shaklga mos?`, a: `«-yapman, -yapti» shakliga: ishlayapman, o'qiyapti, gaplashyapmiz.` }, { q: `Hozirgi zamonni qanday adashtirmaslik kerak?`, a: `Vaqt so'zlariga qarang: now, at the moment, today — Continuous; every day, usually, always — Simple.` }],
    lesson: [`beginner`, `present-continuous`], related: [`present-simple`, `will-va-going-to`],
  },
  {
    slug: 'past-simple', level: 'beginner',
    h1: `Past Simple: o'tgan oddiy zamon qoidasi`,
    metaTitle: `Past Simple qoidasi: -ed, tartibsiz fe'llar, did bilan savol (o'zbekcha)`,
    metaDesc: `Past Simple (o'tgan oddiy zamon): to'g'ri fe'llarga -ed, tartibsiz fe'llar, didn't bilan inkor, Did bilan savol, yesterday, last week kabi so'zlar. Misollar bilan.`,
    intro: `Past Simple o'tmishda tugagan ishni ifodalaydi: «Men kecha kinoga bordim», «U 2020-yilda ko'chib o'tdi». Aniq o'tgan vaqt bo'lsa, odatda shu zamon ishlatiladi.`,
    sections: [
      { h2: `To'g'ri fe'llar: -ed`, p: [`To'g'ri fe'llarga -ed qo'shiladi (barcha shaxslar uchun bir xil): work → worked, play → played, start → started.`], list: [`-e bilan tugasa faqat -d: like → liked.`, `Undosh + y → ied: study → studied.`, `Qisqa unli + undosh ikkilanadi: stop → stopped.`] },
      { h2: `Tartibsiz fe'llar`, p: [`Ko'p muhim fe'llar -ed olmaydi, ularning o'tgan zamon shakli alohida yodlanadi:`], table: { head: [`Hozirgi`, `O'tgan`, `Ma'nosi`], rows: [[`go`, `went`, `bormoq`], [`see`, `saw`, `ko'rmoq`], [`have`, `had`, `ega bo'lmoq`], [`do`, `did`, `qilmoq`], [`eat`, `ate`, `yemoq`], [`buy`, `bought`, `sotib olmoq`], [`take`, `took`, `olmoq`], [`come`, `came`, `kelmoq`]] } },
      { h2: `Inkor va savol`, p: [`Inkorda didn't + asl fe'l, savolda Did + ega + asl fe'l. Fe'l o'tgan shaklga o'tmaydi, chunki o'tgan zamon did da ko'rsatilgan.`], ex: [[`I didn't go to work yesterday.`, `Men kecha ishga bormadim.`], [`Did you see the film?`, `Siz filmni ko'rdingizmi?`], [`She watched TV last night.`, `U kecha kechqurun televizor ko'rdi.`]] },
      { h2: `Vaqt ko'rsatkichlari`, list: [`yesterday (kecha), last week / month / year (o'tgan hafta / oy / yil)`, `two days ago (ikki kun oldin), in 2019, when I was a child`] },
    ],
    traps: [`Did bilan fe'lni o'tgan shaklda yozmang: «Did you went?» emas, «Did you go?».`, `Didn't dan keyin ham asl fe'l: «He didn't came» emas, «He didn't come».`, `-ed ning o'qilishi: worked /t/, played /d/, wanted /ɪd/.`],
    faq: [{ q: `Past Simple va Present Perfect farqi nima?`, a: `Aniq o'tgan vaqt bor bo'lsa Past Simple (I saw him yesterday). Vaqt aytilmagan yoki natija hozirga bog'liq bo'lsa Present Perfect (I have seen him).` }, { q: `Tartibsiz fe'llarni qanday tez yodlash mumkin?`, a: `Kuniga 5–6 tadan, jumla ichida va audio bilan takrorlang. Eng ko'p ishlatiladiganlardan (be, have, go, do, see, take) boshlang.` }],
    lesson: [`beginner`, `past-simple-regular-verbs`], related: [`ingliz-tilida-tartibsiz-fellar`, `present-perfect`],
  },
  {
    slug: 'will-va-going-to', level: 'beginner',
    h1: `Kelasi zamon: will va going to farqi`,
    metaTitle: `Will va going to: kelasi zamon farqi va qoidasi (o'zbekcha tushuntirish)`,
    metaDesc: `Ingliz tilida kelasi zamon: will va be going to qachon ishlatiladi, farqi, inkor va savol, misollar. Reja, bashorat, va'da va qaror uchun qoidalar.`,
    intro: `Ingliz tilida kelasi zamonni ifodalashning ikki asosiy usuli bor: will va be going to. Ular ko'pincha almashadi, lekin ma'nosida nozik farq bor.`,
    sections: [
      { h2: `Be going to: reja va dalilga asoslangan bashorat`, p: [`Tuzilishi: am/is/are + going to + fe'l. Oldindan qilingan reja yoki hozirgi dalilga ko'ra ishonch bilan aytilgan bashorat.`], ex: [[`I'm going to study medicine.`, `Men tibbiyotni o'qimoqchiman (reja).`], [`Look at the clouds! It's going to rain.`, `Bulutlarga qara! Yomg'ir yog'adi (dalil).`]] },
      { h2: `Will: qaror, va'da, taxmin`, p: [`Tuzilishi: will + fe'l (barcha shaxslarda o'zgarmaydi). Gap paytida qabul qilingan qaror, va'da, taklif yoki shaxsiy taxmin uchun.`], ex: [[`I'm cold. I'll close the window.`, `Sovuq qotdim. Derazani yopaman (shu zahoti qaror).`], [`I will call you tonight.`, `Men senga kechqurun qo'ng'iroq qilaman (va'da).`], [`I think she will pass the exam.`, `Menimcha, u imtihondan o'tadi (taxmin).`]] },
      { h2: `Inkor va savol`, p: [`Will not = won't. Savolda will gap boshiga chiqadi.`], ex: [[`I won't be late.`, `Men kechikmayman.`], [`Will you help me?`, `Menga yordam berasizmi?`], [`Are you going to travel this summer?`, `Bu yozda sayohat qilmoqchimisiz?`]] },
      { h2: `Tez eslab qolish qoidasi`, list: [`Oldindan o'ylangan reja → going to`, `Shu payt qaror, va'da, taklif → will`, `Fikr, taxmin (I think, probably) → will`, `Ko'z o'ngidagi dalil → going to`] },
    ],
    traps: [`Will dan keyin to qo'yilmaydi: «I will to go» emas, «I will go».`, `Will va going to dan keyin fe'l asl shaklda, -s qo'shilmaydi: «She will goes» emas.`, `Vaqt va shart gaplarida (when, if) will ishlatilmaydi: «If it rains, I will stay» to'g'ri, «If it will rain» xato.`],
    faq: [{ q: `Will va going to ni almashtirsa bo'ladimi?`, a: `Taxmin gaplarida ko'pincha ha. Reja bor bo'lsa going to, shu payt qaror qilingan bo'lsa will tabiiyroq.` }, { q: `Present Continuous bilan ham kelasi zamonni aytish mumkinmi?`, a: `Ha, aniq kelishilgan reja uchun: «We are meeting at 5 tomorrow.»` }],
    lesson: [`beginner`, `future-will`], related: [`present-continuous`, `past-simple`],
  },
  {
    slug: 'articles-a-an-the', level: 'beginner',
    h1: `Artikllar: a, an, the qachon ishlatiladi`,
    metaTitle: `Ingliz tilida artikllar: a, an, the qoidasi (o'zbek tilida tushuntirish)`,
    metaDesc: `Ingliz tilida a, an va the artikllari: qachon ishlatiladi, qachon ishlatilmaydi. O'zbek tilida artikl yo'qligi sabab xatolar va ularning oldini olish. Misollar.`,
    intro: `O'zbek tilida artikl yo'q, shuning uchun o'zbek o'quvchilari uchun a/an/the eng qiyin mavzulardan biri. Lekin qoidalar kam va ularni bir marta tushunsangiz, amalda ishlatish osonlashadi.`,
    sections: [
      { h2: `A va an: bitta, noma'lum narsa`, p: [`A / an «bitta» ma'nosini bildiradi va sanaladigan birlik ot oldida ishlatiladi. Tanlash tovushga bog'liq (harfga emas):`], list: [`Undosh tovush oldida a: a book, a student, a university (/juː/ — undosh tovush).`, `Unli tovush oldida an: an apple, an egg, an hour (h aytilmaydi).`] },
      { h2: `The: ma'lum, aniq narsa`, p: [`The — suhbatdosh qaysi narsa haqida gapirayotganimizni biladi, yoki narsa yagona:`], list: [`Oldin tilga olingan: I have a dog. The dog is very friendly.`, `Yagona narsa: the sun, the moon, the Internet.`, `Superlativ bilan: the best, the largest.`, `Aniq joy yoki odam: the teacher (bizning o'qituvchi), the station.`] },
      { h2: `Artikl kerak emas (zero article)`, list: [`Ko'plik va sanalmaydigan otlarni umumiy ma'noda aytganda: I like music. Dogs are friendly.`, `Ko'pchilik shahar, davlat va shaxs ismlari: Tashkent, Uzbekistan, Ali.`, `Til, ovqat vaqti va sport nomlari: I speak English. We have lunch at 1. He plays football.`] },
      { h2: `Qisqa misollar`, ex: [[`She is a nurse.`, `U hamshira (kasb).`], [`I saw an elephant at the zoo.`, `Men hayvonot bog'ida fil ko'rdim.`], [`Close the door, please.`, `Eshikni yoping (qaysi eshik ekani ma'lum).`]] },
    ],
    traps: [`Kasb oldida a/an kerak: «I am teacher» emas, «I am a teacher».`, `A/an faqat birlik sanaladigan otlar bilan: «a books», «an information» xato.`, `Harfga emas tovushga qarang: an hour, a university.`, `The ni hamma joyda qo'ymang: «The life is beautiful» (umumiy ma'noda) emas, «Life is beautiful».`],
    faq: [{ q: `Artiklsiz gapirsam tushunisharmikan?`, a: `Ko'pincha tushunishadi, lekin gap noto'g'ri eshitiladi va IELTS kabi imtihonlarda grammatik xato hisoblanadi. Eng muhimi kasb oldidagi a/an va ma'lum narsa oldidagi the.` }, { q: `Qaysi so'zlar oldida an ishlatiladi?`, a: `Unli tovush bilan boshlanuvchi so'zlar oldida: an apple, an umbrella, an hour. Harf emas, birinchi tovush hal qiladi.` }],
    lesson: [`beginner`, `a-an-plurals`], related: [`there-is-there-are`, `shaxs-olmoshlari`],
  },
  {
    slug: 'there-is-there-are', level: 'beginner',
    h1: `There is va there are: «bor» ma'nosi`,
    metaTitle: `There is va there are qoidasi: ingliz tilida «bor» (o'zbekcha misollar)`,
    metaDesc: `Ingliz tilida «bor» ma'nosini beruvchi there is va there are: ishlatilishi, inkor, savol, some/any, a lot of. O'zbekcha tushuntirish va misollar.`,
    intro: `Biror joyda nimadir borligini aytish uchun there is (birlik) va there are (ko'plik) ishlatiladi: «Xonada stol bor», «Shaharda ko'p parklar bor». Ingliz tilida bu «have» emas.`,
    sections: [
      { h2: `Tuzilishi`, table: { head: [`Shakl`, `Birlik`, `Ko'plik`], rows: [[`Darak`, `There is a table.`, `There are two chairs.`], [`Inkor`, `There isn't a table.`, `There aren't any chairs.`], [`Savol`, `Is there a table?`, `Are there any chairs?`]] } },
      { h2: `Some, any, a lot of`, list: [`Darak gapda some: There are some books on the shelf.`, `Inkor va savolda any: There aren't any books. Are there any books?`, `Ko'p: There are a lot of people in the park.`] },
      { h2: `Joy predloglari bilan`, p: [`There is/are odatda joy bildiruvchi so'z bilan keladi: in, on, under, next to, near, between.`], ex: [[`There is a bank next to the school.`, `Maktab yonida bank bor.`], [`Are there any shops near here?`, `Bu yerda yaqin atrofda do'konlar bormi?`]] },
    ],
    traps: [`«Bor» ni have bilan tarjima qilmang: «In my room have a bed» emas, «There is a bed in my room».`, `Keyingi otning sonidan kelib chiqing: There is a car / There are two cars.`, `Bir nechta narsa sanalsa, birinchisiga qarab: There is a pen and two books (norasmiy), rasmiy yozuvda ko'plikka yaqin.`],
    faq: [{ q: `There is va it is farqi nima?`, a: `There is nimadir borligini bildiradi (There is a cat on the sofa), it is esa ma'lum narsani tavsiflaydi (It is a black cat).` }, { q: `Have got bilan farqi?`, a: `Have got egalikni bildiradi (I have got a car), there is esa joyda mavjudlikni (There is a car in the garage).` }],
    lesson: [`beginner`, `there-is-there-are`], related: [`articles-a-an-the`, `prepositions-in-on-at`],
  },
  {
    slug: 'can-must-should', level: 'beginner',
    h1: `Can, must, should: modal fe'llar qoidasi`,
    metaTitle: `Can, must, should: modal fe'llar (qoida va misollar o'zbek tilida)`,
    metaDesc: `Ingliz tilida modal fe'llar: can/can't (qila olish), must/mustn't (majburiyat va taqiq), should (maslahat), have to. Tuzilishi, inkor va savol, misollar.`,
    intro: `Modal fe'llar (can, must, should va boshqalar) imkoniyat, majburiyat va maslahatni ifodalaydi. Ularning ikki muhim xususiyati bor: shaxsga qarab o'zgarmaydi va keyingi fe'l to siz, asl shaklda keladi.`,
    sections: [
      { h2: `Can: qila olish, ruxsat`, ex: [[`I can swim.`, `Men suza olaman.`], [`She can't drive.`, `U mashina haydamaydi (haydashni bilmaydi).`], [`Can I open the window?`, `Derazani ochsam bo'ladimi?`]] },
      { h2: `Must va have to: majburiyat`, p: [`Must — shaxsiy yoki qat'iy majburiyat, have to — tashqi qoida bo'yicha zarurat. Mustn't — taqiq, don't have to — shart emas.`], ex: [[`You must wear a seat belt.`, `Xavfsizlik kamarini taqish shart.`], [`I have to get up early on Mondays.`, `Dushanba kunlari erta turishim kerak.`], [`You mustn't smoke here.`, `Bu yerda chekish mumkin emas.`], [`You don't have to come.`, `Kelishingiz shart emas.`]] },
      { h2: `Should: maslahat`, ex: [[`You should drink more water.`, `Ko'proq suv ichishingiz kerak (maslahat).`], [`He shouldn't stay up late.`, `U kech yotmasligi kerak.`]] },
      { h2: `Tuzilish qoidasi`, list: [`Modal + asl fe'l: She can swim (swims, swimming emas).`, `Inkor: can't, mustn't, shouldn't. Savol: Can you...? Should I...?`, `-s qo'shilmaydi: He can (cans emas).`] },
    ],
    traps: [`Modaldan keyin to yo'q: «I can to swim» emas, «I can swim».`, `Mustn't (taqiq) va don't have to (shart emas) ma'nosi butunlay boshqacha.`, `Modal fe'lga -s qo'shilmaydi: «He cans» emas, «He can».`],
    faq: [{ q: `Must va have to ni qanday farqlash kerak?`, a: `Must — gapiruvchining fikri («Men shunday hisoblayman»), have to — qoida yoki vaziyat talabi. Kundalik nutqda ko'pincha have to ishlatiladi.` }, { q: `Could va can farqi nima?`, a: `Could — can ning o'tgan zamon shakli (I could swim at five) va muloyim iltimos (Could you help me?).` }],
    lesson: [`beginner`, `can-cant`], related: [`present-simple`, `will-va-going-to`],
  },
  {
    slug: 'comparatives-superlatives', level: 'beginner',
    h1: `Qiyosiy va orttirma daraja: bigger, the biggest`,
    metaTitle: `Comparative va superlative: qoida va misollar (ingliz tili, o'zbekcha)`,
    metaDesc: `Ingliz tilida sifatning qiyosiy (-er, more) va orttirma (-est, the most) darajalari: qoidalar, tartibsiz shakllar (good, better, best), than va as...as. Misollar.`,
    intro: `Ikki narsani solishtirish uchun qiyosiy daraja (comparative), eng yuqori darajani ko'rsatish uchun orttirma daraja (superlative) ishlatiladi: «Toshkent Samarqanddan katta», «Bu eng yaxshi kitob».`,
    sections: [
      { h2: `Qoidalar`, table: { head: [`Sifat`, `Comparative`, `Superlative`], rows: [[`Qisqa: tall`, `taller`, `the tallest`], [`-e bilan: large`, `larger`, `the largest`], [`Undosh+y: easy`, `easier`, `the easiest`], [`Qisqa unli+undosh: big`, `bigger`, `the biggest`], [`Uzun: beautiful`, `more beautiful`, `the most beautiful`]] },
        p: [`Bir bo'g'inli sifatlarga -er / -est, ikki va undan ko'p bo'g'inli (asosan) sifatlarga more / the most qo'yiladi.`] },
      { h2: `Tartibsiz shakllar`, table: { head: [`Sifat`, `Comparative`, `Superlative`], rows: [[`good`, `better`, `the best`], [`bad`, `worse`, `the worst`], [`far`, `farther / further`, `the farthest / furthest`], [`little`, `less`, `the least`]] } },
      { h2: `Than va as...as`, ex: [[`My brother is taller than me.`, `Akam mendan balandroq.`], [`This book is more interesting than that one.`, `Bu kitob anavidan qiziqarliroq.`], [`He is as tall as his father.`, `U otasidek baland.`], [`She is the best student in the class.`, `U sinfdagi eng yaxshi o'quvchi.`]] },
    ],
    traps: [`Ikki marta qiyoslamang: «more taller» emas, «taller».`, `Than ni unutmang: «bigger of me» emas, «bigger than me».`, `Superlativ oldida the: «the best», «the most expensive».`, `Than dan keyin I emas me yoki «than I am»: «taller than me» kundalik nutqda keng tarqalgan.`],
    faq: [{ q: `Qaysi sifat -er oladi, qaysi biri more?`, a: `Bir bo'g'inli sifatlar -er (fast → faster). Ko'p bo'g'inlilar more (expensive → more expensive). Ikki bo'g'inli -y bilan tugasa y → ier (happy → happier).` }, { q: `As...as nimani bildiradi?`, a: `Tenglik: «as tall as» — «...dek baland». Inkorda not as...as «...dek emas» degani.` }],
    lesson: [`beginner`, `comparatives-superlatives`], related: [`articles-a-an-the`, `present-simple`],
  },
  {
    slug: 'present-perfect', level: 'elementary',
    h1: `Present Perfect: have/has + V3 qoidasi`,
    metaTitle: `Present Perfect qoidasi: have/has + V3, ever, never, for, since (o'zbekcha)`,
    metaDesc: `Present Perfect zamoni: tuzilishi, qachon ishlatiladi (tajriba, natija, davom etayotgan holat), for va since, Past Simple bilan farqi. O'zbek tilida misollar bilan.`,
    intro: `Present Perfect o'tmishdagi voqeani hozir bilan bog'laydi: tajriba («Men Londonda bo'lganman»), natija («Kalitni yo'qotdim») yoki hozirgacha davom etayotgan holat («U 5 yildan beri shu yerda ishlaydi»).`,
    sections: [
      { h2: `Tuzilishi`, p: [`have / has + fe'lning 3-shakli (past participle). He/she/it bilan has, qolganlarida have.`], table: { head: [`Gap turi`, `Misol`], rows: [[`Darak`, `I have visited Turkey.`], [`Inkor`, `She hasn't finished yet.`], [`Savol`, `Have you ever eaten sushi?`]] } },
      { h2: `Qachon ishlatiladi`, list: [`Hayotiy tajriba (ever, never): Have you ever been to Japan? — No, I have never been there.`, `Hozirga bog'liq natija: I have lost my keys (hozir ular yo'q).`, `Yaqinda bo'lgan voqea (just, already, yet): She has just arrived.`, `Hozirgacha davom etayotgan holat (for, since): We have lived here for ten years.`] },
      { h2: `For va since`, ex: [[`I have studied English for two years.`, `Men ikki yildan beri ingliz tilini o'rganyapman (davomiylik).`], [`He has worked here since 2020.`, `U 2020-yildan beri shu yerda ishlaydi (boshlanish nuqtasi).`]] },
      { h2: `Past Simple bilan farqi`, p: [`Aniq o'tgan vaqt aytilsa (yesterday, in 2019, last week), Past Simple ishlatiladi. Present Perfect aniq vaqt bilan ishlatilmaydi.`], ex: [[`I saw this film yesterday.`, `Men bu filmni kecha ko'rdim (aniq vaqt).`], [`I have seen this film.`, `Men bu filmni ko'rganman (qachon ekani muhim emas).`]] },
    ],
    traps: [`Yesterday, last year, ago bilan Present Perfect ishlatilmaydi: «I have seen him yesterday» xato.`, `Been va gone: «He has been to Paris» (borib qaytgan), «He has gone to Paris» (hozir u yerda).`, `Fe'lning 3-shaklini yodlash kerak: seen, been, done, written.`],
    faq: [{ q: `Present Perfect o'zbek tilida qaysi shaklga mos?`, a: `Ko'pincha «-gan» shakliga: borganman, ko'rganman, yozganman. Lekin o'zbek tilida o'tgan zamon hamma vaqt yagona, ingliz tilida esa Past Simple va Present Perfect ajratiladi.` }, { q: `Just, already, yet qayerga qo'yiladi?`, a: `Just va already have/has dan keyin (I have just arrived), yet esa gap oxirida (Have you finished yet?).` }],
    lesson: [`elementary`, `have-you-ever`], related: [`past-simple`, `ingliz-tilida-tartibsiz-fellar`],
  },
  {
    slug: 'ingliz-tilida-tartibsiz-fellar', level: 'beginner',
    h1: `Ingliz tilida tartibsiz fe'llar ro'yxati (tarjima bilan)`,
    metaTitle: `Tartibsiz fe'llar ro'yxati (irregular verbs): 40 ta asosiy fe'l tarjimasi bilan`,
    metaDesc: `Ingliz tilidagi eng ko'p ishlatiladigan 40 ta tartibsiz fe'l (irregular verbs): 1, 2 va 3-shakllari, o'zbekcha tarjimasi, yodlash usullari. Jadval ko'rinishida.`,
    intro: `Tartibsiz fe'llar o'tgan zamonda va Present Perfect da -ed qo'shimchasini olmaydi, ularning shakllari o'zgaradi. Quyida eng ko'p ishlatiladigan fe'llar jadvali. Ularni jumlada va audio bilan takrorlash eng samarali usul.`,
    sections: [
      { h2: `Eng muhim 40 ta tartibsiz fe'l`, table: { head: [`V1 (hozirgi)`, `V2 (o'tgan)`, `V3 (participle)`, `Ma'nosi`], rows: [
        [`be`, `was / were`, `been`, `bo'lmoq`], [`become`, `became`, `become`, `bo'lib qolmoq`], [`begin`, `began`, `begun`, `boshlamoq`], [`break`, `broke`, `broken`, `sindirmoq`], [`bring`, `brought`, `brought`, `olib kelmoq`],
        [`build`, `built`, `built`, `qurmoq`], [`buy`, `bought`, `bought`, `sotib olmoq`], [`catch`, `caught`, `caught`, `ushlamoq`], [`choose`, `chose`, `chosen`, `tanlamoq`], [`come`, `came`, `come`, `kelmoq`],
        [`do`, `did`, `done`, `qilmoq`], [`drink`, `drank`, `drunk`, `ichmoq`], [`drive`, `drove`, `driven`, `haydamoq`], [`eat`, `ate`, `eaten`, `yemoq`], [`fall`, `fell`, `fallen`, `yiqilmoq`],
        [`feel`, `felt`, `felt`, `his qilmoq`], [`find`, `found`, `found`, `topmoq`], [`fly`, `flew`, `flown`, `uchmoq`], [`forget`, `forgot`, `forgotten`, `unutmoq`], [`get`, `got`, `got`, `olmoq, bo'lmoq`],
        [`give`, `gave`, `given`, `bermoq`], [`go`, `went`, `gone / been`, `bormoq`], [`have`, `had`, `had`, `ega bo'lmoq`], [`hear`, `heard`, `heard`, `eshitmoq`], [`know`, `knew`, `known`, `bilmoq`],
        [`leave`, `left`, `left`, `tark etmoq`], [`make`, `made`, `made`, `yasamoq`], [`meet`, `met`, `met`, `uchrashmoq`], [`pay`, `paid`, `paid`, `to'lamoq`], [`read`, `read /red/`, `read /red/`, `o'qimoq`],
        [`run`, `ran`, `run`, `yugurmoq`], [`say`, `said`, `said`, `aytmoq`], [`see`, `saw`, `seen`, `ko'rmoq`], [`sell`, `sold`, `sold`, `sotmoq`], [`sit`, `sat`, `sat`, `o'tirmoq`],
        [`sleep`, `slept`, `slept`, `uxlamoq`], [`speak`, `spoke`, `spoken`, `gapirmoq`], [`take`, `took`, `taken`, `olmoq`], [`tell`, `told`, `told`, `aytib bermoq`], [`write`, `wrote`, `written`, `yozmoq`],
      ] } },
      { h2: `Yodlash uchun guruhlar`, p: [`Fe'llarni o'xshash shakllari bo'yicha guruhlash yodlashni osonlashtiradi:`], list: [`V2 va V3 bir xil: buy–bought–bought, bring–brought–brought, make–made–made, have–had–had.`, `Uchala shakl bir xil: cut, put, read (yozilishi), hit.`, `-en bilan tugaydigan V3: break–broken, speak–spoken, take–taken, write–written.`, `i–a–u ketma-ketligi: drink–drank–drunk, begin–began–begun, swim–swam–swum.`] },
      { h2: `Jumla ichida`, ex: [[`I bought a new phone last week.`, `Men o'tgan hafta yangi telefon sotib oldim.`], [`She has written three emails today.`, `U bugun uchta email yozdi.`], [`Did you see him? — Yes, I saw him at school.`, `Siz uni ko'rdingizmi? — Ha, maktabda ko'rdim.`]] },
    ],
    traps: [`Tartibsiz fe'lga -ed qo'shmang: «goed», «buyed» xato, «went», «bought» to'g'ri.`, `Did va didn't bilan asl shakl ishlatiladi: «Did you see» (saw emas).`, `Read ning o'tgan shakli yoziladi bir xil, lekin /red/ deb o'qiladi.`],
    faq: [{ q: `Nechta tartibsiz fe'lni bilish kerak?`, a: `Kundalik nutq uchun eng ko'p ishlatiladigan 50–70 tasi yetarli. IELTS va ish uchun taxminan 100 ga yaqin.` }, { q: `Tartibsiz fe'llarni qanday tez yodlash mumkin?`, a: `Har kuni 5 tadan jumla ichida takrorlang, guruhlarga bo'ling va ularni audio bilan eshiting. Scorify darslarida ular alohida mashqlar bilan takrorlanadi.` }],
    lesson: [`beginner`, `irregular-verbs-1`], related: [`past-simple`, `present-perfect`],
  },
  {
    slug: 'prepositions-in-on-at', level: 'beginner',
    h1: `In, on, at predloglari: vaqt va joy uchun qoida`,
    metaTitle: `In, on, at: vaqt va joy predloglari qoidasi (jadval va misollar, o'zbekcha)`,
    metaDesc: `Ingliz tilida in, on, at predloglari: vaqt (soat, kun, oy, yil) va joy uchun qachon qaysi biri ishlatiladi. Jadval, misollar va o'zbekcha tushuntirish.`,
    intro: `In, on, at — eng ko'p ishlatiladigan predloglar. O'zbek tilida ular o'rniga «-da, -dan, -ga» qo'shimchalari ishlaydi, ingliz tilida esa har bir holat uchun alohida predlog tanlanadi. Bitta qoidani eslab qolish kifoya: kichikdan kattagacha.`,
    sections: [
      { h2: `Vaqt uchun`, table: { head: [`Predlog`, `Qachon`, `Misol`], rows: [[`at`, `aniq vaqt, soat`, `at 7 o'clock, at noon, at night, at the weekend`], [`on`, `kun va sana`, `on Monday, on 5 May, on my birthday`], [`in`, `oy, fasl, yil, kun qismi`, `in June, in summer, in 2025, in the morning`]] } },
      { h2: `Joy uchun`, table: { head: [`Predlog`, `Qachon`, `Misol`], rows: [[`at`, `aniq nuqta`, `at home, at school, at the bus stop`], [`on`, `sirt ustida`, `on the table, on the wall, on the second floor`], [`in`, `ichida, chegaralangan joy`, `in the room, in Tashkent, in Uzbekistan`]] } },
      { h2: `Misollar`, ex: [[`The lesson starts at 9 on Monday.`, `Dars dushanba kuni soat 9 da boshlanadi.`], [`I was born in 2000 in Samarkand.`, `Men 2000-yilda Samarqandda tug'ilganman.`], [`The keys are on the table in the kitchen.`, `Kalitlar oshxonada stol ustida.`]] },
      { h2: `Istisnolar`, list: [`in the morning / afternoon / evening, lekin at night.`, `on Monday morning (kun nomi bilan kelsa on).`, `at home, lekin in the house.`] },
    ],
    traps: [`«In Monday» emas, «on Monday».`, `«At the morning» emas, «in the morning».`, `Shahar va davlat bilan in: «in Tashkent», «at Tashkent» emas.`],
    faq: [{ q: `In, on, at ni qanday eslab qolish mumkin?`, a: `Vaqt: at — soat, on — kun, in — oy/yil. Joy: at — nuqta, on — sirt, in — ichi.` }, { q: `Kunning qaysi qismlari uchun qaysi predlog?`, a: `In the morning/afternoon/evening, lekin at night va at noon.` }],
    lesson: [`beginner`, `days-months-in-on-at`], related: [`there-is-there-are`, `present-simple`],
  },
  {
    slug: 'savol-tuzish-wh-questions', level: 'beginner',
    h1: `Ingliz tilida savol tuzish: what, where, when, why, how`,
    metaTitle: `Ingliz tilida savol berish: Wh-savollar va do/does bilan savol (o'zbekcha)`,
    metaDesc: `Ingliz tilida savol tuzish: what, where, when, who, why, how savol so'zlari, do/does/did bilan savol, to be bilan savol. Tuzilish tartibi va misollar o'zbek tilida.`,
    intro: `O'zbek tilida savol ohang yoki «-mi» yuklamasi bilan beriladi, ingliz tilida esa so'z tartibi o'zgaradi. Savol tuzish qoidasi aniq: savol so'zi + yordamchi fe'l + ega + asosiy fe'l.`,
    sections: [
      { h2: `Savol so'zlari`, table: { head: [`So'z`, `Ma'nosi`, `Misol`], rows: [[`What`, `nima, qanday`, `What is your name?`], [`Where`, `qayerda, qayerga`, `Where do you live?`], [`When`, `qachon`, `When does the class start?`], [`Who`, `kim`, `Who is your teacher?`], [`Why`, `nega`, `Why are you late?`], [`How`, `qanday`, `How do you go to work?`], [`How much / many`, `qancha`, `How much is it?`], [`Which`, `qaysi`, `Which book do you want?`]] } },
      { h2: `Savol tuzilishi`, list: [`To be bilan: savol so'zi + am/is/are + ega: Where are you from?`, `Present Simple: savol so'zi + do/does + ega + fe'l: What do you do?`, `Past Simple: savol so'zi + did + ega + fe'l: Where did you go?`, `Ha/yo'q savol: Do you like tea? Is she at home?`] },
      { h2: `Misollar`, ex: [[`What time does the film start?`, `Film soat nechada boshlanadi?`], [`How long have you lived here?`, `Siz bu yerda qancha vaqtdan beri yashaysiz?`], [`Who did you meet yesterday?`, `Kecha kim bilan uchrashdingiz?`]] },
    ],
    traps: [`Savolda do/does ni unutmang: «Where you live?» emas, «Where do you live?».`, `Does dan keyin fe'lga -s qo'shilmaydi: «Where does he lives?» emas, «Where does he live?».`, `Kim ega bo'lsa (Who) do kerak emas: «Who called?» (Who did call? emas).`],
    faq: [{ q: `Savol gapda nega do/does kerak?`, a: `Ingliz tilida savolni faqat yordamchi fe'l bilan qurish mumkin. To be, can, will kabi fe'llar o'zi yordamchi vazifasini bajaradi, boshqa fe'llarda do/does/did kerak.` }, { q: `What va which farqi nima?`, a: `Which cheklangan tanlovda (Which color: red or blue?), what esa keng ma'noda (What color do you like?).` }],
    lesson: [`beginner`, `wh-questions`], related: [`present-simple`, `to-be-am-is-are`],
  },
];
