import type { Task2Question } from './types.js';

export const TASK2_MORE: Task2Question[] = [
  {
    slug: "fast-food-and-health",
    title: "Fast food and public health",
    category: "Health",
    type: "Problem and solution",
    question: "Fast food is becoming more popular and is damaging public health. What problems does this cause and what can be done to solve them?",
    analysis: "Two tasks: explain the health problems caused by fast food and suggest solutions. Link every solution to a problem you mentioned.",
    outline: [
      { heading: "Introduction", text: "Paraphrase and say the essay will describe health problems and propose realistic solutions." },
      { heading: "Body 1: problems", text: "Obesity and heart disease, plus the burden on healthcare systems and lost productivity." },
      { heading: "Body 2: solutions", text: "Nutrition education, clear labelling and taxes on unhealthy products, plus affordable healthy alternatives." },
      { heading: "Conclusion", text: "Summarise that combined action by governments, schools and companies can reduce the damage." },
    ],
    sample: [
      "The growing popularity of fast food is a worrying trend in many countries. This essay will outline the main health problems that result from it and suggest several practical ways to address them.",
      "The most serious problem is the rise in diseases linked to poor diet. Fast food is usually high in fat, sugar and salt, so people who eat it regularly are more likely to become overweight and to develop heart disease or diabetes. These conditions are expensive to treat, and they place a heavy burden on public healthcare systems. In addition, people with poor health are often less productive at work, which has an economic cost for society as a whole.",
      "There are several ways to tackle this problem. Firstly, schools should teach children about nutrition and cooking so that they learn to make healthier choices from an early age. Secondly, governments could require clear labels showing calories and sugar content, and place higher taxes on the least healthy products, using the revenue to subsidise fresh fruit and vegetables. Finally, restaurants can be encouraged to offer healthier options, for example grilled dishes and salads, at competitive prices.",
      "Such measures need cooperation, but they are realistic. Several countries that have taxed sugary drinks have already reported a fall in consumption.",
      "Parents also play an important part. When families cook together at home and eat meals at the table, children learn that food is more than a quick snack, and they are less likely to depend on fast food. Community programmes that teach simple, cheap recipes can make this change realistic even for busy households.",
      "In conclusion, fast food contributes to obesity, illness and higher healthcare costs, but education, labelling and fair pricing can reduce its harmful effects."
    ],
    vocab: [["obesity", "a condition of being very overweight"], ["processed food", "food changed by factory methods"], ["subsidise", "reduce price with public money"], ["healthcare burden", "pressure on medical services"], ["nutritional labelling", "information on food packaging"], ["consumption", "the amount used or eaten"], ["competitive prices", "prices similar to or lower than others"]],
    mistakes: ["Writing about personal taste instead of public health.", "Offering solutions that do not match the problems.", "Using vague words such as “bad food” instead of precise terms."],
  },
  {
    slug: "minimum-driving-age",
    title: "Raising the minimum driving age",
    category: "Society",
    type: "Opinion (agree/disagree)",
    question: "Some people think that the minimum age for a driving licence should be raised to reduce road accidents. To what extent do you agree or disagree?",
    analysis: "Decide whether raising the age is an effective way to reduce accidents. You can partly agree if you explain which part you accept and which you reject, but keep the position consistent.",
    outline: [
      { heading: "Introduction", text: "Say that you partly agree: young drivers are riskier, but better training may work better than a higher age." },
      { heading: "Body 1: why age matters", text: "Statistics show young drivers have more accidents because of inexperience and risk-taking." },
      { heading: "Body 2: limits of the policy", text: "Some young people need a car for work or study; graduated licences and training are more flexible." },
      { heading: "Conclusion", text: "Support stricter rules for the young, combined with better education." },
    ],
    sample: [
      "Road accidents cause thousands of deaths every year, and young drivers are involved in a high proportion of them. Some people therefore argue that the minimum driving age should be increased. I partly agree with this view, although I believe that better training would be more effective than a simple age limit.",
      "It is true that younger drivers are more likely to cause accidents. They have less experience, overestimate their skills and are more likely to take risks, such as driving too fast or using a phone. Many insurance companies charge young drivers much more for this reason. Raising the minimum age by a year or two would give teenagers more time to mature and would probably reduce the number of serious accidents in the short term.",
      "However, a higher age limit is not a complete solution. Many young people in rural areas need a car to reach college or work, and a ban could limit their opportunities. Moreover, a person who turns eighteen is not automatically a safe driver. A better approach would be a graduated licence, which allows new drivers to drive only with an experienced adult at night, along with compulsory lessons on hazard awareness.",
      "This system would address the real cause of accidents, which is inexperience, rather than age alone.",
      "Technology could also help. Many insurance companies now offer devices that record how fast and how carefully a young person drives, and they reduce prices for safe drivers. This gives teenagers a financial reason to behave responsibly, and it provides parents with real information, which is more convincing than any warning.",
      "In conclusion, raising the minimum age could save lives, but I believe that stricter training and graduated licences would achieve better results without limiting young people unfairly."
    ],
    vocab: [["driving licence", "official permission to drive"], ["graduated licence", "a licence with limits for new drivers"], ["inexperience", "lack of practical knowledge"], ["hazard awareness", "noticing danger on the road"], ["mature", "become more adult in behaviour"], ["risk-taking", "doing dangerous things"], ["compulsory", "required by rule"]],
    mistakes: ["Giving personal driving stories instead of arguments.", "Saying “young people are always careless”.", "Forgetting to explain the position in the introduction."],
  },
  {
    slug: "free-museums",
    title: "Free entry to museums",
    category: "Government",
    type: "Opinion (agree/disagree)",
    question: "Some people believe that museums and art galleries should be free for everyone. Others think visitors should pay. Discuss both views and give your opinion.",
    analysis: "Discuss why free entry is valuable and why charging might be necessary, then state which view you support, ideally in the introduction and conclusion.",
    outline: [
      { heading: "Introduction", text: "Introduce the debate and say you support free entry, with exceptions for special exhibitions." },
      { heading: "Body 1: for free entry", text: "Access to culture and education for all; more visitors, especially students and low-income families." },
      { heading: "Body 2: for charging", text: "Museums need money for conservation and staff; ticket income can reduce pressure on public budgets." },
      { heading: "Conclusion", text: "A balanced solution is free general entry with paid special events." },
    ],
    sample: [
      "Museums preserve our cultural heritage, but who should pay for them is a matter of debate. Some argue that entry should be free, while others believe that visitors should pay. In my opinion, general admission should be free, with charges only for special exhibitions.",
      "Supporters of free entry point out that culture and education should be available to everyone, not only to those who can afford a ticket. When entry is free, families with low incomes and students can visit museums regularly, and children can learn about history and science in an enjoyable way. Evidence from several cities that have abolished fees shows a large increase in visitors, including many who had never entered a museum before.",
      "On the other hand, those who favour charging argue that museums are expensive to run. Staff, security, conservation and new exhibitions all require funds, and public money is limited. Ticket sales can provide a stable source of income and encourage museums to offer high-quality displays. Some people also believe that visitors value something more when they pay for it.",
      "However, these concerns can be addressed without charging everyone. Museums can raise money through gift shops, cafés, donations and paid special exhibitions, while basic access remains free.",
      "There is also a practical argument connected with tourism. Visitors who enter a free museum often spend money in nearby cafés, shops and hotels, which supports the local economy. Some cities calculate that this extra income is greater than the money they would collect from ticket sales, so free entry can actually pay for itself.",
      "In conclusion, charging for all visitors may help finances, but free general entry brings greater social and educational benefits, so I support a model in which core collections are free."
    ],
    vocab: [["cultural heritage", "traditions and objects from the past"], ["admission fee", "the price to enter"], ["conservation", "protecting objects from damage"], ["accessible", "easy for everyone to use"], ["special exhibition", "a temporary display"], ["public funding", "money from taxes"], ["donation", "a gift of money"]],
    mistakes: ["Listing both views without giving your own opinion.", "Treating all museums as the same.", "Not supporting claims with examples."],
  },
  {
    slug: "celebrity-influence-on-young-people",
    title: "Celebrity influence on young people",
    category: "Media",
    type: "Discussion + opinion",
    question: "Some people think that celebrities have a positive influence on young people, while others believe the influence is negative. Discuss both views and give your opinion.",
    analysis: "Explain how celebrities can inspire and how they can mislead young people, then say which effect is stronger in your view.",
    outline: [
      { heading: "Introduction", text: "Introduce the debate and say the influence can be both, but is mostly negative unless balanced by other role models." },
      { heading: "Body 1: positive", text: "Motivation, charity work, promoting education, health and sports." },
      { heading: "Body 2: negative", text: "Unrealistic beauty and wealth, materialism, bad behaviour copied by fans." },
      { heading: "Conclusion", text: "Celebrities can help, but parents and schools must balance their influence." },
    ],
    sample: [
      "Celebrities are followed by millions of young fans, so their behaviour has a great deal of influence. Some people see this influence as beneficial, while others consider it harmful. In my view, the effect can be positive, but at present the negative side is stronger.",
      "On the positive side, many famous people inspire young people to work hard and follow their dreams. A sports star who describes years of training can motivate teenagers to be disciplined, and celebrities who support charities or speak about education and mental health can draw attention to important causes. Their fame gives them a voice that ordinary people do not have.",
      "However, the negative effects are also significant. Social media shows celebrities in a carefully edited way, with perfect bodies, expensive clothes and glamorous holidays. Young people may compare themselves unfavourably and feel unhappy, or believe that success depends on appearance and wealth rather than effort. Some fans also copy harmful behaviour, such as extreme dieting or reckless spending, simply because their idol does it.",
      "Parents and schools therefore have an important role in helping teenagers think critically about what they see.",
      "Another point worth mentioning is the rise of social media influencers, who often appear ordinary and honest, so teenagers trust them completely. When these influencers promote products without explaining that they are paid, young viewers may spend money they do not have. Clear rules about advertising would reduce this risk without limiting freedom of expression.",
      "In conclusion, celebrities can inspire and support good causes, but their influence is often negative, so young people need guidance and a wider range of role models."
    ],
    vocab: [["role model", "a person others want to copy"], ["materialism", "valuing money and possessions too much"], ["unrealistic expectations", "hopes that cannot be achieved"], ["motivate", "give someone a reason to try"], ["edited image", "a picture changed to look perfect"], ["think critically", "judge information carefully"], ["raise awareness", "make people informed about an issue"]],
    mistakes: ["Naming real celebrities and criticising them personally.", "Giving only one view.", "Using “celebrities are always bad” type statements."],
  },
  {
    slug: "homework-for-children",
    title: "Homework for primary school children",
    category: "Education",
    type: "Opinion (agree/disagree)",
    question: "Some people think that primary school children should not be given homework. To what extent do you agree or disagree?",
    analysis: "Decide whether young children should have any homework. A balanced position (limited, short homework) is possible but must be clear.",
    outline: [
      { heading: "Introduction", text: "State that you largely agree: heavy homework harms young children, but small tasks can help." },
      { heading: "Body 1: why not", text: "Tiredness, less play and family time, stress and loss of interest in learning." },
      { heading: "Body 2: limited benefits", text: "Reading and short revision can build habits; but quality of lessons matters more." },
      { heading: "Conclusion", text: "Support minimal homework such as daily reading." },
    ],
    sample: [
      "Whether young children should do homework is a topic on which educators disagree. I largely agree that primary school pupils should not be given homework, although I think that some very light tasks, such as reading, can be useful.",
      "The main reason is that children aged six to eleven need time to rest and play after a full day at school. Play is not a waste of time; it develops creativity, social skills and physical health. When children spend several hours on exercises every evening, they become tired and stressed, and some begin to dislike school. In addition, homework reduces the time that families can spend together, which is important for emotional development.",
      "Some people claim that homework teaches discipline and helps children remember what they have learned. This may be true to a certain extent, but young children can develop good habits through other routines, such as tidying their own room or reading a short story before bed. Furthermore, if children need extra work to understand the lesson, the problem may lie in the teaching method rather than in a lack of homework.",
      "Parents are often also under pressure to help with assignments they do not understand, which can lead to arguments at home.",
      "Teachers can also improve the situation by making lessons more interactive, so that learning happens in the classroom instead of at the kitchen table. When children use practical activities, group work and short discussions, they remember the material better, and the need for extra exercises at home becomes much smaller.",
      "In conclusion, heavy homework brings more harm than benefit at primary level, so schools should limit it to a small amount of reading and encourage children to learn through play."
    ],
    vocab: [["primary school pupils", "children aged about 5 to 11"], ["emotional development", "growth of feelings and relationships"], ["revision", "reviewing what you learned"], ["discipline", "the ability to follow rules or routines"], ["to a certain extent", "partly"], ["assignment", "a piece of schoolwork"], ["stressed", "under mental pressure"]],
    mistakes: ["Writing about university students.", "Using “children hate homework” without reasons.", "Not mentioning the limited benefits for a balanced answer."],
  },
  {
    slug: "tourism-advantages-and-disadvantages",
    title: "Tourism: do the benefits outweigh the drawbacks?",
    category: "Globalization",
    type: "Advantages and disadvantages",
    question: "International tourism has become the world's largest industry. Do the advantages of this development outweigh the disadvantages?",
    analysis: "You must weigh economic and cultural benefits against environmental and social costs and give a clear judgement.",
    outline: [
      { heading: "Introduction", text: "State that the advantages are greater if tourism is managed well." },
      { heading: "Body 1: advantages", text: "Jobs and income, funding for heritage, cultural exchange." },
      { heading: "Body 2: disadvantages", text: "Pollution, overcrowding, rising prices; solutions like limits and eco-tourism." },
      { heading: "Conclusion", text: "Benefits outweigh costs with proper management." },
    ],
    sample: [
      "Millions of people travel abroad every year, making tourism one of the largest industries in the world. Although it creates some problems, I believe that its advantages outweigh its disadvantages, provided that it is carefully managed.",
      "The most obvious benefit is economic. Tourism creates jobs in hotels, restaurants, transport and souvenir shops, and it brings foreign money into the country. In poorer regions, it may be the main source of income. This money can also be used to restore historic buildings and protect nature reserves, which might otherwise be neglected. In addition, meeting visitors from other countries encourages understanding between cultures and makes local people proud of their heritage.",
      "On the other hand, tourism can cause serious damage. Large numbers of visitors may pollute beaches, wear down ancient monuments and put pressure on water and electricity supplies. Local residents sometimes suffer from higher prices and crowded streets. Moreover, jobs in tourism are often seasonal and badly paid.",
      "These risks can be reduced if authorities limit visitor numbers, charge fees for protected sites and promote eco-friendly tourism.",
      "Local participation is another key factor. When residents own small hotels and guesthouses, and when guides and craftspeople come from the area, the money stays in the community instead of leaving with international companies. Governments can support this by offering loans and training to local entrepreneurs who want to work in tourism.",
      "In conclusion, tourism brings valuable income, jobs and cultural exchange, and with sensible regulation its harmful effects can be controlled, so the benefits are greater overall."
    ],
    vocab: [["foreign currency", "money from other countries"], ["seasonal work", "work available only at some times"], ["nature reserve", "a protected natural area"], ["cultural exchange", "sharing customs and ideas"], ["overcrowding", "too many people in a place"], ["eco-friendly", "not harmful to the environment"], ["regulation", "official rules"]],
    mistakes: ["Describing holidays you have taken.", "Not weighing the two sides.", "Writing only about the economy."],
  },
  {
    slug: "immigration-benefits-and-problems",
    title: "Immigration: benefits and problems",
    category: "Society",
    type: "Advantages and disadvantages",
    question: "More and more people are moving to other countries to live and work. Do the advantages of immigration outweigh the disadvantages for the destination country?",
    analysis: "Weigh economic and cultural benefits against pressure on services and integration challenges, then judge.",
    outline: [
      { heading: "Introduction", text: "Say advantages are greater when immigration is well planned." },
      { heading: "Body 1: advantages", text: "Fills labour shortages, pays taxes, brings skills and diversity." },
      { heading: "Body 2: disadvantages", text: "Pressure on housing, schools and healthcare; tension if integration is poor; solutions." },
      { heading: "Conclusion", text: "Planned immigration with language and integration support benefits society." },
    ],
    sample: [
      "Global migration has increased in recent decades, and many countries now have large immigrant communities. Although immigration creates certain challenges, I believe that its benefits for the receiving country are greater, as long as it is properly managed.",
      "The most significant advantage is economic. Immigrants often fill jobs that local workers do not want or cannot do, in sectors such as healthcare, construction and agriculture. They also pay taxes, start new businesses and contribute skills and ideas. In countries with ageing populations, young immigrants help to support pensions and keep the economy growing. Culturally, they bring new food, music and traditions that make society more diverse and interesting.",
      "On the other hand, a rapid increase in population can put pressure on housing, schools and hospitals, especially in large cities. If newcomers do not learn the local language or feel excluded, communities may become divided and tension can grow.",
      "These problems are not inevitable. Governments can invest in housing and public services in advance, offer language courses and encourage immigrants to take part in local life.",
      "It is also important to remember that many immigrants come as students and later stay as highly skilled workers. These graduates have already been educated at the country's universities, so employing them gives the economy a quick return on its investment, and they often become strong links with other countries for trade and research.",
      "In conclusion, immigration brings economic and cultural advantages, and with careful planning and integration policies, the difficulties can be limited, so the advantages outweigh the disadvantages."
    ],
    vocab: [["labour shortage", "not enough workers"], ["ageing population", "a society with more older people"], ["integrate", "become part of a community"], ["diversity", "variety of people and cultures"], ["public services", "healthcare, schools and similar"], ["contribute to", "give something to"], ["tension", "feelings of conflict"]],
    mistakes: ["Making negative generalisations about groups of people.", "Ignoring solutions.", "Writing about your own country only without explaining."],
  },
  {
    slug: "who-should-recycle",
    title: "Recycling: responsibility of individuals or governments",
    category: "Environment",
    type: "Discussion + opinion",
    question: "Some people think that recycling is the responsibility of individuals, while others believe that governments should take the main responsibility. Discuss both views and give your opinion.",
    analysis: "Discuss the role of individuals and the role of governments, then state which is more important or how they work together.",
    outline: [
      { heading: "Introduction", text: "Both matter, but government systems make recycling work." },
      { heading: "Body 1: individuals", text: "Sorting waste at home, buying less packaging, setting an example." },
      { heading: "Body 2: governments", text: "Providing bins and collection, laws on packaging, penalties and education." },
      { heading: "Conclusion", text: "Government systems are the foundation; individuals make them effective." },
    ],
    sample: [
      "Recycling reduces waste and saves natural resources, but there is disagreement about who should be responsible for it. Some believe that individuals should lead, whereas others argue that governments must take charge. In my opinion, both have a role, but governments are more important.",
      "Those who favour individual responsibility point out that recycling begins at home. People decide what to throw away, whether to separate paper from plastic and whether to buy products with excessive packaging. If every household sorts its rubbish carefully, the amount of waste sent to landfill can fall dramatically. Individuals can also influence others by setting an example, especially in front of their children.",
      "However, people can only recycle if the system makes it possible. Governments are responsible for providing separate bins, regular collection and recycling plants. They can pass laws that force companies to reduce packaging and use recycled materials, and they can fine those who dump waste illegally. In several countries, a deposit scheme for bottles has increased recycling rates quickly, which shows what good policy can achieve.",
      "Public information campaigns also depend on government support, since they must reach everyone.",
      "Education should not be overlooked either. Children who learn about recycling at school frequently teach their parents, and many families begin to sort waste because of their children's enthusiasm. Therefore, government investment in school programmes can change habits across a whole generation, and the effect lasts long after the lessons have finished.",
      "In conclusion, individuals must make the daily effort, but without proper infrastructure and laws their efforts have limited effect, so I believe that governments should take the main responsibility."
    ],
    vocab: [["landfill", "a place where rubbish is buried"], ["excessive packaging", "too much wrapping"], ["deposit scheme", "money returned when bottles are recycled"], ["infrastructure", "basic systems like roads and bins"], ["sort rubbish", "separate waste by type"], ["set an example", "behave as a model for others"], ["penalty", "a punishment for breaking a rule"]],
    mistakes: ["Choosing only one side without explaining the other view.", "Using vague words such as “things” and “stuff”.", "Mixing up recycling with reducing waste."],
  },
  {
    slug: "social-media-age-limit",
    title: "An age limit for social media",
    category: "Technology",
    type: "Opinion (agree/disagree)",
    question: "Some people think that children under 16 should not be allowed to use social media. To what extent do you agree or disagree?",
    analysis: "Decide whether a ban is the right solution. You can agree with restrictions but suggest alternatives such as supervision, as long as the position is clear.",
    outline: [
      { heading: "Introduction", text: "State that you agree with limits for younger children, but a total ban is hard to enforce." },
      { heading: "Body 1: risks", text: "Cyberbullying, addiction, sleep loss, exposure to unsuitable content." },
      { heading: "Body 2: practical issues", text: "Children bypass rules; parental guidance and platform safety settings are more effective." },
      { heading: "Conclusion", text: "Support age limits plus education and supervision." },
    ],
    sample: [
      "Social media has become a central part of teenage life, but many parents and experts worry about its effects on younger users. I agree that children under 16 need protection, although I believe that a combination of limits and guidance would work better than a complete ban.",
      "There are strong reasons for concern. Young children may not understand how to protect their privacy, and they can be exposed to violent or inappropriate content. Cyberbullying can have serious effects on self-esteem, and constant notifications are addictive, leading to poor sleep and a lack of concentration at school. Because their brains are still developing, children are especially vulnerable to these pressures.",
      "However, a total ban would be difficult to enforce. Children can easily lie about their age or use a friend's account, and a strict rule might push them to use social media secretly, without any adult knowing. Moreover, social media can have some benefits, such as keeping in touch with friends or learning new skills.",
      "A more realistic approach is to set a minimum age for independent accounts, require platforms to verify age and offer child-safe settings, and teach children digital literacy at school and at home.",
      "Schools can also play a valuable role. Lessons on how to recognise false information, protect personal data and respond to online bullying give children practical tools that they can use for the rest of their lives. This kind of education is more lasting than a rule that children will try to avoid whenever they can.",
      "In conclusion, I agree that under-16s need restrictions, but supervision and education are more effective than banning social media entirely."
    ],
    vocab: [["cyberbullying", "bullying using digital devices"], ["inappropriate content", "material unsuitable for children"], ["addictive", "hard to stop using"], ["vulnerable", "easily harmed"], ["digital literacy", "ability to use technology safely"], ["verify age", "check how old someone is"], ["enforce", "make sure a rule is followed"]],
    mistakes: ["Describing social media only as bad.", "Not discussing whether the ban can work.", "Using “kids” in a formal essay; use “children”."],
  },
  {
    slug: "professional-athletes-salaries",
    title: "High salaries of professional athletes",
    category: "Work",
    type: "Opinion (agree/disagree)",
    question: "Professional athletes and entertainers are paid far more than doctors and teachers. Do you think this is fair? To what extent do you agree or disagree?",
    analysis: "Consider why athletes earn so much and whether this reflects the value of their work. State a clear position on fairness.",
    outline: [
      { heading: "Introduction", text: "Say that the pay gap is understandable in market terms but unfair in terms of social value." },
      { heading: "Body 1: why they earn more", text: "Global audiences, sponsorship, short careers, rare talent." },
      { heading: "Body 2: why it is unfair", text: "Essential workers contribute more to society; salaries reflect market, not importance." },
      { heading: "Conclusion", text: "Society should increase rewards and respect for essential professions." },
    ],
    sample: [
      "It is common for famous athletes and entertainers to earn millions, while nurses, doctors and teachers receive much smaller salaries. Although this situation can be explained by market forces, I largely agree that it is unfair.",
      "There are reasons why top performers earn so much. A single match or film is watched by millions around the world, so television companies and sponsors pay enormous amounts for the rights. Athletes also have short careers, usually ending before the age of forty, and only a tiny number of people have the talent to reach the highest level. Their income therefore reflects scarcity and global demand.",
      "Nevertheless, high pay in entertainment does not mean that these jobs contribute more to society. Doctors save lives, and teachers shape the future of every child, yet they often work long hours for modest pay. This imbalance can discourage talented young people from entering these professions, causing shortages that harm everyone. A fair system should recognise the real value of work, not only its popularity.",
      "Governments could address the gap by increasing salaries in essential public services and by taxing very high incomes more heavily.",
      "It should also be noted that most athletes and entertainers do not earn huge salaries. For every star, there are thousands of players and performers who earn little and have no security after their careers end. This shows that large rewards are concentrated among a few people, which makes the contrast with essential workers even more striking.",
      "In conclusion, the market explains why entertainers earn more, but it does not make the situation fair, and I believe that society should reward essential professions more generously."
    ],
    vocab: [["sponsorship", "money from companies for support"], ["market forces", "supply and demand"], ["scarcity", "being rare or in short supply"], ["essential services", "services society cannot do without"], ["modest pay", "a fairly low salary"], ["imbalance", "an unequal situation"], ["recognise the value of", "understand the importance of"]],
    mistakes: ["Saying athletes “do nothing” or insulting them.", "Not explaining why they are paid so much.", "Focusing only on one country."],
  },
  {
    slug: "shorter-working-week",
    title: "A four-day working week",
    category: "Work",
    type: "Advantages and disadvantages",
    question: "Some companies are introducing a four-day working week. Do the advantages of this change outweigh the disadvantages?",
    analysis: "Weigh well-being and productivity gains against costs such as customer service and scheduling, then give a judgement.",
    outline: [
      { heading: "Introduction", text: "Say the advantages outweigh disadvantages if the change is planned." },
      { heading: "Body 1: advantages", text: "Better work-life balance, lower stress, higher productivity, lower costs for staff." },
      { heading: "Body 2: disadvantages", text: "Longer days, difficult for some sectors, customer coverage; solutions like shifts." },
      { heading: "Conclusion", text: "A flexible four-day week benefits most workplaces." },
    ],
    sample: [
      "A growing number of companies are testing a four-day working week. Although this change creates some practical challenges, I believe that its advantages outweigh its disadvantages.",
      "The biggest advantage is that employees have more time for rest, family and hobbies, which improves their well-being. Workers who feel less stressed tend to take fewer sick days and make fewer mistakes. Several trials have shown that productivity does not fall, because people use their time more efficiently when they know they have a long weekend ahead. Employers may also save money on office costs, and staff save on commuting.",
      "However, there are drawbacks. In some sectors, such as hospitals, shops and public transport, services must be available every day, so a shorter week is difficult to organise. In other cases, employees may have to work longer hours on the four days to complete the same tasks, which could be tiring. Customers might also find it harder to reach companies during the day off.",
      "These problems can be reduced by using shifts, so that different groups of employees take different days off, and by introducing the change gradually.",
      "Employees themselves would benefit in other ways, too. With an extra free day each week, they can attend medical appointments, study part-time or take care of relatives without using their annual leave. This flexibility makes jobs more attractive, which helps companies to keep their best workers and reduces the cost of hiring and training replacements.",
      "In conclusion, a four-day week offers real benefits for health, productivity and happiness, and with flexible planning, its disadvantages can be managed."
    ],
    vocab: [["work-life balance", "a healthy balance of work and private life"], ["productivity", "how much work is done"], ["well-being", "health and happiness"], ["commute", "travel regularly to work"], ["shift system", "workers take turns at different times"], ["trial", "a test of something new"], ["sick days", "days off because of illness"]],
    mistakes: ["Writing about holidays instead of working hours.", "Not mentioning how disadvantages can be solved.", "Using “weekend” and “day off” interchangeably."],
  },
  {
    slug: "disappearing-languages",
    title: "Languages disappearing around the world",
    category: "Globalization",
    type: "Problem and solution",
    question: "Many languages are disappearing as fewer people speak them. What problems does this cause and what can be done to protect them?",
    analysis: "Explain the cultural and practical problems of language loss and suggest realistic protection measures.",
    outline: [
      { heading: "Introduction", text: "Say language loss damages culture and can be reduced." },
      { heading: "Body 1: problems", text: "Loss of identity, traditional knowledge, literature; weaker ties between generations." },
      { heading: "Body 2: solutions", text: "Teach local languages in schools, support media and technology, document elders' speech." },
      { heading: "Conclusion", text: "Action by governments and communities can preserve languages." },
    ],
    sample: [
      "Linguists estimate that thousands of languages may disappear this century as younger generations switch to dominant languages such as English or Chinese. This development causes serious problems, but there are practical ways to slow it down.",
      "When a language dies, a unique part of human culture disappears with it. Many languages carry traditional knowledge about plants, medicine, local history and ways of seeing the world, and this information is rarely translated. Language is also a central part of identity, so speakers who abandon it may feel disconnected from their heritage. In families, grandparents and grandchildren may no longer be able to communicate fully, weakening family ties.",
      "Several measures could help. Schools in minority regions should teach the local language alongside the national one, so that children grow up as bilingual speakers. Governments can fund radio, television and online content in minority languages, and technology companies can add them to translation tools and keyboards. Finally, researchers should record elderly speakers and create dictionaries and recordings, which can be used by future generations.",
      "Such programmes work best when communities are directly involved and see the language as useful in daily life, not only as a tradition.",
      "Technology provides new opportunities as well. Smartphone apps, online dictionaries and social media groups allow young people to use minority languages in modern contexts, such as messaging and music. When a language is seen as part of everyday digital life rather than only a tradition, young speakers are more likely to continue using it.",
      "In conclusion, the loss of languages weakens cultural diversity, but with education, media support and careful documentation, many of them can be preserved."
    ],
    vocab: [["minority language", "a language spoken by few people"], ["cultural diversity", "a variety of cultures"], ["traditional knowledge", "information passed down in a community"], ["bilingual", "able to speak two languages"], ["document a language", "record it in writing or audio"], ["heritage", "history and traditions passed down"], ["abandon", "stop using"]],
    mistakes: ["Using “dead languages” and “disappearing languages” as the same thing.", "Proposing solutions without linking them to problems.", "Writing only about English."],
  },
  {
    slug: "taking-a-gap-year",
    title: "Taking a gap year before university",
    category: "Education",
    type: "Advantages and disadvantages",
    question: "More and more students take a year off between school and university to travel or work. Do the advantages of this outweigh the disadvantages?",
    analysis: "Weigh personal growth and experience against risks such as losing study habits and costs. Give a clear judgement.",
    outline: [
      { heading: "Introduction", text: "Say the advantages are greater if the year is used well." },
      { heading: "Body 1: advantages", text: "Maturity, practical experience, clearer course choice, motivation." },
      { heading: "Body 2: disadvantages", text: "Loss of study rhythm, cost, delay of career; can be reduced by planning." },
      { heading: "Conclusion", text: "A planned gap year helps most students." },
    ],
    sample: [
      "Increasingly, school leavers are choosing to delay university in order to travel, volunteer or work. Although this choice carries some risks, I believe that a well-planned gap year is usually beneficial.",
      "The main advantage is personal development. After years of studying, students gain independence and confidence by working or living abroad. They learn practical skills such as managing money, solving problems and working with different people. A year of experience also helps students to understand what they really want to study, so they are less likely to drop out of a course they chose without thinking. Many universities report that returning students are more focused and motivated.",
      "On the other hand, a gap year has drawbacks. Some students find it hard to return to a routine of academic study after a long break. Travelling can be expensive, and families may not be able to afford it. A delay also means that students start their careers a year later than their classmates.",
      "However, these risks are limited if the year has a clear purpose, such as paid work, a volunteering project or a course related to the future degree.",
      "Employers frequently value the skills that students develop in this period. A year of volunteering or working abroad shows initiative, adaptability and the ability to communicate with different people, all of which stand out on a CV. For many graduates, these experiences make the difference when they apply for their first job.",
      "In conclusion, a gap year can bring maturity, experience and motivation, and its disadvantages can be reduced with planning, so the benefits are greater overall."
    ],
    vocab: [["gap year", "a year off between school and university"], ["independence", "being able to look after yourself"], ["drop out", "leave a course before finishing"], ["volunteering", "working without payment to help"], ["maturity", "adult-like behaviour"], ["academic routine", "regular study habits"], ["well-planned", "organised carefully in advance"]],
    mistakes: ["Describing your own plans instead of arguments.", "Not addressing the cost.", "Writing as if every student travels abroad."],
  },
  {
    slug: "advertising-aimed-at-children",
    title: "Advertising aimed at children",
    category: "Media",
    type: "Opinion (agree/disagree)",
    question: "Some people believe that advertising aimed at children should be banned. To what extent do you agree or disagree?",
    analysis: "Decide how far advertising to children should be restricted. You may support a ban on certain types of ads (for example, unhealthy food) but you must explain.",
    outline: [
      { heading: "Introduction", text: "Say you agree with strong restrictions because children are especially vulnerable." },
      { heading: "Body 1: why restrict", text: "Children cannot judge persuasion; unhealthy food and pester power; materialism." },
      { heading: "Body 2: limits of a ban", text: "Advertising supports children's media; parents also have responsibility." },
      { heading: "Conclusion", text: "Support a ban on harmful ads and clear regulation for the rest." },
    ],
    sample: [
      "Children are exposed to thousands of advertisements, on television, online and even at school. Many people believe such advertising should be banned. I largely agree, at least for products that are harmful, because children cannot judge persuasion in the way adults can.",
      "Young children usually believe what they see and do not understand that the aim of an advertisement is to sell something. Companies take advantage of this by using cartoon characters and bright colours to promote sweets, fast food and expensive toys. As a result, children pressure their parents to buy these products, which can damage family budgets and encourage unhealthy eating. Constant advertising may also teach children that happiness depends on owning things.",
      "Nevertheless, a complete ban may be difficult to apply and could have side effects. Many children's television channels and websites are paid for by advertising, so they might disappear without it. Parents should also share responsibility by choosing what their children watch and by talking to them about advertisements.",
      "A sensible compromise would be to forbid advertising of unhealthy food and to set strict rules about how products are presented to children.",
      "Several countries already show that stricter rules are possible. Some have forbidden advertisements for sugary products during children's programmes, and others have limited the use of cartoon characters to promote unhealthy food. Reports suggest that such rules reduce children's requests for these products, which shows that regulation can have a real effect.",
      "In conclusion, children need protection from manipulative marketing, so I agree with banning harmful advertising and strictly controlling the rest."
    ],
    vocab: [["persuasion", "convincing someone to do something"], ["vulnerable", "easily harmed"], ["pester power", "children's influence on parents' purchases"], ["marketing", "promoting products"], ["manipulative", "controlling in an unfair way"], ["regulation", "official rules"], ["materialistic", "focused on owning things"]],
    mistakes: ["Suggesting that all advertising is dishonest.", "Ignoring the role of parents.", "Not distinguishing harmful products from others."],
  },
  {
    slug: "traffic-congestion-in-cities",
    title: "Traffic congestion in big cities",
    category: "Society",
    type: "Problem and solution",
    question: "Traffic congestion is a serious problem in many big cities. What are the causes and what solutions can be proposed?",
    analysis: "Two tasks: causes (not only effects) and solutions. Keep causes and solutions logically connected.",
    outline: [
      { heading: "Introduction", text: "Paraphrase and say the main causes are too many private cars and weak public transport." },
      { heading: "Body 1: causes", text: "Population growth, cheap cars, poor public transport, poor planning." },
      { heading: "Body 2: solutions", text: "Improve public transport, congestion charges, cycling lanes, flexible working hours." },
      { heading: "Conclusion", text: "Mix of better alternatives and incentives." },
    ],
    sample: [
      "Traffic jams waste time, increase pollution and cause stress in many large cities. This essay will examine the main causes of congestion and propose several practical solutions.",
      "The first cause is the rapid growth of urban populations, which means that more people need to travel at the same time, especially during rush hour. Secondly, many cities have inadequate public transport, with crowded buses and few metro lines, so people prefer to drive. Cheap loans for cars and a lack of parking control also encourage car ownership. Finally, poor planning, such as locating offices and schools in the centre, forces everyone to travel in the same direction.",
      "Several measures can help. Cities should invest in fast, frequent and affordable public transport, because people will leave their cars at home if the alternatives are reliable. A congestion charge for entering the centre, as used in London and Singapore, can reduce traffic and raise money for improvements. Building safe cycle lanes and encouraging employers to offer flexible hours or remote work would also spread demand over the day.",
      "Together, these actions address both the number of cars and the timing of journeys.",
      "The role of technology should also be mentioned. Real-time traffic apps help drivers avoid crowded roads, and smart traffic lights can adjust to the flow of vehicles, which shortens waiting times. Although these tools cannot replace public transport, they make existing roads work more efficiently and reduce the time wasted in queues.",
      "In conclusion, congestion results from population growth, weak public transport and poor planning, and it can be reduced by better alternatives, charges for drivers and flexible working patterns."
    ],
    vocab: [["congestion", "too much traffic"], ["rush hour", "busy travel time"], ["congestion charge", "a fee to drive in a busy area"], ["inadequate", "not good enough"], ["car ownership", "having a car"], ["flexible hours", "working times you can adjust"], ["urban planning", "designing cities"]],
    mistakes: ["Describing the effects of traffic only.", "Offering the same solution twice in different words.", "Ignoring the causes."],
  },
  {
    slug: "care-for-elderly-people",
    title: "Who should care for elderly people?",
    category: "Society",
    type: "Discussion + opinion",
    question: "Some people think that family members should look after elderly relatives. Others believe the government should provide care. Discuss both views and give your opinion.",
    analysis: "Discuss family care and state care fairly and say which is more suitable or how they may work together.",
    outline: [
      { heading: "Introduction", text: "Say that families give emotional care, but the state must provide support." },
      { heading: "Body 1: family care", text: "Emotional bonds, familiar environment, cost saving, moral duty." },
      { heading: "Body 2: state care", text: "Professional medical care, relief for working families, ageing societies." },
      { heading: "Conclusion", text: "Shared responsibility is best." },
    ],
    sample: [
      "As life expectancy increases, societies must decide who should look after elderly people. Some believe that this is a family duty, while others think the government should be responsible. In my opinion, both should share the responsibility.",
      "Supporters of family care argue that children owe a debt to their parents, who raised them. Elderly people usually feel happier in a familiar home with relatives who love them, and emotional support is difficult for institutions to provide. Family care also reduces the cost for governments and strengthens bonds between generations, which is a strong tradition in many cultures.",
      "However, caring for an older person can be a heavy burden. Many adults work full-time and raise children, so they cannot provide the constant attention that someone with a serious illness needs. Professional nurses and specialised facilities offer better medical treatment and 24-hour supervision. Governments therefore have a duty to provide care homes, healthcare and financial support, especially for people without relatives.",
      "The best solution is cooperation: the state could provide medical services, home visits and allowances, while families supply company and emotional care.",
      "Communities can also contribute by organising volunteer visits, clubs and day centres for elderly people. These activities reduce loneliness, which is a major cause of poor health in older age, and they give relatives some time to rest. With such support, families can continue caring at home for longer, which is what most older people want.",
      "In conclusion, relatives are best able to offer love and companionship, but professional care requires public funding, so both families and governments should take part."
    ],
    vocab: [["life expectancy", "how long people usually live"], ["care home", "a residence with care for older people"], ["emotional support", "help with feelings"], ["institution", "an organisation such as a hospital"], ["burden", "a heavy responsibility"], ["allowance", "regular financial help"], ["supervision", "watching over someone"]],
    mistakes: ["Presenting only your own culture.", "Forgetting to explain the role of the state.", "Using “old people” repeatedly; vary with “elderly people” and “older adults”."],
  },
  {
    slug: "art-in-the-school-curriculum",
    title: "The importance of art subjects in schools",
    category: "Education",
    type: "Opinion (agree/disagree)",
    question: "Some people think that schools should spend less time on art and music and more time on subjects like science and maths. To what extent do you agree or disagree?",
    analysis: "Decide whether art and music are less important than science and maths. Defend your position with the benefits of each.",
    outline: [
      { heading: "Introduction", text: "Say you disagree: art and music develop skills that other subjects do not." },
      { heading: "Body 1: benefits of arts", text: "Creativity, emotional expression, teamwork, and links to concentration." },
      { heading: "Body 2: balance", text: "Science and maths are essential, but a rounded education includes both." },
      { heading: "Conclusion", text: "Keep arts as a core part of the curriculum." },
    ],
    sample: [
      "With increasing competition for science and technology jobs, some argue that schools should reduce time for art and music. I disagree with this view, because creative subjects bring benefits that are important for every student.",
      "Art and music develop creativity, which is a valuable skill in any career, including science and engineering. Playing an instrument or painting requires patience and concentration, and group activities such as a school choir teach teamwork and confidence. These subjects also give children a way to express emotions, which supports their mental health. For students who find academic subjects difficult, success in art or music can raise self-esteem and motivation to study.",
      "It is true that science and maths are essential in modern economies, and schools should give them enough time. However, the two areas are not in competition. Studies often link musical training to better memory and attention, and design and visual thinking are important in fields such as architecture and medicine. A student who only studies calculations may become a skilled technician, but not necessarily an innovative thinker.",
      "A school day has enough room for both, if the time is planned carefully.",
      "Finally, many employers say that creativity and communication are the qualities that they struggle to find in graduates. Subjects such as drama and art encourage students to present ideas, work in groups and think in original ways. These skills are difficult to measure in an exam, but they are exactly what modern workplaces demand.",
      "In conclusion, art and music should remain a core part of education because they develop creativity, teamwork and well-being, and these qualities help students succeed in all areas."
    ],
    vocab: [["curriculum", "subjects taught in a school"], ["creativity", "the ability to produce new ideas"], ["self-esteem", "confidence in your own value"], ["well-rounded education", "learning in many areas"], ["emotional expression", "showing feelings"], ["innovative", "introducing new ideas"], ["core subject", "a main compulsory subject"]],
    mistakes: ["Saying maths and science are “useless”.", "Not giving examples of skills developed by arts.", "Writing about a single school you know."],
  },
  {
    slug: "plastic-waste-problem",
    title: "Plastic waste in the oceans",
    category: "Environment",
    type: "Problem and solution",
    question: "Huge amounts of plastic waste end up in the oceans. What problems does this cause and what can be done to reduce it?",
    analysis: "Explain environmental and human problems caused by plastic pollution, and suggest solutions at government, company and individual level.",
    outline: [
      { heading: "Introduction", text: "Say plastic pollution threatens marine life and humans and can be reduced by joint action." },
      { heading: "Body 1: problems", text: "Harm to animals, microplastics in food chain, damage to tourism and fishing." },
      { heading: "Body 2: solutions", text: "Bans on single-use plastic, better waste systems, recycling, individual choices." },
      { heading: "Conclusion", text: "Cooperation reduces the problem." },
    ],
    sample: [
      "Every year, millions of tonnes of plastic enter the world's oceans, creating a growing environmental crisis. This essay will discuss the main problems caused by plastic waste and suggest measures to reduce it.",
      "The most visible problem is the harm to marine life. Turtles, birds and fish often swallow plastic or become trapped in it, and many die as a result. Over time, plastic breaks into tiny pieces called microplastics, which enter the food chain and eventually reach humans through seafood. Plastic pollution also damages beaches, reducing income from tourism, and clogs the nets and engines of fishing boats.",
      "There are several solutions. Governments can ban or tax single-use plastics such as bags and straws and improve waste collection, especially in countries where rubbish is dumped near rivers. Companies should design packaging that is easier to recycle and use recycled material. Individuals can make a difference by carrying reusable bottles and bags and by taking part in beach clean-ups.",
      "International agreements are also necessary, since waste travels across borders in ocean currents.",
      "Innovation offers further hope. Researchers are developing packaging made from seaweed and starch, which breaks down naturally, and some companies already collect plastic from rivers before it reaches the sea. When governments give financial support to such projects, new solutions can move quickly from laboratories to everyday use, which is essential given the scale of the problem.",
      "In conclusion, plastic pollution harms animals, people and economies, but through stricter laws, better packaging and responsible behaviour, the amount of waste entering the oceans can be reduced."
    ],
    vocab: [["marine life", "animals and plants in the sea"], ["microplastics", "tiny pieces of plastic"], ["single-use plastic", "plastic used once and thrown away"], ["food chain", "the order in which living things eat each other"], ["waste collection", "taking rubbish away"], ["reusable", "able to be used again"], ["clean-up", "an event to remove rubbish"]],
    mistakes: ["Writing about only one type of solution.", "Describing the ocean in poetic language instead of problems.", "Using “nature” and “environment” without detail."],
  },
  {
    slug: "university-or-work-after-school",
    title: "University or work after school",
    category: "Education",
    type: "Discussion + opinion",
    question: "Some people believe that students should go to university immediately after school. Others think they should start working first. Discuss both views and give your opinion.",
    analysis: "Discuss both paths fairly and say which you find more beneficial, or when each is suitable.",
    outline: [
      { heading: "Introduction", text: "Say both have merit; going to university suits most when there is a clear goal." },
      { heading: "Body 1: university first", text: "Qualifications, career progress, study habits still fresh, networking." },
      { heading: "Body 2: work first", text: "Practical experience, clearer goals, financial independence, less debt." },
      { heading: "Conclusion", text: "Personal circumstances decide; a clear plan matters most." },
    ],
    sample: [
      "After leaving school, young people face an important decision: to continue directly to university or to start working. Both options have advantages, but I believe that going to university is better for most students who already know what they want to study.",
      "Those who favour going straight to university argue that study habits are strongest right after school. Students who delay may lose their academic rhythm. A degree also opens the door to higher-paid and more specialised jobs, and students start building a network of friends and contacts early. Finishing education earlier means a longer career and more years of higher income.",
      "On the other hand, some people prefer work first. A job gives practical experience and a sense of how the real world functions, so students may make a more informed choice about their degree. It also provides money, which reduces the need for loans and makes young people more independent. For some, the workplace can show that a different career path suits them better than a university course.",
      "However, these benefits can also be gained through part-time jobs, internships and holiday work during university.",
      "Cultural expectations also matter. In some countries, families expect young people to enter university immediately, while in others, working for a few years is considered normal and respected. Because attitudes differ, there is no single correct path, and the best choice depends on the student's motivation, finances and the support available at home.",
      "In conclusion, working first can be valuable for students without a clear plan, but I believe that direct entry to university is the better route for most, as it combines study with the chance to gain experience later."
    ],
    vocab: [["qualification", "an official proof of education"], ["career path", "the route of a person's working life"], ["internship", "short-term work experience"], ["financial independence", "not needing money from others"], ["student loan", "borrowed money for study"], ["network", "a group of useful contacts"], ["informed decision", "a choice based on knowledge"]],
    mistakes: ["Describing only your own choice.", "Ignoring the position of the “other” side.", "Not giving reasons for the final opinion."],
  },
  {
    slug: "trust-in-news-media",
    title: "Trust in the news media",
    category: "Media",
    type: "Opinion (agree/disagree)",
    question: "Some people say that we cannot trust the news media because it is controlled by powerful organisations. To what extent do you agree or disagree?",
    analysis: "Decide how much the media can be trusted. Avoid absolute statements: consider independent journalism and the effect of ownership.",
    outline: [
      { heading: "Introduction", text: "Say you partly agree: some news is influenced by owners, but reliable sources exist." },
      { heading: "Body 1: why distrust", text: "Ownership, advertising, political bias, sensational headlines." },
      { heading: "Body 2: why trust remains possible", text: "Independent outlets, fact-checking, competition and readers' ability to compare." },
      { heading: "Conclusion", text: "Be critical, not cynical." },
    ],
    sample: [
      "News shapes our understanding of the world, but many people doubt whether it is honest. I partly agree that the media cannot always be trusted, because owners and advertisers can influence it, although reliable sources do exist.",
      "There are good reasons for caution. Many large media companies belong to wealthy individuals or groups with political and business interests, and they may prefer stories that support those interests. Outlets also depend on advertising and clicks, which encourages sensational headlines rather than careful reporting. In some countries, the government controls television and newspapers, so alternative views rarely appear.",
      "However, it would be wrong to say that all news is untrustworthy. Many journalists work for independent newspapers or public broadcasters that follow strict standards, and they correct their mistakes publicly. Competition between outlets and fact-checking websites also make it harder to spread falsehoods unnoticed. Readers can compare several sources and look for evidence, such as official data or original documents.",
      "Media education in schools would help people to question sources and recognise bias without becoming cynical.",
      "Social media has complicated the situation further. News now spreads through shares and recommendations, and algorithms show people stories that match their existing opinions. This can create a narrow view of events, so even honest reporting may reach readers in a distorted way, which makes it more necessary than ever to seek different sources.",
      "In conclusion, the media is sometimes influenced by powerful interests, but trustworthy reporting is still available, so people should read critically instead of rejecting all news."
    ],
    vocab: [["bias", "unfair preference for one side"], ["sensational", "designed to shock or excite"], ["independent outlet", "a media organisation free from control"], ["fact-checking", "verifying that information is true"], ["public broadcaster", "a media company funded by the state or public"], ["cynical", "believing that people are only selfish"], ["media literacy", "ability to evaluate media"]],
    mistakes: ["Saying all journalists lie.", "Not giving reasons for or against trust.", "Confusing “media” with “social media” only."],
  },
  {
    slug: "sports-for-health-or-competition",
    title: "School sports: health or competition?",
    category: "Education",
    type: "Discussion + opinion",
    question: "Some people think that school sports should focus on competition and winning. Others believe sport at school should be for health and enjoyment. Discuss both views and give your opinion.",
    analysis: "Discuss the benefits of competitive sport and of non-competitive sport and give a clear opinion on which approach should dominate.",
    outline: [
      { heading: "Introduction", text: "Say that health and enjoyment should come first, with some competition." },
      { heading: "Body 1: competition", text: "Motivation, teamwork, resilience and discipline." },
      { heading: "Body 2: health and enjoyment", text: "Inclusion of all pupils, lifelong habits, avoiding pressure and injuries." },
      { heading: "Conclusion", text: "Balance with emphasis on participation." },
    ],
    sample: [
      "Physical education is part of almost every school's programme, but there is disagreement about its purpose. Some people believe that sport should focus on competition, whereas others stress health and enjoyment. In my opinion, the main goal should be health and participation, with competition as an optional extra.",
      "Supporters of competitive sport argue that it motivates students to improve and teaches important life skills. Pupils learn teamwork, discipline and how to cope with both winning and losing. School teams can also create a sense of pride and belonging, and they sometimes uncover talented athletes who might later represent their country.",
      "However, focusing on winning can exclude many children. Those who are less athletic may feel embarrassed and lose interest in exercise, which is a serious problem at a time when childhood obesity is increasing. A programme based on health and enjoyment, with a wide variety of activities such as dance, swimming and cycling, encourages every pupil to be active and helps them build habits that last a lifetime. It also reduces the risk of injuries caused by excessive pressure to win.",
      "Competition can still exist for those who want it, through voluntary school teams and friendly tournaments.",
      "Teachers can also adapt activities to different abilities. For example, a running lesson can reward personal improvement instead of the fastest time, and team games can be organised with mixed groups so that every child contributes. Such approaches keep the positive side of competition while protecting pupils who are less confident in their physical abilities.",
      "In conclusion, competitive sport has some benefits, but school sport should mainly promote health and enjoyment for all, with competition as an additional choice."
    ],
    vocab: [["physical education", "school sport lessons"], ["participation", "taking part"], ["resilience", "ability to recover from difficulty"], ["inclusive", "including everyone"], ["lifelong habit", "a habit kept through life"], ["tournament", "a series of competitions"], ["childhood obesity", "being very overweight as a child"]],
    mistakes: ["Describing professional sports only.", "Not explaining the risks of too much competition.", "Forgetting to give your opinion."],
  },
  {
    slug: "children-and-screen-time",
    title: "Children and screen time",
    category: "Technology",
    type: "Two-part question",
    question: "Children today spend a lot of time looking at screens. What are the reasons for this and what effects does it have on them?",
    analysis: "Two questions: reasons and effects. Write one body paragraph for reasons and another for effects, using specific points.",
    outline: [
      { heading: "Introduction", text: "Paraphrase and say reasons are availability, busy parents and entertainment, with mixed effects." },
      { heading: "Body 1: reasons", text: "Easy access to devices, busy parents, attractive content, fewer outdoor spaces." },
      { heading: "Body 2: effects", text: "Less exercise and sleep, shorter attention span, but some educational benefits." },
      { heading: "Conclusion", text: "Balanced, supervised use is best." },
    ],
    sample: [
      "It is common to see young children watching videos or playing games on phones and tablets. This essay will explain why they spend so much time on screens and consider the effects of this habit.",
      "There are several reasons for the trend. Devices are now cheap and available in almost every home, and many parents give a tablet to their children to keep them quiet while they work or cook. Apps and videos are designed to be attractive and addictive, with bright colours and constant rewards. In addition, in crowded cities, safe places for children to play outdoors are limited, so screens become the easiest form of entertainment.",
      "The effects can be both negative and positive. Children who spend many hours online usually exercise less, which contributes to obesity, and they may sleep poorly if they use devices at night. Their attention span can become shorter, and they may have fewer face-to-face interactions, which are important for developing social skills. On the other hand, educational apps and programmes can help children learn languages, numbers and creative skills when used with supervision.",
      "The key factor is the amount of time and the type of content.",
      "Cultural and economic factors play a role as well. In families where both parents work long hours, grandparents or nannies may use devices to keep children occupied, and expensive after-school activities are not available to everyone. Therefore, solutions should include affordable clubs and play areas so that screens are not the only option.",
      "In conclusion, children spend time on screens because of easy access, parents' busy lives and attractive content, and while heavy use is harmful, limited and supervised use can be beneficial."
    ],
    vocab: [["screen time", "time spent using screens"], ["attention span", "how long someone can focus"], ["addictive", "hard to stop using"], ["face-to-face interaction", "communication in person"], ["supervision", "adult watching over"], ["sedentary lifestyle", "a lifestyle with little movement"], ["educational app", "an app designed to teach"]],
    mistakes: ["Writing only about effects or only about reasons.", "Using only negative examples.", "Writing about teenagers when the question says children."],
  },
  {
    slug: "science-funding-or-arts",
    title: "Funding science or the arts",
    category: "Government",
    type: "Discussion + opinion",
    question: "Some people think that governments should spend more on scientific research, while others believe they should support the arts. Discuss both views and give your opinion.",
    analysis: "Present arguments for funding science and for funding the arts and state which should have priority or whether both deserve support.",
    outline: [
      { heading: "Introduction", text: "Say that science should have priority, but the arts deserve reasonable support." },
      { heading: "Body 1: science", text: "Medical discoveries, technology, economic growth, solving global problems." },
      { heading: "Body 2: arts", text: "Culture, identity, well-being, tourism and creative industries." },
      { heading: "Conclusion", text: "Prioritise science, maintain arts funding." },
    ],
    sample: [
      "Government budgets are limited, so choices have to be made about what to support. Some people believe that research in science deserves more funding, while others favour the arts. I think science should receive priority, although the arts also deserve fair support.",
      "Scientific research has produced the technologies that improve our daily lives, from vaccines and clean water systems to computers and renewable energy. Investment in research can lead to medical breakthroughs and new industries, creating jobs and economic growth. Moreover, many global challenges, such as climate change and pandemics, can only be solved with scientific knowledge, which makes it a matter of public safety.",
      "On the other hand, the arts are essential for a healthy society. Museums, theatres and music give people a shared identity and a way to express emotions. Cultural activities also attract tourists and support creative industries that employ many people. For some individuals, art is the main source of meaning and well-being.",
      "However, the arts can attract funding from private sponsors, ticket sales and donations more easily than basic research, which rarely produces immediate profit.",
      "The two areas are also more connected than they appear. Designers use art to make scientific discoveries understandable, and musicians and engineers work together to create new instruments and sound technology. When both are supported, ideas can pass between them, and the combination often leads to innovations that neither field would produce alone.",
      "In conclusion, both science and the arts enrich society, but because research addresses urgent problems and is difficult to fund privately, I believe the government should prioritise it while still supporting culture."
    ],
    vocab: [["scientific research", "systematic study to find new facts"], ["breakthrough", "an important discovery"], ["public safety", "protection of people from harm"], ["creative industries", "businesses based on art and design"], ["private sponsor", "a company or person funding for promotion"], ["cultural identity", "a shared sense of culture"], ["priority", "something treated as most important"]],
    mistakes: ["Treating science and arts as completely opposite.", "Not giving your own priority.", "Using vague claims such as “science is more useful” without examples."],
  },
];
