import type { Part1Topic } from './types.js';

export const PART3: Part1Topic[] = [
  {
    slug: "education",
    title: "Education",
    intro: "Part 3 education questions ask for opinions and comparisons. Give a view, explain why and add an example or a limitation.",
    qa: [
      { q: "What makes a good teacher?", a: "I think patience and the ability to explain things clearly matter most. A good teacher also motivates students, because someone who is excited about the subject often makes learning enjoyable even when the material is difficult." },
      { q: "Should students be allowed to choose all of their subjects?", a: "Partly. Choice increases motivation, but some basic subjects such as maths and languages are essential for everyone. A balance, with core subjects and a few electives, seems fair to me." },
      { q: "Is it better to study at home or at school?", a: "At school, for most children, because they learn to cooperate and communicate with others. Studying at home can be flexible, but it can also be lonely and lacks the daily structure that school provides." },
      { q: "Do you think exams are a good way to measure ability?", a: "They are useful because they are fair and easy to compare, but they do not show creativity or teamwork. A combination of exams and projects would give a fuller picture of a student." },
      { q: "How will education change in the future?", a: "I expect more online learning and personalised lessons that adapt to each student. However, teachers will remain important because technology cannot replace human encouragement and guidance." },
    ],
    vocab: [["motivate", "give someone a reason to try"], ["core subjects", "main compulsory subjects"], ["personalised learning", "lessons adapted to one student"], ["assessment", "a way of measuring ability"], ["curriculum", "the subjects taught in a school"], ["cooperate", "work together"], ["lifelong learning", "learning throughout life"]],
    tips: ["Start with a clear view: “I think…”, “In my opinion…”.", "Add a limitation to show balance: “However…”.", "Use future forms for predictions: “I expect…”, “will probably…”."],
  },
  {
    slug: "technology",
    title: "Technology and Society",
    intro: "Technology questions often ask about change. Compare past and present and think about advantages and risks.",
    qa: [
      { q: "How has technology changed the way people communicate?", a: "People can now contact each other instantly across the world, which keeps families connected. On the other hand, many conversations have become shorter and less personal, since people often send messages instead of meeting." },
      { q: "Do you think children should use tablets and smartphones?", a: "In moderation, yes. Educational apps can help them learn, but too much screen time harms sleep and concentration, so parents should set clear limits and encourage outdoor play." },
      { q: "Will robots replace human workers?", a: "In some jobs, such as factory work, they already have. However, jobs that need creativity and empathy, like teaching and nursing, are more difficult to automate, so I think humans will keep an important role." },
      { q: "What are the dangers of relying on technology?", a: "If a system fails, daily life can stop, and people may lose basic skills such as navigating without a map. There are also privacy risks, because companies collect a lot of personal data." },
      { q: "Which invention has changed life the most?", a: "The internet, I would say. It changed how we learn, work, shop and entertain ourselves, and almost every other modern technology depends on it." },
    ],
    vocab: [["automate", "make a process work without people"], ["privacy", "the right to keep personal information secret"], ["rely on", "depend on"], ["instant communication", "contact with no delay"], ["screen time", "time spent using screens"], ["breakthrough", "an important discovery"], ["digital skills", "ability to use technology"]],
    tips: ["Balance benefits with risks in two sentences.", "Use “on the other hand” and “however” naturally.", "Give an example, such as a device or an app."],
  },
  {
    slug: "environment",
    title: "The Environment",
    intro: "Environment questions ask who is responsible and what can be done. Give causes, effects and realistic solutions.",
    qa: [
      { q: "What are the main environmental problems in your country?", a: "Air pollution in big cities and water shortages are serious concerns. Traffic and industry produce a lot of emissions, while climate change makes dry periods longer, which affects farming." },
      { q: "Who is more responsible for protecting the environment: individuals or governments?", a: "Both, but governments have more power. They can pass laws and invest in public transport and clean energy, whereas individuals can only make small changes such as recycling and saving electricity." },
      { q: "Do you think people care enough about the environment?", a: "Awareness is growing, especially among young people, but habits change slowly. Many people agree that pollution is a problem, but they still prefer cheap or convenient options." },
      { q: "How can schools teach children about the environment?", a: "Through practical activities such as planting trees, sorting waste and cleaning parks. Children remember what they do better than what they only hear in a lesson." },
      { q: "Will the environment be better or worse in the future?", a: "It depends on action taken now. If countries invest in renewable energy, things could improve, but if nothing changes, I am afraid the situation will get worse." },
    ],
    vocab: [["emissions", "gases released into the air"], ["renewable energy", "power from sources that do not run out"], ["awareness", "knowing about a problem"], ["water shortage", "not enough water"], ["landfill", "a place where rubbish is buried"], ["sustainable", "able to continue without harming nature"], ["carbon footprint", "the amount of carbon you produce"]],
    tips: ["Use conditionals for the future: “If… will…”.", "Name a specific problem rather than saying “pollution” only.", "Contrast individual and government roles with “whereas”."],
  },
  {
    slug: "work-and-careers",
    title: "Work and Careers",
    intro: "Work questions usually compare generations or jobs. Explain what matters and why.",
    qa: [
      { q: "What is more important in a job: salary or satisfaction?", a: "Ideally both, but in the long term satisfaction matters more. A high salary may help for a while, but if you dislike your work every day, you will probably feel stressed and unhappy." },
      { q: "Why do some people change careers?", a: "They may find a new interest, want better pay or feel that they cannot progress in their current job. Others change because of redundancy, when a company closes or no longer needs their role." },
      { q: "Is it better to work for a company or to be self-employed?", a: "Working for a company is more secure because you receive a regular salary. Self-employment offers freedom, but you also carry the risk if business is slow, so it suits confident people." },
      { q: "How has work changed in recent years?", a: "More people work from home or have flexible hours thanks to technology. This saves commuting time, although it can make it harder to separate work from private life." },
      { q: "What skills will be important for future workers?", a: "Communication, problem-solving and digital skills. As machines do routine tasks, employers will value people who can think creatively and work well in teams." },
    ],
    vocab: [["job satisfaction", "feeling happy with your work"], ["secure job", "a job with little risk of ending"], ["self-employed", "working for yourself"], ["flexible hours", "working times you can adjust"], ["career progression", "moving up in a profession"], ["redundancy", "losing a job because it is no longer needed"], ["work-life balance", "a healthy balance of work and private life"]],
    tips: ["Say which factor is more important and explain why.", "Use “whereas” to compare two choices.", "Mention one modern change, such as remote work."],
  },
  {
    slug: "culture-and-tradition",
    title: "Culture and Tradition",
    intro: "Culture questions ask about change and identity. Explain what is kept, what is lost and why it matters.",
    qa: [
      { q: "Why are traditions important to a society?", a: "They give people a shared identity and a sense of belonging. Traditions connect generations, because children learn their history and values through customs and family celebrations." },
      { q: "Are young people interested in traditional culture?", a: "Some are, but many are more influenced by global trends from social media. However, when traditions are presented in a modern and interesting way, young people often become proud of them." },
      { q: "Is globalisation a threat to local cultures?", a: "It can be, since global brands and entertainment spread quickly and may replace local products. On the other hand, globalisation also helps share local culture with the world, so the effect is mixed." },
      { q: "How can governments protect cultural heritage?", a: "By funding museums and restoration projects, supporting craftspeople and including local history in schools. Laws that protect historic buildings are also essential." },
      { q: "Do you think traditions should change over time?", a: "Some adaptation is natural, because society changes. But the core values should remain, otherwise the tradition loses its meaning and becomes only a show for tourists." },
    ],
    vocab: [["identity", "who you are as a person or group"], ["sense of belonging", "feeling part of a group"], ["heritage", "history and traditions passed down"], ["globalisation", "the spread of ideas and products worldwide"], ["customs", "traditional ways of behaving"], ["preserve", "keep from being lost"], ["craftsperson", "someone skilled at making things by hand"]],
    tips: ["Give a mixed view with “but” or “on the other hand”.", "Use abstract nouns accurately: identity, heritage, belonging.", "Add an example from your own culture."],
  },
  {
    slug: "health",
    title: "Health and Lifestyle",
    intro: "Health questions in Part 3 ask about society, not just you. Link lifestyle, education and government.",
    qa: [
      { q: "Why do some people not exercise?", a: "Many are busy or tired after work, and some simply do not enjoy it. Desk jobs and long commutes also leave little energy, so exercise starts to feel like another task on a long list." },
      { q: "Who should be responsible for people's health: the individual or the government?", a: "Mainly the individual, because daily choices decide our health. But governments should help by providing clean environments, health education and affordable healthcare, since not everyone can manage alone." },
      { q: "Is fast food the main reason for health problems?", a: "It is one factor, but not the only one. A lack of exercise, stress and poor sleep also play a part, so blaming only food would be too simple." },
      { q: "How can schools encourage children to be healthy?", a: "By offering healthy meals, regular sport lessons and classes that explain nutrition. Children copy teachers, so adults setting a good example also makes a difference." },
      { q: "Do you think people live longer today than in the past?", a: "Yes, because of better medicine, hygiene and food. However, lifestyle diseases such as diabetes are rising, so living longer does not always mean living healthier." },
    ],
    vocab: [["sedentary", "involving a lot of sitting"], ["nutrition", "the food you eat and its effect"], ["preventive care", "action to stop illness before it starts"], ["lifestyle disease", "a disease linked to daily habits"], ["life expectancy", "how long people usually live"], ["affordable healthcare", "medical care people can pay for"], ["balanced diet", "a mix of healthy foods"]],
    tips: ["Use “not only… but also” for balanced causes.", "Link individual choices and government support.", "Avoid very strong claims; use “mainly” and “partly”."],
  },
  {
    slug: "media-and-news",
    title: "Media and News",
    intro: "Media questions ask about trust and influence. Show that you can evaluate information critically.",
    qa: [
      { q: "How do most people get their news today?", a: "Mostly from their phones, through social media and news apps. It is quick and free, but the information can be unreliable, since anyone can post a story without checking the facts." },
      { q: "Can we trust the news?", a: "Not always. Some outlets want clicks or have political interests, so it is wise to read several sources and check whether a claim is supported by evidence." },
      { q: "Does social media have a positive or negative effect on society?", a: "Both. It connects people and spreads useful information quickly, yet it also spreads rumours and can make people feel anxious or compare themselves with others unfairly." },
      { q: "Should the government control what appears in the media?", a: "Some control is necessary to stop harmful content such as hate speech. But too much control would limit freedom of speech and make people distrust the media." },
      { q: "Do you think newspapers will disappear?", a: "Printed newspapers will probably become rare, because readers prefer online news. Quality journalism will continue, though, because people still need reliable and well-researched reporting." },
    ],
    vocab: [["reliable source", "a source that can be trusted"], ["fake news", "false information presented as news"], ["freedom of speech", "the right to express opinions"], ["journalism", "reporting the news"], ["outlet", "a media organisation"], ["misinformation", "wrong information"], ["fact-check", "verify that something is true"]],
    tips: ["Use cautious language: “not always”, “often”, “usually”.", "Show critical thinking by mentioning evidence and sources.", "Present both sides before your conclusion."],
  },
  {
    slug: "tourism",
    title: "Tourism and Travel",
    intro: "Tourism questions ask about benefits and costs for places and people. Think about the economy and culture.",
    qa: [
      { q: "What are the benefits of tourism to a country?", a: "Tourism creates jobs, brings foreign money into the economy and encourages the restoration of historic sites. Local businesses such as hotels, restaurants and craft shops also grow." },
      { q: "Can tourism damage a place?", a: "Yes. Large crowds can harm fragile sites, increase pollution and push up prices for local people. Some towns have become so crowded that residents no longer enjoy living there." },
      { q: "Why do people like travelling to other countries?", a: "To experience different cultures, taste new food and relax from routine. Travelling also broadens the mind, because you see that people live in very different ways." },
      { q: "Is it better to travel independently or on a package tour?", a: "Independent travel is more flexible and cheaper, but a package tour is easier and safer, especially for older people or those visiting a country for the first time." },
      { q: "How will travel change in the future?", a: "I think it will become more sustainable, with more electric transport and eco-friendly hotels. Virtual reality may also let people visit fragile places without going there." },
    ],
    vocab: [["tourist attraction", "a place visitors want to see"], ["package tour", "a holiday with everything arranged"], ["foreign currency", "money from other countries"], ["fragile", "easily damaged"], ["eco-friendly", "not harmful to the environment"], ["broaden the mind", "give you new ideas and experiences"], ["overcrowded", "too full of people"]],
    tips: ["Give both benefits and costs.", "Use specific words: crowds, prices, jobs.", "Look to the future with “will probably”."],
  },
  {
    slug: "money",
    title: "Money and Spending",
    intro: "Money questions are about attitudes. Explain what money can and cannot do and how habits are formed.",
    qa: [
      { q: "Does money bring happiness?", a: "Up to a point. Enough money removes worries about food and housing, which certainly helps. Beyond that, relationships, health and a sense of purpose matter more to happiness." },
      { q: "Should children be given pocket money?", a: "Yes, I think so, because it teaches them to manage money. If they spend it all in one day, they learn a useful lesson about saving without any serious consequences." },
      { q: "Why do some people spend more than they earn?", a: "They may be influenced by advertising, or want to impress others. Credit cards also make it easy to buy things now and worry later, which can lead to debt." },
      { q: "Is it better to save or to spend?", a: "A balance is best. Saving gives security for emergencies, but life should also be enjoyed, so spending on experiences and family is worthwhile." },
      { q: "Will cash disappear in the future?", a: "Probably in many countries, since card and phone payments are faster and safer. But some people, especially older ones, will keep using cash for a long time." },
    ],
    vocab: [["manage money", "control how you spend and save"], ["pocket money", "small regular money for children"], ["debt", "money you owe"], ["emergency fund", "savings for unexpected costs"], ["impulse spending", "unplanned buying"], ["living expenses", "regular costs of living"], ["financial security", "having enough money to feel safe"]],
    tips: ["Use “up to a point” to give a balanced answer.", "Give a cause and its result.", "Make a prediction with “probably”."],
  },
  {
    slug: "cities-and-housing",
    title: "Cities and Housing",
    intro: "City questions ask about change and quality of life. Compare big cities with small towns and rural areas.",
    qa: [
      { q: "What are the advantages of living in a big city?", a: "Cities offer more jobs, better education and entertainment. Public transport is usually better too, so you can reach almost anywhere without a car." },
      { q: "And the disadvantages?", a: "Housing is expensive, the air is polluted and the pace of life is stressful. Noise and traffic can also make it difficult to relax, even at home." },
      { q: "Why are so many people moving from villages to cities?", a: "Mostly for work and education. Young people feel that opportunities are limited in the countryside, so they move to cities to build their careers." },
      { q: "How can cities be improved?", a: "By adding more green spaces, better public transport and affordable housing. Cycle lanes and pedestrian areas would also reduce traffic and make streets more pleasant." },
      { q: "Do you think people will want to live in the countryside in the future?", a: "Possibly, as remote work grows. If people can work from anywhere, many will choose quieter places with cheaper homes and cleaner air." },
    ],
    vocab: [["urbanisation", "growth of cities"], ["affordable housing", "homes people can pay for"], ["green space", "parks and gardens in a city"], ["pedestrian area", "a zone for walking"], ["cost of living", "how much everyday life costs"], ["rural", "in the countryside"], ["amenities", "useful facilities like shops and schools"]],
    tips: ["Give advantages and disadvantages in separate sentences.", "Suggest realistic improvements.", "Use “as” or “if” to explain future trends."],
  },
  {
    slug: "family-and-relationships",
    title: "Family and Relationships",
    intro: "Relationship questions ask about society and change. Think about generations and how life has changed.",
    qa: [
      { q: "How has family life changed over the years?", a: "Families are smaller now, and fewer generations live together. People also marry later, and both parents often work, so there is less time to spend with children." },
      { q: "Do you think grandparents should help look after children?", a: "It is a good idea if they are willing. Children benefit from their love and experience, and parents who work long hours get much-needed support." },
      { q: "What makes a friendship last?", a: "Honesty, trust and effort from both people. Friends who stay in touch and support each other in difficult times usually remain close even when they live far apart." },
      { q: "Is it better to have a few close friends or many acquaintances?", a: "A few close friends, I think, because they offer real support. Acquaintances are useful for networking, but you cannot rely on them in a crisis." },
      { q: "Should children live with their parents after they become adults?", a: "It depends. Living together can save money and strengthen bonds, but young adults also need independence to develop responsibility." },
    ],
    vocab: [["nuclear family", "parents and children only"], ["extended family", "relatives beyond parents and children"], ["generation gap", "differences between age groups"], ["bond", "a close connection"], ["support network", "people who help you"], ["independence", "being able to look after yourself"], ["acquaintance", "someone you know slightly"]],
    tips: ["Use “it depends” and then explain on what.", "Compare past and present with “used to” and present perfect.", "Keep your examples general but specific enough to be believable."],
  },
  {
    slug: "fame-and-celebrities",
    title: "Fame and Celebrities",
    intro: "Fame questions invite critical opinions. Discuss influence, privacy and responsibility.",
    qa: [
      { q: "Why are people interested in the lives of celebrities?", a: "Because their lives seem exciting and different from ordinary life. People enjoy comparing themselves with celebrities and following their stories like an ongoing television series." },
      { q: "Do celebrities have a responsibility to be good role models?", a: "Yes, since millions of young people watch them. They do not need to be perfect, but they should avoid promoting harmful behaviour." },
      { q: "Is fame always positive?", a: "No. Famous people lose their privacy, and a single mistake can be criticised by millions online. The pressure can seriously affect their mental health." },
      { q: "Should celebrities' private lives be protected?", a: "I believe so. Public work can be discussed, but photographing their families or homes without permission is intrusive and not necessary for the public interest." },
      { q: "Why do some young people want to become famous?", a: "They see fame as a route to money and admiration. Social media has made it look easy, but only a tiny number of people actually achieve lasting success." },
    ],
    vocab: [["role model", "a person others copy or admire"], ["in the public eye", "known and watched by many people"], ["privacy", "the right to keep personal life private"], ["intrusive", "entering where not welcome"], ["influencer", "a person with a large online audience"], ["admiration", "respect and approval"], ["tabloid", "a newspaper focusing on gossip"]],
    tips: ["Give a balanced judgement: positive and negative.", "Use modals for opinion: “should”, “need to”.", "Avoid naming real people; speak in general."],
  },
  {
    slug: "sports-and-competition",
    title: "Sports and Competition",
    intro: "Sports questions in Part 3 are about society: why people compete, who benefits and how sport affects young people.",
    qa: [
      { q: "Why do people enjoy watching sports?", a: "Sport is unpredictable and emotional. Fans feel part of a team, and the shared excitement of a match brings strangers together in a way that few other activities can." },
      { q: "Is it good for children to compete in sports?", a: "Competition can motivate them and teach them to handle both winning and losing. However, too much pressure may spoil their enjoyment, so parents should focus on effort, not only results." },
      { q: "Do you think professional athletes are paid too much?", a: "Their salaries are very high compared to nurses or teachers, but they bring in huge revenue through sponsors and television rights. Still, I think society should value essential jobs more." },
      { q: "How can governments encourage people to do more sport?", a: "By building affordable facilities, organising public events and making physical education a serious school subject. Making sport accessible is more effective than advertising campaigns." },
      { q: "Do big sporting events like the Olympics benefit the host country?", a: "They can bring tourism, jobs and national pride. But the cost of stadiums is enormous, and if buildings are not used afterwards, the benefits are not so clear." },
    ],
    vocab: [["competitive spirit", "the desire to win"], ["sponsorship", "money from companies for support"], ["professional athlete", "someone paid to play sport"], ["revenue", "money received"], ["facilities", "buildings and equipment for an activity"], ["national pride", "feeling proud of your country"], ["fair play", "following the rules honestly"]],
    tips: ["Present both sides, then give your own view.", "Use comparisons with “compared to”.", "Link ideas with “but” and “however” to sound balanced."],
  },
  {
    slug: "food-and-diet",
    title: "Food and Diet",
    intro: "Food questions at this level ask about trends and society. Explain causes and effects.",
    qa: [
      { q: "Why is fast food so popular?", a: "It is cheap, quick and convenient for busy people. Heavy advertising also makes it attractive, especially to young people who do not have time or skills to cook." },
      { q: "Do you think people eat more healthily than in the past?", a: "In some ways, since people know more about nutrition. But processed food is everywhere, and portions are larger, so many people still eat too much sugar and fat." },
      { q: "Should unhealthy food be taxed?", a: "It might help, because higher prices reduce consumption, as seen with sugary drinks in some countries. But the tax should be combined with education, or people will simply pay more and keep eating the same." },
      { q: "How has the way people cook changed?", a: "People cook less at home now and rely on ready meals or delivery. Technology such as air fryers and recipe videos has made cooking easier, but it has not stopped the trend." },
      { q: "Are traditional dishes disappearing?", a: "Not disappearing, but they are eaten less often in cities. At festivals and family gatherings, though, people still make them, so traditions remain alive." },
    ],
    vocab: [["processed food", "food changed by industrial methods"], ["convenience food", "food that is quick to prepare"], ["portion size", "the amount of food served"], ["consumption", "the amount used or eaten"], ["nutritious", "good for your health"], ["ready meal", "a prepared meal you just heat"], ["home-cooked", "made at home"]],
    tips: ["Link cause and effect with “so”, “because” and “as a result”.", "Use “might” and “could” to avoid over-claiming.", "Mention your culture when it is relevant."],
  },
  {
    slug: "art-and-creativity",
    title: "Art and Creativity",
    intro: "Creativity questions ask about value and funding. Explain why art matters and who should support it.",
    qa: [
      { q: "Why is art important to society?", a: "Art expresses emotions and ideas that are hard to put into words. It also records history and gives people a shared experience through music, films or paintings." },
      { q: "Should governments spend money on the arts?", a: "I think so, in moderate amounts. Artists need support, and cultural life makes a city more attractive, but health and education should come first." },
      { q: "Can creativity be taught?", a: "To some extent. Techniques can be taught, and a supportive environment helps people feel free to experiment, but imagination also depends on personality and curiosity." },
      { q: "Do you think modern art is real art?", a: "Often yes, although it can be hard to understand. If a work makes people think or feel something, I believe it has value, even if it does not look traditional." },
      { q: "Is it hard for artists to make a living?", a: "Yes, many struggle because income is unstable. Only a few become famous, so most artists need another job or a patron to support their work." },
    ],
    vocab: [["express emotions", "show feelings"], ["cultural life", "arts and entertainment in a society"], ["funding", "money provided for a purpose"], ["imagination", "the ability to create ideas"], ["patron", "someone who supports an artist financially"], ["unstable income", "money that is not regular"], ["traditional", "following old methods"]],
    tips: ["Give a reasoned opinion and then limit it.", "Use “to some extent” to show nuance.", "Mention forms of art: music, film, painting."],
  },
  {
    slug: "communication",
    title: "Communication",
    intro: "Communication questions ask about change and quality. Compare face-to-face and online communication.",
    qa: [
      { q: "Is face-to-face communication better than online communication?", a: "For personal and important matters, yes, because you can see expressions and hear the tone of voice. Online communication is excellent for speed and distance, but misunderstandings are more common." },
      { q: "What makes someone a good communicator?", a: "Good listening is the key. A skilled communicator also speaks clearly, adapts to the audience and shows respect, even when they disagree." },
      { q: "Do people communicate less in person today?", a: "In many situations, yes. People often prefer messaging to calling, and even families sitting together may be looking at their phones, which weakens real conversation." },
      { q: "Why is it important to learn foreign languages for communication?", a: "Because it helps people understand other cultures, not just words. It also creates opportunities for work, study and friendships across borders." },
      { q: "How might communication change in the future?", a: "Translation technology may let people speak different languages and still understand each other instantly. However, human skills such as empathy will remain essential." },
    ],
    vocab: [["body language", "communication through gestures and posture"], ["tone of voice", "how your voice sounds emotionally"], ["misunderstanding", "failure to understand correctly"], ["active listening", "listening carefully and showing it"], ["empathy", "understanding another person's feelings"], ["translation technology", "tools that translate speech or text"], ["face-to-face", "in person"]],
    tips: ["Compare two options and finish with a view.", "Use “however” to introduce limits.", "Mention both language and non-verbal communication."],
  },
  {
    slug: "rules-and-laws",
    title: "Rules and Laws",
    intro: "Law questions ask about fairness and behaviour. Discuss why rules exist and how people respond.",
    qa: [
      { q: "Why do we need rules in society?", a: "Without rules, people would pursue only their own interests, and there would be conflict. Rules protect safety and fairness, and they let strangers trust each other." },
      { q: "Do you think punishments are effective in reducing crime?", a: "Partly. Punishment can discourage some crimes, but education, employment and social support address the causes. Without them, punishment alone does not solve the problem." },
      { q: "Should people always obey rules?", a: "Generally, yes, since rules protect everyone. But unfair laws can be questioned through peaceful means such as petitions or voting, rather than ignoring them." },
      { q: "Why do some people break the rules?", a: "They may think they will not be caught, or they feel the rule is unfair. Others are under pressure, such as poverty, which makes illegal choices seem necessary." },
      { q: "Are rules in schools important?", a: "Yes. They teach students discipline and respect, and they create a safe environment. However, rules should be explained so that children understand why they exist." },
    ],
    vocab: [["law-abiding", "obeying the law"], ["deterrent", "something that discourages action"], ["enforce", "make sure a rule is followed"], ["regulation", "an official rule"], ["fairness", "treating people equally"], ["consequence", "the result of an action"], ["discipline", "training to obey rules"]],
    tips: ["Use “partly” and “generally” to avoid absolute claims.", "Explain causes as well as punishments.", "Use conditionals: “Without rules, people would…”."],
  },
  {
    slug: "history-and-the-past",
    title: "History and the Past",
    intro: "History questions ask why the past matters. Link learning from history to the present and future.",
    qa: [
      { q: "Why is it important to study history?", a: "It helps us understand how the present came about, and we can learn from earlier mistakes. Knowing the past also gives people a sense of identity and pride in their country." },
      { q: "Is history taught well in schools?", a: "Often it focuses too much on dates and names, which is boring. If lessons used stories, films and visits to historic sites, students would remember much more." },
      { q: "Should old buildings be preserved or replaced with modern ones?", a: "Important historic buildings should be preserved because they cannot be replaced. For ordinary old buildings, I think modern use or careful renovation is better than leaving them empty." },
      { q: "Do people today know enough about the past?", a: "Many know the main events but not the details. With so much entertainment competing for attention, history is often seen as less interesting than the latest news." },
      { q: "How do museums and documentaries help?", a: "They make history visual and emotional. Seeing real objects or hearing eyewitness stories helps people connect with events that happened long ago." },
    ],
    vocab: [["heritage site", "a place protected for its history"], ["preserve", "keep from damage or loss"], ["eyewitness", "a person who saw an event"], ["renovation", "repair and improvement of a building"], ["historical event", "an important event in the past"], ["learn from mistakes", "improve by understanding errors"], ["national identity", "a shared sense of belonging to a country"]],
    tips: ["Use second conditionals: “If lessons used…, students would…”.", "Support opinions with ideas about education and culture.", "Refer to both past and present."],
  },
];
