import type { GrammarQuestion } from './grammar.ts';

// Used only when AI cannot supply all 20 valid questions. Kept local so one
// failed AI response does not trigger repeated paid requests that day.
export const FALLBACK_QUESTIONS: GrammarQuestion[] = [
  { prompt: 'Choose the correct sentence about a daily habit.', options: ['She go to school.', 'She goes to school.', 'She going to school.', 'She gone to school.'], correctAnswer: 1, explanation: 'Use goes with she in the present simple.', skill: 'Subject–verb agreement' },
  { prompt: 'Complete: I have lived here ___ 2020.', options: ['for', 'since', 'during', 'from'], correctAnswer: 1, explanation: 'Since introduces the starting point of a period.', skill: 'Prepositions' },
  { prompt: 'Choose the correct article: She is ___ engineer.', options: ['a', 'an', 'the', 'no article'], correctAnswer: 1, explanation: 'Use an before a vowel sound such as engineer.', skill: 'Articles' },
  { prompt: 'Complete: If it rains tomorrow, we ___ at home.', options: ['stayed', 'will stay', 'would stay', 'staying'], correctAnswer: 1, explanation: 'The first conditional uses will in the result clause.', skill: 'Conditionals' },
  { prompt: 'Choose the correct past tense sentence.', options: ['They buyed a ticket.', 'They bought a ticket.', 'They have buy a ticket.', 'They buying a ticket.'], correctAnswer: 1, explanation: 'Bought is the irregular past form of buy.', skill: 'Past tense' },
  { prompt: 'Complete: There ___ many reasons for this change.', options: ['is', 'are', 'was', 'be'], correctAnswer: 1, explanation: 'The plural noun reasons requires are.', skill: 'Subject–verb agreement' },
  { prompt: 'Choose the correct comparison.', options: ['This method is more efficient than the old one.', 'This method is efficienter than the old one.', 'This method is most efficient than the old one.', 'This method is more efficient that the old one.'], correctAnswer: 0, explanation: 'Use more efficient than to compare two methods.', skill: 'Comparatives' },
  { prompt: 'Complete: Students should ___ their answers carefully.', options: ['checks', 'checking', 'check', 'checked'], correctAnswer: 2, explanation: 'A modal verb is followed by the base form check.', skill: 'Modal verbs' },
  { prompt: 'Choose the sentence with correct punctuation.', options: ['However the policy is expensive.', 'However, the policy is expensive.', 'However; the policy is expensive.', 'However: the policy is expensive.'], correctAnswer: 1, explanation: 'An introductory however is followed by a comma.', skill: 'Punctuation' },
  { prompt: 'Complete: The report was written ___ the research team.', options: ['by', 'with', 'from', 'at'], correctAnswer: 0, explanation: 'By identifies the agent in a passive sentence.', skill: 'Passive voice' },
  { prompt: 'Choose the correct relative clause.', options: ['The book who I read was useful.', 'The book which I read was useful.', 'The book where I read was useful.', 'The book whose I read was useful.'], correctAnswer: 1, explanation: 'Which refers to a thing such as a book.', skill: 'Relative clauses' },
  { prompt: 'Complete: By the time we arrived, the lecture ___.', options: ['starts', 'has started', 'had started', 'is starting'], correctAnswer: 2, explanation: 'Past perfect shows that the lecture started earlier.', skill: 'Past perfect' },
  { prompt: 'Choose the sentence with parallel structure.', options: ['The course teaches reading, writing, and to speak.', 'The course teaches reading, writing, and speaking.', 'The course teaches read, writing, and speaking.', 'The course teaches reading, write, and speaking.'], correctAnswer: 1, explanation: 'List items should use the same grammatical form.', skill: 'Parallel structure' },
  { prompt: 'Complete: Despite ___ tired, she finished the essay.', options: ['be', 'being', 'was', 'to be'], correctAnswer: 1, explanation: 'Despite is followed by a noun or an -ing form.', skill: 'Gerunds' },
  { prompt: 'Choose the correct subject–verb agreement.', options: ['The number of cars are rising.', 'The number of cars is rising.', 'The number of cars were rising.', 'The number of cars be rising.'], correctAnswer: 1, explanation: 'The number is a singular subject and takes is.', skill: 'Subject–verb agreement' },
  { prompt: 'Complete: Not only ___ costs, but it also saves time.', options: ['it reduces', 'does it reduce', 'it reduce', 'reduces it'], correctAnswer: 1, explanation: 'After fronted not only, use auxiliary–subject inversion.', skill: 'Inversion' },
  { prompt: 'Choose the correct hypothetical sentence.', options: ['If I were you, I would revise the essay.', 'If I was you, I will revise the essay.', 'If I am you, I would revise the essay.', 'If I were you, I will revise the essay.'], correctAnswer: 0, explanation: 'Use if I were and would for an unreal present situation.', skill: 'Conditionals' },
  { prompt: 'Complete: The more people cycle, ___ the air becomes.', options: ['cleaner', 'the cleaner', 'the cleanest', 'more cleaner'], correctAnswer: 1, explanation: 'The more … the cleaner expresses a linked change.', skill: 'Comparative structures' },
  { prompt: 'Choose the sentence with a clear reference.', options: ['They said it was bad, which was unclear.', 'The committee rejected the plan because its cost was too high.', 'It was said by them that this was bad.', 'This shows that it is a problem for it.'], correctAnswer: 1, explanation: 'Its cost clearly refers to the plan.', skill: 'Clarity' },
  { prompt: 'Complete: The government aims to prevent waste ___ increasing recycling.', options: ['by', 'to', 'for', 'with'], correctAnswer: 0, explanation: 'By followed by -ing explains the method.', skill: 'Prepositions' },
];
