import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u7-l2-d1',
    title: 'Like + -ing',
    titleUz: 'Like + fe\'l-ing',
    goal: "**like / love / enjoy / hate + -ing**, imlo va **I am like** xatosidan qochishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*I enjoy ___ in the park.*', opts: ['walk', 'walking', 'to walk', 'walks'], a: 1, why: "**enjoy** dan keyin faqat **-ing**." },
      { k: 'choice', q: '*She ___ cooking.*', opts: ['like', 'is like', 'likes', 'does like'], a: 2, why: "**she** + fe'l **-s**: *She likes cooking.*" },
      { k: 'match', pairs: [['swim', 'swimming'], ['dance', 'dancing'], ['run', 'running'], ['make', 'making'], ['play', 'playing']] },
      { k: 'fill', q: 'My brother loves ___. (swim)', a: ['swimming'], uz: "Akam suzishni juda yaxshi ko'radi.", why: "Qisqa fe'l: **m** ikkilanadi — **swimming**." },
      { k: 'fill', q: "I don't mind ___ dinner. (make)", a: ['making'], uz: "Kechki ovqat tayyorlashga qarshi emasman.", why: "**-e** tushadi: **making**." },
      { k: 'tf', q: "*I'm like dancing.* — \"Raqsga tushishni yoqtiraman\" degani, to'g'ri gap.", a: false, why: "**like** — fe'l, **am** kerak emas: *I like dancing.*" },
      { k: 'listen', say: "He can't stand getting up early.", opts: ["He can't stand getting up early.", 'He loves getting up early.', "He can't stand going to bed early.", "She can't stand getting up early."], a: 0, why: "**can't stand** — chiday olmaydi." },
      { k: 'order', uz: 'U kutishni yoqtirmaydi.', words: ['He', "doesn't", 'like', 'waiting'], extra: ["don't", 'likes'], why: "**doesn't** dan keyin fe'l **-s** siz." },
      { k: 'fix', wrong: 'I enjoy to read books.', a: ['I enjoy reading books.'], hint: 'enjoy dan keyin', why: "**enjoy** + **-ing**." },
      { k: 'fix', wrong: 'He doesn\'t likes cooking.', a: ["He doesn't like cooking."], why: "**doesn't** dan keyin **-s** kerak emas." },
      { k: 'translate', uz: 'Akangiz baliq ovini yoqtiradimi?', a: ['Does your brother like fishing', 'Does your brother enjoy fishing'], why: "**Does** + ega + fe'l + **-ing**." },
      { k: 'dictation', say: 'My mum loves travelling.' },
    ],
  },
  {
    id: 'u7-l5-d1',
    title: 'Plans with -ing',
    titleUz: 'Present Continuous: rejalar',
    goal: "Kelishilgan rejalarni **am / is / are + -ing** bilan aytishni va kelajak vaqtlari oldida predlogni tushirib qoldirishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*What ___ you doing tonight?*', opts: ['do', 'are', 'is', 'will'], a: 1, why: "**you** + **are** + -ing." },
      { k: 'choice', q: '*We ___ to Khiva next week.*', opts: ['go', 'are going', 'going', 'goes'], a: 1, why: "Reja: **are going**." },
      { k: 'match', pairs: [['tonight', 'bugun kechqurun'], ['tomorrow', 'ertaga'], ['next week', 'keyingi hafta'], ['the day after tomorrow', 'indinga'], ['this weekend', 'shu dam olish kunlari']] },
      { k: 'fill', q: "I ___ my grandma tomorrow. (visit)", a: ['am visiting', "'m visiting", 'm visiting'], hint: 'am / is / are + -ing', uz: "Ertaga buvimni ko'rgani boraman.", why: "Kelishilgan reja → **am visiting**." },
      { k: 'fill', q: 'She ___ Aziz at six. (meet)', a: ['is meeting', "'s meeting", 's meeting'], uz: "U soat oltida Aziz bilan uchrashadi.", why: "**she** → **is meeting**." },
      { k: 'tf', q: "*I'm seeing Bobur on next Tuesday.* — to'g'ri gap.", a: false, why: "**next** oldida predlog yo'q: *I'm seeing Bobur next Tuesday.*" },
      { k: 'listen', say: "What are you doing on Saturday?", opts: ["What are you doing on Saturday?", "What do you do on Saturday?", "What are you doing on Sunday?", "Where are you going on Saturday?"], a: 0, why: "**are you doing** — reja haqida savol." },
      { k: 'order', uz: 'Shanba kuni biror ish qilyapsizmi?', words: ['Are', 'you', 'doing', 'anything', 'on', 'Saturday'], extra: ['Do', 'does'], why: "**Are you doing…?** — savolda **Are** boshida." },
      { k: 'fix', wrong: 'I go to Samarkand tomorrow.', a: ["I'm going to Samarkand tomorrow.", 'I am going to Samarkand tomorrow.'], hint: 'Shaxsiy reja', why: "Reja uchun **Present Simple** emas: **I'm going**." },
      { k: 'fix', wrong: 'We meeting at six.', a: ["We're meeting at six.", 'We are meeting at six.'], hint: 'Fe\'l yetishmayapti', why: "**are** tushib qolgan." },
      { k: 'translate', uz: 'Ertaga ishlamayman. Dam olish kunim.', a: ["I'm not working tomorrow. It's my day off", 'I am not working tomorrow. It is my day off', "I'm not working tomorrow, it's my day off", "I'm not working tomorrow. It's my day off."], why: "Inkor: **I'm not working**." },
      { k: 'dictation', say: "We're having dinner with my parents on Sunday." },
    ],
  },
  {
    id: 'u7-l6-d1',
    title: 'Would like & invitations',
    titleUz: 'Would like va takliflar',
    goal: "**would like + to**, **How about + -ing**, **Let's** va taklifga odobli javob berishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "*I'd like ___ a table.*", opts: ['book', 'to book', 'booking', 'books'], a: 1, why: "**would like + to + fe'l**." },
      { k: 'choice', q: '*How about ___ to the cinema?*', opts: ['go', 'to go', 'going', 'goes'], a: 2, why: "**How about + -ing**." },
      { k: 'match', pairs: [["I'd love to!", 'Albatta, mamnuniyat bilan!'], ["I'm afraid I can't.", 'Afsuski, kela olmayman.'], ['That sounds great!', "Bu zo'r eshitiladi!"], ["Let's go!", 'Ketdik!']] },
      { k: 'fill', q: 'Would you like ___ come to my party?', a: ['to'], uz: "Ziyofatimga kelasizmi?", why: "**would like to** + fe'l." },
      { k: 'fill', q: "Why don't we ___ for a walk?", a: ['go'], uz: "Sayrga chiqsak-chi?", why: "**Why don't we** + fe'l (**to** siz)." },
      { k: 'choice', q: '*Would you like some more tea?* — Siz xohlaysiz.', opts: ['Yes, I do.', 'Yes, please.', 'Yes, I like.', 'Yes, I would.'], a: 1, why: "Taklifga: **Yes, please.**" },
      { k: 'tf', q: "*Would you like a sandwich? — Yes, I like.* — to'g'ri javob.", a: false, why: "Taklifga **Yes, please.** deyiladi." },
      { k: 'listen', say: "I'd love to, but I'm working on Friday.", opts: ["I'd love to, but I'm working on Friday.", "I'd love to come on Friday.", "I'm sorry, I can't come.", "I'd like to, but I'm free on Friday."], a: 0, why: "**I'd love to, but…** — odobli rad." },
      { k: 'order', uz: 'Men bir stakan suv olsam bo\'ladimi?', words: ["I'd", 'like', 'a', 'glass', 'of', 'water', 'please'], extra: ['want', 'to'], why: "**I'd like + ot**." },
      { k: 'fix', wrong: "She'd likes a coffee.", a: ["She'd like a coffee."], why: "**would** dan keyin **-s** yo'q." },
      { k: 'fix', wrong: "Let's to go to the park.", a: ["Let's go to the park."], why: "**Let's** + fe'l, **to** siz." },
      { k: 'translate', uz: 'Biz bilan kechki ovqatga kelasizmi?', a: ['Would you like to have dinner with us', 'Would you like to come to dinner with us', 'Would you like to come for dinner with us', 'Would you like to join us for dinner'], why: "Odobli taklif: **Would you like to…?**" },
    ],
  },
  {
    id: 'u7-l8-d1',
    title: 'How often? How long?',
    titleUz: 'How often, How long, How far',
    goal: "**How often / How long / How far** savollarini va **It takes…** javobini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*___ is it from here to the station?* — About two kilometres.', opts: ['How long', 'How far', 'How often', 'How much'], a: 1, why: "Masofa → **How far**." },
      { k: 'choice', q: '*___ do you go to the gym?* — Twice a week.', opts: ['How long', 'How far', 'How often', 'How old'], a: 2, why: "Necha marta → **How often**." },
      { k: 'match', pairs: [['once a week', 'haftada bir marta'], ['twice a month', 'oyda ikki marta'], ['three times a year', 'yiliga uch marta'], ['every day', 'har kuni'], ['never', 'hech qachon']] },
      { k: 'fill', q: 'I go swimming three times ___ week.', a: ['a'], uz: "Haftasiga uch marta suzishga boraman.", why: "**a week** — \"har hafta\"." },
      { k: 'fill', q: 'It takes me ___ hour to get to work.', a: ['an', 'one'], uz: "Ishga yetib borishim bir soat oladi.", why: "**hour** — *h* o'qilmaydi: **an hour**." },
      { k: 'tf', q: "*How long it takes?* — to'g'ri savol.", a: false, why: "Yordamchi fe'l kerak: **How long does it take?**" },
      { k: 'listen', say: 'How far is the airport from here?', opts: ['How far is the airport from here?', 'How long is the flight?', 'How often is the bus?', 'How far is the station from here?'], a: 0, why: "**How far** — masofa." },
      { k: 'order', uz: 'Ishga borish qancha vaqt oladi?', words: ['How', 'long', 'does', 'it', 'take', 'to', 'get', 'to', 'work'], extra: ['is', 'far'], why: "**How long does it take to…?**" },
      { k: 'fix', wrong: 'How often you go to the gym?', a: ['How often do you go to the gym?'], hint: 'Yordamchi fe\'l', why: "**do** tushib qolgan." },
      { k: 'fix', wrong: 'It need twenty minutes.', a: ['It takes twenty minutes.'], why: "Vaqt haqida: **It takes** + vaqt." },
      { k: 'translate', uz: 'Toshkentdan Samarqandgacha qancha masofa?', a: ['How far is it from Tashkent to Samarkand', 'How far is Samarkand from Tashkent'], why: "**How far is it…?** — **it** ni unutmang." },
      { k: 'dictation', say: 'It takes twenty minutes to walk to the metro.' },
    ],
  },
];
