import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u3-l2-d1',
    title: 'Verb, no am/are',
    titleUz: "Fe'l — am/are siz",
    goal: "I / you / we / they bilan fe'lni o'zgartirmasdan, ega + fe'l + to'ldiruvchi tartibida gap tuzishni mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['live', 'yashamoq'], ['work', 'ishlamoq'], ['drink', 'ichmoq'], ['speak', 'gapirmoq'], ['watch', "ko'rmoq, tomosha qilmoq"]] },
      { k: 'choice', q: "To'g'ri gapni tanlang:", opts: ['We are drink tea.', 'We tea drink.', 'We drink tea.'], a: 2, why: "Fe'l bor, **am / are** kerak emas. Tartib: ega + fe'l + to'ldiruvchi: **We drink tea.**" },
      { k: 'fill', q: 'I ___ tea every morning.', a: ['drink'], hint: 'drink', uz: 'Men har ertalab choy ichaman.', why: "ichmoq — **drink**. **I** bilan fe'l o'zgarmaydi." },
      { k: 'tf', q: '"I am work in a shop" — to\'g\'ri gap.', a: false, why: "Fe'l (**work**) bor, shuning uchun **am** ortiqcha: *I **work** in a shop.*" },
      { k: 'order', uz: 'Biz Buxoroda yashaymiz.', words: ['We', 'live', 'in', 'Bukhara'], extra: ['are'], why: "Ega (**We**) → fe'l (**live**) → joy (**in Bukhara**)." },
      { k: 'listen', say: 'They play tennis in the park', opts: ['They plays tennis in the park', 'They play tennis in the park', 'They are play tennis in the park', 'They like tennis in the park'], a: 1 },
      { k: 'fix', wrong: 'I am live in Tashkent.', a: ['I live in Tashkent.'], hint: 'Ortiqcha so\'zni olib tashlang.', why: "Fe'l **live** bor, **am** kerak emas: *I **live** in Tashkent.*" },
      { k: 'fill', q: 'My friends ___ in Samarkand. (live)', a: ['live'], uz: "Do'stlarim Samarqandda yashashadi.", why: "*My friends* = **they**, fe'l o'zgarmaydi: **live**." },
      { k: 'fix', wrong: 'We English speak.', a: ['We speak English.'], hint: "Fe'l ikkinchi o'rinda bo'lishi kerak.", why: "Inglizchada fe'l egadan keyin keladi: **We speak English.**" },
      { k: 'dictation', say: 'You speak English very well.' },
      { k: 'translate', uz: "Ular televizor ko'rishadi.", a: ['They watch TV', 'They watch television'], why: "**They watch TV.** — *are* kerak emas." },
      { k: 'translate', uz: "Biz yangi so'zlarni o'rganamiz.", a: ['We learn new words', 'We study new words'], why: "Ega → fe'l → to'ldiruvchi: **We learn new words.**" },
    ],
  },
  {
    id: 'u3-l3-d1',
    title: 'Add -s with he / she / it',
    titleUz: "he / she / it — fe'lga -s",
    goal: "he / she / it bilan fe'lga to'g'ri -s, -es, -ies qo'shishni va has, goes, does shakllarini mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['go', 'goes'], ['have', 'has'], ['do', 'does'], ['fly', 'flies'], ['watch', 'watches']] },
      { k: 'choice', q: "To'g'ri gapni tanlang:", opts: ['She work in a bank.', 'She works in a bank.', 'She are works in a bank.'], a: 1, why: "**she** bilan fe'lga **-s** qo'shiladi: *She **works** in a bank.*" },
      { k: 'fill', q: 'He ___ English at school. (teach)', a: ['teaches'], uz: 'U maktabda ingliz tilidan dars beradi.', why: "**-ch** bilan tugasa **+es**: *teaches*." },
      { k: 'fill', q: 'The baby ___. (cry)', a: ['cries'], uz: "Chaqaloq yig'laydi.", why: "Undosh + y → **ies**: *cry → cries*." },
      { k: 'tf', q: '"She playes tennis" — imlo to\'g\'ri.', a: false, why: "**y** dan oldin unli (*a*) bo'lsa, faqat **-s**: *She **plays** tennis.*" },
      { k: 'choice', q: "Qaysi fe'l **-es** oladi?", opts: ['play', 'wash', 'like', 'live'], a: 1, why: "**-sh** bilan tugagan fe'lga **-es**: *washes*." },
      { k: 'listen', say: 'He watches TV every evening', opts: ['He watch TV every evening', 'He watches TV every evening', 'He washes TV every evening', 'They watch TV every evening'], a: 1 },
      { k: 'order', uz: 'Singlim ingliz tilidan dars beradi.', words: ['My', 'sister', 'teaches', 'English'], extra: ['teach'], why: "*My sister* = she → **teaches**." },
      { k: 'fix', wrong: 'My brother have a new phone.', a: ['My brother has a new phone.'], hint: 'have → ?', why: "*My brother* = he → **has**." },
      { k: 'fix', wrong: 'She studys English at university.', a: ['She studies English at university.', 'She studies English at the university.'], hint: 'Imloga e\'tibor bering.', why: "Undosh + **y** → **ies**: *study → studies*." },
      { k: 'translate', uz: 'U (ayol) uy vazifasini qiladi.', a: ['She does her homework', 'She does the homework'], why: "do → **does**: *She does her homework.*" },
      { k: 'dictation', say: 'The cat catches a fish.' },
    ],
  },
  {
    id: 'u3-l3-d2',
    title: 'He work? Spot the -s',
    titleUz: "-s ni topamiz: qiyinroq",
    goal: "He work, She have, Ali go kabi tipik xatolarni topasiz va -s, -es, -ies imlosini aralash holda mustahkamlaysiz.",
    exercises: [
      { k: 'choice', q: "Qaysi gap to'g'ri?", opts: ['My friends lives in Fergana.', 'My friends live in Fergana.', 'My friend live in Fergana.'], a: 1, why: "*My friends* = **they**, fe'lga -s qo'shilmaydi: **live**." },
      { k: 'fill', q: 'Ali ___ his homework in the evening. (do)', a: ['does'], uz: 'Ali kechqurun uy vazifasini qiladi.', why: "Ali = he; do → **does**." },
      { k: 'tf', q: '"The students speaks English" — to\'g\'ri gap.', a: false, why: "*The students* = **they**, shuning uchun **speak** (s'siz)." },
      { k: 'choice', q: "**fixes** so'zining oxiri qanday o'qiladi?", say: 'fixes', opts: ['/s/', '/z/', '/ɪz/'], a: 2, why: "**-x** dan keyin yangi bo'g'in qo'shiladi: **/ɪz/**." },
      { k: 'fill', q: 'My mother ___ a small garden. (have)', a: ['has'], uz: "Onamning kichkina bog'i bor.", why: "*My mother* = she → **has**." },
      { k: 'fix', wrong: 'Aziz go to school at eight.', a: ['Aziz goes to school at eight.'], hint: 'Aziz = he', why: "Aziz = he; go → **goes** (-o bilan tugasa **+es**)." },
      { k: 'fix', wrong: 'The lesson finishs at four.', a: ['The lesson finishes at four.'], hint: 'Imloga e\'tibor bering.', why: "**-sh** bilan tugasa **+es**: *finishes*." },
      { k: 'fix', wrong: 'He haves a big family.', a: ['He has a big family.'], why: "have → **has** (\"haves\" bo'lmaydi)." },
      { k: 'order', uz: 'Uning akasi mashinalarni tuzatadi.', words: ['Her', 'brother', 'fixes', 'cars'], extra: ['fix'], why: "*Her brother* = he; **-x** → **fixes**." },
      { k: 'listen', say: 'She tries hard', opts: ['She try hard', 'She tries hard', 'She tires hard', 'She cries hard'], a: 1 },
      { k: 'translate', uz: "U (erkak) universitetda o'qiydi.", a: ['He studies at university', 'He studies at the university'], why: "undosh + y → **ies**: **He studies** at university." },
      { k: 'dictation', say: 'My father goes to work at eight.' },
    ],
  },
  {
    id: 'u3-l4-d1',
    title: "Don't or doesn't?",
    titleUz: "don't yoki doesn't?",
    goal: "don't / doesn't ni to'g'ri tanlashni va doesn't dan keyin fe'lni -s siz qoldirishni mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['tea', 'choy'], ['meat', "go'sht"], ['rice', 'guruch'], ['sugar', 'shakar'], ['bread', 'non']] },
      { k: 'fill', q: "I ___ drink coffee.", a: ["don't", 'do not'], uz: 'Men qahva ichmayman.', why: "**I** → **don't**." },
      { k: 'fill', q: "She ___ eat meat.", a: ["doesn't", 'does not'], uz: "U go'sht yemaydi.", why: "**she** → **doesn't**." },
      { k: 'choice', q: "To'g'ri gapni tanlang:", opts: ["He doesn't drinks tea.", "He don't drink tea.", "He doesn't drink tea.", 'He not drink tea.'], a: 2, why: "**he** → **doesn't** + fe'l **-s siz**." },
      { k: 'tf', q: '"We doesn\'t eat rice" — to\'g\'ri gap.', a: false, why: "**we** → **don't**: *We **don't** eat rice.*" },
      { k: 'listen', say: "They don't eat bread", opts: ["They eat bread", "They don't eat bread", "They doesn't eat bread", "They don't need bread"], a: 1 },
      { k: 'order', uz: 'Ular sharbat ichmaydi.', words: ['They', "don't", 'drink', 'juice'], extra: ["doesn't"], why: "**they** → **don't** + **drink**." },
      { k: 'fix', wrong: "He doesn't likes sugar.", a: ["He doesn't like sugar.", 'He does not like sugar.'], hint: "doesn't dan keyin fe'l qanday bo'ladi?", why: "-s **doesn't** da bor, fe'lda emas: *doesn't **like***." },
      { k: 'fix', wrong: "I'm not like vegetables.", a: ["I don't like vegetables.", 'I do not like vegetables.'], why: "**like** — fe'l, demak **don't** kerak." },
      { k: 'fill', q: "Ali doesn't ___ fruit. (eat)", a: ['eat'], uz: 'Ali meva yemaydi.', why: "**doesn't** dan keyin fe'l -s siz: **eat**." },
      { k: 'translate', uz: 'Biz qahva ichmaymiz.', a: ["We don't drink coffee", 'We do not drink coffee'], why: "**we** → **don't**: *We don't drink coffee.*" },
      { k: 'dictation', say: "She doesn't drink tea or coffee." },
    ],
  },
  {
    id: 'u3-l5-d1',
    title: 'Do or does?',
    titleUz: 'Do yoki does?',
    goal: "Do / Does bilan savol tuzishni va Yes, I do. / No, she doesn't. kabi qisqa javoblarni mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['watch films', "film ko'rmoq"], ['listen to music', 'musiqa tinglamoq'], ['play chess', "shaxmat o'ynamoq"], ['go to the cinema', 'kinoga bormoq'], ['play the guitar', 'gitara chalmoq']] },
      { k: 'fill', q: '___ you play chess?', a: ['Do', 'do'], uz: "Siz shaxmat o'ynaysizmi?", why: "**you** → **Do**." },
      { k: 'fill', q: '___ your brother like football?', a: ['Does', 'does'], uz: 'Akangiz futbolni yoqtiradimi?', why: "*your brother* = he → **Does**." },
      { k: 'choice', q: "To'g'ri savolni tanlang:", opts: ['Do you likes music?', 'Does you like music?', 'Do you like music?', 'Are you like music?'], a: 2, why: "**Do** + you + fe'l: *Do you like music?*" },
      { k: 'tf', q: '"Does she plays the guitar?" — to\'g\'ri savol.', a: false, why: "**Does** dan keyin fe'l -s siz: *Does she **play** the guitar?*" },
      { k: 'listen', say: 'Do they like parties?', opts: ['They like parties.', 'Does they like parties?', 'Do they like parties?', "They don't like parties."], a: 2 },
      { k: 'choice', q: "**Does he watch films?** — qisqa javob (ha):", opts: ['Yes, he watches.', 'Yes, he does.', 'Yes, he do.', 'Yes, he is.'], a: 1, why: "Savoldagi yordamchi takrorlanadi: **Yes, he does.**" },
      { k: 'fill', q: 'Do your parents go to the cinema? — Yes, they ___.', a: ['do'], why: "**Do** savoliga → **they do**." },
      { k: 'order', uz: 'Singlingiz shaxmat o\'ynaydimi?', words: ['Does', 'your', 'sister', 'play', 'chess'], extra: ['plays'], why: "**Does** + ega + **play** (s'siz)." },
      { k: 'fix', wrong: 'Do she like music?', a: ['Does she like music?'], why: "**she** → **Does**." },
      { k: 'translate', uz: 'Siz musiqa tinglaysizmi?', a: ['Do you listen to music'], why: "**Do you listen to music?** — *listen **to***." },
      { k: 'dictation', say: 'Does your brother play football?' },
    ],
  },
  {
    id: 'u3-l5-d2',
    title: 'Questions and short answers',
    titleUz: 'Savol va qisqa javoblar',
    goal: "Do / Does savollaridagi tipik xatolarni topasiz va qisqa javoblarni aralash holda mustahkamlaysiz.",
    exercises: [
      { k: 'choice', q: "Qaysi savol to'g'ri?", opts: ['Do your sister watch TV?', 'Does your sister watches TV?', 'Does your sister watch TV?', 'Is your sister watch TV?'], a: 2, why: "*your sister* = she → **Does** + **watch** (s'siz)." },
      { k: 'fill', q: 'Do your friends play games? — No, they ___.', a: ["don't", 'do not'], why: "**Do** savoliga yo'q javob: **they don't**." },
      { k: 'fill', q: 'Does Aziz have a guitar? — Yes, he ___.', a: ['does'], why: "*Aziz* = he; savol **Does** → **he does**." },
      { k: 'tf', q: '"Do you like tea? — Yes, I like." — javob to\'g\'ri.', a: false, why: "Qisqa javobda fe'l takrorlanmaydi: **Yes, I do.**" },
      { k: 'fix', wrong: 'Does he has a computer?', a: ['Does he have a computer?'], hint: 'Does dan keyin fe\'l qanday bo\'ladi?', why: "**Does** dan keyin fe'l -s siz: **have**." },
      { k: 'fix', wrong: 'Are you play chess?', a: ['Do you play chess?'], why: "**play** — fe'l, demak **Do**, **Are** emas." },
      { k: 'fix', wrong: 'Yes, she likes.', a: ['Yes, she does.'], hint: 'Savol: Does she like sport?', why: "Qisqa javob: **Yes, she does.** — fe'l takrorlanmaydi." },
      { k: 'order', uz: "Do'stlaringiz bazmlarga boradimi?", words: ['Do', 'your', 'friends', 'go', 'to', 'parties'], extra: ['Does'], why: "*your friends* = they → **Do**." },
      { k: 'listen', say: 'Does he go to the cinema?', opts: ['Do he go to the cinema?', 'He goes to the cinema.', 'Does he goes to the cinema?', 'Does he go to the cinema?'], a: 3 },
      { k: 'translate', uz: 'Akangiz gitara chaladimi?', a: ['Does your brother play the guitar'], why: "**Does** your brother **play** the guitar?" },
      { k: 'translate', uz: "Yo'q, ular o'ynamaydi.", a: ["No, they don't", 'No, they do not'], why: "Qisqa javob: **No, they don't.**" },
      { k: 'dictation', say: 'Do you listen to music at home?' },
    ],
  },
  {
    id: 'u3-l7-d1',
    title: 'In, on or at?',
    titleUz: 'in, on yoki at?',
    goal: "Hafta kunlari va oylarni katta harf bilan yozishni, in / on / at ni to'g'ri tanlashni mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['Tuesday', 'seshanba'], ['Thursday', 'payshanba'], ['Saturday', 'shanba'], ['weekend', 'dam olish kunlari'], ['month', 'oy']] },
      { k: 'fill', q: 'I have English ___ Tuesday.', a: ['on'], uz: 'Seshanba kuni ingliz tili darsim bor.', why: "Hafta kuni → **on**." },
      { k: 'fill', q: 'My birthday is ___ October.', a: ['in'], uz: "Tug'ilgan kunim oktabrda.", why: "Oy → **in**." },
      { k: 'fill', q: 'We have lunch ___ one o\'clock.', a: ['at'], uz: 'Biz soat birda tushlik qilamiz.', why: "Soat → **at**." },
      { k: 'choice', q: "Qaysi ibora to'g'ri?", opts: ['in Saturday', 'on Saturday', 'at Saturday', 'on the Saturday'], a: 1, why: "Hafta kuni → **on**, *the* siz." },
      { k: 'tf', q: '"I get up on seven" — to\'g\'ri gap.', a: false, why: "Soat bilan **at**: *I get up **at** seven.*" },
      { k: 'listen', say: 'I go to the cinema on Friday', opts: ['I go to the cinema in Friday', 'I go to the cinema on Friday', 'I go to the cinema on Sunday', 'I go to the cinema at Friday'], a: 1 },
      { k: 'fix', wrong: 'We have a test in Friday.', a: ['We have a test on Friday.'], why: "Hafta kuni → **on Friday**." },
      { k: 'fix', wrong: 'I go to bed in night.', a: ['I go to bed at night.'], why: "Maxsus ibora: **at night**." },
      { k: 'fix', wrong: 'My birthday is on July.', a: ['My birthday is in July.'], why: "Oy → **in July** (**on** — hafta kuni uchun)." },
      { k: 'order', uz: 'Yakshanba kuni oilam bilan kechki ovqat qilaman.', words: ['I', 'have', 'dinner', 'with', 'my', 'family', 'on', 'Sunday'], extra: ['in'], alt: [['On', 'Sunday', 'I', 'have', 'dinner', 'with', 'my', 'family']], why: "Hafta kuni → **on Sunday**." },
      { k: 'translate', uz: 'Biz dam olish kunlari ishlamaymiz.', a: ["We don't work at the weekend", 'We do not work at the weekend', "We don't work on the weekend", 'We do not work on the weekend'], why: "**at the weekend** (amerikacha *on the weekend*)." },
    ],
  },
];
