import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u4-l2-d1',
    title: 'There is or there are?',
    titleUz: 'There is yoki there are?',
    goal: "There is / there are, some / any va \"In my room have a bed\" xatosini mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['kitchen', 'oshxona'], ['bedroom', 'yotoqxona'], ['fridge', 'muzlatkich'], ['carpet', 'gilam'], ['shelf', 'javon']] },
      { k: 'choice', q: 'There ___ two lamps in the bedroom.', opts: ['is', 'are', 'am', 'be'], a: 1, why: "*two lamps* — ko'plik → **there are**." },
      { k: 'fill', q: 'There ___ a fridge in the kitchen.', a: ['is'], why: "*a fridge* — birlik → **there is**." },
      { k: 'choice', q: "\"Xonamda karavot bor.\"", opts: ['In my room have a bed.', 'There is a bed in my room.', 'There have a bed in my room.', 'In my room is a bed.'], a: 1, why: "\"…da … bor\" = **There is** + narsa + joy. **have** bu yerda kerak emas." },
      { k: 'fill', q: 'Are there ___ shelves in the bathroom?', a: ['any'], why: "Savolda ko'plik ot oldida **any** ishlatiladi." },
      { k: 'tf', q: "*Is there a lamp in the bedroom?* savoliga **Yes, there's.** deb javob berish mumkin.", a: false, why: "Qisqa ijobiy javobda qisqartirma ishlatilmaydi: **Yes, there is.**" },
      { k: 'order', uz: 'Mehmonxonada ikkita divan bor.', words: ['There', 'are', 'two', 'sofas', 'in', 'the', 'living', 'room'], extra: ['is'], why: "*two sofas* — ko'plik → **There are** + narsa + joy." },
      { k: 'listen', say: 'Is there a carpet in your bedroom?', opts: ['Is there a carpet in your bedroom?', 'Are there any carpets in your bedroom?', "There isn't a carpet in your bedroom.", 'Is there a carpet in your bathroom?'], a: 0 },
      { k: 'fix', wrong: 'In my room have a bed.', a: ['There is a bed in my room.', "There's a bed in my room.", 'In my room there is a bed.', "In my room there's a bed."], hint: "\"…da … bor\" — inglizchada qaysi qolip kerak?", why: "Inglizchada **have** emas, **there is** ishlatiladi: **There is** a bed in my room." },
      { k: 'fix', wrong: "There aren't some chairs in the kitchen.", a: ["There aren't any chairs in the kitchen."], hint: 'Inkor gapda some o\'rniga nima ishlatiladi?', why: "Inkor gapda **some** emas, **any**: There aren't **any** chairs." },
      { k: 'translate', uz: 'Kvartiramda uchta yotoqxona bor.', a: ['There are three bedrooms in my flat', 'There are three bedrooms in my apartment', 'There are 3 bedrooms in my flat', 'There are 3 bedrooms in my apartment'], why: "*three bedrooms* — ko'plik → **There are** three bedrooms…" },
      { k: 'dictation', say: "There isn't a bed in the living room." },
    ],
  },
  {
    id: 'u4-l4-d1',
    title: 'Much, many or a lot of?',
    titleUz: 'Much, many yoki a lot of?',
    goal: "Sanaladigan va sanalmaydigan otlarni ajratib, much / many hamda a bottle of kabi o'lchov so'zlarini to'g'ri ishlatishni mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['banana', 'banan'], ['cheese', 'pishloq'], ['butter', "sariyog'"], ['flour', 'un'], ['salt', 'tuz']] },
      { k: 'choice', q: 'Qaysi ot **sanalmaydi**?', opts: ['banana', 'egg', 'rice', 'apple'], a: 2, why: "**rice** — sanalmaydigan ot: *a rice* ham, *rices* ham bo'lmaydi." },
      { k: 'fill', q: 'There ___ some cheese in the fridge.', a: ['is'], why: "*cheese* — sanalmaydi → fe'l birlikda: **is**." },
      { k: 'choice', q: 'How ___ eggs do we need?', opts: ['much', 'many', 'any', 'a lot'], a: 1, why: "*eggs* — sanaladigan ko'plik → **How many**." },
      { k: 'fill', q: 'How ___ sugar do you need?', a: ['much'], why: "*sugar* — sanalmaydi → **How much**." },
      { k: 'tf', q: "**two breads** — to'g'ri ibora.", a: false, why: "**bread** sanalmaydi: **two pieces of bread**." },
      { k: 'choice', q: "\"Ikki shisha suv\"", opts: ['two bottle of water', 'two bottles of water', 'two bottles of waters', 'two bottle of waters'], a: 1, why: "**-s** faqat idish so'ziga qo'shiladi: two **bottles** of water." },
      { k: 'fix', wrong: 'How much bananas do you need?', a: ['How many bananas do you need?'], hint: "*bananas* sanaladimi?", why: "*bananas* — sanaladigan ko'plik → **How many**." },
      { k: 'fix', wrong: 'I need two bottle of water.', a: ['I need two bottles of water.'], hint: 'Ikkita narsa bo\'lsa, idish so\'zi qanday o\'zgaradi?', why: "Ikki shisha → idish so'ziga **-s**: two **bottles** of water." },
      { k: 'order', uz: 'Menga bir paket choy kerak.', words: ['I', 'need', 'a', 'packet', 'of', 'tea'], extra: ['packets'], why: "Sanalmaydigan ot oldida idish so'zi: **a packet of** tea." },
      { k: 'translate', uz: "Muzlatkichda sut ko'p emas.", a: ["There isn't much milk in the fridge", "There isn't a lot of milk in the fridge", 'There is not much milk in the fridge', 'There is not a lot of milk in the fridge', "There's not much milk in the fridge", "There's not a lot of milk in the fridge"], why: "*milk* — sanalmaydi, inkor gap → **much** (yoki **a lot of**)." },
      { k: 'dictation', say: 'How much flour do you need?' },
    ],
  },
  {
    id: 'u4-l5-d1',
    title: "Can or can't?",
    titleUz: "Can yoki can't?",
    goal: "can / can't dan keyin to va -s qo'shmaslikni hamda Do you can…? xatosidan qochishni mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['swim', 'suzmoq'], ['cook', 'ovqat pishirmoq'], ['dance', 'raqsga tushmoq'], ['draw', 'rasm chizmoq'], ['ride', '(ot, velosiped) minmoq']] },
      { k: 'choice', q: 'My brother ___ drive.', opts: ['can', 'cans', 'can to', 'does can'], a: 0, why: "**can** hamma shaxs uchun bir xil: *-s* yo'q, *to* yo'q." },
      { k: 'listen', say: "I can't ski.", opts: ['I can ski.', "I can't ski.", "I can't swim.", 'Can I ski?'], a: 1, why: "Uzun **\"ka:nt\"** → *can't*." },
      { k: 'fill', q: '___ you cook plov? — Yes, I can.', a: ['Can'], why: "Savolda **Can** oldinga chiqadi." },
      { k: 'tf', q: "**Do you can swim?** — to'g'ri savol.", a: false, why: "**can** o'zi savol tuzadi: **Can you swim?**" },
      { k: 'choice', q: "\"U ingliz tilida gapira oladi.\"", opts: ['He can to speak English.', 'He can speaks English.', 'He can speak English.', 'He cans speak English.'], a: 2, why: "**can + fe'lning asosiy shakli**: *to* ham, *-s* ham yo'q." },
      { k: 'fill', q: "I can't swim ___ all.", a: ['at'], why: "\"Umuman\" = **not … at all**." },
      { k: 'fix', wrong: 'My sister can to dance very well.', a: ['My sister can dance very well.'], hint: 'can dan keyin nima qo\'yilmaydi?', why: "**can** dan keyin **to** qo'yilmaydi: can **dance**." },
      { k: 'fix', wrong: 'He cans ride a horse.', a: ['He can ride a horse.'], hint: 'he/she/it bilan can o\'zgaradimi?', why: "**can** ga hech qachon **-s** qo'shilmaydi: He **can** ride." },
      { k: 'fix', wrong: 'Do you can draw?', a: ['Can you draw?'], hint: 'Savolni nima tuzadi?', why: "**do/does** kerak emas: **Can you draw?**" },
      { k: 'order', uz: 'Men juda yaxshi raqsga tusha olaman.', words: ['I', 'can', 'dance', 'very', 'well'], extra: ['to'], why: "Daraja so'zi gap oxirida: can dance **very well**." },
      { k: 'translate', uz: "Derazani ochsam bo'ladimi?", a: ['Can I open the window', 'Can I open the window please', 'Can I open the window, please'], why: "Ruxsat so'rash → **Can I…?**" },
    ],
  },
  {
    id: 'u4-l8-d1',
    title: 'Am, is or are + -ing',
    titleUz: 'Am, is, are + -ing',
    goal: "Present Continuous da am/is/are ni tashlab ketmaslik, -ing imlosi va do/does siz savol hamda inkor tuzishni mashq qilasiz.",
    exercises: [
      { k: 'match', pairs: [['sit', 'sitting'], ['make', 'making'], ['run', 'running'], ['write', 'writing'], ['play', 'playing']] },
      { k: 'choice', q: 'She ___ a letter now.', opts: ['writing', 'is writing', 'write', 'is write'], a: 1, why: "**is + writing** — ikkala qism ham kerak." },
      { k: 'fill', q: 'swim → ___', a: ['swimming'], why: "Qisqa unli + bitta undosh → **m** ikkilanadi: **swimming**." },
      { k: 'fill', q: 'dance → ___', a: ['dancing'], why: "**-e** tushadi: **dancing**." },
      { k: 'tf', q: "**They playing football now.** — to'g'ri gap.", a: false, why: "**are** tushib qolgan: They **are** playing football." },
      { k: 'choice', q: 'What ___ you doing?', opts: ['are', 'do', 'does', 'is'], a: 0, why: "Present Continuous da savolni **am/is/are** tuzadi: What **are** you doing?" },
      { k: 'fill', q: 'Shh! The baby ___ sleeping.', a: ['is'], why: "*the baby* — he/she/it → **is** sleeping." },
      { k: 'fix', wrong: 'I reading a book now.', a: ["I'm reading a book now.", 'I am reading a book now.'], hint: 'Qaysi so\'z tushib qolgan?', why: "**am** tushib qolgan: I **am** (I'm) reading." },
      { k: 'fix', wrong: 'She is runing in the park.', a: ['She is running in the park.', "She's running in the park."], hint: '-ing imlosini tekshiring.', why: "Qisqa unli + bitta undosh → **n** ikkilanadi: **running**." },
      { k: 'fix', wrong: "We don't watching TV now.", a: ["We aren't watching TV now.", 'We are not watching TV now.', "We're not watching TV now."], hint: 'don\'t o\'rniga nima kerak?', why: "Inkorni **aren't** tuzadi, **don't** emas: We **aren't** watching TV." },
      { k: 'order', uz: 'Ular hozir nima qilyapti?', words: ['What', 'are', 'they', 'doing', 'now'], extra: ['do'], why: "**What + are + they + doing?** — *do* kerak emas." },
      { k: 'translate', uz: 'Bolalar hozir uxlayapti.', a: ['The children are sleeping now', 'The kids are sleeping now', 'The children are sleeping at the moment', 'The kids are sleeping at the moment', 'The children are sleeping', 'The kids are sleeping'], why: "Hozirgi harakat → **are sleeping**." },
    ],
  },
];
