import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u2-l2-d1',
    title: 'Am, is or are?',
    titleUz: 'Am, is yoki are?',
    goal: "**am / is / are** ni olmoshga qarab tanlashni va qisqa shakllarni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*We ___ hungry.*', opts: ['am', 'is', 'are'], a: 2, why: '**we** bilan **are** ishlatiladi.' },
      { k: 'choice', q: '*I ___ tired.*', opts: ['am', 'is', 'are'], a: 0, why: '**I** bilan faqat **am** keladi.' },
      { k: 'match', pairs: [["she's", 'she is'], ["they're", 'they are'], ["I'm", 'I am'], ["it's", 'it is'], ["you're", 'you are']] },
      { k: 'fill', q: 'My teacher ___ busy.', a: ['is'], uz: "O'qituvchim band.", why: "Bitta odam (he/she) → **is**." },
      { k: 'tf', q: '*She are happy.* — to\'g\'ri gap.', a: false, why: '**she** bilan **is** kerak: *She is happy.*' },
      { k: 'listen', say: "They're thirsty.", opts: ["They're thirsty.", "She's thirsty.", "They're hungry.", "We're thirsty."], a: 0, why: "**they're** = they are." },
      { k: 'fill', q: 'Tom and Sara ___ sad.', a: ['are'], uz: "Tom va Sara xafa.", why: 'Ikki kishi (they) → **are**.' },
      { k: 'order', uz: "O'g'il bolaning qorni och.", words: ['The', 'boy', 'is', 'hungry'], extra: ['are'], why: 'Bitta bola (he) → **is**.' },
      { k: 'translate', uz: 'Men xursandman.', a: ["I'm happy", 'I am happy'], why: '**I am happy.** — o\'zbekchada fe\'l yo\'q, inglizchada **am** shart.' },
      { k: 'fix', wrong: 'She tired.', a: ['She is tired.', "She's tired."], hint: 'Fe\'l yetishmayapti', why: '**is** tushib qolgan: *She is tired.*' },
      { k: 'dictation', say: 'My friends are busy.' },
    ],
  },
  {
    id: 'u2-l2-d2',
    title: 'To be: tricky mix',
    titleUz: 'To be: qiyin aralash mashqlar',
    goal: "**to be** ni tushirib qoldirmaslik, ism va olmoshlar bilan adashmaslikni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Ali and his friend ___ tired.*', opts: ['is', 'am', 'are', '—'], a: 2, why: 'Ali va do\'sti = ikki kishi (they) → **are**.' },
      { k: 'choice', q: '*The cat and the dog ___ hungry.*', opts: ['is', 'are', 'am', '—'], a: 1, why: 'Ikkita hayvon = they → **are**.' },
      { k: 'fill', q: '___ busy. (she is)', a: ["She's"], hint: 'Qisqa shaklda yozing', why: '**she is** → **she\'s**.' },
      { k: 'tf', q: "*I'm hungry* — \"Qornim och\" degani.", a: true, why: 'Ha: inglizchada **I am hungry** deyiladi.' },
      { k: 'tf', q: "*They're* = *they is*.", a: false, why: "**They're** = **they are**, \"they is\" yo'q." },
      { k: 'order', uz: "Mening do'stlarim xursand.", words: ['My', 'friends', 'are', 'happy'], extra: ['is'], why: "Ko'plik → **are**." },
      { k: 'fix', wrong: 'I a student.', a: ["I'm a student.", 'I am a student.'], hint: 'Fe\'l yetishmayapti', why: "**am** tushib qolgan — o'zbeklarning eng ko'p xatosi." },
      { k: 'fix', wrong: 'Malika and Aziz is late.', a: ['Malika and Aziz are late.'], why: 'Ikki kishi → **are**.' },
      { k: 'fix', wrong: 'He are angry.', a: ['He is angry.', "He's angry."], why: '**he** bilan **is** keladi.' },
      { k: 'translate', uz: 'Qornim och va chanqadim.', a: ["I'm hungry and thirsty", 'I am hungry and thirsty'], why: '**I\'m hungry and thirsty.**' },
      { k: 'translate', uz: "Do'stim band.", a: ['My friend is busy', "My friend's busy"], why: 'Bitta odam → **is**.' },
      { k: 'dictation', say: "She's tired and hungry." },
    ],
  },
  {
    id: 'u2-l3-d1',
    title: 'Not or no?',
    titleUz: 'Inkor gaplar: not',
    goal: "**isn't / aren't / I'm not** shakllarini va qarama-qarshi sifatlarni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "*We ___ late.*", opts: ["isn't", "aren't", "amn't", 'not'], a: 1, why: "**we** → **aren't**." },
      { k: 'choice', q: '*I ___ hungry.*', opts: ['am not', 'is not', 'are not', "amn't"], a: 0, why: "**I** bilan **am not** (qisqasi *I'm not*)." },
      { k: 'match', pairs: [['dirty', 'iflos'], ['expensive', 'qimmat'], ['poor', "kambag'al"], ['old', 'qari'], ['short', "past bo'yli"]] },
      { k: 'fill', q: "My bag ___ expensive. It's cheap.", a: ["isn't", 'is not'], uz: 'Sumkam qimmat emas. U arzon.', why: "**it** → **isn't**." },
      { k: 'fill', q: 'They ___ rich. They are poor.', a: ["aren't", 'are not'], uz: 'Ular boy emas.', why: "**they** → **aren't**." },
      { k: 'listen', say: "She isn't young.", opts: ["She isn't young.", "She is young.", "He isn't young.", "She isn't old."], a: 0, why: "**isn't** — inkor." },
      { k: 'tf', q: "*She's not old* va *She isn't old* bir xil ma'noni beradi.", a: true, why: "Ikkalasi ham **is not** ning qisqa shakli." },
      { k: 'order', uz: 'Sumkam arzon emas.', words: ['My', 'bag', "isn't", 'cheap'], extra: ["aren't"], alt: [['My', 'bag', 'is', 'not', 'cheap'], ['My', "bag's", 'not', 'cheap']], why: "**not** — **is** dan keyin." },
      { k: 'fix', wrong: 'The table not clean.', a: ["The table isn't clean.", 'The table is not clean.', "The table's not clean."], hint: 'is yetishmayapti', why: '**is** tushib qolgan: *isn\'t* yoki *is not*.' },
      { k: 'translate', uz: "Ular kambag'al emas.", a: ["They aren't poor", "They're not poor", 'They are not poor'], why: "**They aren't poor.**" },
      { k: 'dictation', say: "My teacher isn't old." },
    ],
  },
  {
    id: 'u2-l4-d1',
    title: 'Questions with be',
    titleUz: "To be bilan savol va javob",
    goal: "**Are you…? Is she…?** savollarini tuzishni va **Yes, I am / No, he isn't** javoblarini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*___ they at school?*', opts: ['Is', 'Am', 'Are', 'Do'], a: 2, why: '**they** → **Are** gap boshiga chiqadi.' },
      { k: 'choice', q: '*___ Ali tired?*', opts: ['Are', 'Is', 'Am', 'Be'], a: 1, why: 'Ali = he → **Is**.' },
      { k: 'fill', q: '___ the bank open?', a: ['Is'], uz: 'Bank ochiqmi?', why: 'Bitta narsa → **Is**.' },
      { k: 'match', pairs: [['Are you hungry?', "No, I'm not."], ['Is the bank open?', 'Yes, it is.'], ['Are they tired?', "No, they aren't."], ['Is Tom at work?', 'Yes, he is.']] },
      { k: 'listen', say: 'Is he at home?', opts: ['Is he at home?', 'Is she at home?', 'He is at home.', 'Is he at work?'], a: 0, why: '**Is he** — savol.' },
      { k: 'tf', q: "*Is she at home? — Yes, she's.* — to'g'ri javob.", a: false, why: "Ha javobida qisqartirish yo'q: **Yes, she is.**" },
      { k: 'fill', q: "Is Laylo at the office? — No, ___ isn't.", a: ['she'], why: 'Laylo → **she**.' },
      { k: 'order', uz: 'Ali uydami?', words: ['Is', 'Ali', 'at', 'home'], extra: ['Are'], why: '**Is** boshiga chiqadi.' },
      { k: 'fix', wrong: 'You are at home?', a: ['Are you at home?'], hint: "So'zlar tartibini o'zgartiring", why: '**Are** gap boshiga chiqadi.' },
      { k: 'fix', wrong: 'Are you ready? Yes, I\'m.', a: ['Are you ready? Yes, I am.'], why: "Ha javobida **am** to'liq turadi." },
      { k: 'translate', uz: "Ular kutubxonadami?", a: ['Are they at the library'], why: '**Are they at the library?**' },
      { k: 'dictation', say: 'Is your friend at work?' },
    ],
  },
  {
    id: 'u2-l4-d2',
    title: 'Questions: tricky mix',
    titleUz: 'Savollar: qiyin aralash mashqlar',
    goal: "Qisqa javobda to'g'ri olmosh tanlashni va savoldagi tipik xatolarni tuzatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Are Tom and Sara at home?* — Yes, ___.', opts: ['they are', "they're", 'Tom and Sara are', 'we are'], a: 0, why: 'Ikki kishi → **they are**; ha javobida qisqartirilmaydi.' },
      { k: 'choice', q: "*Is the market open?* — No, ___.", opts: ["it isn't", "he isn't", "they aren't", "market isn't"], a: 0, why: 'Bozor — narsa: **it**.' },
      { k: 'choice', q: '*Am I late?* — Yes, ___.', opts: ['I am', 'you are', "you're", 'am you'], a: 1, why: 'Savol **I** bilan bo\'lsa, javobda **you**: *Yes, you are.*' },
      { k: 'tf', q: "*at the home* — to'g'ri ibora.", a: false, why: "Tayyor ibora: **at home** (the siz)." },
      { k: 'fill', q: 'Is Malika at work? — Yes, ___ is.', a: ['she'], why: 'Malika → **she**.' },
      { k: 'fill', q: "Are you and your friend tired? — No, ___ aren't.", a: ['we'], why: 'Sen + do\'sting = **we**.' },
      { k: 'fix', wrong: 'Is he at the work?', a: ['Is he at work?'], why: '**at work** — the siz.' },
      { k: 'fix', wrong: 'Is they at home?', a: ['Are they at home?'], why: '**they** bilan **Are** keladi.' },
      { k: 'fix', wrong: "Is the shop open? No, he isn't.", a: ["Is the shop open? No, it isn't."], why: "Do'kon — narsa: **it**." },
      { k: 'order', uz: "Yo'q, ular bog'da emas.", words: ['No', 'they', "aren't", 'in', 'the', 'park'], extra: ['at'], alt: [['No', "they're", 'not', 'in', 'the', 'park']], why: "Park uchun **in the park**." },
      { k: 'translate', uz: 'Sen va Ali kutubxonadamisizlar?', a: ['Are you and Ali at the library'], why: '**Are you and Ali at the library?**' },
      { k: 'translate', uz: "Yo'q, u uyda emas (ayol).", a: ["No, she isn't at home", "No, she's not at home", 'No, she is not at home', "No she isn't at home", "No she's not at home", 'No she is not at home'], why: "**She isn't at home.**" },
    ],
  },
  {
    id: 'u2-l5-d1',
    title: 'A / an and plurals',
    titleUz: "A / an va ko'plik",
    goal: "**a / an** ni tovushga qarab tanlashni va ko'plik shakllarini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "*It's ___ egg.*", opts: ['a', 'an', '—'], a: 1, why: '*egg* unli tovush bilan boshlanadi → **an**.' },
      { k: 'choice', q: "*She's ___ engineer.*", opts: ['a', 'an', '—'], a: 1, why: '*engineer* unli bilan boshlanadi → **an**.' },
      { k: 'choice', q: "*It's ___ big house.*", opts: ['an', 'a', '—'], a: 1, why: '*big* undosh bilan boshlanadi → **a**.' },
      { k: 'match', pairs: [['bus', 'buses'], ['city', 'cities'], ['wife', 'wives'], ['man', 'men'], ['leaf', 'leaves']] },
      { k: 'fill', q: 'one dish → two ___', a: ['dishes'], why: '**-sh** → **-es**.' },
      { k: 'fill', q: 'one boy → three ___', a: ['boys'], why: 'Unli + y (*oy*) → faqat **-s**.' },
      { k: 'fill', q: 'one woman → two ___', a: ['women'], why: "Noto'g'ri ko'plik: woman → **women**." },
      { k: 'listen', say: 'three babies', opts: ['three baby', 'three babies', 'three boys', 'three buses'], a: 1, why: 'baby → **babies**.' },
      { k: 'tf', q: "*two cat* ham, *two cats* ham to'g'ri.", a: false, why: "Son 1 dan katta bo'lsa ot ko'plikda: **two cats**." },
      { k: 'order', uz: 'Qutilar katta.', words: ['The', 'boxes', 'are', 'big'], extra: ['is', 'boxs'], why: 'Ko\'plik → **are**; box → **boxes**.' },
      { k: 'translate', uz: 'uchta shahar', a: ['three cities', '3 cities'], why: 'city → **cities**.' },
      { k: 'dictation', say: "She's an old woman." },
    ],
  },
];

drills.push({
  id: 'u2-l5-d2',
  title: 'A / an and plurals: tricky mix',
  titleUz: "A / an va ko'plik: qiyin aralash mashqlar",
  goal: "Tovushga qarab **a / an** tanlash va ko'plikdagi tipik xatolarni tuzatishni mashq qilasiz.",
  exercises: [
    { k: 'choice', q: 'Qaysi gap **to\'g\'ri**?', opts: ["It's a orange bus.", "It's an orange bus.", "It's an bus.", "It's a oranges bus."], a: 1, why: '*orange* unli bilan boshlanadi → **an orange bus**.' },
    { k: 'choice', q: "Qaysi ko'plik **to'g'ri**?", opts: ['two childs', 'two children', 'two child', 'two childrens'], a: 1, why: 'child → **children**.' },
    { k: 'choice', q: '**cats** so\'zidagi **-s** qanday o\'qiladi?', say: 'cats', opts: ['/s/', '/z/', '/ɪz/'], a: 0, why: '*t* ovozsiz tovush → **/s/**.' },
    { k: 'tf', q: '*a university* — to\'g\'ri, chunki *u* "yu" deb o\'qiladi.', a: true, why: '"yu" — undosh tovush, shuning uchun **a**.' },
    { k: 'fill', q: 'one wife → two ___', a: ['wives'], why: '**-fe** → **-ves**.' },
    { k: 'fill', q: 'one foot → two ___', a: ['feet'], why: "Noto'g'ri ko'plik: foot → **feet**." },
    { k: 'fix', wrong: "She's teacher.", a: ["She's a teacher.", 'She is a teacher.'], hint: 'Artikl yetishmayapti', why: 'Bitta kasb egasi oldidan **a** kerak.' },
    { k: 'fix', wrong: 'Three boy are in the park.', a: ['Three boys are in the park.'], why: "Son 1 dan katta → ot ko'plikda: **boys**." },
    { k: 'fix', wrong: 'Two peoples are here.', a: ['Two people are here.'], why: '**people** — o\'zi ko\'plik, -s qo\'shilmaydi.' },
    { k: 'fix', wrong: 'He is an university student.', a: ['He is a university student.', "He's a university student."], why: '*university* — "yu" bilan boshlanadi → **a**.' },
    { k: 'translate', uz: 'Ular eski soatlar.', a: ['They are old watches', "They're old watches"], why: 'watch → **watches**; ko\'plikda **a** yo\'q.' },
    { k: 'order', uz: "Bu go'zal shahar.", words: ['It', 'is', 'a', 'beautiful', 'city'], extra: ['an'], alt: [["It's", 'a', 'beautiful', 'city']], why: '*beautiful* undosh bilan boshlanadi → **a**.' },
  ],
});
