import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Navbar } from '@/components/Navbar';
import { SEOHead } from '@/components/SEOHead';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { teacherApi, typeName, type AssessmentType, type Settings } from '@/lib/teacher';
import { toast } from 'sonner';
import { ArrowLeft, Clock, Save, Send, RotateCcw, CheckCircle2 } from 'lucide-react';

type Q={index:number;text:string;options:{index:number;text:string}[];topic?:string};
type Run={id:string;title:string;type:AssessmentType;description:string;prompt:string;settings:Settings;
  questions:Q[];attempt:{id:string;number:number;startedAt:string;submittedAt:string|null;answers:Record<string,number>;essay:string;gradeStatus:string}};
type Result={id:string;number:number;submittedAt:string|null;gradeStatus:string;score:number|null;
  essay:string;result:Record<string,unknown>|null;questionReview:{text:string;selected:number|null;correct?:number;options:string[];explanation?:string}[]|null;resultAvailable:boolean;answersAvailable:boolean};
export default function TeacherRunner(){const {id}=useParams();const [test,setTest]=useState<Run|null>(null);const [result,setResult]=useState<Result|null>(null);const [answers,setAnswers]=useState<Record<string,number>>({});const [essay,setEssay]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [time,setTime]=useState(Date.now());const [saveState,setSaveState]=useState('Saved');const first=useRef(true);
  const autoSubmitted=useRef(false);
  useEffect(()=>{if(!id)return;void teacherApi<{test:Run;result:Result|null}>('attempt',{id}).then(r=>{
    setTest(r.test);setResult(r.result);
    const local=localStorage.getItem(`scorify:teacher-attempt:${id}`);
    let saved:{answers?:Record<string,number>;essay?:string}|null=null;
    try { if(local)saved=JSON.parse(local); } catch { localStorage.removeItem(`scorify:teacher-attempt:${id}`); }
    setAnswers(saved?.answers??r.test.attempt.answers??{});setEssay(saved?.essay??r.test.attempt.essay??'');
    if(r.test.attempt.submittedAt)localStorage.removeItem(`scorify:teacher-attempt:${id}`);
  }).catch(e=>toast.error(e instanceof Error?e.message:'Test unavailable')).finally(()=>setLoading(false));},[id]);
  useEffect(()=>{const timer=setInterval(()=>setTime(Date.now()),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(first.current){first.current=false;return;}if(!test||test.attempt.submittedAt)return;
    localStorage.setItem(`scorify:teacher-attempt:${test.attempt.id}`,JSON.stringify({answers,essay}));
    setSaveState('Saving…');const timer=setTimeout(async()=>{try{await teacherApi('save',{id:test.attempt.id,answers,essay});setSaveState('Saved');}catch{setSaveState('Saved on this device — check connection');}},500);return()=>clearTimeout(timer);},[answers,essay,test?.attempt.id]);
  const remaining=test?Math.max(0,Math.floor((Date.parse(test.attempt.startedAt)+(test.settings?.timeLimit??30)*60000-time)/1000)):0;
  useEffect(()=>{if(!test||test.attempt.submittedAt||remaining>0||autoSubmitted.current)return;autoSubmitted.current=true;
    void teacherApi<{result:Result}>('submit',{id:test.attempt.id,answers,essay}).then(r=>{setResult(r.result);setTest(t=>t?{...t,attempt:{...t.attempt,submittedAt:new Date().toISOString()}}:t);localStorage.removeItem(`scorify:teacher-attempt:${test.attempt.id}`);if(test.type!=='grammar')void grade();})
      .catch(()=>toast.error('Time is up. Saved work could not be submitted automatically.'));},[remaining,test?.attempt.id,test?.attempt.submittedAt]);
  const words=essay.trim().split(/\s+/).filter(Boolean).length;
  const submit=async()=>{if(!test)return;if(test.type==='grammar'&&Object.keys(answers).length!==test.questions.length){toast.error('Answer every question before submitting');return;}if(test.type!=='grammar'&&essay.trim().length<50){toast.error('Write at least 50 characters');return;}if(!window.confirm('Submit this attempt? You cannot edit it afterward.'))return;setBusy(true);try{const r=await teacherApi<{result:Result}>('submit',{id:test.attempt.id,answers,essay});setResult(r.result);setTest(t=>t?{...t,attempt:{...t.attempt,submittedAt:new Date().toISOString()}}:t);localStorage.removeItem(`scorify:teacher-attempt:${test.attempt.id}`);toast.success('Submitted successfully');if(test.type!=='grammar')await grade();}catch(e){toast.error(e instanceof Error?e.message:'Submission failed');}finally{setBusy(false);}};
  const grade=async()=>{if(!id)return;setBusy(true);try{const r=await teacherApi<{result?:Result;pending?:boolean}>('grade',{id});if(r.result)setResult(r.result);if(r.pending)toast.message('Grading is already in progress. Check again shortly.');}catch(e){toast.error(e instanceof Error?e.message:'Grading failed. Your essay is saved; retry when ready.');}finally{setBusy(false);}};
  const check=async()=>{if(!id)return;try{const r=await teacherApi<{test:Run;result:Result|null}>('attempt',{id});setResult(r.result);}catch(e){toast.error(e instanceof Error?e.message:'Could not refresh');}};
  if(loading)return <div className="min-h-screen bg-background"><Navbar/><main className="pt-24 text-center">Loading assessment…</main></div>;
  if(!test)return <div className="min-h-screen bg-background"><Navbar/><main className="pt-24 max-w-3xl mx-auto px-4"><p>Assessment unavailable.</p><Link to="/my-tests" className="text-primary">My Tests</Link></main></div>;
  const done=!!test.attempt.submittedAt;
  return <div className="min-h-screen bg-background pb-28"><SEOHead title={test.title} description="Teacher assessment" path={`/my-tests/${id}`} noindex/><Navbar/>
    <main className="max-w-4xl mx-auto px-4 sm:px-6 pt-24 pb-12"><Link to="/my-tests" className="text-sm text-muted-foreground hover:text-primary flex gap-2 items-center"><ArrowLeft className="w-4 h-4"/>My Tests</Link>
      <header className="mt-5 mb-6"><p className="text-primary text-sm font-semibold">{typeName[test.type]} · Attempt {test.attempt.number}</p><h1 className="text-3xl font-bold mt-2">{test.title}</h1><p className="text-sm text-muted-foreground mt-2 whitespace-pre-wrap">{test.description}</p></header>
      {!done&&<div className="sticky top-16 z-30 glass-card p-3 mb-6 flex justify-between gap-3 items-center"><span className="flex items-center gap-2 text-sm"><Clock className="w-4 h-4 text-primary"/><strong className={remaining<60?'text-destructive':''}>{Math.floor(remaining/60).toString().padStart(2,'0')}:{(remaining%60).toString().padStart(2,'0')}</strong></span><span className="text-xs text-muted-foreground flex items-center gap-1"><Save className="w-3 h-3"/>{saveState}</span></div>}
      {done?<section className="glass-card p-5 sm:p-8"><div className="w-12 h-12 rounded-xl bg-primary/10 text-primary grid place-items-center"><CheckCircle2/></div><h2 className="text-2xl font-bold mt-4">Assessment submitted</h2>{result?.resultAvailable?<><p className="text-lg mt-3">{result.score!=null?`${test.type==='grammar'?'Score':'IELTS Band'}: ${result.score}${test.type==='grammar'?'%':''}`:'Result pending'}</p>{result.result&&test.type!=='grammar'&&<div className="grid sm:grid-cols-2 gap-3 mt-5">{['taskAchievement','coherenceCohesion','lexicalResource','grammaticalRange'].map(k=>{const c=result.result?.[k] as {score:number;feedback:string}|undefined;return c&&<div className="rounded-xl border p-4" key={k}><h3 className="font-semibold capitalize">{k.replace(/([A-Z])/g,' $1')} · {c.score}</h3><p className="text-sm text-muted-foreground mt-2">{c.feedback}</p></div>;})}</div>}{result.questionReview?.map((q,i)=><div className="border-t mt-4 pt-4" key={i}><p className="font-medium">{i+1}. {q.text}</p><p className="text-sm mt-1">Your answer: {q.selected==null?'Unanswered':q.options[q.selected]}</p>{q.correct!=null&&<p className="text-sm text-primary">Correct answer: {q.options[q.correct]} {q.explanation&&`· ${q.explanation}`}</p>}</div>)}</>:<p className="text-sm text-muted-foreground mt-3">Results are hidden until your teacher releases them.</p>}
        {test.type!=='grammar'&&result?.gradeStatus!=='graded'&&<div className="mt-5 flex gap-2"><Button disabled={busy} onClick={grade}><RotateCcw className="w-4 h-4 mr-2"/>{busy?'Grading…':'Retry grading'}</Button><Button variant="outline" onClick={check}>Check status</Button></div>}
      </section>:<><p className="text-sm text-muted-foreground mb-5">Your progress is saved as you work. Refreshing the page does not reset your timer.</p>{test.type==='grammar'?<div className="space-y-4">{test.questions.map((q,i)=><section className="glass-card p-5" key={q.index}><p className="text-xs text-primary font-semibold">QUESTION {i+1} OF {test.questions.length}</p><h2 className="font-semibold text-lg mt-2">{q.text}</h2><div className="grid sm:grid-cols-2 gap-2 mt-4">{q.options.map(o=><button type="button" key={o.index} onClick={()=>setAnswers(a=>({...a,[q.index]:o.index}))} className={`text-left rounded-xl border p-3 transition-colors ${answers[String(q.index)]===o.index?'border-primary bg-primary/10':'hover:border-primary/40'}`}>{o.text}</button>)}</div></section>)}</div>:<section className="glass-card p-5 sm:p-7"><p className="text-sm font-semibold text-primary">Writing prompt</p><p className="whitespace-pre-wrap text-lg mt-3">{test.prompt}</p><div className="border-t mt-6 pt-5"><Textarea rows={18} aria-label="Your essay" placeholder="Write your response here…" value={essay} onChange={e=>setEssay(e.target.value)} className="min-h-[320px]"/><p className="text-sm text-muted-foreground mt-2">{words} words · recommended {test.type==='writing_task_1'?150:250}+</p></div></section>}
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 mt-6"><p className="text-sm text-muted-foreground">{test.type==='grammar'?`${Object.keys(answers).length} / ${test.questions.length} answered`:`${words} words written`}</p><Button size="lg" disabled={busy||remaining===0} onClick={submit}><Send className="w-4 h-4 mr-2"/>{busy?'Submitting…':'Submit assessment'}</Button></div>{remaining===0&&<p className="text-destructive text-sm mt-3">Time is up. Your saved work remains available to your teacher.</p>}</>}
    </main></div>;
}
