import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: "u5-l3-d1",
    title: "Past Simple: -ed",
    titleUz: "Past Simple: -ed ni to'g'ri yozing",
    goal: "To'g'ri fe'llarning o'tgan zamon shaklini (studied, stopped, played) xatosiz yozishni mashq qilasiz.",
    exercises: [
      { k: "choice", q: "Yesterday we ___ football in the yard.", opts: ["play", "plays", "played", "playing"], a: 2, why: "**yesterday** — o'tgan zamon: **played**. Hamma shaxs uchun bir xil." },
      { k: "match", pairs: [["study", "studied"], ["stop", "stopped"], ["arrive", "arrived"], ["play", "played"], ["plan", "planned"]] },
      { k: "listen", say: "She cleaned the kitchen.", opts: ["She cleans the kitchen.", "She cleaned the kitchen.", "She closed the kitchen."], a: 1, why: "\"klind\" — o'tgan zamon: **cleaned**." },
      { k: "choice", q: "**watched** — -ed qanday o'qiladi?", say: "watched", opts: ["/t/", "/d/", "/ɪd/"], a: 0, why: "*watch* **ch** (jarangsiz) bilan tugaydi → **/t/**: \"vochT\"." },
      { k: "fill", q: "Last year she ___ English at university. (study)", a: ["studied"], why: "undosh + **y** → **ied**: *studied*." },
      { k: "fill", q: "The bus ___ at the corner. (stop)", a: ["stopped"], why: "Qisqa fe'l: undosh + unli + undosh → **p** ikkilanadi: *stopped*." },
      { k: "choice", q: "Qaysi yozilish to'g'ri?", opts: ["stoped", "stopped", "stopt", "stoppped"], a: 1, why: "*stop* → **stopped** (**p** ikkilanadi)." },
      { k: "tf", q: "**She playeds tennis yesterday.** — to'g'ri gap.", a: false, why: "**-ed** ga yana **-s** qo'shilmaydi: *She **played** tennis.*" },
      { k: "fix", wrong: "She was worked late last night.", a: ["She worked late last night."], hint: "was kerakmi?", why: "Harakat uchun **was** kerak emas: *She **worked**.*" },
      { k: "fix", wrong: "My brother studyed English last year.", a: ["My brother studied English last year."], hint: "-ed imlosi", why: "undosh + **y** → **ied**: *studied*, **studyed** emas." },
      { k: "order", uz: "Ular kecha uyda qolishdi.", words: ["They", "stayed", "at", "home", "yesterday"], extra: ["stay", "were"], why: "Harakat uchun **stayed** — **were** kerak emas." },
      { k: "translate", uz: "Mening do'stim ikki kun oldin yetib keldi.", a: ["My friend arrived two days ago", "My friend arrived 2 days ago", "A friend of mine arrived two days ago", "My friend arrived two days before"], why: "**arrive** **e** bilan tugaydi → faqat **+d**: *arrived*." },
    ],
  },
  {
    id: "u5-l4-d1",
    title: "Irregular verbs: go, come, take",
    titleUz: "Noto'g'ri fe'llar: went, came, took",
    goal: "Eng muhim noto'g'ri fe'llarning o'tgan zamon shaklini (went, came, took, saw, made) tez eslab qolasiz.",
    exercises: [
      { k: "match", pairs: [["go", "went"], ["come", "came"], ["take", "took"], ["see", "saw"], ["make", "made"], ["say", "said"]] },
      { k: "listen", say: "She came home late.", opts: ["She called home late.", "She comes home late.", "She came home late."], a: 2, why: "\"keym\" — **came**." },
      { k: "choice", q: "Yesterday I ___ to the market.", opts: ["goed", "go", "went", "wented"], a: 2, why: "**go → went**. *goed* degan so'z yo'q." },
      { k: "fill", q: "We ___ breakfast at eight o'clock. (have)", a: ["had"], why: "**have → had**." },
      { k: "fill", q: "He ___ his homework after school. (do)", a: ["did"], why: "**do → did** (uy vazifasi — **do** bilan)." },
      { k: "choice", q: "\"Kecha men choy damladim.\"", opts: ["I make tea yesterday.", "I maked tea yesterday.", "I made tea yesterday.", "I did tea yesterday."], a: 2, why: "Choy va ovqat — **make** bilan: **made** tea." },
      { k: "tf", q: "**I goed to school yesterday.** — to'g'ri gap.", a: false, why: "**go → went**: *I **went** to school.*" },
      { k: "fix", wrong: "I went to home at six.", a: ["I went home at six."], hint: "home oldidan to kerakmi?", why: "**home** oldidan **to** qo'yilmaydi: *went **home***." },
      { k: "fix", wrong: "She comed to my house yesterday.", a: ["She came to my house yesterday."], hint: "come ning o'tgan shakli", why: "**come → came**; **comed** degan so'z yo'q." },
      { k: "order", uz: "Men bekatda do'stimni ko'rdim.", words: ["I", "saw", "my", "friend", "at", "the", "bus", "stop"], extra: ["see", "seed"], why: "**see → saw**." },
      { k: "dictation", say: "I got up at seven and had breakfast." },
      { k: "translate", uz: "Men kecha uyga kech keldim.", a: ["I came home late yesterday", "I got home late yesterday", "Yesterday I came home late", "Yesterday I got home late", "Yesterday, I came home late", "Yesterday, I got home late"], why: "**come → came**, **home** oldidan **to** yo'q." },
    ],
  },
  {
    id: "u5-l4-d2",
    title: "Irregular verbs: mixed",
    titleUz: "Noto'g'ri fe'llar: aralash mashq",
    goal: "Barcha o'rgangan noto'g'ri fe'llarni aralash holda ishlatib, tipik xatolarni topasiz va tuzatasiz.",
    exercises: [
      { k: "match", pairs: [["came", "keldi"], ["went", "bordi"], ["saw", "ko'rdi"], ["said", "dedi"], ["made", "tayyorladi"], ["had", "ega edi; yedi"]] },
      { k: "listen", say: "We took a taxi.", opts: ["We took a taxi.", "We make a taxi.", "We took two taxis."], a: 0, why: "\"tuk\" — **took**, birlikda: *a taxi*." },
      { k: "choice", q: "They ___ at the party last night.", opts: ["was", "were", "are", "did"], a: 1, why: "**they** → **were**." },
      { k: "tf", q: "**I was went to the bank.** — to'g'ri gap.", a: false, why: "**was** kerak emas: *I **went** to the bank.*" },
      { k: "fill", q: "He ___ up late and missed the bus. (get)", a: ["got"], why: "**get up → got up**." },
      { k: "fill", q: "I ___ a lot of photos in Samarkand. (take)", a: ["took"], why: "**take → took** (\"tuk\")." },
      { k: "choice", q: "Qaysi gap **xato**?", opts: ["We saw a film.", "He said hello.", "They comed home.", "I had lunch."], a: 2, why: "**come → came**: *They **came** home.*" },
      { k: "fix", wrong: "We seed a nice film last night.", a: ["We saw a nice film last night."], hint: "see ning o'tgan shakli", why: "**see → saw**; **seed** degan so'z yo'q." },
      { k: "fix", wrong: "I made my homework yesterday.", a: ["I did my homework yesterday."], hint: "do yoki make?", why: "Uy vazifasi — **do** bilan: *I **did** my homework*." },
      { k: "fix", wrong: "He haved breakfast at seven.", a: ["He had breakfast at seven."], hint: "have ning o'tgan shakli", why: "**have → had**; **haved** emas." },
      { k: "order", uz: "Biz kecha soat yettida turdik va nonushta qildik.", words: ["We", "got", "up", "at", "seven", "and", "had", "breakfast", "yesterday"], extra: ["get", "have"], alt: [["Yesterday", "we", "got", "up", "at", "seven", "and", "had", "breakfast"]], why: "**got up** va **had breakfast** — ikkalasi ham V2." },
      { k: "translate", uz: "Kecha ishga avtobusda bordim.", a: ["I took the bus to work yesterday", "Yesterday I took the bus to work", "Yesterday, I took the bus to work", "I went to work by bus yesterday", "Yesterday I went to work by bus", "Yesterday, I went to work by bus"], why: "**take the bus → took the bus**; yoki **went … by bus**." },
    ],
  },
  {
    id: "u5-l5-d1",
    title: "didn't and Did…?",
    titleUz: "didn't va Did…? — fe'l V1 da qoladi",
    goal: "O'tgan zamonda inkor va savol tuzishda didn't / did dan keyin fe'lni asosiy shaklda qoldirishni mashq qilasiz.",
    exercises: [
      { k: "match", pairs: [["eat", "ate"], ["drink", "drank"], ["buy", "bought"], ["write", "wrote"], ["meet", "met"], ["find", "found"]] },
      { k: "listen", say: "Did you eat breakfast?", opts: ["Do you eat breakfast?", "Did you have breakfast?", "Did you eat breakfast?"], a: 2, why: "**Did you eat** — savol, fe'l **eat** (V1)." },
      { k: "fill", q: "Last night I ___ a long letter to my friend. (write)", a: ["wrote"], why: "**write → wrote** (\"rout\")." },
      { k: "fill", q: "He didn't ___ the answer. (know)", a: ["know"], why: "**didn't** dan keyin doim V1: *didn't **know***." },
      { k: "choice", q: "She ___ go to school yesterday. She was ill.", opts: ["didn't", "doesn't", "don't", "wasn't"], a: 0, why: "O'tgan zamon + harakat fe'li → **didn't** + V1." },
      { k: "choice", q: "What ___ you eat for lunch?", opts: ["do", "did", "ate", "does"], a: 1, why: "O'tgan zamon savoli: **did** + ega + **eat** (V1)." },
      { k: "tf", q: "**Where did she went yesterday?** — to'g'ri savol.", a: false, why: "**did** bor → fe'l V1: *Where did she **go**?*" },
      { k: "fix", wrong: "I didn't bought the tickets.", a: ["I didn't buy the tickets."], hint: "didn't dan keyin qaysi shakl?", why: "**didn't** + V1: *didn't **buy***." },
      { k: "fix", wrong: "Did they met your sister?", a: ["Did they meet your sister?"], hint: "Did dan keyin V1", why: "**Did** + ega + V1: *Did they **meet**…?*" },
      { k: "order", uz: "U kecha qahva ichmadi.", words: ["She", "didn't", "drink", "coffee", "yesterday"], extra: ["drank", "not"], why: "**didn't** + V1 (*drink*), **drank** emas." },
      { k: "order", uz: "Siz kecha kim bilan uchrashdingiz?", words: ["Who", "did", "you", "meet", "yesterday"], extra: ["met", "do"], why: "**did** + ega + V1: *did you **meet***." },
      { k: "translate", uz: "Siz kecha nima sotib oldingiz?", a: ["What did you buy yesterday", "Yesterday what did you buy", "Yesterday, what did you buy"], why: "Savol so'zi + **did** + ega + **buy** (V1)." },
    ],
  },
  {
    id: "u5-l6-d1",
    title: "be going to",
    titleUz: "be going to — rejalar",
    goal: "am / is / are + going to + V1 qolipini xatosiz ishlatib, reja va niyatlar haqida gapirasiz.",
    exercises: [
      { k: "match", pairs: [["ticket", "chipta"], ["suitcase", "chamadon"], ["passport", "pasport"], ["abroad", "chet elga, chet elda"], ["airport", "aeroport"], ["hotel", "mehmonxona"]] },
      { k: "choice", q: "My sister ___ going to travel abroad.", opts: ["am", "is", "are", "be"], a: 1, why: "**my sister** = she → **is** going to." },
      { k: "fill", q: "We ___ going to visit Bukhara next week.", a: ["are"], uz: "Kelasi hafta Buxoroga bormoqchimiz.", why: "**we** → **are** going to." },
      { k: "listen", say: "They are going to stay at a hotel.", opts: ["They stayed at a hotel.", "They are going to stay at a hotel.", "They aren't going to stay at a hotel."], a: 1, why: "**are going to stay** — reja, inkor emas." },
      { k: "choice", q: "Look! The baby is very sleepy. She ___ sleep.", opts: ["is going to", "are going to", "going to", "is go to"], a: 0, why: "Dalil ko'z oldimizda → **is going to** + V1." },
      { k: "tf", q: "**I'm going to visited my grandmother.** — to'g'ri gap.", a: false, why: "**going to** + V1: *I'm going to **visit***." },
      { k: "fix", wrong: "They going to go abroad next summer.", a: ["They are going to go abroad next summer.", "They're going to go abroad next summer."], hint: "are tushib qolgan", why: "**are** kerak: *They **are** going to go*." },
      { k: "fix", wrong: "Do you going to take a big suitcase?", a: ["Are you going to take a big suitcase?"], hint: "savolda qaysi fe'l?", why: "Savol **am / is / are** bilan: ***Are** you going to…?*" },
      { k: "fix", wrong: "We are going to visit Khiva in next week.", a: ["We are going to visit Khiva next week.", "We're going to visit Khiva next week."], hint: "next week oldidan", why: "**next week** oldidan **in** qo'yilmaydi." },
      { k: "fix", wrong: "She is going to buys a ticket.", a: ["She is going to buy a ticket."], hint: "going to dan keyin", why: "**going to** + V1, **-s** yo'q: *to **buy***." },
      { k: "order", uz: "Siz kelasi hafta nima qilmoqchisiz?", words: ["What", "are", "you", "going", "to", "do", "next", "week"], extra: ["is", "the"], why: "Savol so'zi + **are** + ega + **going to** + V1." },
      { k: "translate", uz: "Biz kelasi yoz chet elga bormoqchimiz.", a: ["We're going to go abroad next summer", "We are going to go abroad next summer", "We're going to travel abroad next summer", "We are going to travel abroad next summer", "Next summer we're going to go abroad", "Next summer we are going to go abroad", "Next summer we're going to travel abroad", "Next summer we are going to travel abroad"], why: "**are going to** + V1; **abroad** oldidan **to** yo'q." },
    ],
  },
  {
    id: "u5-l7-d1",
    title: "will or going to?",
    titleUz: "will yoki going to?",
    goal: "will va going to ni farqlaysiz: shu zahoti qaror, va'da va fikr uchun will; reja va dalil uchun going to.",
    exercises: [
      { k: "choice", q: "I think she ___ come tomorrow.", opts: ["will", "wills", "will to", "is will"], a: 0, why: "**will** + V1, hamma shaxs uchun bir xil." },
      { k: "listen", say: "She won't come tomorrow.", opts: ["She won't come tomorrow.", "She will come tomorrow.", "She didn't come yesterday."], a: 0, why: "\"wount\" — **won't** (kelmaydi)." },
      { k: "fill", q: "Wait here. I ___ be back in ten minutes.", a: ["will"], why: "Va'da → **will** + V1." },
      { k: "choice", q: "Tea or coffee? — I ___ have tea, please.", opts: ["'ll", "am going to", "having", "had"], a: 0, why: "Shu zahoti qaror → **I'll** (= I will)." },
      { k: "choice", q: "I've got two tickets for tomorrow. I ___ to the concert.", opts: ["am going to go", "will go", "go", "went"], a: 0, why: "Chiptalar bor — oldindan reja → **am going to go**." },
      { k: "choice", q: "Look! That boy is riding a bike without a helmet. He ___ fall!", opts: ["will fall", "is going to fall", "falls", "fell"], a: 1, why: "Dalil ko'z oldimizda → **is going to** + V1." },
      { k: "tf", q: "**Maybe he will come later.** — to'g'ri gap.", a: true, why: "**Maybe** + **will** + V1 — fikr, to'g'ri." },
      { k: "fix", wrong: "I will to call you tonight.", a: ["I will call you tonight.", "I'll call you tonight."], hint: "will dan keyin to kerakmi?", why: "**will** dan keyin **to** yo'q: *will **call***." },
      { k: "fix", wrong: "Do you will help me tomorrow?", a: ["Will you help me tomorrow?"], hint: "will o'zi savol yasaydi", why: "**do** kerak emas: ***Will** you help me?*" },
      { k: "fix", wrong: "She will goes home soon.", a: ["She will go home soon."], hint: "will dan keyin V1", why: "**will** dan keyin fe'l o'zgarmaydi: *will **go***." },
      { k: "order", uz: "Menimcha, ertaga yomg'ir yog'adi.", words: ["I", "think", "it", "will", "rain", "tomorrow"], extra: ["going", "rains"], why: "Fikr → **I think** + **will** + V1." },
      { k: "translate", uz: "Va'da beraman, hech kimga aytmayman.", a: ["I promise I won't tell anybody", "I promise I won't tell anyone", "I promise I will not tell anybody", "I promise I will not tell anyone", "I promise that I won't tell anybody", "I promise that I won't tell anyone"], why: "Va'da (inkor) → **won't** + V1." },
    ],
  },
  {
    id: "u5-l8-d1",
    title: "bigger, the biggest",
    titleUz: "Qiyoslash: -er / more / the best",
    goal: "Sifatlarning qiyosiy va orttirma darajasini to'g'ri yasaysiz: bigger, happier, more difficult, better, the worst.",
    exercises: [
      { k: "match", pairs: [["good", "better"], ["bad", "worse"], ["big", "bigger"], ["easy", "easier"], ["hot", "hotter"], ["nice", "nicer"]] },
      { k: "listen", say: "My brother is taller than me.", opts: ["My brother is the tallest of us.", "My brother is taller than me.", "My brother is shorter than me."], a: 1, why: "**taller than me** — qiyosiy daraja, **the** yo'q." },
      { k: "choice", q: "A train is ___ than a bus.", opts: ["fast", "faster", "fastest", "more fast"], a: 1, why: "Qisqa sifat + **-er** + **than**: *faster than*." },
      { k: "fill", q: "This bag is ___ than that one. (big)", a: ["bigger"], why: "Qisqa unli + undosh → **g** ikkilanadi: *bigger*." },
      { k: "fill", q: "My brother is ___ than me. (thin)", a: ["thinner"], why: "**thin** → **n** ikkilanadi: *thinner*." },
      { k: "choice", q: "This exercise is ___ than the last one.", opts: ["more difficult", "difficulter", "most difficult", "more difficulter"], a: 0, why: "Uzun sifat → **more difficult**." },
      { k: "choice", q: "It was the ___ film of the year.", opts: ["worse", "worst", "baddest", "most bad"], a: 1, why: "**bad – worse – the worst**." },
      { k: "tf", q: "**This phone is more cheaper than that one.** — to'g'ri gap.", a: false, why: "**more** va **-er** birga kelmaydi: *cheaper*." },
      { k: "fix", wrong: "She is more taller than me.", a: ["She is taller than me."], hint: "more kerakmi?", why: "Qisqa sifat: faqat **-er**, **more** kerak emas." },
      { k: "fix", wrong: "This is the most easy exercise.", a: ["This is the easiest exercise."], hint: "easy ning orttirma darajasi", why: "**easy** → **the easiest** (**y → i**)." },
      { k: "order", uz: "Bu telefon o'sha telefondan arzonroq.", words: ["This", "phone", "is", "cheaper", "than", "that", "phone"], extra: ["more", "cheap"], why: "**cheaper than** — **more** kerak emas." },
      { k: "translate", uz: "Mening opam mendan baxtliroq.", a: ["My sister is happier than me", "My sister is happier than I am", "My older sister is happier than me", "My older sister is happier than I am", "My elder sister is happier than me", "My elder sister is happier than I am"], why: "undosh + **y** → **ier**: *happier*, keyin **than**." },
    ],
  },
];
