import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u8-l2-d1',
    title: 'A few, a little or a lot of?',
    titleUz: 'A few, a little yoki a lot of?',
    goal: "Sanaladigan va sanalmaydigan otlar bilan **a few / a little / much / many / no** ni to'g'ri tanlashni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*There are ___ eggs in the fridge.*', opts: ['a little', 'a few', 'much'], a: 1, why: '**eggs** sanaladi (ko\'plik) → **a few eggs**.' },
      { k: 'choice', q: '*Add ___ sugar to my tea, please.*', opts: ['a few', 'a little', 'many'], a: 1, why: '**sugar** sanalmaydi → **a little sugar**.' },
      { k: 'match', pairs: [['a few', 'bir nechta'], ['a little', 'ozgina'], ['a lot of', "ko'p"], ['not much', "ko'p emas (sanalmaydigan)"], ['none', "umuman yo'q"]] },
      { k: 'fill', q: 'How ___ water is there in the bottle?', a: ['much'], uz: "Shishada qancha suv bor?", why: '**water** sanalmaydi → **how much**.' },
      { k: 'fill', q: "There isn't ___ milk. We need to buy some.", a: ['any'], uz: "Sut yo'q. Sotib olishimiz kerak.", why: "Inkor gapda **not any** (= *no*): *There isn't any milk.*" },
      { k: 'tf', q: "*There isn't no milk.* — to'g'ri gap.", a: false, why: "Bitta gapda **bitta inkor**: *There's no milk* yoki *There isn't any milk.*" },
      { k: 'listen', say: 'We have a little time.', opts: ['We have a little time.', 'We have no time.', 'We have a lot of time.'], a: 0, why: '**a little** — "ozgina".' },
      { k: 'order', uz: "Muzlatkichda bir nechta tuxum bor.", words: ['There', 'are', 'a', 'few', 'eggs', 'in', 'the', 'fridge'], extra: ['little'], why: '**eggs** sanaladi → **a few**.' },
      { k: 'fix', wrong: 'We have lot of potatoes.', a: ['We have a lot of potatoes.', 'We have lots of potatoes.'], hint: 'Bitta so\'z yetishmayapti', why: '**a lot of** — uchta so\'z; **a** tushib qolgan. (*lots of* da **a** yo\'q.)' },
      { k: 'fix', wrong: 'I have a few money.', a: ['I have a little money.'], hint: 'money sanalmaydi', why: '**money** sanalmaydi → **a little money**.' },
      { k: 'translate', uz: "Menda vaqt yo'q.", a: ['I have no time', "I don't have any time", "I haven't got any time", "I've got no time", "I don't have time"], why: "**no time** yoki **don't have any time** — ikki inkor emas." },
      { k: 'dictation', say: 'There is a little butter and a few eggs.' },
    ],
  },
  {
    id: 'u8-l2-d2',
    title: 'Quantity: tricky mix',
    titleUz: 'Miqdor: qiyin aralash mashqlar',
    goal: "**many / much / a few / a little / no** dagi tipik xatolarni topishni va tuzatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: 'Qaysi gap **to\'g\'ri**?', opts: ["We don't have no eggs.", 'We have no eggs.', 'We have no any eggs.', "We haven't no eggs."], a: 1, why: '**no** bilan fe\'l ijobiy: *We have no eggs.*' },
      { k: 'choice', q: '*How many ___ do we have?*', opts: ['rice', 'onions', 'milk'], a: 1, why: '**many** faqat sanaladigan ko\'plik ot bilan: *onions*.' },
      { k: 'choice', q: '*Not ___ people came to the party.*', opts: ['many', 'much', 'little'], a: 0, why: '**people** sanaladi → **not many**.' },
      { k: 'tf', q: '*a little minutes* — to\'g\'ri ibora.', a: false, why: '**minutes** sanaladi → **a few minutes**.' },
      { k: 'tf', q: '*money* inglizchada sanalmaydi, shuning uchun *a little money* deymiz.', a: true, why: 'Ha: **money** va **time** sanalmaydi.' },
      { k: 'fill', q: 'Can I have a ___ grapes, please?', a: ['few'], uz: "Bir nechta uzum olsam bo'ladimi?", why: '**grapes** — ko\'plik → **a few**.' },
      { k: 'fill', q: 'How ___ money do you have?', a: ['much'], uz: 'Sizda qancha pul bor?', why: '**money** sanalmaydi → **how much**.' },
      { k: 'fix', wrong: 'I have no any money.', a: ["I have no money.", "I don't have any money."], why: '**no** va **any** birga kelmaydi: *no money* yoki *not any money.*' },
      { k: 'fix', wrong: 'There are a little apples in the bag.', a: ['There are a few apples in the bag.'], why: '**apples** sanaladi → **a few**.' },
      { k: 'fix', wrong: 'How much eggs do we have?', a: ['How many eggs do we have?'], why: '**eggs** sanaladi → **how many**.' },
      { k: 'order', uz: "Bizda sut yo'q, lekin non ko'p.", words: ['We', 'have', 'no', 'milk', 'but', 'a', 'lot', 'of', 'bread'], extra: ['much'], why: '**no milk** (inkor so\'zsiz) va **a lot of bread**.' },
      { k: 'translate', uz: "Ko'p odam kelmadi.", a: ['Not many people came', "Many people didn't come"], why: '**people** sanaladi → **not many**.' },
    ],
  },
  {
    id: 'u8-l7-d1',
    title: 'Should and shouldn\'t',
    titleUz: 'Should va shouldn\'t',
    goal: "**should / shouldn't** + fe'lning boshlang'ich shakli bilan maslahat berish va savol tuzishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*You ___ drink more water.*', opts: ['should', 'should to', 'shoulds'], a: 0, why: '**should** + fe\'l, **to** va **-s** yo\'q.' },
      { k: 'choice', q: "*He ___ eat too much sugar.*", opts: ["shouldn't", "doesn't should", "don't should"], a: 0, why: "Inkor: **shouldn't** + fe'l (*do* kerak emas)." },
      { k: 'match', pairs: [["I feel sick.", 'You should see a doctor.'], ["I'm tired all the time.", 'You should go to bed early.'], ["I can't sleep.", "You shouldn't drink coffee at night."], ["I'm always hungry.", 'You should eat breakfast.']] },
      { k: 'fill', q: "You ___ skip breakfast. It's bad for you.", a: ["shouldn't", 'should not'], uz: "Nonushtani o'tkazib yubormasligingiz kerak.", why: "Zararli odat → **shouldn't**." },
      { k: 'fill', q: '___ I call the doctor?', a: ['Should'], uz: "Shifokorga qo'ng'iroq qilsammi?", why: 'Savolda **Should** gap boshiga chiqadi.' },
      { k: 'tf', q: '*She should to go to bed early.*', a: false, why: '**should** dan keyin **to** kelmaydi: *She should go…*' },
      { k: 'listen', say: 'You should eat more fruit.', opts: ["You shouldn't eat fruit.", 'You should eat more fruit.', 'You should drink more water.'], a: 1, why: '**should eat more fruit** — "ko\'proq meva yeyishing kerak".' },
      { k: 'order', uz: "Kechqurun kofe ichmasligingiz kerak.", words: ['You', "shouldn't", 'drink', 'coffee', 'in', 'the', 'evening'], extra: ['to', "don't"], alt: [['You', 'should', 'not', 'drink', 'coffee', 'in', 'the', 'evening']], why: "**shouldn't** + fe'lning boshlang'ich shakli." },
      { k: 'fix', wrong: 'Do I should call the doctor?', a: ['Should I call the doctor?'], hint: "So'zlar tartibini o'zgartiring", why: '**Do** kerak emas: *Should I…?*' },
      { k: 'fix', wrong: 'He should goes to bed early.', a: ['He should go to bed early.'], why: '**should** dan keyin fe\'l o\'zgarmaydi: **go**.' },
      { k: 'translate', uz: "Menimcha, sen ko'proq suv ichishing kerak.", a: ['I think you should drink more water'], why: '**I think you should…** — muloyim maslahat.' },
      { k: 'dictation', say: 'What should I eat for breakfast?' },
    ],
  },
  {
    id: 'u8-l8-d1',
    title: 'Better, the best, as… as',
    titleUz: 'Better, the best, as… as',
    goal: "**better / worse**, **the best … in** va **as … as / not as … as** ni qiyoslashda to'g'ri ishlatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*This plov is ___ than that one.*', opts: ['better', 'gooder', 'more good'], a: 0, why: '**good** → **better** (noto\'g\'ri shakl).' },
      { k: 'choice', q: "*It's the ___ plov in town.*", opts: ['best', 'better', 'most good'], a: 0, why: '**the best** — eng yaxshi.' },
      { k: 'choice', q: '*Ali is as tall ___ his brother.*', opts: ['than', 'as', 'that'], a: 1, why: '**as … as** — ikkinchi **as** ham shart.' },
      { k: 'match', pairs: [['better', 'yaxshiroq'], ['worse', 'battarroq'], ['the best', 'eng yaxshi'], ['as cheap as', 'xuddi shunday arzon'], ['not as fresh as', 'unchalik yangi emas']] },
      { k: 'fill', q: "Tom's pizza is good, but Sara's pizza is ___.", a: ['better'], uz: "Tomning pitsasi yaxshi, Saraniki esa yaxshiroq.", why: '**good** → **better**.' },
      { k: 'fill', q: 'Apples are not as expensive ___ meat.', a: ['as'], uz: "Olma go'shtchalik qimmat emas.", why: '**not as … as** — ikkinchi **as**.' },
      { k: 'tf', q: '*very cheaper* va *much cheaper* ikkalasi ham to\'g\'ri.', a: false, why: 'Qiyosiy daraja bilan **much / a bit** ishlatiladi, **very** emas.' },
      { k: 'order', uz: "Bu shaharning eng yaxshi restorani.", words: ['It', 'is', 'the', 'best', 'restaurant', 'in', 'town'], extra: ['of', 'better'], alt: [["It's", 'the', 'best', 'restaurant', 'in', 'town']], why: '**the best … in** + joy.' },
      { k: 'fix', wrong: 'This bread is more better than that bread.', a: ['This bread is better than that bread.'], why: '**better** o\'zi qiyosiy daraja — **more** kerak emas.' },
      { k: 'fix', wrong: 'My cake is as sweeter as yours.', a: ['My cake is as sweet as yours.'], why: '**as … as** orasida sifat oddiy shaklda: **sweet**.' },
      { k: 'translate', uz: "Bozor supermarketdan ancha arzonroq.", a: ['The bazaar is much cheaper than the supermarket', 'The market is much cheaper than the supermarket', 'The bazaar is a lot cheaper than the supermarket', 'The market is a lot cheaper than the supermarket'], why: '**much cheaper than** — ancha arzonroq.' },
      { k: 'dictation', say: 'This plov is not as spicy as that one.' },
    ],
  },
];
