import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u9-l2-d1',
    title: 'Irregular verbs: slept, told, brought',
    titleUz: "Noto'g'ri fe'llar: slept, told, brought",
    goal: "**slept, felt, left, spent, sent, lost, brought, taught, told, heard** shakllarini va **tell / say** farqini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*I ___ well last night.*', opts: ['sleeped', 'slept', 'slepted'], a: 1, why: 'sleep → **slept** (noto\'g\'ri fe\'l).' },
      { k: 'choice', q: '*She ___ me the news.*', opts: ['said', 'told', 'speak'], a: 1, why: '**tell** + kimga: *told me*. **say** dan keyin "kimga" to\'g\'ridan-to\'g\'ri kelmaydi.' },
      { k: 'match', pairs: [['lose', 'lost'], ['bring', 'brought'], ['teach', 'taught'], ['hear', 'heard'], ['spend', 'spent']] },
      { k: 'fill', q: 'He ___ a message to his mother. (send)', a: ['sent'], uz: 'U onasiga xabar yubordi.', why: 'send → **sent**.' },
      { k: 'fill', q: 'We ___ a noise in the night. (hear)', a: ['heard'], uz: 'Biz tunda shovqin eshitdik.', why: 'hear → **heard**.' },
      { k: 'tf', q: '*She said me the answer.* — to\'g\'ri gap.', a: false, why: '**told me** kerak: *She told me the answer.*' },
      { k: 'listen', say: 'I lost my bag at school.', opts: ['I left my bag at school.', 'I lost my bag at school.', 'I felt bad at school.'], a: 1, why: '**lost** — yo\'qotdim.' },
      { k: 'order', uz: "Do'stim menga kitob olib keldi.", words: ['My', 'friend', 'brought', 'me', 'a', 'book'], extra: ['took', 'bringed'], why: 'bring → **brought**.' },
      { k: 'fix', wrong: 'He teached us English last year.', a: ['He taught us English last year.'], why: 'teach → **taught** (*teached* yo\'q).' },
      { k: 'fix', wrong: 'She said me a secret.', a: ['She told me a secret.'], why: '**tell** + kimga → **told me**.' },
      { k: 'fix', wrong: "I didn't heard the phone.", a: ["I didn't hear the phone.", 'I did not hear the phone.'], why: "**didn't** dan keyin fe'l **boshlang'ich** shaklda: *hear*." },
      { k: 'translate', uz: "U kecha telefonini yo'qotdi.", a: ['She lost her phone yesterday', 'He lost his phone yesterday'], why: 'lose → **lost**.' },
    ],
  },
  {
    id: 'u9-l3-d1',
    title: 'Where did you go?',
    titleUz: "O'tgan zamonda savollar",
    goal: "**Where did you go? What did you do? How was it?** kabi savollarni **did + V1** va **was / were** bilan tuzishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Where ___ you go yesterday?*', opts: ['did', 'do', 'were'], a: 0, why: 'Savol so\'zi + **did** + ega + fe\'l: *Where did you go?*' },
      { k: 'choice', q: '*Where ___ you last night?*', opts: ['did', 'were', 'was'], a: 1, why: '**be** fe\'li bilan **did** kerak emas: *Where were you?*' },
      { k: 'choice', q: '*How ___ the film?*', opts: ['was', 'did', 'were'], a: 0, why: 'Film = bitta narsa → **was**.' },
      { k: 'match', pairs: [['Where did you go?', 'To the market.'], ['Who did you meet?', 'My old friend.'], ['What did you eat?', 'Plov.'], ['How was the party?', 'It was great.'], ['When did you come?', 'At six.']] },
      { k: 'fill', q: 'Where did you ___ your bag? (buy)', a: ['buy'], uz: 'Sumkangni qayerdan sotib olding?', why: '**did** dan keyin fe\'l boshlang\'ich shaklda: **buy**.' },
      { k: 'fill', q: 'Why ___ he late yesterday?', a: ['was'], uz: 'U kecha nega kech qoldi?', why: 'he + **be** → **was** (*did* emas).' },
      { k: 'tf', q: '*Where did you went?* — to\'g\'ri gap.', a: false, why: '**did** dan keyin **go**: *Where did you go?*' },
      { k: 'listen', say: 'Who did you meet?', opts: ['Who did you meet?', 'Who met you?', 'Where did you meet?'], a: 0, why: '**Who did you meet?** — kimni uchratding?' },
      { k: 'order', uz: 'Kecha kechqurun nima qilding?', words: ['What', 'did', 'you', 'do', 'last', 'night'], extra: ['does', 'done'], why: 'Savol so\'zi + **did** + ega + **do**.' },
      { k: 'fix', wrong: 'Where you went on Saturday?', a: ['Where did you go on Saturday?'], why: '**did** yetishmayapti va fe\'l boshlang\'ich shaklda: *go*.' },
      { k: 'fix', wrong: 'What did she bought?', a: ['What did she buy?'], why: '**did** dan keyin **buy**, *bought* emas.' },
      { k: 'translate', uz: 'Dam olish kunida qayerga bording?', a: ['Where did you go at the weekend', 'Where did you go on the weekend', 'Where did you go over the weekend', 'Where did you go on the weekend'], why: '**Where did you go…?** — *went* emas.' },
    ],
  },
  {
    id: 'u9-l4-d1',
    title: 'There was / were, could / couldn\'t',
    titleUz: 'There was / were va could / couldn\'t',
    goal: "O'tmishda **there was / were**, **was there…?** va **could / couldn't** ni to'g'ri ishlatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*There ___ a big park near my house.*', opts: ['was', 'were', 'is'], a: 0, why: 'Bitta narsa, o\'tgan zamon → **was**.' },
      { k: 'choice', q: '*There ___ many people at the concert.*', opts: ['was', 'were', 'are'], a: 1, why: '**many people** ko\'plik, o\'tgan zamon → **were**.' },
      { k: 'choice', q: '*I ___ swim when I was five.*', opts: ['could', 'can', 'did'], a: 0, why: 'O\'tmishdagi qobiliyat → **could**.' },
      { k: 'match', pairs: [["There wasn't any milk.", "Sut yo'q edi."], ['There were two shops.', 'Ikkita dokon bor edi.'], ["I couldn't sleep.", 'Uxlay olmadim.'], ['Was there a bank?', 'Bank bor edimi?']] },
      { k: 'fill', q: '___ there a bank in your street?', a: ['Was'], uz: "Ko'changizda bank bor edimi?", why: 'Bitta narsa, savol → **Was there…?**' },
      { k: 'fill', q: "I ___ sleep last night. It was too noisy.", a: ["couldn't", 'could not'], uz: "Kecha uxlay olmadim. Juda shovqinli edi.", why: "Qila olmadim → **couldn't** + fe'l." },
      { k: 'tf', q: '*In our village had a school.* — to\'g\'ri gap.', a: false, why: 'Inglizchada **There was a school…** deyiladi.' },
      { k: 'listen', say: "There weren't any shops.", opts: ["There weren't any shops.", "There aren't any shops.", "There wasn't any shop."], a: 0, why: "**weren't** — ko'plik, o'tgan zamon." },
      { k: 'order', uz: 'Uyimiz yonida katta bozor bor edi.', words: ['There', 'was', 'a', 'big', 'market', 'near', 'our', 'house'], extra: ['were', 'is'], why: 'Bitta narsa → **There was**.' },
      { k: 'fix', wrong: 'It was many people at the concert.', a: ['There were many people at the concert.'], why: '**There were** + ko\'plik ot, *It was* emas.' },
      { k: 'fix', wrong: 'He could to read at four.', a: ['He could read at four.'], why: '**could** dan keyin **to** kelmaydi.' },
      { k: 'translate', uz: 'U kecha ishga kela olmadi.', a: ["He couldn't come to work yesterday", "She couldn't come to work yesterday", 'He could not come to work yesterday', 'She could not come to work yesterday'], why: "**couldn't** + fe'lning boshlang'ich shakli." },
    ],
  },
  {
    id: 'u9-l8-d1',
    title: 'Irregular verbs: won, broke, caught',
    titleUz: "Noto'g'ri fe'llar: won, broke, caught",
    goal: "**swam, ran, began, sang, won, broke, forgot, wore, caught, fell** shakllarini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*She ___ the race.*', opts: ['winned', 'won', 'wan'], a: 1, why: 'win → **won**.' },
      { k: 'choice', q: '*He ___ his arm last week.*', opts: ['breaked', 'broke', 'broken'], a: 1, why: 'break → **broke**.' },
      { k: 'match', pairs: [['swim', 'swam'], ['run', 'ran'], ['begin', 'began'], ['sing', 'sang'], ['catch', 'caught']] },
      { k: 'fill', q: 'Yesterday we ___ the last bus. (catch)', a: ['caught'], uz: 'Kecha oxirgi avtobusga ulgurdik.', why: 'catch → **caught**.' },
      { k: 'fill', q: 'She ___ a red dress at the party. (wear)', a: ['wore'], uz: "U ziyofatda qizil ko'ylak kiygan edi.", why: 'wear → **wore**.' },
      { k: 'tf', q: '*Did you won the game?* — to\'g\'ri gap.', a: false, why: '**Did** dan keyin boshlang\'ich shakl: *Did you win…?*' },
      { k: 'listen', say: 'The film began at eight.', opts: ['The film began at eight.', 'The film ended at eight.', 'The film began at eleven.'], a: 0, why: 'begin → **began**.' },
      { k: 'order', uz: 'Bola daraxtdan yiqildi.', words: ['The', 'boy', 'fell', 'from', 'the', 'tree'], extra: ['fall', 'falled'], why: 'fall → **fell**.' },
      { k: 'fix', wrong: "I didn't forgot my homework.", a: ["I didn't forget my homework.", 'I did not forget my homework.'], why: "**didn't** dan keyin **forget**, *forgot* emas." },
      { k: 'fix', wrong: 'Where they swam yesterday?', a: ['Where did they swim yesterday?'], why: 'Savolda **did** + boshlang\'ich shakl: *swim*.' },
      { k: 'translate', uz: "Biz maktabda qo'shiq aytdik.", a: ['We sang a song at school', 'We sang songs at school', 'We sang at school'], why: 'sing → **sang**.' },
      { k: 'dictation', say: 'He ran fast and won the race.' },
    ],
  },
  {
    id: 'u9-l8-d2',
    title: 'Past Simple: tricky mix',
    titleUz: "O'tgan zamon: qiyin aralash mashqlar",
    goal: "Past Simple ning barcha shakllarini (**did, didn't, was / were, there was, could**) aralash holda mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*___ you catch the ball?*', opts: ['Did', 'Were', 'Do'], a: 0, why: 'O\'tgan zamon savoli → **Did** + fe\'l.' },
      { k: 'choice', q: '*There ___ a lot of children at sports day.*', opts: ['was', 'were', 'are'], a: 1, why: '**children** ko\'plik → **were**.' },
      { k: 'choice', q: '*I ___ the match because I was ill.*', opts: ["couldn't watch", "didn't can watch", "couldn't watched", "didn't could watch"], a: 0, why: "**couldn't** + boshlang'ich shakl." },
      { k: 'tf', q: "*She didn't wore a hat.* — to'g'ri gap.", a: false, why: "**didn't** dan keyin **wear**: *She didn't wear a hat.*" },
      { k: 'fill', q: 'Our team ___ the game, so we were happy. (win)', a: ['won'], uz: "Jamoamiz o'yinda yutdi, shuning uchun xursand edik.", why: 'win → **won**.' },
      { k: 'fill', q: 'Where ___ you last night? — I was at home.', a: ['were'], uz: 'Kecha kechqurun qayerda eding?', why: '**you** + o\'tgan zamon **be** → **were**.' },
      { k: 'fill', q: 'He fell and broke his leg. It ___ a bad day.', a: ['was'], uz: "U yiqilib oyog'ini sindirdi. Yomon kun bo'ldi.", why: 'it + o\'tgan zamon → **was**.' },
      { k: 'fix', wrong: 'Who you saw at the party?', a: ['Who did you see at the party?'], why: 'Savolda **did** + **see** (*saw* emas).' },
      { k: 'fix', wrong: "She didn't wore her new shoes.", a: ["She didn't wear her new shoes.", 'She did not wear her new shoes.'], why: "**didn't** dan keyin **wear**." },
      { k: 'fix', wrong: 'Was there a lot of people in the stadium?', a: ['Were there a lot of people in the stadium?'], why: '**people** ko\'plik → **Were there…?**' },
      { k: 'order', uz: 'Kecha telefonimni topa olmadim.', words: ['I', "couldn't", 'find', 'my', 'phone', 'yesterday'], extra: ["didn't", 'found'], alt: [['I', 'could', 'not', 'find', 'my', 'phone', 'yesterday']], why: "**couldn't** + **find**." },
      { k: 'translate', uz: "Ular o'yinda g'alaba qozonishmadi.", a: ["They didn't win the game", "They didn't win the match", 'They did not win the game', 'They did not win the match'], why: "**didn't** + **win** (*won* emas)." },
    ],
  },
];
