import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u14-l1-d1',
    title: 'Bigger, better, more…',
    titleUz: 'Qiyosiy daraja: -er yoki more?',
    goal: "Qisqa va uzun sifatlarning qiyosiy shaklini, **better / worse** va **than** ni mashq qilasiz; *more bigger* xatosidan qochasiz.",
    exercises: [
      { k: 'choice', q: '*This chair is ___ than that one.*', opts: ['more comfortable', 'comfortabler', 'most comfortable', 'more comfortabler'], a: 0, why: '*comfortable* uzun sifat → **more comfortable**.' },
      { k: 'match', pairs: [['nice', 'nicer'], ['hot', 'hotter'], ['busy', 'busier'], ['good', 'better'], ['expensive', 'more expensive']] },
      { k: 'fill', q: 'This street is ___ than that one. (noisy)', a: ['noisier'], uz: "Bu ko'cha anavisidan shovqinliroq.", why: '*noisy* → y tushib **-ier**: *noisier*.' },
      { k: 'fill', q: 'My phone is ___ than yours. (thin)', a: ['thinner'], uz: 'Mening telefonim seniknidan yupqaroq.', why: '*thin* → undosh + unli + undosh → **thinner** (n ikkilanadi).' },
      { k: 'choice', q: '*The weather today is ___ than yesterday. It rained all day.*', opts: ['worse', 'more bad', 'badder', 'more worse'], a: 0, why: '*bad* → **worse** (noto\'g\'ri shakl).' },
      { k: 'tf', q: '*Her flat is more bigger than mine.* — to\'g\'ri gap.', a: false, why: '**more** va **-er** birga kelmaydi: *Her flat is bigger than mine.*' },
      { k: 'listen', say: 'Bread is cheaper than meat.', opts: ['Bread is cheaper than meat.', 'Meat is cheaper than bread.', 'Bread is cheaper then meat.', 'Bread is more cheap than meat.'], a: 0, why: '**cheaper than** — non go\'shtdan arzonroq.' },
      { k: 'order', uz: 'Mening akam mendan ancha baland.', words: ['My', 'brother', 'is', 'much', 'taller', 'than', 'me'], extra: ['very', 'more'], why: '**much** + qiyosiy daraja; **very** ishlatilmaydi.' },
      { k: 'fix', wrong: 'My English is more better than last year.', a: ['My English is better than last year.'], hint: 'Ikki marta qiyoslangan', why: '*good* → **better**; oldiga **more** qo\'shilmaydi.' },
      { k: 'fix', wrong: 'Tashkent is bigger then Bukhara.', a: ['Tashkent is bigger than Bukhara.'], hint: 'Solishtirish so\'zi', why: 'Solishtirishda **than** (-dan); *then* — "keyin".' },
      { k: 'translate', uz: 'Mening kvartiram seniknidan kichikroq.', a: ['My flat is smaller than yours', "My flat's smaller than yours", 'My apartment is smaller than yours', "My apartment's smaller than yours"], why: '**smaller than yours** — qisqa sifat + **-er** + **than**.' },
      { k: 'dictation', say: 'The new bus is more comfortable than the old one.' },
    ],
  },
  {
    id: 'u14-l2-d1',
    title: 'The best, the most…',
    titleUz: 'Orttirma daraja: the -est yoki the most?',
    goal: "**the** ni unutmaslikni, **the -est / the most** ni, **the best / the worst** va **in / of** ni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Aziz is ___ boy in our class.*', opts: ['the tallest', 'tallest', 'the most tall', 'taller'], a: 0, why: 'Orttirma darajadan oldin **the**, qisqa sifat → **-est**.' },
      { k: 'match', pairs: [['big', 'the biggest'], ['easy', 'the easiest'], ['good', 'the best'], ['bad', 'the worst'], ['famous', 'the most famous']] },
      { k: 'fill', q: 'Today is ___ day of my life! (good)', a: ['the best'], uz: 'Bugun hayotimdagi eng yaxshi kun!', why: '*good* → **the best**.' },
      { k: 'fill', q: 'This is ___ cafe in the street. (cheap)', a: ['the cheapest'], uz: "Bu ko'chadagi eng arzon kafe.", why: '*cheap* → **the cheapest**.' },
      { k: 'choice', q: '*Samarkand is one of the oldest ___ in Uzbekistan.*', opts: ['city', 'cities', 'citys', 'the cities'], a: 1, why: '**one of the** + orttirma + **ko\'plik ot**: *cities*.' },
      { k: 'tf', q: '*She is the most tall girl in the class.* — to\'g\'ri gap.', a: false, why: 'Qisqa sifatga **most** qo\'shilmaydi: *the tallest*.' },
      { k: 'choice', q: '*Baikal is the deepest lake ___ the world.*', opts: ['in', 'of', 'at', 'from'], a: 0, why: 'Joy / guruh bilan **in**: *in the world*.' },
      { k: 'listen', say: 'This is the most delicious plov.', opts: ['This is the most delicious plov.', 'This is the more delicious plov.', 'This is the most delicious soup.', 'This is a most delicious plov.'], a: 0, why: '**the most delicious** — uzun sifat.' },
      { k: 'order', uz: "Bu men o'qigan eng qiziqarli kitob.", words: ['This', 'is', 'the', 'most', 'interesting', 'book', 'I', 'have', 'ever', 'read'], extra: ['more', 'a'], why: '**the most interesting** + **ever** — tajriba haqida.' },
      { k: 'fix', wrong: 'Ali is best student in our school.', a: ['Ali is the best student in our school.'], hint: 'Artikl yetishmayapti', why: 'Orttirma darajadan oldin **the** shart.' },
      { k: 'fix', wrong: 'This is the most big house in the street.', a: ['This is the biggest house in the street.'], why: 'Qisqa sifat: **the biggest** (*the most big* emas).' },
      { k: 'translate', uz: "Bu bizning sinfdagi eng qiyin dars.", a: ['This is the most difficult lesson in our class', "It's the most difficult lesson in our class", 'It is the most difficult lesson in our class', 'This is the hardest lesson in our class', "It's the hardest lesson in our class", 'It is the hardest lesson in our class'], why: '**the most difficult … in our class** — guruh bilan **in**.' },
    ],
  },
  {
    id: 'u14-l3-d1',
    title: 'As … as',
    titleUz: 'as … as, the same as, different from',
    goal: "**as … as**, **not as … as**, **the same as**, **different from**, **similar to** ni to'g'ri predloglar bilan mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*My brother is as tall ___ me.*', opts: ['as', 'than', 'like', 'then'], a: 0, why: '**as tall as** — ikkinchi so\'z ham **as**.' },
      { k: 'match', pairs: [['as tall as', '…chalik baland'], ['not as big as', '…chalik katta emas'], ['the same as', '…dek bir xil'], ['different from', '…dan farq qiladi'], ['similar to', "…ga o'xshash"]] },
      { k: 'fill', q: 'Her dress is similar ___ mine.', a: ['to'], uz: "Uning ko'ylagi meniknaga o'xshash.", why: '**similar to** (*with* emas).' },
      { k: 'fill', q: "Tea isn't as expensive ___ coffee.", a: ['as'], uz: 'Choy qahvachalik qimmat emas.', why: '**not as … as** — oxirida ham **as**.' },
      { k: 'choice', q: '*Ali is 20. Sardor is 20. Ali is ___ Sardor.*', opts: ['as old as', 'older than', 'as older as', 'not as old as'], a: 0, why: 'Yoshi teng → **as old as**; sifat o\'zgarmaydi.' },
      { k: 'tf', q: '*My phone is different with yours.* — to\'g\'ri gap.', a: false, why: 'To\'g\'risi: **different from** (*with* emas).' },
      { k: 'listen', say: "The bus isn't as fast as the metro.", opts: ["The bus isn't as fast as the metro.", 'The bus is as fast as the metro.', "The metro isn't as fast as the bus.", "The bus isn't as slow as the metro."], a: 0, why: '**isn\'t as fast as** — avtobus metrochalik tez emas.' },
      { k: 'order', uz: "Mening akam mendek baland emas.", words: ['My', 'brother', 'is', 'not', 'as', 'tall', 'as', 'me'], extra: ['than', 'taller'], alt: [['My', 'brother', "isn't", 'as', 'tall', 'as', 'me']], why: '**not as tall as** — *taller* kerak emas.' },
      { k: 'fix', wrong: 'Kamol is as taller as Aziz.', a: ['Kamol is as tall as Aziz.'], hint: 'Sifat shakli', why: '**as … as** orasida sifat o\'zgarmaydi: *as tall as*.' },
      { k: 'fix', wrong: 'My bag is the same with yours.', a: ['My bag is the same as yours.'], hint: 'Predlog', why: '**the same as** (*with* emas).' },
      { k: 'fix', wrong: 'This film is as interesting than that one.', a: ['This film is as interesting as that one.'], why: '**as … as**; *than* faqat qiyosiy darajada.' },
      { k: 'translate', uz: 'Samarqand Toshkentchalik katta emas.', a: ["Samarkand isn't as big as Tashkent", 'Samarkand is not as big as Tashkent', "Samarkand's not as big as Tashkent"], why: '**not as big as** — "…chalik katta emas".' },
    ],
  },
  {
    id: 'u14-l4-d1',
    title: 'Too or enough?',
    titleUz: 'Too va enough: o\'rni va much / many',
    goal: "**too**, **enough** ning gapdagi o'rnini hamda **too much / too many** ni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "*This coffee is ___ hot. I can't drink it.*", opts: ['too', 'very', 'enough', 'too much'], a: 0, why: 'Ichib bo\'lmaydi — muammo bor → **too hot**.' },
      { k: 'choice', q: '*There is ___ traffic in the centre.*', opts: ['too many', 'too much', 'too', 'enough many'], a: 1, why: '*traffic* sanalmaydi → **too much**.' },
      { k: 'match', pairs: [['too much sugar', "juda ko'p shakar"], ['too many cars', "juda ko'p mashinalar"], ['big enough', 'yetarlicha katta'], ['enough money', 'yetarli pul'], ['too small', 'juda kichik']] },
      { k: 'fill', q: 'The room is big ___ for ten people.', a: ['enough'], uz: 'Xona o\'n kishi uchun yetarlicha katta.', why: 'Sifatdan **keyin** → *big enough*.' },
      { k: 'fill', q: "We don't have ___ chairs for everyone.", a: ['enough'], uz: 'Hamma uchun stullar yetarli emas.', why: 'Otdan **oldin** → *enough chairs*.' },
      { k: 'tf', q: '*She is enough tall to play basketball.* — to\'g\'ri gap.', a: false, why: '**sifat + enough**: *tall enough*.' },
      { k: 'listen', say: 'He is too tired to study.', opts: ['He is too tired to study.', 'He is tired enough to study.', "He isn't tired enough to study.", 'He is too tired to work.'], a: 0, why: '**too tired to study** — o\'qish uchun juda charchagan.' },
      { k: 'order', uz: "Bu sumka men uchun juda og'ir.", words: ['This', 'bag', 'is', 'too', 'heavy', 'for', 'me'], extra: ['much', 'enough'], why: '**too** sifat oldidan, **much** kerak emas.' },
      { k: 'fix', wrong: 'The soup is too much salty.', a: ['The soup is too salty.'], hint: 'Sifat bilan nima keladi?', why: 'Sifat bilan faqat **too**; *too much* — ot bilan.' },
      { k: 'fix', wrong: 'There are too much people in the shop.', a: ['There are too many people in the shop.'], why: '*people* sanaladi → **too many**.' },
      { k: 'fix', wrong: "The room isn't enough big for us.", a: ["The room isn't big enough for us.", 'The room is not big enough for us.'], hint: "So'zlar o'rni", why: '**enough** sifatdan keyin: *big enough*.' },
      { k: 'translate', uz: "Sayohat qilish uchun pulim yetarli emas.", a: ["I don't have enough money to travel", 'I do not have enough money to travel', "I haven't got enough money to travel"], why: '**enough money** — otdan oldin; keyin **to** + fe\'l.' },
    ],
  },
  {
    id: 'u14-l5-d1',
    title: 'Good or well?',
    titleUz: 'Ravish: good / well, hard, fast',
    goal: "**good** (sifat) va **well** (ravish), **-ly** ravishlari hamda **hard / fast** ni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*She sings very ___.*', opts: ['good', 'well', 'goodly', 'best'], a: 1, why: 'Fe\'lni tavsiflash uchun ravish kerak → **well**.' },
      { k: 'choice', q: '*The plov tastes ___.*', opts: ['good', 'well', 'goodly', 'quickly'], a: 0, why: '**taste** dan keyin sifat keladi → **good**.' },
      { k: 'match', pairs: [['slow', 'slowly'], ['happy', 'happily'], ['easy', 'easily'], ['good', 'well'], ['bad', 'badly']] },
      { k: 'fill', q: "Please speak ___. I can't understand you. (slow)", a: ['slowly'], uz: 'Iltimos, sekin gapiring. Sizni tushunmayapman.', why: '*slow* + **-ly** → *slowly*.' },
      { k: 'fill', q: 'She is a careful driver. She drives ___.', a: ['carefully'], uz: 'U ehtiyotkor haydovchi. U ehtiyotkorlik bilan haydaydi.', why: '*careful* + **-ly** → *carefully*.' },
      { k: 'fill', q: 'Dilnoza studies very ___ for her exams. (hard)', a: ['hard'], uz: 'Dilnoza imtihonlarga juda qattiq tayyorlanadi.', why: '*hard* ravishda ham o\'zgarmaydi (*hardly* — "deyarli emas").' },
      { k: 'tf', q: '*He drives fastly.* — to\'g\'ri gap.', a: false, why: '**fast** ravishda ham o\'zgarmaydi: *He drives fast.*' },
      { k: 'listen', say: 'She plays the piano beautifully.', opts: ['She plays the piano beautifully.', 'She plays the piano beautiful.', 'She plays the piano badly.', 'She plays beautifully the piano.'], a: 0, why: '**beautifully** — fe\'l va to\'ldiruvchidan keyin.' },
      { k: 'order', uz: 'U ingliz tilida juda yaxshi gapiradi.', words: ['She', 'speaks', 'English', 'very', 'well'], extra: ['good'], why: '**well** — to\'ldiruvchi (*English*) dan keyin.' },
      { k: 'fix', wrong: 'He speaks well English.', a: ['He speaks English well.'], hint: "So'zlar tartibi", why: 'Tartib: fe\'l + to\'ldiruvchi + ravish → *speaks English **well***.' },
      { k: 'fix', wrong: 'My sister cooks very good.', a: ['My sister cooks very well.'], hint: 'Sifat emas, ravish', why: 'Fe\'l (*cooks*) dan keyin ravish → **well**.' },
      { k: 'translate', uz: 'Iltimos, sekinroq gapiring.', a: ['Please speak more slowly', 'Please speak slower', 'Speak more slowly, please', 'Speak slower, please'], why: '**-ly** ravish → **more slowly**.' },
    ],
  },
];
