import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u11-l1-d1',
    title: 'Have you ever…?',
    titleUz: 'Have you ever…?',
    goal: "**have / has + V3**, **Have you ever…?** savollari va **Yes, I have / No, I haven't** javoblarini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*She ___ been to Japan.*', opts: ['have', 'has', 'is', 'did'], a: 1, why: '**she** → **has** + V3.' },
      { k: 'choice', q: '*We have ___ this film.*', opts: ['saw', 'seen', 'see', 'sawn'], a: 1, why: '**have** dan keyin **V3**: see – saw – **seen**.' },
      { k: 'choice', q: '*Have you ever ridden a camel?* — "Ha" javobi:', opts: ['Yes, I have.', 'Yes, I did.', "Yes, I've.", 'Yes, I am.'], a: 0, why: "Savol **Have…?** → **Yes, I have.** (oxirida qisqartma yo'q)." },
      { k: 'match', pairs: [['be', 'been'], ['see', 'seen'], ['eat', 'eaten'], ['ride', 'ridden'], ['fly', 'flown']] },
      { k: 'fill', q: 'Have you ever ___ sushi? (eat)', a: ['eaten'], uz: 'Hech sushi yeganmisiz?', why: 'eat – ate – **eaten**.' },
      { k: 'fill', q: 'My grandmother has ___ flown.', a: ['never'], uz: 'Buvim hech qachon samolyotda uchmagan.', why: '**has never + V3** — "hech qachon".' },
      { k: 'tf', q: "*I haven't never been to Spain.* — to'g'ri gap.", a: false, why: "**never** o'zi inkor, qo'shimcha *not* kerak emas: *I've **never** been…* yoki *I **haven't** been…*" },
      { k: 'listen', say: 'Has he ever met a famous person?', opts: ['Has he ever met a famous person?', 'Have you ever met a famous person?', 'Has she ever met a famous person?'], a: 0, why: '**Has he** — savol *he* bilan.' },
      { k: 'order', uz: "Siz hech Xivada bo'lganmisiz?", words: ['Have', 'you', 'ever', 'been', 'to', 'Khiva'], extra: ['did', 'went'], why: '**Have you ever been to…?** — tajriba haqida savol.' },
      { k: 'fix', wrong: 'I have saw this film.', a: ['I have seen this film.', "I've seen this film."], hint: '3-shakl kerak', why: '**have** dan keyin **V3**: *seen* (saw emas).' },
      { k: 'fix', wrong: 'Did you ever been to Khiva?', a: ['Have you ever been to Khiva?'], hint: 'Yordamchi fe\'l noto\'g\'ri', why: "Tajriba savoli **Have you ever been…?** bilan tuziladi." },
      { k: 'translate', uz: "Biz hech qachon Yaponiyada bo'lmaganmiz.", a: ['We have never been to Japan', "We've never been to Japan", "We haven't been to Japan", 'We have not been to Japan'], why: '**have never been to** — hech qachon bo\'lmaganman.' },
    ],
  },
  {
    id: 'u11-l1-d2',
    title: 'Have you ever…? Tricky mix',
    titleUz: 'Have you ever…?: qiyin aralash mashqlar',
    goal: "**never, once, twice**, qisqa javoblar va **'s = has / is** kabi tuzoqlarni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "Qaysi gap **to'g'ri**?", opts: ["I've went to Bukhara.", "I've been to Bukhara.", "I've be to Bukhara.", "I've goed to Bukhara."], a: 1, why: "**have + V3**: *I've **been** to Bukhara.*" },
      { k: 'choice', q: '*Has your sister ever flown?* — "Yo\'q" javobi:', opts: ["No, she hasn't.", "No, she didn't.", "No, she haven't.", "No, she isn't."], a: 0, why: "Savol **Has…?** → **No, she hasn't.**" },
      { k: 'match', pairs: [["I've never been abroad.", "Hech qachon chet elda bo'lmaganman."], ["She's flown twice.", 'U ikki marta uchgan.'], ['Have you ever read this book?', "Bu kitobni o'qiganmisiz?"], ["They've met him once.", 'Ular u bilan bir marta uchrashgan.']] },
      { k: 'fill', q: "We've met that man ___.", a: ['once'], uz: 'Biz o\'sha odam bilan bir marta uchrashganmiz.', why: '**once** — bir marta.' },
      { k: 'fill', q: 'They have ___ to Turkey twice. (be)', a: ['been'], why: 'be – was/were – **been**: *have been to*.' },
      { k: 'tf', q: "*Yes, I've.* — *Have you ever been there?* ga to'g'ri javob.", a: false, why: "Qisqa javob oxirida qisqartma ishlatilmaydi: **Yes, I have.**" },
      { k: 'tf', q: "*He's met my sister.* gapidagi **'s** = **has**.", a: true, why: "**'s + V3 (met)** = **has**. *He's tired* da esa 's = is." },
      { k: 'listen', say: "I've never been to Japan.", opts: ["I've never been to Japan.", "I've been to Japan.", "She's never been to Japan."], a: 0, why: "**never** — hech qachon." },
      { k: 'order', uz: "Ular bu filmni uch marta ko'rishgan.", words: ['They', 'have', 'seen', 'this', 'film', 'three', 'times'], extra: ['saw', 'has'], why: '**have + V3** + necha marta: *three times*.' },
      { k: 'fix', wrong: "I haven't never been to Samarkand.", a: ["I've never been to Samarkand.", 'I have never been to Samarkand.', "I haven't been to Samarkand.", 'I have not been to Samarkand.'], hint: 'Ikki inkor bor', why: "**never** va **haven't** birga ishlatilmaydi — bittasi yetadi." },
      { k: 'fix', wrong: 'He have flown to Dubai twice.', a: ['He has flown to Dubai twice.', "He's flown to Dubai twice."], why: '**he** bilan **has** + V3.' },
      { k: 'translate', uz: "Singlim hech qachon samolyotda uchmagan.", a: ['My sister has never flown', "My sister's never flown", 'My sister has never flown in a plane', 'My sister has never been on a plane', "My sister hasn't flown"], why: '**has never + V3**: *has never flown*.' },
    ],
  },
  {
    id: 'u11-l2-d1',
    title: 'V3 and been / gone',
    titleUz: '3-shakl fe\'llar va been / gone',
    goal: "Noto'g'ri fe'llarning **V3** shaklini va **been to** (borib kelgan) bilan **gone to** (ketgan) farqini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '**break** ning V3 shakli:', opts: ['broke', 'broken', 'breaked', 'broked'], a: 1, why: 'break – broke – **broken**.' },
      { k: 'choice', q: "*Where's your dad?* — *He's ___ to work.* (U hozir ishda)", opts: ['been', 'gone', 'went', 'go'], a: 1, why: "U hali qaytmagan → **gone to**." },
      { k: 'match', pairs: [['write', 'written'], ['speak', 'spoken'], ['forget', 'forgotten'], ['drive', 'driven'], ['wear', 'worn']] },
      { k: 'fill', q: 'Look! Somebody has ___ the window. (break)', a: ['broken'], why: 'break – broke – **broken**.' },
      { k: 'fill', q: 'He has ___ me an email. (send)', a: ['sent'], uz: 'U menga elektron xat yuborgan.', why: 'send – sent – **sent**.' },
      { k: 'tf', q: "*I've gone to Japan three times.* — to'g'ri gap.", a: false, why: "O'zingiz haqingizda tajriba → **been**: *I've **been** to Japan…*" },
      { k: 'listen', say: 'She has forgotten her phone.', opts: ['She has forgotten her phone.', 'She has forgot her phone.', 'She has found her phone.'], a: 0, why: 'forget – forgot – **forgotten**.' },
      { k: 'choice', q: '*Have you ever ___ to Japan?*', opts: ['gone', 'been', 'go', 'went'], a: 1, why: 'Tajriba haqida savol → **been to**.' },
      { k: 'order', uz: "U ingliz tilida kitob yozgan.", words: ['She', 'has', 'written', 'a', 'book', 'in', 'English'], extra: ['wrote', 'have'], why: 'write – wrote – **written**.' },
      { k: 'fix', wrong: 'We have drove to Samarkand.', a: ['We have driven to Samarkand.', "We've driven to Samarkand."], hint: '3-shakl kerak', why: 'drive – drove – **driven**. **have** dan keyin V3.' },
      { k: 'fix', wrong: 'My sister has gone to London twice.', a: ['My sister has been to London twice.', "My sister's been to London twice."], hint: 'Borib kelgan', why: "Ikki marta bo'lib, qaytib kelgan → **been to**." },
      { k: 'translate', uz: "Ali yangi velosiped sotib olibdi.", a: ['Ali has bought a new bike', "Ali's bought a new bike", 'Ali has bought a new bicycle', "Ali's bought a new bicycle"], why: 'buy – bought – **bought**: *has bought*.' },
    ],
  },
  {
    id: 'u11-l3-d1',
    title: 'Present Perfect or Past Simple?',
    titleUz: 'Present Perfect yoki Past Simple?',
    goal: "Signal so'zlarga qarab **Present Perfect** (vaqt yo'q) va **Past Simple** (aniq vaqt) ni tanlashni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*I ___ him yesterday.*', opts: ['have seen', 'saw', 'see', 'have saw'], a: 1, why: '*yesterday* — aniq vaqt → Past Simple: **saw**.' },
      { k: 'choice', q: '*We ___ to Khiva last year.*', opts: ['went', 'have been', 'have gone', 'go'], a: 0, why: '*last year* → Past Simple: **went**.' },
      { k: 'match', pairs: [["I've seen it.", 'vaqt aytilmagan'], ['I saw it on Monday.', 'aniq kun bor'], ['Have you ever been there?', 'hayotdagi tajriba'], ['When did you go?', 'qachon? savoli'], ['I went there in 2019.', 'aniq yil bor']] },
      { k: 'fill', q: 'She ___ her phone yesterday. (lose)', a: ['lost'], uz: 'U kecha telefonini yo\'qotdi.', why: '*yesterday* → Past Simple: **lost**.' },
      { k: 'fill', q: "I've ___ this film three times. (see)", a: ['seen'], uz: 'Bu filmni uch marta ko\'rganman.', why: 'Vaqt aytilmagan → Present Perfect: **seen**.' },
      { k: 'tf', q: "*When have you been to Bukhara?* — to'g'ri savol.", a: false, why: "**When…?** doim Past Simple: *When **did** you **go** to Bukhara?*" },
      { k: 'listen', say: 'When did you go to Samarkand?', opts: ['When did you go to Samarkand?', 'Have you ever been to Samarkand?', 'When do you go to Samarkand?'], a: 0, why: '**When did you go…?** — qachon bordingiz?' },
      { k: 'choice', q: '*Have you ever been to Japan?* — *Yes, I have. ___ there in May.*', opts: ['I went', 'I have gone', 'I go', "I've been"], a: 0, why: '*in May* — aniq vaqt → Past Simple: **I went**.' },
      { k: 'order', uz: 'Siz qachon Parijga bordingiz?', words: ['When', 'did', 'you', 'go', 'to', 'Paris'], extra: ['have', 'went'], why: '**When did you go…?** — *did* + V1.' },
      { k: 'fix', wrong: 'She has bought a bag last week.', a: ['She bought a bag last week.'], hint: 'Vaqt so\'ziga qarang', why: '*last week* bor → Past Simple: **bought**.' },
      { k: 'fix', wrong: 'When did you went to Bukhara?', a: ['When did you go to Bukhara?'], why: '**did** dan keyin **V1**: *go* (went emas).' },
      { k: 'translate', uz: "Ali o'tgan hafta yangi ish topdi.", a: ['Ali found a new job last week', 'Ali found a job last week', 'Last week Ali found a new job'], why: '*last week* → Past Simple: **found**.' },
    ],
  },
  {
    id: 'u11-l3-d2',
    title: 'Present Perfect or Past Simple? Tricky mix',
    titleUz: 'Present Perfect yoki Past Simple?: qiyin aralash mashqlar',
    goal: "Yangilik → tafsilot qolipini, **When…?** savollarini va vaqt so'zlari bilan xatolarni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Ali has won the cup.* — Keyingi tabiiy gap qaysi?', opts: ['He has won it on Saturday.', 'He won it on Saturday.', 'He wins it on Saturday.', 'He has win it on Saturday.'], a: 1, why: 'Aniq kun (*on Saturday*) → Past Simple: **won**.' },
      { k: 'choice', q: '*___ you ever lost your passport?*', opts: ['Did', 'Have', 'Do', 'Has'], a: 1, why: 'Vaqt yo\'q, *ever* → **Have you ever lost…?**' },
      { k: 'choice', q: 'Qaysi gap **xato**?', opts: ["I've been to Japan.", 'I went to Japan in May.', "I've been to Japan in May.", 'Have you been to Japan?'], a: 2, why: "*in May* — aniq vaqt bilan Present Perfect bo'lmaydi: *I **went** to Japan in May.*" },
      { k: 'fill', q: 'Have you ever eaten sushi? — Yes, I have. I ___ it last week.', a: ['ate'], uz: 'Ha. O\'tgan hafta yegan edim.', why: '*last week* → Past Simple: eat – **ate**.' },
      { k: 'fill', q: 'Malika has found a job. When ___ she start?', a: ['did'], uz: 'Malika ish topdi. U qachon boshladi?', why: '**When…?** → Past Simple: **did** she start.' },
      { k: 'tf', q: "*I've lived in Fergana in 2018.* — to'g'ri gap.", a: false, why: "*in 2018* — aniq yil → *I **lived** in Fergana in 2018.*" },
      { k: 'listen', say: "I've never seen the ocean.", opts: ["I've never seen the ocean.", 'I never saw the ocean.', "I've seen the ocean."], a: 0, why: '**I\'ve never seen** — hayotda hech qachon.' },
      { k: 'order', uz: 'Kecha ularni ko\'rmadim.', words: ['I', "didn't", 'see', 'them', 'yesterday'], extra: ["haven't", 'seen'], why: '*yesterday* → **didn\'t + V1**.' },
      { k: 'fix', wrong: 'When have you met him?', a: ['When did you meet him?'], hint: 'When bilan qaysi zamon?', why: '**When…?** doim Past Simple: *When **did** you **meet**…?*' },
      { k: 'fix', wrong: 'I have bought a new phone two days ago.', a: ['I bought a new phone two days ago.'], why: '*two days ago* → Past Simple: **bought**.' },
      { k: 'fix', wrong: 'Last summer I have been to Bukhara.', a: ['Last summer I went to Bukhara.'], why: '*Last summer* → Past Simple: **went**.' },
      { k: 'translate', uz: 'Biz kecha yangi filmni ko\'rdik.', a: ['We saw the new film yesterday', 'We saw a new film yesterday', 'We saw the new movie yesterday', 'We saw a new movie yesterday', 'Yesterday we saw the new film', 'Yesterday we saw a new film'], why: '*yesterday* → Past Simple: **saw**.' },
    ],
  },
  {
    id: 'u11-l5-d1',
    title: 'want to or enjoy -ing?',
    titleUz: 'want to yoki enjoy -ing?',
    goal: "**want / need / hope + to**, **enjoy / finish / practise + -ing** va **I want you to…** qoliplarini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*I want ___ a new phone.*', opts: ['to buy', 'buying', 'buy', 'to buying'], a: 0, why: '**want + to + V1**.' },
      { k: 'choice', q: '*She enjoys ___ in the park.*', opts: ['to walk', 'walking', 'walk', 'walks'], a: 1, why: '**enjoy + -ing**.' },
      { k: 'match', pairs: [['I want', 'to learn English'], ['I enjoy', 'learning English'], ["I've decided", 'to study abroad'], ["I don't mind", 'waiting'], ["I've finished", 'reading the book']] },
      { k: 'fill', q: 'I practise ___ English every day. (speak)', a: ['speaking'], uz: 'Har kuni ingliz tilida gapirishni mashq qilaman.', why: '**practise + -ing**.' },
      { k: 'fill', q: 'You need ___ sleep more.', a: ['to'], uz: 'Ko\'proq uxlashing kerak.', why: '**need + to + V1**.' },
      { k: 'tf', q: "*I enjoy to cook.* — to'g'ri gap.", a: false, why: "**enjoy** dan keyin **-ing**: *I enjoy **cooking**.*" },
      { k: 'listen', say: 'I want you to come.', opts: ['I want you to come.', 'I want to come.', 'I want you come.'], a: 0, why: '**want + kishi + to + V1**.' },
      { k: 'choice', q: '"Kelishingni xohlayman" qaysi?', opts: ['I want you to come.', 'I want that you come.', 'I want you come.', 'I want to you come.'], a: 0, why: "**want + you + to + V1**. *that* ishlatilmaydi." },
      { k: 'order', uz: "Do'stim suzishga borishni xohlaydi.", words: ['My', 'friend', 'wants', 'to', 'go', 'swimming'], extra: ['going', 'swim'], why: '**wants to go** + **swimming** (*go* + -ing).' },
      { k: 'fix', wrong: 'She finished to read the book.', a: ['She finished reading the book.'], hint: 'finish dan keyin qaysi shakl?', why: '**finish + -ing**: *finished **reading***.' },
      { k: 'fix', wrong: 'I want that you help me.', a: ['I want you to help me.'], why: '**want + you + to + V1**.' },
      { k: 'translate', uz: "Men bu yil suzishni o'rganmoqchiman.", a: ['I want to learn to swim this year', "I'd like to learn to swim this year", 'I would like to learn to swim this year', "I'm going to learn to swim this year", 'I hope to learn to swim this year', 'I plan to learn to swim this year', "I'm planning to learn to swim this year"], why: '**want to learn to swim** — istak + to + V1.' },
    ],
  },
];
