import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u12-l2-d1',
    title: 'Did you go? I didn\'t go',
    titleUz: "Past Simple: didn't va Did…?",
    goal: "**didn't + V1**, **Did + ega + V1?** va **ago / last / in / on** iboralarini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*She ___ call me yesterday.*', opts: ["didn't", "doesn't", 'not', "wasn't"], a: 0, why: "O'tgan zamon inkori: **didn't + V1**." },
      { k: 'choice', q: '*___ you watch the match last night?*', opts: ['Did', 'Do', 'Were', 'Have'], a: 0, why: "O'tgan zamon savoli **Did** bilan boshlanadi." },
      { k: 'match', pairs: [['two days ago', 'ikki kun oldin'], ['last night', 'kecha kechqurun'], ['in 2019', '2019-yilda'], ['on Monday', 'dushanba kuni'], ['yesterday morning', 'kecha ertalab']] },
      { k: 'fill', q: 'We ___ go out last night because of the rain.', a: ["didn't", 'did not'], uz: "Biz kecha kechqurun yomg'ir tufayli tashqariga chiqmadik.", why: "Inkor: **didn't + go**." },
      { k: 'fill', q: 'Where ___ you buy this bag?', a: ['did'], uz: "Bu sumkani qayerdan sotib oldingiz?", why: "Wh- savol: so'roq so'z + **did** + ega + V1." },
      { k: 'listen', say: 'What did you do last night?', opts: ['What did you do last night?', 'What do you do every night?', 'What are you doing tonight?', 'What did you done last night?'], a: 0, why: "**did you do** — o'tgan zamon savoli." },
      { k: 'tf', q: "*Did he phoned you?* — to'g'ri savol.", a: false, why: "**Did** dan keyin V1: *Did he **phone** you?*" },
      { k: 'fill', q: 'She left the office two hours ___.', a: ['ago'], uz: "U ofisdan ikki soat oldin chiqib ketdi.", why: "Davr + **ago**: *two hours ago*." },
      { k: 'order', uz: 'Siz kecha kechqurun qayerda eding?', words: ['Where', 'were', 'you', 'last', 'night?'], extra: ['did', 'was'], why: "**be** bilan **did** kerak emas: *Where **were** you…?*" },
      { k: 'fix', wrong: "I didn't went to school on Friday.", a: ["I didn't go to school on Friday.", 'I did not go to school on Friday.'], hint: "didn't dan keyin fe'l asl shaklda", why: "O'tgan zamon belgisi faqat **didn't** da: *didn't **go***." },
      { k: 'translate', uz: "Biz o'tgan hafta kinoga bormadik.", a: ["We didn't go to the cinema last week", 'We did not go to the cinema last week', "We didn't go to the movies last week", 'We did not go to the movies last week'], why: "**didn't go**; *last week* oldida **in** yo'q." },
      { k: 'dictation', say: 'Did you see Aziz at the party?' },
    ],
  },
  {
    id: 'u12-l3-d1',
    title: 'Was cooking, were playing',
    titleUz: 'Past Continuous: was / were + -ing',
    goal: "**was / were + V-ing** shaklini, **-ing** imlosini va holat fe'llari bilan xatolarni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*At eight last night we ___ TV.*', opts: ['were watching', 'was watching', 'are watching', 'watching'], a: 0, why: "**we** + **were** + V-ing." },
      { k: 'match', pairs: [['swim', 'swimming'], ['write', 'writing'], ['stop', 'stopping'], ['die', 'dying'], ['carry', 'carrying']] },
      { k: 'fill', q: 'She was ___ a letter to her friend. (write)', a: ['writing'], why: "Oxirgi **-e** tushadi: write → **writing**." },
      { k: 'choice', q: "Qaysi gap **to'g'ri**?", opts: ['They waiting for the bus.', 'They were waiting for the bus.', 'They was waiting for the bus.', 'They did waiting for the bus.'], a: 1, why: "**were** tushib qolmasin: *They **were** waiting*." },
      { k: 'listen', say: 'I was sleeping at midnight.', opts: ['I was sleeping at midnight.', 'I slept at midnight.', 'I am sleeping at midnight.', 'We were sleeping at midnight.'], a: 0, why: "**was sleeping** — Past Continuous." },
      { k: 'fill', q: '___ you studying when I called?', a: ['Were'], uz: "Men qo'ng'iroq qilganda o'qiyotgan edingmi?", why: "*you* + **Were** + V-ing; savolda **did** yo'q." },
      { k: 'tf', q: "*He didn't listening to me.* — to'g'ri gap.", a: false, why: "Past Continuous da inkor: **wasn't listening**." },
      { k: 'order', uz: "Soat to'qqizda ular futbol o'ynayotgan edi.", words: ['At', 'nine', 'they', 'were', 'playing', 'football.'], extra: ['was', 'played'], alt: [['They', 'were', 'playing', 'football', 'at', 'nine.']], why: "*they* + **were playing**." },
      { k: 'fix', wrong: 'I was knowing the answer.', a: ['I knew the answer.'], hint: "know — holat fe'li", why: "**know** Continuous da kelmaydi: **knew**." },
      { k: 'fix', wrong: 'What you were doing at nine?', a: ['What were you doing at nine?'], hint: "So'zlar tartibi", why: "Savolda **were** egadan oldin: *What **were you** doing…?*" },
      { k: 'translate', uz: "Biz kutubxonada o'qiyotgan edik.", a: ['We were studying in the library', 'We were reading in the library', 'We were studying at the library', 'We were reading at the library'], why: "**we** + **were** + V-ing." },
      { k: 'dictation', say: 'My brother was running in the park.' },
    ],
  },
  {
    id: 'u12-l4-d1',
    title: 'When the phone rang…',
    titleUz: 'Past Continuous va Past Simple: when / while',
    goal: "Uzun ish (**was cooking**) va qisqa voqea (**rang**) ni bir gapda to'g'ri tanlashni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*She ___ dinner when the phone rang.*', opts: ['was cooking', 'cooked', 'were cooking', 'cooks'], a: 0, why: "Telefon jiringlaganda ovqat pishirish **davom etayotgan edi**." },
      { k: 'choice', q: '*While Nilufar was shopping, she ___ an old friend.*', opts: ['met', 'was meeting', 'meets', 'was met'], a: 0, why: "Qisqa voqea (uchrashib qoldi) → **Past Simple**: *met*." },
      { k: 'match', pairs: [['lose', 'lost'], ['drive', 'drove'], ['break', 'broke'], ['meet', 'met'], ['hurt', 'hurt']] },
      { k: 'fill', q: 'We were having lunch when the lights ___ out. (go)', a: ['went'], why: "Qisqa voqea → **went** (go – went)." },
      { k: 'fill', q: '___ my sister was cooking, I was setting the table.', a: ['While'], hint: 'Ikki ish bir vaqtda', uz: "Singlim ovqat pishirayotganda, men dasturxon yozayotgan edim.", why: "Ikki parallel ish → **While**." },
      { k: 'listen', say: 'He was sleeping when I arrived.', opts: ['He was sleeping when I arrived.', 'He slept when I was arriving.', 'He was sleeping while I arrived.', 'He is sleeping when I arrive.'], a: 0, why: "Uzun ish — *was sleeping*, qisqa voqea — *arrived*." },
      { k: 'tf', q: "*When I got home, I made tea.* — avval uyga keldim, keyin choy damladim.", a: true, why: "Ikki qisqa voqea ketma-ket → ikkalasi ham **Past Simple**." },
      { k: 'order', uz: "Biz Buxoroga ketayotganimizda mashina buzildi.", words: ['The', 'car', 'broke', 'down', 'while', 'we', 'were', 'driving', 'to', 'Bukhara.'], extra: ['was', 'drove'], alt: [['While', 'we', 'were', 'driving', 'to', 'Bukhara,', 'the', 'car', 'broke', 'down.']], why: "*while we **were driving*** (uzun ish), *the car **broke** down* (qisqa voqea)." },
      { k: 'fix', wrong: 'I was crossing the road when I was seeing my friend.', a: ['I was crossing the road when I saw my friend.'], hint: "Qisqa voqea", why: "Do'stni ko'rish — qisqa voqea: **saw**." },
      { k: 'fix', wrong: 'She cooked dinner when the phone rang.', a: ['She was cooking dinner when the phone rang.'], hint: "Telefon jiringlaganda ovqat tayyorlanayotgan edi", why: "Uzun ish **was cooking** bo'lishi kerak." },
      { k: 'translate', uz: "Men dars qilayotganimda, akam kirib keldi.", a: ['While I was studying, my brother came in', 'My brother came in while I was studying', 'When I was studying, my brother came in', 'My brother came in when I was studying', 'While I was studying, my brother walked in', 'My brother walked in while I was studying'], why: "**was studying** (uzun ish) + **came** (qisqa voqea)." },
      { k: 'dictation', say: 'They were walking home when it started to rain.' },
    ],
  },
  {
    id: 'u12-l4-d2',
    title: 'Past tenses: tricky mix',
    titleUz: "Past Simple va Past Continuous: qiyin aralash mashqlar",
    goal: "Zamon tanlashdagi tuzoqlar va tipik xatolarni tuzatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*When I ___ home, my mother was cooking.*', opts: ['got', 'was getting', 'were getting', 'get'], a: 0, why: "Uyga yetib kelish — qisqa voqea: **got**. Ona esa allaqachon pishirayotgan edi." },
      { k: 'choice', q: '*___ the film started, everybody stopped talking.*', opts: ['When', 'While', 'During', 'Because'], a: 0, why: "Qisqa voqea (film boshlandi) oldidan **When**." },
      { k: 'choice', q: '*I ___ the answer, so I raised my hand.*', opts: ['knew', 'was knowing', 'know', 'were knowing'], a: 0, why: "**know** — holat fe'li, Continuous da kelmaydi: **knew**." },
      { k: 'tf', q: "*While he was crossing the road, a car hit him.* — ikkala ish ham uzoq davom etgan.", a: false, why: "Kesib o'tish — uzun ish, mashina urib ketishi — **qisqa voqea** (*hit*)." },
      { k: 'fill', q: 'Dilnoza was studying while her brother ___ football. (play)', a: ['was playing'], why: "Ikkala ish bir vaqtda → ikkalasi ham Past Continuous." },
      { k: 'fill', q: 'I ___ hear the bell because I was listening to music.', a: ["didn't", 'did not'], uz: "Qo'ng'iroqni eshitmadim, chunki musiqa tinglayotgan edim.", why: "Inkor: **didn't + hear**." },
      { k: 'fix', wrong: 'While I was walking home, I was seeing an accident.', a: ['While I was walking home, I saw an accident.'], why: "Qisqa voqea → **saw**." },
      { k: 'fix', wrong: 'He was reading when I was coming in.', a: ['He was reading when I came in.'], why: "Kirib kelish — qisqa voqea: **came**." },
      { k: 'fix', wrong: 'While we have lunch, the lights went out.', a: ['While we were having lunch, the lights went out.'], hint: "O'tgan zamon, uzun ish", why: "O'tmishdagi uzun ish: **were having**." },
      { k: 'order', uz: "Ofitsiant kelganda biz menyuni o'qiyotgan edik.", words: ['When', 'the', 'waiter', 'came,', 'we', 'were', 'reading', 'the', 'menu.'], extra: ['read', 'was'], alt: [['We', 'were', 'reading', 'the', 'menu', 'when', 'the', 'waiter', 'came.']], why: "**came** (qisqa) va **were reading** (uzun)." },
      { k: 'translate', uz: "Men telefonda gaplashayotganimda, kimdir eshikni taqillatdi.", a: ['While I was talking on the phone, somebody knocked on the door', 'While I was talking on the phone, someone knocked on the door', 'Somebody knocked on the door while I was talking on the phone', 'Someone knocked on the door while I was talking on the phone', 'I was talking on the phone when somebody knocked on the door', 'I was talking on the phone when someone knocked on the door'], why: "**was talking** (uzun) + **knocked** (qisqa)." },
      { k: 'translate', uz: "Yomg'ir yog'a boshlaganda, biz bog'da o'tirgan edik.", a: ['We were sitting in the garden when it started to rain', 'When it started to rain, we were sitting in the garden', 'We were sitting in the garden when it started raining', 'When it started raining, we were sitting in the garden'], why: "**were sitting** (uzun) + **started** (qisqa)." },
    ],
  },
  {
    id: 'u12-l5-d1',
    title: 'Used to + V1',
    titleUz: 'Used to: avval shunday edi',
    goal: "**used to + V1**, **didn't use to** va **Did you use to…?** ni hamda *used to* va Past Simple farqini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*I ___ play chess every day when I was a child.*', opts: ['used to', 'use to', 'am used to', 'used'], a: 0, why: "Darak gapda **used to + V1** (d bilan)." },
      { k: 'choice', q: '*Did you ___ to live in Bukhara?*', opts: ['use', 'used', 'using', 'uses'], a: 0, why: "**Did** dan keyin asosiy shakl: **use to**." },
      { k: 'match', pairs: [['childhood', 'bolalik'], ['grow up', "ulg'ayib kamolga yetmoq"], ['in those days', "o'sha kunlarda"], ['no longer', 'endi ... emas'], ['neighbourhood', 'mahalla']] },
      { k: 'fill', q: "She didn't ___ to like coffee, but now she loves it.", a: ['use'], uz: "U avval kofeni yoqtirmas edi, hozir esa juda yaxshi ko'radi.", why: "**didn't** dan keyin: **use to**." },
      { k: 'fill', q: 'We ___ to eat plov every Sunday, but now we are too busy.', a: ['used'], uz: "Biz avval har yakshanba palov yer edik.", why: "Darak gapda **used to**." },
      { k: 'listen', say: "I didn't use to like running.", opts: ["I didn't use to like running.", "I didn't used to like running.", "I don't use to like running.", "I didn't like running."], a: 0, why: "**didn't use to** — *used* emas." },
      { k: 'tf', q: "*I used to go to Paris three times.* — to'g'ri gap.", a: false, why: "Sanoq (**three times**) bilan **Past Simple**: *I went to Paris three times.*" },
      { k: 'order', uz: "Ular avval hovlida futbol o'ynashar edi.", words: ['They', 'used', 'to', 'play', 'football', 'in', 'the', 'yard.'], extra: ['use', 'playing'], why: "**used to + V1**." },
      { k: 'fix', wrong: 'She used to went to the gym every day.', a: ['She used to go to the gym every day.'], hint: "used to dan keyin", why: "**used to + V1**: *go*, *went* emas." },
      { k: 'fix', wrong: 'We use to live near the sea.', a: ['We used to live near the sea.'], hint: 'used to', why: "Darak gapda **used** (d bilan)." },
      { k: 'fix', wrong: 'He used to live in Tashkent for ten years.', a: ['He lived in Tashkent for ten years.'], hint: 'Aniq muddat', why: "Aniq muddat (**for ten years**) bilan **Past Simple**." },
      { k: 'translate', uz: "Avval biz televizor ko'rmas edik.", a: ["We didn't use to watch TV", 'We did not use to watch TV', "We didn't use to watch television", 'We did not use to watch television'], why: "**didn't use to + V1**." },
    ],
  },
  {
    id: 'u12-l6-d1',
    title: 'Because, so, but, although',
    titleUz: "Because, so, but, although: sabab va qarama-qarshilik",
    goal: "Gaplarni **because / so / but / although** bilan ma'noga qarab bog'lashni va ikkitasini birga ishlatmaslikni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*It was cold, ___ I took a coat.*', opts: ['so', 'because', 'although', 'but'], a: 0, why: "Sovuq — sabab, palto olish — natija → **so**." },
      { k: 'choice', q: '*I took a coat ___ it was cold.*', opts: ['because', 'so', 'although', 'but'], a: 0, why: "Sababni bildiradi → **because**." },
      { k: 'choice', q: '*___ it was cold, we went swimming.*', opts: ['Although', 'Because', 'So', 'And'], a: 0, why: "Kutilmagan natija (sovuq edi, lekin suzdik) → **Although**." },
      { k: 'match', pairs: [['because', 'chunki'], ['so', 'shuning uchun'], ['but', 'lekin'], ['although', 'garchi'], ['because of', '... tufayli']] },
      { k: 'fill', q: 'The film was long, ___ it was interesting.', a: ['but'], hint: 'Qarama-qarshilik', uz: "Film uzun edi, lekin qiziq edi.", why: "Qarama-qarshilik, gap orasida → **but**." },
      { k: 'fill', q: "___ I was hungry, I didn't eat anything.", a: ['Although'], uz: "Garchi qornim och bo'lsa ham, hech narsa yemadim.", why: "Gap boshida **Although** + to'liq gap." },
      { k: 'listen', say: 'We stayed at home because it was raining.', opts: ['We stayed at home because it was raining.', 'We stayed at home although it was raining.', 'It was raining, so we stayed at home.', 'We stayed at home because it rained.'], a: 0, why: "**because** — sabab." },
      { k: 'tf', q: "*I was ill, so I stayed at home.* — **so** sababni bildiradi.", a: false, why: "**so** — natijani bildiradi; sabab — *I was ill*, natija — *I stayed at home*." },
      { k: 'fix', wrong: 'Because it rained, so we stayed at home.', a: ['Because it rained, we stayed at home.', 'It rained, so we stayed at home.'], hint: "Bitta gapda ikkalasi emas", why: "Bitta gapda faqat bittasi: **because** *yoki* **so**." },
      { k: 'fix', wrong: 'Although he was poor, but he was happy.', a: ['Although he was poor, he was happy.', 'He was poor, but he was happy.'], hint: "Ikkalasi birga kelmaydi", why: "**although** va **but** birga ishlatilmaydi." },
      { k: 'order', uz: "Garchi charchagan bo'lsak ham, shaharni ko'rgani chiqdik.", words: ['Although', 'we', 'were', 'tired,', 'we', 'went', 'out', 'to', 'see', 'the', 'city.'], extra: ['but', 'so'], alt: [['We', 'went', 'out', 'to', 'see', 'the', 'city', 'although', 'we', 'were', 'tired.']], why: "**Although** dan keyin *but* kerak emas." },
      { k: 'translate', uz: "Yo'l yomon edi, shuning uchun safar uzoq cho'zildi.", a: ['The road was bad, so the journey was long', 'The road was bad, so the trip was long', 'The road was bad, so the journey took a long time', 'The road was bad, so the trip took a long time'], why: "Sabab, **so**, natija." },
    ],
  },
];
