/**
 * Writes api/_lib/data-course.ts: a compact, static copy of the course outline (levels, units, lessons, words and key
 * takeaways) for the public SEO pages under /ingliz-tili-darslari. The app itself loads lessons from src/; the
 * serverless pages must not import them (they are large), so this file is generated and committed.
 *
 *   npx tsx scripts/build-course-seo.ts
 */
import { writeFileSync } from 'node:fs';
import { LEVELS, WRITTEN_UNITS, loadUnit } from '../src/features/learn/course';
import { UNIT_EXTRAS } from '../src/features/learn/unit-extras';

const plain = (s: string) => s.replace(/[*`_]/g, '').replace(/\\n|\n/g, ' ').replace(/\s+/g, ' ').trim();
const slugify = (s: string) => s.toLowerCase().replace(/[ʻʼ’‘`´']/g, '').normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60);
const LEVEL_SLUG: Record<string, string> = { beginner: 'beginner', a1: 'elementary', a2: 'pre-intermediate' };

const levels = [];
for (const level of LEVELS.filter((l) => LEVEL_SLUG[l.id])) {
  const used = new Set<string>();
  const units = [];
  for (const unit of WRITTEN_UNITS.filter((u) => u.level === level.id)) {
    const lessons = await loadUnit(unit.id);
    units.push({
      id: unit.id, n: unit.n, title: unit.title, titleUz: unit.titleUz, description: plain(unit.description),
      canDo: UNIT_EXTRAS[unit.id]?.canDo ?? [],
      lessons: lessons.map((l) => {
        let slug = slugify(l.title) || l.id;
        if (used.has(slug)) slug = `${slug}-${l.id}`;
        used.add(slug);
        return {
          id: l.id, slug, title: l.title, titleUz: l.titleUz, goal: plain(l.goal),
          words: l.words.map((w) => ({ en: w.en, uz: w.uz, ipa: w.ipa ?? '' })),
          summary: l.summary.map(plain),
        };
      }),
    });
  }
  levels.push({ id: level.id, slug: LEVEL_SLUG[level.id], title: level.title, cefr: level.cefr, text: plain(level.text), units });
}

const out = `// Generated by scripts/build-course-seo.ts. Do not edit by hand.
export type SeoWord = { en: string; uz: string; ipa: string };
export type SeoLesson = { id: string; slug: string; title: string; titleUz: string; goal: string; words: SeoWord[]; summary: string[] };
export type SeoUnit = { id: string; n: number; title: string; titleUz: string; description: string; canDo: string[]; lessons: SeoLesson[] };
export type SeoLevel = { id: string; slug: string; title: string; cefr: string; text: string; units: SeoUnit[] };

export const COURSE: SeoLevel[] = ${JSON.stringify(levels)};
`;
writeFileSync('api/_lib/data-course.ts', out);
console.log(`${levels.length} levels, ${levels.reduce((n, l) => n + l.units.reduce((m, u) => m + u.lessons.length, 0), 0)} lessons, ${Math.round(out.length / 1024)} KB`);
