import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u15-l1-d1',
    title: "Mustn't or don't have to?",
    titleUz: "Must, have to, mustn't, don't have to",
    goal: "**mustn't** (taqiq) va **don't have to** (shart emas) farqini hamda **has to / had to** shakllarini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*You ___ smoke here. It is forbidden.*', opts: ["mustn't", "don't have to", 'must', "doesn't have to"], a: 0, why: 'Taqiq → **mustn\'t**.' },
      { k: 'choice', q: '*Tomorrow is a holiday. We ___ go to work.*', opts: ["don't have to", "mustn't", 'must', 'has to'], a: 0, why: 'Ishga borish shart emas → **don\'t have to**.' },
      { k: 'match', pairs: [["You mustn't park here.", "Bu yerga qo'yish taqiqlangan."], ["You don't have to park here.", "Bu yerga qo'yishingiz shart emas."], ['I have to wear a uniform.', 'Men forma kiyishim kerak.'], ['She had to wait.', "U kutishga majbur bo'ldi."]] },
      { k: 'fill', q: 'My brother ___ to get up at six every day.', a: ['has'], uz: 'Akam har kuni oltida turishi kerak.', why: '**he** bilan → **has to**.' },
      { k: 'fill', q: "Laylo ___ have to cook today. We are going to a restaurant.", a: ["doesn't", 'does not'], uz: 'Laylo bugun ovqat pishirishi shart emas.', why: '**she** + inkor → **doesn\'t have to**.' },
      { k: 'fill', q: 'I was late, so I ___ to take a taxi.', a: ['had'], uz: "Kech qoldim, shuning uchun taksi olishga to'g'ri keldi.", why: 'O\'tgan zamon → **had to**.' },
      { k: 'tf', q: '*You must to wear a seat belt.* — to\'g\'ri gap.', a: false, why: '**must** dan keyin **to** yo\'q: *You must wear a seat belt.*' },
      { k: 'listen', say: "You mustn't be late for the exam.", opts: ["You mustn't be late for the exam.", "You don't have to be late for the exam.", 'You must be late for the exam.', "You mustn't be late for the lesson."], a: 0, why: '**mustn\'t** — kechikish taqiqlanadi.' },
      { k: 'order', uz: "Dushanba kuni maktabga borishimiz shart emas.", words: ['We', "don't", 'have', 'to', 'go', 'to', 'school', 'on', 'Monday'], extra: ["mustn't", 'must'], why: 'Shart emas → **don\'t have to**.' },
      { k: 'fix', wrong: "You mustn't buy a ticket. The museum is free today.", a: ["You don't have to buy a ticket. The museum is free today.", 'You do not have to buy a ticket. The museum is free today.'], hint: 'Taqiq emas, shart emas', why: 'Bilet olish shart emas → **don\'t have to** (*mustn\'t* — taqiq).' },
      { k: 'fix', wrong: 'Does she has to wear a uniform?', a: ['Does she have to wear a uniform?'], why: '**does** dan keyin fe\'l **1-shaklda**: *have to*.' },
      { k: 'translate', uz: 'Bu yerda tez haydashingiz mumkin emas.', a: ["You mustn't drive fast here", 'You must not drive fast here', "You can't drive fast here", 'You cannot drive fast here'], why: 'Taqiq → **mustn\'t** + fe\'l (to yo\'q).' },
    ],
  },
  {
    id: 'u15-l2-d1',
    title: 'Giving advice',
    titleUz: 'Should / shouldn\'t: maslahat berish',
    goal: "**should / shouldn't** + fe'l, maslahat iboralari va **advice** ni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*You look tired. You ___ go to bed early.*', opts: ['should', 'should to', 'shoulds', 'are should'], a: 0, why: '**should** + fe\'l 1-shaklda, **to** yo\'q.' },
      { k: 'choice', q: '*I have a headache. What ___ I do?*', opts: ['should', 'do', 'must to', 'am'], a: 0, why: 'Maslahat so\'rash: **What should I do?**' },
      { k: 'match', pairs: [['I think you should', 'Menimcha, sen … kerak'], ["I don't think you should", 'Menimcha, sen … kerak emas'], ["If I were you, I'd", "Sening o'rningda bo'lsam, men …"], ["Why don't you …?", "… qilib ko'rmaysanmi?"], ['Should I …?', '… qilsammi?']] },
      { k: 'fill', q: "You ___ eat so much sugar. It's bad for you.", a: ["shouldn't", 'should not'], uz: "Shuncha ko'p shakar yemasligingiz kerak.", why: 'Salbiy maslahat → **shouldn\'t**.' },
      { k: 'fill', q: 'Her teeth hurt. She ___ see a dentist.', a: ['should'], uz: "Tishlari og'riyapti. U tish shifokoriga borishi kerak.", why: 'Maslahat → **should** + fe\'l.' },
      { k: 'fill', q: "If I ___ you, I'd take a taxi.", a: ['were'], uz: "Sening o'rningda bo'lsam, taksi olardim.", why: '**If I were you** — *I* bilan ham **were**.' },
      { k: 'tf', q: '*He should to see a doctor.* — to\'g\'ri gap.', a: false, why: '**should** dan keyin **to** yo\'q: *He should see a doctor.*' },
      { k: 'listen', say: 'You should take a break.', opts: ['You should take a break.', "You shouldn't take a break.", 'You should take a bus.', 'You should make a break.'], a: 0, why: '**take a break** — tanaffus qilmoq.' },
      { k: 'order', uz: 'Menimcha, sen shifokorga borishing kerak.', words: ['I', 'think', 'you', 'should', 'see', 'a', 'doctor'], extra: ['to', 'must'], why: '**I think you should** + fe\'l.' },
      { k: 'fix', wrong: 'You should to drink more water.', a: ['You should drink more water.'], hint: 'Ortiqcha so\'z', why: '**should** dan keyin **to** kerak emas.' },
      { k: 'fix', wrong: 'Can you give me an advice, please?', a: ['Can you give me some advice, please?', 'Can you give me advice, please?', 'Can you give me a piece of advice, please?'], hint: 'advice sanalmaydi', why: '**advice** sanalmaydi: *some advice*, *a piece of advice*.' },
      { k: 'translate', uz: "Sen ko'proq uxlashing kerak.", a: ['You should sleep more', 'You should get more sleep'], why: '**You should** + fe\'l: *sleep more*.' },
    ],
  },
  {
    id: 'u15-l3-d1',
    title: 'Can, could, be able to',
    titleUz: "Can, could, be able to: o'tmish va kelajak",
    goal: "**can / could / was able to / will be able to** ni vaqtga qarab tanlashni va *Yesterday I can't* xatosini tuzatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Yesterday I ___ come to the party. I was ill.*', opts: ["couldn't", "can't", "won't be able to", 'can'], a: 0, why: 'Kecha (o\'tgan zamon) → **couldn\'t**.' },
      { k: 'match', pairs: [['can', 'hozir qila oladi'], ['could', "o'tmishda qila olardi"], ['was able to', "o'tmishda (bir marta) uddaladi"], ['will be able to', 'kelajakda qila oladi'], ['Could I …?', "muloyim ruxsat so'rash"]] },
      { k: 'fill', q: 'Yesterday I ___ able to finish my work early.', a: ['was'], uz: 'Kecha ishimni erta tugatishga ulgurdim.', why: 'Bir marta uddalagan voqea → **was able to**.' },
      { k: 'fill', q: 'My grandfather ___ swim very well when he was young.', a: ['could', 'was able to'], uz: 'Bobom yoshligida juda yaxshi suzardi.', why: 'O\'tmishdagi umumiy qobiliyat → **could**.' },
      { k: 'fill', q: "We ___ be able to come tomorrow. We're busy.", a: ["won't", 'will not'], uz: 'Ertaga kela olmaymiz. Biz bandmiz.', why: 'Kelajak → **won\'t be able to**.' },
      { k: 'tf', q: '*I will can help you tomorrow.* — to\'g\'ri gap.', a: false, why: '**will can** yo\'q: *I will be able to help you.*' },
      { k: 'listen', say: "I couldn't find my phone.", opts: ["I couldn't find my phone.", "I can't find my phone.", "I couldn't find my keys.", 'I could find my phone.'], a: 0, why: '**couldn\'t** — o\'tmishda topa olmadim.' },
      { k: 'order', uz: 'Kecha men u bilan gaplasha olmadim.', words: ['Yesterday', 'I', "couldn't", 'talk', 'to', 'him'], extra: ["can't", 'can'], why: 'Kecha → **couldn\'t** + fe\'l (to yo\'q).' },
      { k: 'fix', wrong: "Yesterday I can't call you because my phone was dead.", a: ["Yesterday I couldn't call you because my phone was dead.", "Yesterday I wasn't able to call you because my phone was dead."], hint: 'Zamonni tekshiring', why: '*Yesterday* → o\'tgan zamon: **couldn\'t** yoki **wasn\'t able to**.' },
      { k: 'fix', wrong: 'She can to swim very well.', a: ['She can swim very well.'], why: '**can** dan keyin **to** yo\'q.' },
      { k: 'fix', wrong: "I haven't can see him lately.", a: ["I haven't been able to see him lately."], hint: 'Present Perfect', why: '*have* dan keyin **been able to**; *can* shakli yo\'q.' },
      { k: 'translate', uz: 'Ertaga men kela olmayman.', a: ["I won't be able to come tomorrow", 'I will not be able to come tomorrow', "I can't come tomorrow", 'I cannot come tomorrow'], why: 'Kelajak → **won\'t be able to** + fe\'l.' },
    ],
  },
  {
    id: 'u15-l4-d1',
    title: 'Polite requests and offers',
    titleUz: 'Muloyim iltimos va taklif',
    goal: "**Could you…? I'd like… Shall I…? Would you like…?** va **borrow / lend** ni mashq qilasiz; qo'pol buyruqlarni muloyim qilasiz.",
    exercises: [
      { k: 'choice', q: 'Kafeda qaysi gap eng muloyim?', opts: ['Give me tea.', 'I want tea.', "I'd like a tea, please.", 'Tea!'], a: 2, why: 'Kafeda **I\'d like…** + **please** muloyim eshitiladi.' },
      { k: 'choice', q: '*Can I ___ your pen? I need to write something.*', opts: ['borrow', 'lend', 'give', 'bring'], a: 0, why: '**borrow** — so\'rab olmoq (men olaman).' },
      { k: 'match', pairs: [['Could you help me?', 'Menga yordam bera olasizmi?'], ['Shall I carry your bag?', "Sumkangizni ko'tarib beraymi?"], ['Would you like some tea?', 'Choy xohlaysizmi?'], ["I'll open the door.", 'Men eshikni ochaman.'], ["No, thanks. I'm fine.", "Yo'q, rahmat, hojat yo'q."]] },
      { k: 'fill', q: 'Could you ___ me the salt, please?', a: ['pass', 'give'], uz: 'Tuzni uzatib yuborolasizmi, iltimos?', why: '**Could you** + fe\'l 1-shaklda: *pass me*.' },
      { k: 'fill', q: "It's heavy. ___ I carry it for you?", a: ['Shall', 'Can', 'Could'], uz: "U og'ir. Sizga ko'tarib beraymi?", why: 'Yordam taklifi: **Shall I…?**' },
      { k: 'tf', q: '*Do you like some tea?* — choy taklif qilishning to\'g\'ri usuli.', a: false, why: 'Taklif: **Would you like some tea?** (*Do you like…?* — odatda yoqtirish).' },
      { k: 'listen', say: 'Could you open the window, please?', opts: ['Could you open the window, please?', 'Could I open the window, please?', 'Could you close the window, please?', 'Would you open the door, please?'], a: 0, why: '**Could you** — iltimos, **open the window**.' },
      { k: 'order', uz: 'Derazani yopib bera olasizmi, iltimos?', words: ['Could', 'you', 'close', 'the', 'window', 'please'], extra: ['I', 'want'], why: '**Could you** + fe\'l: muloyim iltimos.' },
      { k: 'fix', wrong: 'Give me a glass of water!', a: ['Could you give me a glass of water?', 'Could you give me a glass of water, please?', 'Can you give me a glass of water, please?', 'Can you give me a glass of water?'], hint: 'Muloyim qiling', why: 'Buyruq qo\'pol; iltimos: **Could you…?**' },
      { k: 'fix', wrong: 'I want a coffee, please.', a: ["I'd like a coffee, please.", 'I would like a coffee, please.'], hint: 'Kafedagi iborani almashtiring', why: 'Kafeda **I want** qo\'pol; **I\'d like** muloyim.' },
      { k: 'fix', wrong: 'Can I lend your phone?', a: ['Can I borrow your phone?'], hint: 'Kim oladi?', why: 'Men olaman → **borrow**; **lend** — men beraman.' },
      { k: 'translate', uz: 'Siz men bilan kofe ichishni xohlaysizmi?', a: ['Would you like to have coffee with me', 'Would you like to have a coffee with me', 'Would you like to drink coffee with me', 'Would you like to drink a coffee with me'], why: '**Would you like to** + fe\'l — taklif.' },
    ],
  },
];
