import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u6-l4-d1',
    title: 'Mine, yours, whose?',
    titleUz: 'Mine, yours va whose',
    goal: "**my / mine**, **yours, hers, ours, theirs** va **whose / who's** ni adashtirmaslikni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*This is my bag. This bag is ___.*', opts: ['my', 'mine', 'me', "mine's"], a: 1, why: "Ot yo'q — **mine** (meniki)." },
      { k: 'choice', q: '*These keys are ___. (we)*', opts: ['our', "our's", 'ours', 'us'], a: 2, why: "Otsiz va apostrofsiz: **ours**." },
      { k: 'match', pairs: [['my', 'mine'], ['your', 'yours'], ['her', 'hers'], ['our', 'ours'], ['their', 'theirs']] },
      { k: 'fill', q: 'Is this your pen? — Yes, it is ___.', a: ['mine'], uz: "Bu sizning ruchkangizmi? — Ha, meniki.", why: "**I** nomidan otsiz — **mine**." },
      { k: 'fill', q: "That car isn't ours. It's ___. (they)", a: ['theirs'], uz: "U mashina bizniki emas. Ularniki.", why: "**they → theirs**, apostrofsiz." },
      { k: 'listen', say: 'Whose scarf is this?', opts: ['Whose scarf is this?', "Who's that?", 'Whose scarves are these?', 'Whose is that scarf?'], a: 0, why: "**Whose** — \"kimning\"." },
      { k: 'tf', q: "*Whose* va *who's* ni yozuvda aralashtirib bo'lmaydi: *Who's coat is this?* — to'g'ri gap.", a: false, why: "**Whose coat is this?** — \"kimning\" uchun **whose**. *Who's* = who is." },
      { k: 'order', uz: 'Bu kimning kalitlari?', words: ['Whose', 'keys', 'are', 'these'], extra: ["Who's", 'is'], why: "Ko'plik — **are these**." },
      { k: 'fix', wrong: 'The red car is her.', a: ['The red car is hers.'], hint: 'Ot yo\'q', why: "Ot kelmasa **hers** kerak." },
      { k: 'fix', wrong: 'This book is your\'s.', a: ['This book is yours.'], why: "**yours** — apostrofsiz." },
      { k: 'translate', uz: 'Bu telefon meniki emas.', a: ["This phone isn't mine", 'This phone is not mine', "This isn't my phone", 'This is not my phone'], why: "Otsiz — **mine**; ot bilan — **my phone**." },
      { k: 'dictation', say: "Whose umbrella is this? It's hers." },
    ],
  },
  {
    id: 'u6-l8-d1',
    title: 'A, an or the?',
    titleUz: 'A, an yoki the?',
    goal: "**a / an** va **the** ni to'g'ri tanlashni, kasb oldida **a** ni unutmaslikni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*My father is ___ engineer.*', opts: ['a', 'an', 'the', '—'], a: 1, why: "Kasb + unli tovush: **an engineer**." },
      { k: 'choice', q: '*I have a dog. ___ dog is very big.*', opts: ['A', 'An', 'The', '—'], a: 2, why: "Ikkinchi marta tilga olindi — **The dog**." },
      { k: 'match', pairs: [['the sun', 'quyosh'], ['the sky', 'osmon'], ['the world', 'dunyo'], ['at work', 'ishda'], ['by bus', 'avtobusda']] },
      { k: 'fill', q: 'It takes ___ hour to get there.', a: ['an', 'one'], hint: 'h o\'qilmaydi', why: "**hour** unli tovush bilan boshlanadi: **an hour**." },
      { k: 'fill', q: 'My sister is ___ teacher.', a: ['a'], uz: "Opam o'qituvchi.", why: "Kasb birlikda — **a teacher**." },
      { k: 'tf', q: "*I'm student.* — to'g'ri gap.", a: false, why: "Kasb oldida **a** shart: *I'm a student.*" },
      { k: 'listen', say: 'The sun is hot today.', opts: ['The sun is hot today.', 'A sun is hot today.', 'The sun is hot tonight.', 'The sea is hot today.'], a: 0, why: "Yagona narsa — **the sun**." },
      { k: 'order', uz: 'Men ishga avtobusda boraman.', words: ['I', 'go', 'to', 'work', 'by', 'bus'], extra: ['the', 'a'], why: "**by bus** — artiklsiz." },
      { k: 'fix', wrong: 'My brother is doctor.', a: ['My brother is a doctor.'], hint: 'Artikl yetishmayapti', why: "Kasb oldida **a** tushib qolgan." },
      { k: 'fix', wrong: 'The life is hard.', a: ['Life is hard.'], hint: 'Umuman hayot haqida gap ketyapti', why: "Umumiy tushuncha — **artiklsiz**: *Life is hard.*" },
      { k: 'translate', uz: 'Men hozir uyda emasman, ishdaman.', a: ["I'm not at home, I'm at work", "I'm at work", 'I am at work', "I'm at work now", "I'm not at home. I'm at work"], why: "**at work** — artiklsiz." },
      { k: 'dictation', say: 'I saw a film. The film was good.' },
    ],
  },
  {
    id: 'u6-l8-d2',
    title: 'Articles: tricky mix',
    titleUz: 'Artikllar: qiyin aralash mashqlar',
    goal: "**the** ni ortiqcha qo'ymaslik (shahar, til, sport, ovqat) va **a / an / the** ni ajratishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*We play ___ football on Sundays.*', opts: ['the', 'a', 'an', '—'], a: 3, why: "Sport — **artiklsiz**." },
      { k: 'choice', q: '*I live in ___ Tashkent.*', opts: ['the', 'a', '—', 'an'], a: 2, why: "Shahar nomi oldida artikl yo'q." },
      { k: 'choice', q: '*She is ___ only doctor in the village.*', opts: ['a', 'the', 'an', '—'], a: 1, why: "**the only** — yagona." },
      { k: 'fill', q: 'Can you close ___ door, please?', a: ['the'], uz: "Eshikni yopib yuborasizmi?", why: "Ikkalamiz biladigan eshik — **the door**." },
      { k: 'fill', q: 'He has ___ university degree.', a: ['a'], hint: '"yu" tovushi', why: "**university** \"yu\" bilan boshlanadi: **a university**." },
      { k: 'tf', q: "*We have the breakfast at seven.* — to'g'ri gap.", a: false, why: "Ovqat nomlari artiklsiz: *We have breakfast at seven.*" },
      { k: 'tf', q: "*I go to bed at eleven.* — to'g'ri gap.", a: true, why: "**go to bed** — turg'un ibora, artiklsiz." },
      { k: 'order', uz: 'Quyosh bugun juda issiq.', words: ['The', 'sun', 'is', 'very', 'hot', 'today'], extra: ['A', 'an'], why: "Yagona narsa — **the sun**." },
      { k: 'fix', wrong: 'I study the English.', a: ['I study English.'], hint: 'Til nomi', why: "Til nomi oldida artikl yo'q." },
      { k: 'fix', wrong: 'She is at the work now.', a: ['She is at work now.', "She's at work now."], why: "**at work** — artiklsiz." },
      { k: 'fix', wrong: 'We live in a same street.', a: ['We live in the same street.', 'We live on the same street.'], why: "**the same** — doim **the** bilan." },
      { k: 'translate', uz: 'Mening otam muhandis, onam esa shifokor.', a: ['My father is an engineer and my mother is a doctor', 'My dad is an engineer and my mum is a doctor', 'My father is an engineer, and my mother is a doctor', 'My dad is an engineer and my mom is a doctor'], why: "Ikkala kasb oldida ham artikl: **an engineer**, **a doctor**." },
    ],
  },
];
