import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u10-l3-d1',
    title: 'Could I / Could you?',
    titleUz: 'Could I yoki Could you?',
    goal: "Mehmonxonada **Could I…?** (ruxsat) va **Could you…?** (iltimos) ni adashtirmay, to'g'ri javob berishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Could I ___ my bag here?*', opts: ['leave', 'to leave', 'leaving', 'left'], a: 0, why: '**Could I + V1**: *Could I **leave**…?* (*to* va *-ing* yo\'q).' },
      { k: 'choice', q: "Xodimdan taksi chaqirib berishni so'rayapsiz. Qaysi gap to'g'ri?", opts: ['Could you call a taxi, please?', 'Could I call a taxi, please?', 'Could you to call a taxi, please?', 'You could call a taxi, please?'], a: 0, why: "Boshqadan iltimos → **Could you + V1…, please?**" },
      { k: 'choice', q: '*My shower doesn\'t work. ___ send someone, please?*', opts: ['Could you', 'Could I', 'Could he', 'Do you'], a: 0, why: "Kimdir yuborishi kerak → siz (xodim) qilasiz: **Could you…?**" },
      { k: 'match', pairs: [['single room', 'bir kishilik xona'], ['double room', 'ikki kishilik xona'], ['towel', 'sochiq'], ['lift', 'lift'], ['view', 'manzara']] },
      { k: 'fill', q: 'Could I use the phone? — Yes, you ___.', a: ['can'], uz: 'Telefondan foydalansam bo\'ladimi? — Ha, bo\'ladi.', why: "Ruxsat berganda **can** aytiladi: *Yes, you can.* (*Yes, you could* tabiiy emas)." },
      { k: 'tf', q: '*Could I sit here?* — *Yes, you could.* tabiiy javob.', a: false, why: "Ruxsat berishda **Yes, you can.** yoki **Yes, of course.** deyiladi." },
      { k: 'listen', say: 'Could you speak more slowly, please?', opts: ['Could you speak more slowly, please?', 'Could I speak more slowly, please?', 'Can you speak more slowly, please?'], a: 0, why: '**Could you** — siz sekinroq gapirasiz.' },
      { k: 'order', uz: 'Menga ikkita sochiq bersangiz, iltimos.', words: ['Could', 'I', 'have', 'two', 'towels', 'please'], extra: ['to', 'you'], why: '**Could I have…?** — biror narsa so\'rash.' },
      { k: 'fix', wrong: 'Could I to leave my bag here?', a: ['Could I leave my bag here?'], hint: 'Ortiqcha so\'z bor', why: '**Could I** dan keyin **to** qo\'yilmaydi: *Could I **leave**…?*' },
      { k: 'fix', wrong: 'Could I call a taxi for me, please?', a: ['Could you call a taxi for me, please?'], hint: 'Taksini kim chaqiradi?', why: "Taksini xodim chaqiradi → **Could you**…?" },
      { k: 'translate', uz: 'Ertaga meni soat yettida uyg\'otib qo\'ya olasizmi?', a: ['Could you wake me up at seven tomorrow', 'Could you wake me up at seven tomorrow, please', 'Could you wake me up tomorrow at seven', 'Could you wake me up tomorrow at seven, please', 'Can you wake me up at seven tomorrow', 'Can you wake me up tomorrow at seven', 'Could you wake me up at 7 tomorrow', 'Could you wake me up tomorrow at 7'], why: '**Could you wake me up…?** — boshqadan iltimos.' },
      { k: 'dictation', say: 'Could you send someone to my room, please?' },
    ],
  },
  {
    id: 'u10-l4-d1',
    title: 'will or going to?',
    titleUz: 'will yoki going to?',
    goal: "Oldindan reja (**going to**), shu zahoti qaror, taklif va va'da (**will**) ni ajratishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Look at those grey clouds! It ___ rain.*', opts: ['is going to', 'will to', 'going to', 'goes to'], a: 0, why: "Ko'z oldida dalil (bulutlar) → **is going to** rain." },
      { k: 'choice', q: '*The phone is ringing! I ___ answer it.*', opts: ["'ll", "'m going", 'going to', 'answer'], a: 0, why: "Qaror hozir qilindi → **I'll** answer it." },
      { k: 'choice', q: "*Kecha chipta oldim.* — *I ___ visit my aunt next week.*", opts: ["'m going to", "'ll", 'will to', 'am'], a: 0, why: "Oldindan reja (chipta olingan) → **I'm going to** visit." },
      { k: 'match', pairs: [["It's going to rain.", 'dalil bor (bulutlar)'], ["I'll carry your bag.", 'yordam taklifi'], ["I'm going to fly to Dubai.", 'oldindan reja'], ["I'll call you tonight.", "va'da"], ['Shall I open the window?', '…aymi? (taklif)']] },
      { k: 'fill', q: 'Your bag looks heavy. ___ I carry it for you?', a: ['Shall', 'Can', 'Should', 'Could', 'May'], uz: "Sumkangiz og'ir ko'rinadi. Ko'tarib beraymi?", why: 'Yordam taklifi savolda → **Shall I…?**' },
      { k: 'fill', q: "I promise I ___ forget your souvenir.", a: ["won't", 'will not'], uz: "Va'da beraman, sovg'angni unutmayman.", why: "Va'da → **will**; inkori **won't** (*want* emas!)." },
      { k: 'listen', say: "We're going to stay in a hotel.", opts: ["We're going to stay in a hotel.", "We'll stay in a hotel.", 'We went to stay in a hotel.'], a: 0, why: "**We're going to** — reja." },
      { k: 'order', uz: 'Kelasi hafta mashina ijaraga olmoqchimiz.', words: ["We're", 'going', 'to', 'rent', 'a', 'car', 'next', 'week'], extra: ['will'], alt: [['We', 'are', 'going', 'to', 'rent', 'a', 'car', 'next', 'week']], why: '**am / is / are + going to + V1**.' },
      { k: 'fix', wrong: 'They going to rent a car next month.', a: ['They are going to rent a car next month.', "They're going to rent a car next month."], hint: 'Fe\'l yetishmayapti', why: '**going to** dan oldin **are** kerak: *They **are** going to…*' },
      { k: 'fix', wrong: 'The phone is ringing! I answer it.', a: ["The phone is ringing! I'll answer it.", 'The phone is ringing! I will answer it.'], hint: 'Kelasi zamon kerak', why: "Hozirgi qaror → **I'll answer**. O'zbekcha \"javob beraman\" inglizchada oddiy zamon emas." },
      { k: 'translate', uz: "Ertaga senga qo'ng'iroq qilaman, va'da beraman.", a: ["I promise I'll call you tomorrow", 'I promise I will call you tomorrow', "I'll call you tomorrow, I promise", 'I will call you tomorrow, I promise', "I'll call you tomorrow. I promise"], why: "Va'da → **I'll call**." },
      { k: 'dictation', say: 'Shall I call a taxi for you?' },
    ],
  },
  {
    id: 'u10-l6-d1',
    title: 'have to or don\'t have to?',
    titleUz: "have to yoki don't have to?",
    goal: "**has to**, **don't have to** (shart emas), **Do I have to…?** va **had to** shakllarini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*My sister ___ to get up at six.*', opts: ['have', 'has', 'is', 'does'], a: 1, why: '**she** → **has to**.' },
      { k: 'choice', q: "*It's free for students. They ___ pay.*", opts: ["don't have to", "can't", 'have to', "doesn't have to"], a: 0, why: "Bepul → to'lash **shart emas**; *they* → **don't have to**." },
      { k: 'match', pairs: [['have to', 'kerak, majburman'], ["don't have to", 'shart emas'], ['had to', "to'g'ri keldi (o'tgan)"], ['Do I have to…?', '…ishim kerakmi?'], ['fill in', "to'ldirmoq"]] },
      { k: 'fill', q: '___ you have to wear a uniform at work?', a: ['Do'], uz: 'Ishda forma kiyishingiz kerakmi?', why: '**you** bilan savol: **Do** you have to…?' },
      { k: 'fill', q: 'Last week I ___ to wait for an hour.', a: ['had'], uz: "O'tgan hafta bir soat kutishimga to'g'ri keldi.", why: "O'tgan zamon → **had to**." },
      { k: 'choice', q: '*Does Aziz have to work on Saturday?* — No, ___.', opts: ["he doesn't", "he hasn't", "he isn't", "he doesn't have"], a: 0, why: "**Does…?** savoliga → **No, he doesn't.**" },
      { k: 'tf', q: '*Does he has to go?* — to\'g\'ri savol.', a: false, why: "**Does** dan keyin **have**: *Does he **have** to go?*" },
      { k: 'listen', say: "She doesn't have to pay.", opts: ["She doesn't have to pay.", 'She has to pay.', "She didn't have to pay."], a: 0, why: "**doesn't have to** — shart emas." },
      { k: 'order', uz: 'Ertaga erta turishim shart emas.', words: ['I', "don't", 'have', 'to', 'get', 'up', 'early', 'tomorrow'], extra: ["doesn't", 'must'], why: "Shart emas → **don't have to** + V1." },
      { k: 'fix', wrong: 'She have to wear a uniform.', a: ['She has to wear a uniform.'], why: '**she** bilan **has to**.' },
      { k: 'fix', wrong: "We didn't had to queue.", a: ["We didn't have to queue.", 'We did not have to queue.'], hint: 'didn\'t dan keyin qaysi shakl?', why: "**didn't** dan keyin fe'l **V1**: *didn't **have** to*." },
      { k: 'translate', uz: "Sen anketani to'ldirishing shart emas.", a: ["You don't have to fill in the form", "You don't have to fill in this form", "You don't have to fill out the form", "You don't have to fill out this form", 'You do not have to fill in the form', 'You do not have to fill in this form'], why: "Shart emas → **don't have to**." },
    ],
  },
  {
    id: 'u10-l7-d1',
    title: "must or mustn't?",
    titleUz: "must yoki mustn't?",
    goal: "Belgilarni **must / mustn't** bilan tushuntirishni va **mustn't** bilan **don't have to** farqini mashq qilasiz.",
    exercises: [
      { k: 'choice', q: 'Belgi: **NO PARKING**. *You ___ park here.*', opts: ["mustn't", 'must', 'have to', 'does'], a: 0, why: "**NO …** → taqiq: **mustn't**." },
      { k: 'choice', q: '*Drivers must ___ at a red light.*', opts: ['stop', 'to stop', 'stops', 'stopping'], a: 0, why: '**must + V1**: *must **stop***.' },
      { k: 'match', pairs: [['KEEP OFF THE GRASS', "You mustn't walk on the grass."], ['SILENCE', 'You must be quiet.'], ['DANGER! DEEP WATER', "You mustn't swim here."], ['DO NOT FEED THE ANIMALS', "You mustn't feed the animals."], ['FASTEN YOUR SEAT BELT', 'You must fasten your seat belt.']] },
      { k: 'fill', q: 'You ___ be quiet in the library.', a: ['must', 'have to'], uz: 'Kutubxonada jim bo\'lishingiz shart.', why: 'Qoida → **must** (yoki *have to*).' },
      { k: 'tf', q: "*You don't must smoke here.* — to'g'ri gap.", a: false, why: "**must** bilan **do** ishlatilmaydi: *You **mustn't** smoke here.*" },
      { k: 'listen', say: "You mustn't take photos here.", opts: ['You must take photos here.', "You mustn't take photos here.", "You don't take photos here."], a: 1, why: '"masnt" — **mustn\'t**.' },
      { k: 'choice', q: '*The museum is free on Sundays.* "Yakshanba kuni pul to\'lash shart emas" qaysi?', opts: ["You mustn't pay.", "You don't have to pay.", 'You must pay.', "You can't pay."], a: 1, why: "**Shart emas** (bepul) → **don't have to**. *mustn't* — taqiq." },
      { k: 'tf', q: '*You mustn\'t wear a tie.* — "Galstuk taqishingiz shart emas" degani.', a: false, why: "**mustn't** = taqiq, mumkin emas. \"Shart emas\" → *You **don't have to** wear a tie.*" },
      { k: 'order', uz: 'Bu yerda telefondan foydalanish mumkin emas.', words: ['You', "mustn't", 'use', 'your', 'phone', 'here'], extra: ['must', 'to'], why: "Taqiq → **mustn't + V1**." },
      { k: 'fix', wrong: 'He musts wear a uniform.', a: ['He must wear a uniform.'], why: "**must** -s olmaydi: hamma shaxs bilan **must**." },
      { k: 'fix', wrong: "You don't must park here.", a: ["You mustn't park here.", 'You must not park here.'], hint: 'Taqiq ma\'nosi', why: "**must** bilan **do** yo'q. Taqiq → **mustn't**." },
      { k: 'translate', uz: "Kecha kech ishlashimga to'g'ri keldi.", a: ['Yesterday I had to work late', 'I had to work late yesterday', 'I had to work late last night'], why: "**must** ning o'tgan zamoni yo'q → **had to**." },
    ],
  },
];
