import type { Drill } from '../../../types';

export const drills: Drill[] = [
  {
    id: 'u16-l1-d1',
    title: 'Present Perfect or Past Simple?',
    titleUz: 'Present Perfect yoki Past Simple?',
    goal: "Aniq vaqt bo'lsa **Past Simple**, tajriba va yangilik bo'lsa **Present Perfect** ni tanlashni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*I ___ him yesterday.*', opts: ['have seen', 'saw', 'have saw'], a: 1, why: "**yesterday** — aniq vaqt → Past Simple: **saw**." },
      { k: 'choice', q: '*___ you ever visited Bukhara?*', opts: ['Did', 'Have', 'Do'], a: 1, why: "Tajriba haqida savol: **Have you ever…?**" },
      { k: 'match', pairs: [['two days ago', 'ikki kun oldin'], ['last year', "o'tgan yili"], ['so far', 'hozirgacha'], ['twice', 'ikki marta'], ['recently', 'yaqinda']] },
      { k: 'fill', q: 'Have you cleaned your room ___?', a: ['yet'], uz: 'Xonangni hali yig\'ishtirdingmi?', why: "Savolda gap oxirida **yet** keladi." },
      { k: 'fill', q: 'We ___ to Bukhara last month. (go)', a: ['went'], why: "**last month** — aniq vaqt → Past Simple: **went**." },
      { k: 'tf', q: "*We have moved here three years ago.* — to'g'ri gap.", a: false, why: "**ago** bilan Past Simple kerak: *We moved here three years ago.*" },
      { k: 'listen', say: 'Have you ever eaten fish soup?', opts: ['Have you ever eaten fish soup?', 'Did you eat fish soup?', 'Have you eaten fish soup yet?', 'Do you eat fish soup?'], a: 0, why: "**Have you ever eaten…?** — tajriba haqida savol." },
      { k: 'order', uz: 'Dilnoza hozirgina ketdi.', words: ['Dilnoza', 'has', 'just', 'left'], extra: ['did', 'leave'], why: "**has just + V3** — hozirgina bo'lgan ish." },
      { k: 'fix', wrong: 'I have seen him yesterday.', a: ['I saw him yesterday.'], hint: "Aniq vaqt bor", why: "**yesterday** bilan **have** ishlatilmaydi: *I saw him yesterday.*" },
      { k: 'translate', uz: 'Biz allaqachon tushlik qilganmiz.', a: ["We've already had lunch", 'We have already had lunch', "We've had lunch already", 'We have had lunch already', 'We already had lunch'], why: "**already** — **have + V3** bilan: *We've already had lunch.*" },
      { k: 'dictation', say: 'Have you ever been abroad?' },
    ],
  },
  {
    id: 'u16-l1-d2',
    title: 'Present Perfect or Past Simple: tricky mix',
    titleUz: 'Present Perfect yoki Past Simple: qiyin aralash mashqlar',
    goal: "**ever, just, already, yet, ago, when** bilan tipik xatolarni topishni va ikki zamonni aralash gapda tanlashni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "Qaysi gap **to'g'ri**?", opts: ['She has gone to Paris in 2019.', 'She went to Paris in 2019.', 'She has been to Paris in 2019.', 'She goes to Paris in 2019.'], a: 1, why: "**in 2019** — aniq vaqt → Past Simple: **went**." },
      { k: 'choice', q: '*Have you ever been to Samarkand? — Yes, I have. I ___ there last spring.*', opts: ['have been', 'went', 'have gone', 'was go'], a: 1, why: "Tafsilot va **last spring** → Past Simple: **went**." },
      { k: 'choice', q: '*When ___ you buy this phone?*', opts: ['have', 'did', 'do', 'has'], a: 1, why: "**When** bilan savol → Past Simple: *did … buy*." },
      { k: 'fill', q: "It's the best film I have ___ seen.", a: ['ever'], uz: "Bu — men ko'rgan eng yaxshi film.", why: "*the best … I have **ever** seen* — qolip." },
      { k: 'fill', q: 'He ___ his keys two days ago. (lose)', a: ['lost'], why: "**two days ago** → Past Simple: **lost**." },
      { k: 'tf', q: "*When have you arrived?* — to'g'ri savol.", a: false, why: "**When** bilan Past Simple: *When did you arrive?*" },
      { k: 'tf', q: "*I've just seen Aziz.* — gap hozirgina bo'lgan ishni bildiradi.", a: true, why: "**just** + Present Perfect = *hozirgina*." },
      { k: 'fix', wrong: 'When have you bought this phone?', a: ['When did you buy this phone?'], hint: 'When bilan qaysi zamon?', why: "**When** bilan savol doim Past Simple: *When did you buy…?*" },
      { k: 'fix', wrong: 'We have moved here three years ago.', a: ['We moved here three years ago.'], why: "**ago** bilan **have** ishlatilmaydi → *We moved…*" },
      { k: 'fix', wrong: "I've finished my homework yet.", a: ["I've already finished my homework.", 'I have already finished my homework.', "I've finished my homework.", 'I have finished my homework.'], hint: 'yet darak gapda kelmaydi', why: "**yet** darak gapda ishlatilmaydi; *already* deymiz: *I've already finished.*" },
      { k: 'order', uz: "Siz hech suši tatib ko'rganmisiz?", words: ['Have', 'you', 'ever', 'tried', 'sushi'], extra: ['Did', 'try'], why: "**Have you ever + V3?** — tajriba haqida savol." },
      { k: 'translate', uz: "Men hali Seulga bormaganman, lekin 2022-yilda Istanbulga borganman.", a: ["I haven't been to Seoul yet, but I went to Istanbul in 2022", "I've not been to Seoul yet, but I went to Istanbul in 2022", 'I have not been to Seoul yet, but I went to Istanbul in 2022'], why: "Birinchi qism — **haven't been … yet**, ikkinchisida **in 2022** → **went**." },
    ],
  },
  {
    id: 'u16-l2-d1',
    title: 'For or since?',
    titleUz: 'For yoki since?',
    goal: "**for** (muddat) va **since** (boshlanish vaqti) ni tanlashni va davom etayotgan holat uchun **Present Perfect** ishlatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "*I've lived here ___ 2020.*", opts: ['for', 'since', 'from'], a: 1, why: "**2020** — boshlanish nuqtasi → **since**." },
      { k: 'choice', q: '*She has worked here ___ two years.*', opts: ['since', 'for', 'ago'], a: 1, why: "**two years** — muddat → **for**." },
      { k: 'match', pairs: [['for ten minutes', "o'n daqiqa davomida"], ['since Monday', 'dushanbadan beri'], ['for ages', 'juda uzoq vaqt'], ['since 2019', "2019-yildan beri"], ['for a week', 'bir hafta davomida']] },
      { k: 'fill', q: 'We have been friends ___ we were at school.', a: ['since'], uz: "Maktabdan beri do'stmiz.", why: "Boshlanish nuqtasi (gap) → **since**." },
      { k: 'fill', q: 'How long ___ you known Aziz?', a: ['have'], uz: 'Azizni qancha vaqtdan beri bilasiz?', why: "Davom etayotgan holat → **have you known**." },
      { k: 'tf', q: "*I live here since 2020.* — to'g'ri gap.", a: false, why: "Davom etayotgan holat uchun **Present Perfect**: *I have lived here since 2020.*" },
      { k: 'listen', say: "I haven't seen him since Friday.", opts: ["I haven't seen him since Friday.", "I haven't seen him for Friday.", "I didn't see him on Friday.", "I haven't seen him for ages."], a: 0, why: "**since Friday** — boshlanish nuqtasi." },
      { k: 'order', uz: 'U ikki yildan beri shu yerda ishlaydi.', words: ['She', 'has', 'worked', 'here', 'for', 'two', 'years'], extra: ['since', 'works'], why: "**has worked** + **for** + muddat." },
      { k: 'fix', wrong: 'I live here since 2020.', a: ['I have lived here since 2020.', "I've lived here since 2020."], hint: 'Zamonni o\'zgartiring', why: "**since** bilan hozirgi zamon emas, **have lived**." },
      { k: 'fix', wrong: 'She has worked here since two years.', a: ['She has worked here for two years.', "She's worked here for two years."], why: "**two years** — muddat → **for**, **since** emas." },
      { k: 'translate', uz: "Biz 2018-yildan beri Toshkentda yashaymiz.", a: ['We have lived in Tashkent since 2018', "We've lived in Tashkent since 2018"], why: "**since 2018** + **have lived**." },
      { k: 'dictation', say: 'We have lived in Tashkent for six years.' },
    ],
  },
  {
    id: 'u16-l3-d1',
    title: 'Who, which, that or where?',
    titleUz: 'Who, which, that yoki where?',
    goal: "Odam, narsa va joy uchun **who / which / that / where** ni tanlashni va ortiqcha olmoshsiz gap tuzishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*The woman ___ teaches us English is very kind.*', opts: ['who', 'which', 'where', 'what'], a: 0, why: "Odam → **who**." },
      { k: 'choice', q: '*This is the café ___ we had lunch.*', opts: ['who', 'which', 'where', 'what'], a: 2, why: "Joy va u yerda bo'lgan ish → **where**." },
      { k: 'match', pairs: [['a dentist', 'tish shifokori'], ['a kettle', 'choynak'], ['a pharmacy', 'dorixona'], ['scissors', 'qaychi'], ['a camel', 'tuya']] },
      { k: 'fill', q: 'A pharmacy is a place ___ you buy medicine.', a: ['where'], uz: 'Dorixona — dori sotib oladigan joy.', why: "Joy → **where**." },
      { k: 'fill', q: 'A teacher is a person ___ teaches children.', a: ['who', 'that'], uz: "O'qituvchi — bolalarga dars beradigan odam.", why: "Odam → **who** (norasmiy: *that*)." },
      { k: 'tf', q: "*The book what I read was great.* — to'g'ri gap.", a: false, why: "**what** bog'lovchi emas: *The book that / which I read…*" },
      { k: 'listen', say: 'The man who lives next door is a doctor.', opts: ['The man who lives next door is a doctor.', 'The man which lives next door is a doctor.', 'The man who lived next door is a doctor.', 'The woman who lives next door is a doctor.'], a: 0, why: "Odam → **who**." },
      { k: 'order', uz: 'Bu men yashaydigan ko\'cha.', words: ['This', 'is', 'the', 'street', 'where', 'I', 'live'], extra: ['which', 'what'], why: "Joy + u yerdagi ish → **where**." },
      { k: 'fix', wrong: 'The man who he lives next door is a dentist.', a: ['The man who lives next door is a dentist.'], hint: 'Ortiqcha so\'z bor', why: "**who** o'zi ega vazifasini bajaradi — *he* ortiqcha." },
      { k: 'fix', wrong: 'The book what I bought was cheap.', a: ['The book that I bought was cheap.', 'The book which I bought was cheap.', 'The book I bought was cheap.'], why: "**what** emas: **that / which** (yoki tushirib qoldirish)." },
      { k: 'translate', uz: 'Bu men sotib olgan sumka.', a: ['This is the bag that I bought', 'This is the bag which I bought', 'This is the bag I bought'], why: "Narsa → **that / which**, uni tushirib ham bo'ladi." },
      { k: 'dictation', say: 'A kettle is a thing that boils water.' },
    ],
  },
  {
    id: 'u16-l3-d2',
    title: 'Relative clauses: tricky mix',
    titleUz: "Ta'riflovchi gaplar: qiyin aralash mashqlar",
    goal: "**who / which / that / where** ni aralash gaplarda tanlashni va ortiqcha olmosh yoki **what** xatolarini tuzatishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "Qaysi gap **to'g'ri**?", opts: ['The film which we saw it was long.', 'The film which we saw was long.', 'The film what we saw was long.', 'The film where we saw was long.'], a: 1, why: "Narsa → **which**; *it* ortiqcha." },
      { k: 'choice', q: '*Is this the hotel ___ you stayed last year?*', opts: ['which', 'who', 'where', 'what'], a: 2, why: "Joy va u yerda bo'lgan ish → **where**." },
      { k: 'choice', q: '*This is the hotel ___ I booked.*', opts: ['where', 'which', 'who', 'what'], a: 1, why: "Hotel — narsa, *booked* ning to'ldiruvchisi → **which**." },
      { k: 'choice', q: '*Everything ___ he said was true.*', opts: ['what', 'that', 'where', 'who'], a: 1, why: "**everything** dan keyin **that**; *what* emas." },
      { k: 'fill', q: 'Do you know a shop ___ I can buy a cheap phone?', a: ['where'], uz: "Arzon telefon sotib oladigan do'kon bilasizmi?", why: "Joy + u yerdagi ish → **where**." },
      { k: 'fill', q: 'The people ___ live on our street are friendly.', a: ['who', 'that'], uz: "Ko'chamizda yashaydigan odamlar mehribon.", why: "Odamlar → **who** (norasmiy: *that*)." },
      { k: 'tf', q: "*I don't know what he wants.* — bu yerda **what** to'g'ri, chunki u savol so'zi.", a: true, why: "**what** — bog'lovchi emas, savol so'zi; bu gapda to'g'ri." },
      { k: 'tf', q: "*The film we saw was long.* — to'g'ri gap (*that* tushirilgan).", a: true, why: "To'ldiruvchi bo'lgan **that / which** ni tushirib qoldirish mumkin." },
      { k: 'fix', wrong: 'The film which we saw it was long.', a: ['The film which we saw was long.', 'The film that we saw was long.', 'The film we saw was long.'], hint: 'Ortiqcha so\'z bor', why: "**which** o'zi *it* ning o'rnini bosadi — *it* ortiqcha." },
      { k: 'fix', wrong: "That's the café which we met.", a: ["That's the café where we met.", 'That is the café where we met.'], why: "Joyda uchrashdik → **where**." },
      { k: 'fix', wrong: 'A teacher is a person which teaches.', a: ['A teacher is a person who teaches.', 'A teacher is a person that teaches.'], why: "Odam → **who**, **which** emas." },
      { k: 'translate', uz: "Menga yordam bergan erkak mening o'qituvchim.", a: ['The man who helped me is my teacher', 'The man that helped me is my teacher', 'The person who helped me is my teacher', 'The person that helped me is my teacher'], why: "Odam → **who**; *he* qo'shilmaydi." },
    ],
  },
  {
    id: 'u16-l4-d1',
    title: 'Passive forms',
    titleUz: 'Majhul nisbat shakllari',
    goal: "**am/is/are + V3** va **was/were + V3** shakllarini tanlashni va **V3** ni to'g'ri yozishni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Rice ___ in warm countries.*', opts: ['is grown', 'grows', 'is grew', 'are grown'], a: 0, why: "Birlik ega + passive → **is grown**." },
      { k: 'choice', q: '*The windows ___ last night.*', opts: ['was broken', 'were broken', 'are broken', 'broken'], a: 1, why: "Ko'plik + o'tgan zamon → **were broken**." },
      { k: 'match', pairs: [['write', 'written'], ['build', 'built'], ['steal', 'stolen'], ['grow', 'grown'], ['speak', 'spoken']] },
      { k: 'fill', q: 'Cars ___ in factories. (make)', a: ['are made'], why: "Ko'plik + hozirgi zamon → **are made**." },
      { k: 'fill', q: 'The letter ___ yesterday. (write)', a: ['was written'], why: "Birlik + o'tgan zamon → **was written**." },
      { k: 'fill', q: 'I ___ born in Samarkand.', a: ['was'], uz: "Men Samarqandda tug'ilganman.", why: "**I was born** — doimiy qolip." },
      { k: 'tf', q: "*Cars made in factories.* — to'g'ri gap.", a: false, why: "**are** tushib qolgan: *Cars are made in factories.*" },
      { k: 'listen', say: 'English is spoken in many countries.', opts: ['English is spoken in many countries.', 'English speaks in many countries.', 'English was spoken in many countries.', 'English is speaking in many countries.'], a: 0, why: "**is spoken** — passive." },
      { k: 'order', uz: 'Bu uy 1990-yilda qurilgan.', words: ['This', 'house', 'was', 'built', 'in', '1990'], extra: ['is', 'build'], why: "Aniq o'tgan vaqt → **was built**." },
      { k: 'fix', wrong: 'The book is wrote by a famous author.', a: ['The book is written by a famous author.'], hint: 'Fe\'lning 3-shakli', why: "**write – wrote – written**: passive da V3 → **written**." },
      { k: 'translate', uz: "Mening sumkam o'g'irlandi.", a: ['My bag was stolen'], why: "**steal – stole – stolen**; **was stolen**." },
      { k: 'dictation', say: 'The carpets are made by hand.' },
    ],
  },
  {
    id: 'u16-l4-d2',
    title: 'The passive: tricky mix',
    titleUz: 'Majhul nisbat: qiyin aralash mashqlar',
    goal: "Inkor va savol shakllarini, **by** ning kerak-kerakmasligini va **I born**, **was happened** kabi xatolarni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: "Qaysi gap **to'g'ri**?", opts: ['The match was happened last night.', 'The match happened last night.', 'The match was happen last night.', 'The match has been happened last night.'], a: 1, why: "**happen** — passive bo'lmaydi: *The match happened.*" },
      { k: 'choice', q: '*Hamlet ___ by Shakespeare.*', opts: ['wrote', 'was written', 'is wrote', 'was wrote'], a: 1, why: "**was written** — passive; V3 = *written*." },
      { k: 'choice', q: '*Where ___ these cups made?*', opts: ['are', 'is', 'do', 'does'], a: 0, why: "Ko'plik (*cups*) + hozirgi zamon → **are**; **do** kerak emas." },
      { k: 'fill', q: 'The window ___ broken last night.', a: ["wasn't", 'was not'], uz: 'Deraza kecha kechqurun sindirilmagan.', why: "Inkor: **was not** — faqat *be* o'zgaradi." },
      { k: 'fill', q: '___ plov cooked in a kazan?', a: ['Is'], uz: 'Palov qozonda pishiriladimi?', why: "Savolda *be* gap boshiga chiqadi: **Is** plov cooked…?" },
      { k: 'tf', q: "*My bag was stolen by somebody.* — bu yerda **by somebody** kerak.", a: false, why: "Kim o'g'irlagani noma'lum — **by somebody** ortiqcha." },
      { k: 'tf', q: "*The cake was baked by my mother.* — bu yerda **by my mother** kerak.", a: true, why: "Kim pishirgani yangi ma'lumot, shuning uchun **by** kerak." },
      { k: 'fix', wrong: 'I born in Tashkent.', a: ['I was born in Tashkent.'], hint: 'Fe\'l yetishmayapti', why: "**was** tushib qolgan: *I was born…*" },
      { k: 'fix', wrong: 'The window was broke last night.', a: ['The window was broken last night.'], why: "Passive da V3 → **broken**, *broke* emas." },
      { k: 'fix', wrong: 'The letters delivered yesterday.', a: ['The letters were delivered yesterday.'], why: "**were** tushib qolgan: ko'plik + o'tgan zamon." },
      { k: 'order', uz: "Gilamlar qo'lda to'qiladi.", words: ['The', 'carpets', 'are', 'made', 'by', 'hand'], extra: ['is', 'makes'], why: "Ko'plik → **are made**; **by hand** — usul." },
      { k: 'translate', uz: 'Uyim 2015-yilda qurilgan.', a: ['My house was built in 2015', 'My home was built in 2015'], why: "Aniq o'tgan vaqt → **was built**." },
    ],
  },
  {
    id: 'u16-l6-d1',
    title: 'Question tags',
    titleUz: 'Question tag: isn\'t it? don\'t you?',
    goal: "Gap oxiriga to'g'ri **question tag** qo'shishni (darak → inkor, inkor → darak) va har gapga **isn't it?** qo'shmaslikni mashq qilasiz.",
    exercises: [
      { k: 'choice', q: '*Laylo works in a bank, ___?*', opts: ["doesn't she", "isn't she", "doesn't it", "does she"], a: 0, why: "Present Simple darak → **doesn't she?**" },
      { k: 'choice', q: "*They aren't at home, ___?*", opts: ["aren't they", 'are they', "do they", "isn't it"], a: 1, why: "Inkor gap → darak tag: **are they?**" },
      { k: 'choice', q: "*Let's go to the park, ___?*", opts: ['will we', "don't we", 'shall we', "aren't we"], a: 2, why: "**Let's…** → doim **shall we?**" },
      { k: 'match', pairs: [['She is late,', "isn't she?"], ['You like tea,', "don't you?"], ['He can swim,', "can't he?"], ["They didn't come,", 'did they?'], ["You've finished,", "haven't you?"]] },
      { k: 'fill', q: 'You live in Tashkent, ___ you?', a: ["don't"], why: "Present Simple darak → **don't you?**" },
      { k: 'fill', q: "She didn't call, ___ she?", a: ['did'], why: "Inkor gap → darak tag: **did she?**" },
      { k: 'tf', q: "*You like football, isn't it?* — to'g'ri tag.", a: false, why: "**isn't it?** har gapga mos kelmaydi: *You like football, **don't you**?*" },
      { k: 'listen', say: "You've seen that film, haven't you?", opts: ["You've seen that film, haven't you?", "You've seen that film, didn't you?", "You saw that film, didn't you?", "You haven't seen that film, have you?"], a: 0, why: "**have** → tag: **haven't you?**" },
      { k: 'order', uz: 'Sen suzishni bilasan, a?', words: ['You', 'can', 'swim', "can't", 'you'], extra: ["don't", "isn't"], why: "**can** → tag: **can't you?**" },
      { k: 'fix', wrong: "Aziz lives here, isn't he?", a: ["Aziz lives here, doesn't he?"], hint: 'Gapdagi fe\'lga qarang', why: "**lives** (Present Simple) → **doesn't he?**" },
      { k: 'fix', wrong: "I'm late, amn't I?", a: ["I'm late, aren't I?", 'I am late, aren\'t I?'], why: "*I am* uchun tag: **aren't I?** (*amn't I* deyilmaydi)." },
      { k: 'translate', uz: "Siz ingliz tilini yaxshi ko'rasiz, shunday emasmi?", a: ["You like English, don't you", "You love English, don't you"], why: "**like** (Present Simple) → **don't you?**" },
    ],
  },
];
